CMS-Enterprise/easi-app

public/index.html, src/index.scss
This PR adds the font family Public Sans via Google Fonts. This will allow the frontend to use the correct font so that the UI looks more like the mockups Design provides.
I have left comments noting that this is not the end state of the implementation. Ideally, we should be getting Public Sans from USWDS (see `uswds/src/fonts`), but for some reason the font family isn't getting required.
Using Google Fronts isn't the worst thing in the world, but we should not need to use it because the font is packaged up with USWDS.
=> Add Public Sans

package.json, yarn.lock
This PR fixes the security risk reported by GitHub. This security risk would not affect the application code because the compromised library is only used at build time. However, the error should be resolved for peace of mind.
=> Update serialize-javascript package

.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE.md, .pre-commit-config.yaml, .spelling, README.md, cmd/easi/test.go, cmd/easi/test/test.go
- Add a CI job for running app tests.
- Add a CI job for building the app in docker & pushing the built image to our ECR repository.
- Define a CI workflow to verify that pre-commit & app tests pass before the docker build job is performed.
- Remove `easi` code that executed `golangci-lint`.
* This is now being performed by pre-commit in CI.
- Remove `pre-commit autoupdate` from the circleci config.
* This will cause pre-commit to run different versions of the hooks in CI than are being checked out locally, which will cause unexpected build failures.
* We can run this command periodically or as needed, but changes to the pre-commit config should be code reviewed & committed to this repo.
- Add circleci-validate pre-commit hook.
- Add a pull request …
=> Add app tests, docker build & push to ECR process in circleCI

.circleci/config.yml
- Remove `$CIRCLE_BRANCH` from the docker image tag.
Originally we were tagging images with the git branch name followed by the commit hash. Unfortunately git is more permissive about what can go in a branch name than docker is about what can go in a tag, which leads to unexpected build failures.
This PR unblocks branch protection on master. We may revisit the tagging scheme later on.
=> Remove git branch name from image tag

.spelling, docs/adr/0015-api-schema.md, docs/adr/index.md
- ADR only for rest schema decision
=> Add rest schema ADR only

.circleci/config.yml, scripts/build_docker_image
- When building from master, tag image with `easi:impl` and restart IMPL fargate service
- When building from others, tag image with `easi:dev` and restart DEV fargate service
=> Add CI deployment workflow for IMPL

scripts/build_docker_image
- Every build will now be tagged `:dev`. Before this change, the DEV fargate service would be restarted without a corresponding image tag being pushed
=> Always tag :dev image on every build

go.sum, pkg/context/context.go, pkg/context/context_test.go, pkg/handlers/systems.go, pkg/handlers/systems_test.go, pkg/server/logger.go, pkg/server/logger_test.go, pkg/server/routes.go, pkg/server/server.go, pkg/server/server_test.go, pkg/server/trace.go, pkg/server/trace_test.go
- Adds a trace ID to every request
- Creates a child logger with the trace ID so all logs are traceable to the original request
- Puts them in middleware and sets it up in routes
=> Add request logging

.circleci/config.yml
- Comment out the deploy_impl job from the CI workflow
=> Disable deploy_impl in CI per code freeze

pkg/handlers/system_intake_test.go, pkg/integration/integration_test.go, pkg/okta/okta_test.go, pkg/server/routes.go, pkg/server/server.go, pkg/storage/store_test.go, pkg/storage/system_intake_test.go, pkg/testhelpers/config.go, pkg/testhelpers/okta.go
- Uses a shared config across tests
- Locks access token so only one will be retrieved
=> Add Lock for Okta Access Token in Tests

pkg/server/routes.go, pkg/services/system_intakes_test.go
- Use "local" instead of "LOCAL" since they are not considered the same value for env vars
=> Switch Local to local everywhere

.circleci/config.yml
- Uncomments the deploy_impl job in the compile workflow. As before, deployments to IMPL are only run off the master branch.
=> Resume IMPL deployments on master branch

scripts/release_static
- Adds the `--delete` switch to the aws s3 sync operation that releases new static assets
This removes files in the destination that are not present in the source.
=> Purge old static assets from S3 during deploy

.circleci/config.yml
- Update the circleci configuration to execute database migrations during a deployment in IMPL
Notes:
- We do not clean the database in IMPL before running migrations because we do not roll back migrations in PROD: this should keep the IMPL db in a state as close to production as possible for now.
=> Add db migrations execution step in IMPL deploy

docker-compose.yml
- Remove db_clean container from docker-compose.yml
A race condition between the migration containers was causing the database to sometimes get cleaned after migrations had been run. Rather than hack together scripts to track this state I'm simply removing the clean service from the docker-compose configuration. 
See also:
* https://docs.docker.com/compose/startup-order/
* https://github.com/docker/compose/issues/374
Note: After pulling this change locally, start once with `docker-compose up --remove-orphans` to clear out the orphaned db_clean image. After that, the services can be started normally with just `docker-compose up`.
=> Remove db_clean service from docker-compose.yml

pkg/testhelpers/okta.go
- Returns a helpful error message if no session token is received.
=> Okta test helper fails if no session token received from OTP challenge

src/components/Header/UserActionList/index.scss, src/components/Header/UserActionList/index.tsx, src/components/Header/index.scss, src/components/Header/index.tsx
This PR fixes some header username mistakes.
1. The username and caret are now one single button. The focus wraps around the whole thing and the actions menu opens/closes as expected.
2. The actions menu hover text color is white.
Additionally, I added some accessibility fixes to the username/caret and actions menu. I'll leave comments inline.
=> Fix header username button

scripts/restart_ecs
- Add a 3-minute waiting period to the ECS deployment process to verify the correct version of the application is deployed
=> Add healthcheck waiter in restart_ecs script

scripts/db_lambda_invoke
- Add a step to CI that pretty-prints the response from the lambda using jq
=> Add explicit logging of db lambda response

.circleci/config.yml, scripts/release_static
- Move the Okta and other React environment variables from `.circleci/config.yml` to `scripts/release_static`. This way, we can reserve the `environment:` section for environment variables that are needed in multiple steps within a job.
- Remove unneeded environment variables and refactor how the others are composed
=> Refactor environment variables for static asset build

pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- Fetch for existing error shouldn't affect saving a brand new intake
=> Fix saving intake with new id

src/components/Header/index.tsx, src/views/BusinessCase/index.tsx, src/views/SystemIntake/index.tsx, yarn.lock
Due to accessibility constraints, this PR moves the "Save & Exit button from the header to below the "back" and "next" buttons in the main content area.
Along with this change, I also included some small clean up work:
- Move logic for header name into the view rather than managing it from the Header component
- Remove unnecessary dependencies
=> Move "Save & Exit" from header to main content area

package.json, yarn.lock
Found out about changes to ECMA script that I wanted to have available to us that are in react-scripts 3.3.0+, so I thought I'd update it.
- Updates react-scripts to 3.4.1 [changelog here](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md)
=> Update react-scripts to 3.4.1

src/views/App/index.tsx, src/views/SystemIntake/index.tsx
- Removes the `/system/:systemId` route so users can't access the system profile page since it's not in scope
- After Save & Exit, users are redirected to the home page.
=> Remove system profile page

src/views/SystemIntake/index.tsx
How to produce the bug?
1. Checkout to `master`
2. Navigate to `/system/new`
3. Type in something for the Requester's name
Notice there's a flash that makes it appear that the page refreshed. The URL changes (as it should). Because the URL changes, `match.params.systemId` changes as well. The `useEffect` hook executes and attempts to fetch that system intake by its `id`.
In this situation with the give acceptance criteria, we only need to fetch the data when the page mounts. This way, when the app autosaves and updates the URL, the app doesn't try to fetch the data again.
=> Fix flashing that occurs after autosave on system intake

.circleci/config.yml, scripts/rds-snapshot-app-db
- Add a script to snapshot the RDS instance before running database migrations
For initial testing, the script is backing up the dev RDS instance. Once the PR passes initial code review, I can remove the backup step in dev.
=> Create RDS snapshot before running database migration

src/constants/enums/cmsDivisionsAndOffices.ts, src/views/SystemIntake/ContactDetails/index.tsx
This PR adds the component acronym to the dropdown options on the System Intake.
For example:
`Center for Medicare (CM)`
=> Add acronyms to CMS component dropdown options

src/views/App/index.tsx
The intake view route is above the grt-review, which will get hit even if there is a subpath afterwards. This changes the order
=> put grt-review subpath before system view in routes

src/components/shared/AutoSave/index.tsx, src/data/systemIntake.ts, src/views/App/index.tsx, src/views/Home/index.tsx, src/views/SystemIntake/index.tsx
This PR adds browser back/next functionality to the System Intake form **only**. The business case will need to be tackled separately.
```
/system/new/contact-details
/system/new/request-details
/system/:systemId/contact-details
/system/:systemId/request-details
```
- If users try to visit an unknown/invalid page that isn't a part of the form, they will be redirected to `contact-details`, the first page.
- At this time, users are able to manually enter the URL to get to `request-details` and bypass `contact-details`. This is a known issue and in future work we will add checks to run validations so that a user is bounced to the right page.
- Integration test are in a holding pattern. If we can get this merged in, I can begin adding additional integration test cases in #175
=> Add browser back/next to system intake form

.circleci/config.yml, scripts/deploy_service, scripts/healthcheck, scripts/restart_ecs
- Set circleci deployment workflow to use ecs-manager lambda for deploying images to the db-migrate and easi-app services
- Container definitions in those services now pull images named from the git digest of the current build
Notably, this PR does not change the process for cleaning the database in dev. Since the image running in that service is not being rebuilt for each deployment it is unnecessary to pin it to the same version as the others. For more, see the commit message to 6bd5a83.
=> Pin depolyed images to git commit digests

scripts/healthcheck
- Increase the healthcheck timeout from 3 minutes to 5 minutes
- Add a max duration for each `curl` call to limit artificially extending the timeout in cases where the endpoint is unresponsive
=> Increase healthcheck timeout

.circleci/config.yml
The update service operation does not start a task if the desiredCount is 0, as in the flyway services. An explicit run task command is required.
Therefore this PR restores the migrations lambda invocation after deploying the new image.
- Invoke db migrations lambda after deploying migrations image
=> Run db_lambda_invoke after deploying migrations image

.circleci/config.yml, scripts/circleci-announce-broken-branch
- Send a Slack notification when a job on the master branch fails
To test, I added a temporary step to simulate failure (https://github.com/CMSgov/easi-app/pull/207/commits/5b121d0564a6c4d006469b141e037ca130200a55) and confirmed it didn't send a slack notification on my branch build. I then commented out the part that checks which branch we're on (https://github.com/CMSgov/easi-app/pull/207/commits/9d1fdccaef00d667610d45462a64a7eb82705f9b) and confirmed the failure message was sent to Slack.
=> Send Slack notification on master branch failures

migrations/V10__Add_Created_At.sql, pkg/models/business_case.go, pkg/models/system_intake.go, pkg/server/routes.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/services/system_intakes.go, pkg/storage/business_case.go, pkg/storage/system_intake.go
We should log "created at" on our models in general, but also this is needed for metrics.
- Add "created at" to system and business case
- Add "updated" at to business case
=> Add Created At to Models

pkg/appvalidation/business_case.go, pkg/appvalidation/business_case_test.go, pkg/services/business_case.go, pkg/services/business_case_test.go
- Temporarily removes lifecycle cost validations for post and put
- Maintains that a intake must be submitted
(Reminder for later, all code has comment 
```// Uncomment below when UI has changed for unique lifecycle costs``` 
for easy reverting)
=> Remove unique lifecycle cost validations for right now

src/components/EstimatedLifecycleCost/index.scss, src/components/EstimatedLifecycleCost/index.tsx, src/components/shared/RadioField/index.scss, src/components/shared/RadioField/index.tsx
I branched off to make this suggestion in how to handle the radio buttons overlapping the help and guidance box. I noticed the grid columns were changed to accomodate for the overlap, but this would continue to be a problem if the radio labels got longer or more margin/padding was introduced.
Instead of changing the grid columns, it would be better to make the radio buttons wrap and stack.
=> Wrap radio buttons in a RadioGroup and have them wrap

src/components/shared/DropdownField/index.tsx, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx
I added a `disabled` prop to the `DropdownItem` component. This will make a `DropdownItem` not selectable.
This fixes the issue of allowing a default option to be selected.
=> Add disabled to initial dropdown values

src/views/SystemIntake/index.tsx
This PR fixes the issue with errors clearing when a user is filling out the form. We are resetting the form after saves to bring the form back to a "fresh" state. But because of resetting the form, the errors are getting cleared out too. This PR keeps the errors when resetting.
=> Fix errors clearing in system intake on save

src/views/Home/index.tsx
This PR adds the link on the homepage to take a user from EASi to sharepoint. Right now it is configured to open in a new tab, but that can be changed if we want to.
=> Add link to navigate to sharepoint

src/reducers/systemIntakeReducer.test.ts, src/reducers/systemIntakeReducer.ts, src/types/routines.ts, src/views/SystemIntake/index.tsx
- After clicking save and exit, I should be able to start a new system intake without the old existing one auto-filling my form.
Open questions: 
- Is remove the right verb to use? Or should I use clear?
- Should this be on save and exit or on starting a new form? I'm inclined to suggest on save and exit because it says I'm currently done with this particular system intake.
=> Clear system intake from store on save and exit

pkg/models/system_intake.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
This adds the query for the metrics we want to check in golive
- Add a model for returning metrics
- Add queries to obtain metrics
Not included:
- a way to trigger these via API
- a way to return them/send them
=> Add metrics digest query

pkg/appconfig/config.go, pkg/appconfig/config_test.go, pkg/appses/ses_test.go, pkg/email/email.go, pkg/integration/cedar_test.go, pkg/integration/integration_test.go, pkg/integration/system_intakes_test.go, pkg/server/config.go, pkg/server/health_check.go, pkg/server/healthcheck.go, pkg/server/routes.go, pkg/server/server.go
- Check CEDAR connection at startup by querying systems
- Check email client at startup by sending email
- Convenience methods for `Environment` to stop using `config.GetString` so much
- Add `Prod` environment
=> add server integration validations

src/reducers/businessCaseReducer.test.ts, src/reducers/businessCaseReducer.ts, src/types/routines.ts, src/views/BusinessCase/index.tsx
This PR  fixes the bug where they use sees the previous business case when trying to switch between business cases. This fix will allow the user to see the business case they are expecting to see when clicking on the banners.
=> Clear previous business case

src/views/App/index.tsx
This PR removes the sandbox page from the production build. The sandbox page will only appear on development environments.
To test this, you'll see `/sandbox` when running `yarn start`.
To run production build locally, run `yarn build` and follow the output instructions. This will probably involve installing a package to serve up the built files.
=> remove sandbox from production build

src/data/businessCase.ts
Currently, API requests set alternative B fields to empty string if they are not filled out. When a user attempts to submit, the backend sees empty string as it being filled.
This PR sets alternative B fields to be null by default.
Should we be validating for length instead on the backend?
=> Pass null to backend instead of empty string for alt b

src/reducers/businessCaseReducer.test.ts, src/reducers/businessCaseReducer.ts, src/reducers/systemIntakeReducer.test.ts, src/reducers/systemIntakeReducer.ts
This PR resets the data to match the initial state of the reducer when cleared. Previously we were only resetting the form data.
=> Properly reset form(s) to initial state when clearing the form

pkg/storage/system_intake.go
- When updated a system intake, don't overwrite `created_at`
=> do not update created at on system intake

Dockerfile
Previously, the alpine image was set to major version 3. When alpine
3.12.0 was released we had builds failing because the ECR vulnerability
scanner does not support this version yet. Minor version 12 does not
appear to have any updates critical to our use case. Therefore we need
to pin to minor version 11 so that app development can continue.
- Set base alpine image to minor revision 3.11
=> Set base alpine image to minor revision 3.11

.circleci/config.yml
- Add a manual hold step before performing deployments to DEV
=> Add manual hold before deploy_dev

.circleci/config.yml
- Remove the dependency on deploy_dev from deploy_impl
The hold_dev step added in #263 also procs in the master branch. deploy_impl depends on a successful deploy_dev job to run. That means that after merging a PR to master, an additional manual step is required to release the deploy_dev job so that deploy_impl can then run. 
But branch protection rules already ensure that a successful DEV deployment has been performed before any new code can be merged in to master. Therefore, we can remove this dependency and simply deploy directly to IMPL after merging to master. This will remove the extra post-merge release step _and_ eliminate one more redundant automated DEV deployment.
I also added an ignore filter for hold_dev so that there aren't dangling …
=> Remove deploy_dev requirement from deploy_impl

src/components/shared/Label/index.test.tsx, src/components/shared/Label/index.tsx, src/views/SystemIntake/ContactDetails/GovernanceTeamOptions.tsx
The comments from our consult are a little out of date. We've added the team's acronym to the label already.
In this PR, I added an `aria-label` to the HTML label so that users using assistive technology will have a clear readout of what the input label is for.
=> Add aria label for governance collaborator name

src/components/CharacterCounter/index.scss, src/components/CharacterCounter/index.test.tsx, src/components/CharacterCounter/index.tsx, src/views/BusinessCase/AlternativeSolution/index.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx
This PR makes character counters for text areas accessible.
- Update `2000 characters left` to `2000 characters remaining` (confirmed with design)
- Create `CharacterCounter` component to reuse
- Add accessibility HTML attributes (see [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) to learn more about `aria-live` and `aria-atomic`.
Most of us have the new(er) Macbook Pros. Macbooks have macOS VoiceOver installed. This is a good screen reader for us to use for testing.
1. Hold down `command` and click the TouchID button 3 times and the VoiceOver prompt should appear.
2. Optional: You can "Learn More" and run through the tutorial.
3. Activate VoiceOver and navigate to the EASi app.
4. Warning: after activation VoiceOver, the screen reader will start …
=> Make character counter accessible

src/components/UsGovBanner/index.tsx
This PR updates the `aria-expanded` to be dynamic rather than being `false` all the time. This fixes the issue reported by Mario.
=> (Gov Banner) update aria-expanded to be dynamic

src/components/shared/CollapsableLink/index.test.tsx, src/components/shared/CollapsableLink/index.tsx, src/views/GovernanceOverview/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx
This work is a part of both issues above. The `CollapsableLink` component wasn't letter assistive technology know when the content is expanded and what content the link controls.
This is fixed by adding `aria-expanded` and `aria-controls` to the button/link.
=> Make CollapsableLink accessible

src/views/Home/index.tsx
This PR fixes some spacing introduced when the `MainContent` component was added in #266.
This fix took less than 10 minutes so there is no JIRA ticket associated with it.
Before (Notice the spacing and border right above `Welcome to EASi`
After (Extra spacing is gone)
=> Fix main content heading

src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx
This adds accessibility requirements needed for the Governance Task List. The specifically add aria-expanded on the "show/hide remaining items" to let users know if the list is displayed of hidden.
It also adds tests for those attributes.
=> add accessibility tests to governance task list

migrations/V16__Rename_System_Intake_Statuses.sql, migrations/V17__Add_Approved_Intake_Status.sql, pkg/models/system_intake.go, src/views/App/index.tsx, src/views/GovernanceTaskList/TaskListItem.test.tsx, src/views/GovernanceTaskList/TaskListItem.tsx, src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx, src/views/Home/index.test.tsx
- Adds migrations for getting all intake statuses the same
- Adds those statuses into our allowed type for the API
- Uses those statuses during step 1 in the task list
=> Add statuses to backend and to task list

src/views/TimeOutWrapper/index.tsx
Previously, the modal would appear based on the user's access token expiration. This wasn't working because I user can have continuous activity, but the access tokens aren't updated. That means the modal will display every time the access token is 5 minutes from expiration.
Instead, I've changed the modal to display when a user has been inactive based on the user's `lastActiveAt`.
Additionally I moved the logout logic to it's own hook because that logic shouldn't be dependent on the modal being open. As long as the user is logged in, the interval will be counting for a user's activity. This will protect us from any bugs, like if the modal doesn't show up for some reason. We will still be logging a user out when they've been inactive.
=> Update session timeout to be based on a user's last activity rather than token

src/views/AuthenticationWrapper/index.tsx, src/views/TimeOutWrapper/index.tsx
This PR reverts some of the core session timeout work since it's not currently working to unblock deployments. 
Basically, I only reverted stuff that affects what's in prod now. For example, I removed everything in the `TimeOutWrapper`, but left things like the `useInterval` hook, CSS changes, i18n files, etc. The stuff I left is just hanging out behind the scenes, but not used or displayed anywhere in the app.
=> revert session timeout work until we have a resolution

Dockerfile, scripts/check_ecr_findings
- Display the contents of the image scan response in CI. This will at least provide some additional information when scans generate errors in future. I experimented with improved error handling, but the formatting of the lambda response (string vs. json) is different depending on whether the lambda returns an error or a success message. As for that, I'd prefer to refactor what the lambda returns on successful execution, rather than invest too much additional effort into how the bash script parses the response. The work to refactor the lambda will be tracked in a different story.
=> Display contents of image scan response in CI

docs/adr/0018-integration-tests-third-party-apis.md, docs/adr/index.md
- Add ADR for how the EASi application will approach third-party API integration tests that run in CI
=> Add ADR for third-party API integration tests

.circleci/config.yml, scripts/deploy_service
- Add the `secrets` field to the deployment payload when the service being deployed is `easi-app`, to take advantage of [automated SSM parameter management](https://github.com/trussworks/terraform-aws-lambda-ecs-manager#ssm-parameters).
- Move the `integration_tests` dependency from `hold_dev` to `deploy_dev`. This means the hold can be approved at the start of the build process, saving time waiting for integration tests to pass before it can be released.
=> Add SSM parameter automation

src/views/SystemIntake/index.tsx
This fixes issues with autosave.
Currently in IMPL, the autosave isn't working properly. the initial `POST` works, but the following `PUT` requests don't. The reason for that is because the intake ID isn't getting set in Formik from the `POST` response. In order to have it set, we need to update Formik with the data from Redux (which has the intake ID) in `initialValues`.
I believe this might be related to some of the issues with system intake submissions as well.
=> Fix system intake autosave

pkg/storage/system_intake.go, pkg/storage/system_intake_test.go, src/data/systemIntake.ts
There was a bug caused here which saved biz case id to an intake that didn't get passed up the chain.
- fixes a bug where we actually save and send the biz case id when fetching intakes by eua id.
=> Fix biz case id to actually return on fetch intakes

.circleci/config.yml
- Update `deploy_dev` job to ignore builds on the master branch. Previously, `deploy_dev` was inheriting the branch filter from `hold_dev`, but with the additional dependency on `integration_tests`, we need to explicitly add the branch filter on `deploy_dev` as well.
=> Skip deploy_dev on master branch builds

pkg/authn/principal.go, pkg/authn/principal_test.go
* This is the first of several PRs that I will be submitting for this project. I feel that I will be better able to tell a story and bring folks along with me by doing little ones, rather than doing one big honkin' PR.
* The code here is strictly _additive_, and will not end up in the active-path of the application used until later PRs
* The `anonymous` type is part of a larger pattern that I feel helps reduce the need for `if err != nil then` clauses, by using "no-op" types that represent the negative cases. There are shades of this in this [blog post](https://dave.cheney.net/2019/01/27/eliminate-error-handling-by-eliminating-errors), and some concrete examples from other frameworks are the [go-kit …
=> EASI-621 intro security principal

.circleci/config.yml, scripts/run-cypress-test-docker
- Update the integration test step and script so that we're not storing the cypress video in CI artifacts
=> Don't store cypress video in CI artifacts

pkg/appcontext/context.go, pkg/appcontext/context_test.go, pkg/okta/okta.go, pkg/okta/okta_test.go
* This is another small PR in a sequence (previous being #321) that will combine to address the functionality needed for EASI-621.
* This code is also strictly additive, but it does actually involve the new code from this PR as well as the code from #321 into the active path, yet there are no new consumers of the `Principal` just yet (that'll be the next PR).
* Notice that the func `appcontext.Principal(...)` does not have an error return. This is the realization of what I proposed on the previous PR, using an object for the negative case, rather than forcing an `if err != nil` clause in any consuming code.
* Notice that in the case of a successful JWT decoding, this PR now ensures that there is both a `User` object as well as a `Principal` object on …
=> EASI-621 Principal stored on context

src/views/BusinessCase/index.tsx, src/views/SystemIntake/index.tsx
This PR fixes the issue where system intake data is deleted when a user attempts to "save and exit".
This was happening because we had additional code that attempts to save a user's form data when they leave the form. The user was redirected away from the page and the "autosave" was clearing out what was saved.
There's a better way to do this, but for now, we should revert this change so user's aren't affected.
=> Remove autosave on unmount

pkg/appcontext/context.go, pkg/appcontext/context_test.go, pkg/services/business_case.go, pkg/services/metrics.go, pkg/services/system_intakes.go
* Reduce the need for so many `if err != nil` checks throughout the code, by making sure the cross-cutting concern method signature ALWAYS returns a `*zap.Logger`
* Make sure to use the contextual logger in the `service` package, this ensures access to things like the Request ID, which is not available on the non-contextual (aka system) logger.
* While in this code, I noticed several types of naming collisions and possibilities of variable shadowing, so I tidied that up, in pursuit of "easier to read and reason about".
=> prefer contextual logger

pkg/appconfig/config.go, pkg/integration/cedar_test.go, pkg/server/config.go, pkg/server/routes.go
- Given instability of CEDAR dev, we will no longer check the connection to CEDAR in dev or impl
- Checks that we still have necessary configs for CEDAR clients
- Simplifies CEDAR api keys to a single key
=> Only test cedar connection for prod and dedupe cedar keys

pkg/appcontext/context.go, pkg/handlers/business_case.go, pkg/handlers/business_case_test.go, pkg/handlers/business_cases.go, pkg/handlers/business_cases_test.go, pkg/handlers/system_intake.go, pkg/handlers/system_intake_test.go, pkg/handlers/system_intakes.go, pkg/handlers/system_intakes_test.go, pkg/local/authorization.go, pkg/okta/okta.go, pkg/okta/okta_test.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
* This PR makes the `authn.Principal` the load bearing object for authorization in the system, replacing the `model.User`
* Actually wiring up code to set `EUAPrincipal.AllowGRT()` will happen in on a later ticket (EASI-740) after EUA + Okta configurations have happened
=> Nelz use principal

pkg/integration/business_case_test.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/services/metrics.go, pkg/services/metrics_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/storage/business_case.go, pkg/storage/business_case_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
* this continues the work previously done at the `services` layer into the `storage` layer
* use the request context for finding the logger to write out logs
* this ensures that things like `request ID` are still associated with logs emitted when problems arise talking to the database
=> req context in storage layer

src/views/TimeOutWrapper/index.tsx
There were edge cases where the timeout modal initially display `0 seconds remaining` or display `-1 seconds remaining` after the session timed out. This removes those edge cases
=> Fix timeout modal message

src/data/businessCase.ts, src/views/BusinessCase/Confirmation/__snapshots__/index.test.tsx.snap, src/views/BusinessCase/Confirmation/index.tsx
Since `businessCase.alternativeB` is always truthy we need to use the function to check if any of the fields are filled. This was just a missing piece I forgot to change previously.
The major block of code moving is just moving the function to be instantiated before it is used to satisfy lint rules
=> omit alternative b data so that business case can submit

src/i18n/en-US/accessibilityStatement.ts, src/views/AccessibilityStatement/index.tsx, src/views/App/index.tsx
This PR represents my feedback for @downeyn-cms's #355 PR. I left feedback on the Accessibility Statement. They should also be incorporated into other static pages.
Overall, I thought #355 was pretty good. You achieved the main goal of creating the pages and using i18n to reflect the copy. I've outlined a few suggestions and you can align them with my change set.
1. **Be mindful of the named keys in the i18n file**
- Naming is hard, but the thing I wanted to avoid is using identifiers like `paragraph1`, `paragraph2`, `element1`, element2`, etc. (with the exception of addresses because that's how they're named, literally). As a maintainer, this isn't descriptive and I would need to count out paragraphs and compare the file to what is one the page. If there are more descriptive keys, it is …
=> add feedback for accessibility statement.

pkg/server/health_check.go, pkg/server/routes.go
- CEDAR checks happen on startup in all the "deployed" environments (e.g. DEV, IMPL, PROD)
- CEDAR checks only log at `ERROR` severity and do not take down the app during startup
=> error not fatal for CEDAR problems

package.json, src/components/UsGovBanner/index.tsx, src/stylesheets/_settings.scss, src/stylesheets/custom.scss, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/NotFound/__snapshots__/index.test.tsx.snap, src/views/TermsAndConditions/__snapshots__/index.test.tsx.snap, yarn.lock
This PR updates USWDS to v2.8.1.
This update allows us to:
- Override SCSS variable to set footer width (rather than targeting class names)
- Use the new Gov Banner. See https://designsystem.digital.gov/whats-new/updates/2020/09/08/Improvements-banner/
- Update snapshot tests because of the gov banner changes
=> Update USWDS to 2.8.1, Footer, and Gov Banner

README.md
- Add README docs on 1Password
=> Add documentation on EASi 1Password

src/components/Footer/index.scss
This PR adds padding to accommodate for the link outline. On USWDS, they have a "Return to top" button that contains the proper padding to accommodate for the outline width.
Since we don't have that button, we need to add additional padding so the outline isn't cut off.
=> Fix Footer link outline

pkg/server/server.go
- Use [zap.NewDevelopment](https://godoc.org/go.uber.org/zap#NewDevelopment) to create the logger when running in the `local` or `dev` environment. This formats log messages in a more human-legible way, although the request itself is still shown as JSON. It's still a big improvement, though, especially for stack traces.
Here is the before and after of this change. Before, everything is on one line:
```
{"level":"error","ts":1600278397.170604,"caller":"cedareasi/translated_client.go:165","msg":"Failed to submit intake for CEDAR with error: Post \"https://webmethods-apigw.cedardev.cms.gov/gateway/EASi%20Core%20API/1.0/intake/governance\": context deadline exceeded","traceID":"f6e0745e-97b8-4963-8df5-686ce7ee69ce","stacktrace":"github.com/cmsgov/easi-app …
```
=> Use the zap development logger for local development.

.circleci/config.yml, package.json
- Build the frontend code in the `lint` job to catch compilation warnings earlier in the CI pipeline
- Add `CI=true` to the `build` script in package.json so that running a yarn build locally or in the Dockerized Cypress tests will also error our on compilation warnings
This is to address an issue where a particular build passed the `lint` and `integration_tests` jobs, but failed when building the static assets in the `deploy_dev` job.
CircleCI sets `CI=true` automatically in all the different jobs in the CI workflow. The `yarn test` in the `lint` job and the `yarn run build` in the `deploy_dev `job have `CI` set to true because they're either running directly in a CircleCI command or in a Bash script. The `integration_tests` job is a little …
=> Attempt to catch frontend compilation warnings earlier in CI

pkg/appcontext/context.go, pkg/appcontext/context_test.go, pkg/handlers/handler_base_test.go, pkg/server/trace.go, pkg/server/trace_test.go
- Adding what is logged as the `traceID` to the response header `X-TRACE-ID`
- Basically a direct port of https://github.com/trussworks/go-sample-api/pull/11
=> emit traceID on response header as well

src/views/TimeOutWrapper/index.tsx
I've been getting these errors locally. I haven't dug into the real cause, but in order to get the issue to go away and unblock development I added a check to prevent the issue.
Here's what I'm seeing before this change:
And after, I don't see it.
=> Only access expiresAt when accessToken exists.

.envrc, cypress/integration/taskList.spec.js, src/views/App/index.tsx, src/views/GovernanceTaskList/index.tsx
- Users who visit `/governance-task-list/new` page via the back button will be redirected to the page for their recently created system intake. This is similar to what we do on the contact details page.
- The `OKTA_TEST_*` environment variables are now documented in `.envrc` to help developer know that they need to be set.
=> Redirect users when a system intake exists

pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- A follow up to refactoring the system intake submit: if the confirmation email fails to send, this should not error, but only log an error.
=> Don't error if email fails to send on submit intake

.circleci/config.yml
- Add the REACT_APP environment variables to the lint job in CI so front end unit tests can access them
This PR uses the env var values as set in .envrc, withe the exception of REACT_APP_APP_ENV, which is set to `test`.
=> Add REACT_APP env vars to lint job

src/views/GrtSystemIntakeReview/index.tsx
This PR fixes the GRT Reviewer page i18n keys. It was separated by colon (`:`) rather than a period (`.`). Colons are used for file namespace, while periods are for object nesting. This was a page missed when we consolidated review page into the `governanceReviewTeam` i18n namespace.
=> Fix GRT Reviewer page i18n keys

pkg/cedar/cedareasi/translated_client.go, pkg/cedar/cedareasi/translated_client_test.go, pkg/handlers/systems.go, pkg/handlers/systems_test.go, pkg/server/health_check.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/services/systems.go
- just doing some housekeeping, propagating the "context is first param to every layer" pattern to the package that wraps the generated client
=> context to wrapper of generated client

src/components/BusinessCaseReview/AlternativeAnalysisReview/index.tsx, src/components/BusinessCaseReview/GeneralRequestInfoReview/index.tsx, src/components/BusinessCaseReview/RequestDescriptionReview/index.tsx, src/components/BusinessCaseReview/index.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/BusinessCaseReview/index.test.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/index.tsx, src/views/GovernanceReviewTeam/index.tsx
This PR adds the business case view to the GRT reviewer.
http://localhost:3000/governance-review-team/:systemId/business-case
Because of the page structure in the requester review (full width background color), it can't be easily reused in the GRT reviewer view. I broke it into even smaller chunks by page. Each page of the business case has its own review component that are building blocks for the business case review.
Not only do we need to verify the GRT reviewer business case view, but we also have to verify there are no regressions on the requester reviewer view.
(We have snapshots of the business case review so we should be good since it matches the diff)
=> Add GRT business case reviewer view

src/views/GovernanceReviewTeam/IntakeReview/index.test.tsx
For the System Intake Review page, it uses the current time to indicate the submission date before the intake is submitted. We added a snapshot test, but the date will change every day because it uses the current time.
This PR mocks the date so we don't have this issue again.
Below is an example of the date changed from yesterday to today
```
Submission Date
</dt>
<dd
className="description-definition margin-0"
>
-               Sep 30, 2020
+               Oct 1, 2020
</dd>
</div>
```
=> Mock current date in snapshot test

cypress/integration/systemIntake.spec.js, src/components/BusinessCaseReview/GeneralRequestInfoReview/index.tsx, src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/components/SystemIntakeReview/index.tsx, src/i18n/en-US/intake.ts, src/validations/businessCaseSchema.ts, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap, src/views/SystemIntake/RequestDetails/index.tsx
This PR updates the user facing "Request Name" to "Project Name". This PR **only** updates that specific field label because that is what's confusing users.
All other instances of "request" will be kept as is until further notice.
We should probably find a way to document the discrepancy between "project" and "request". It can be confusing for folks joining the team.
Intake
Business Case
=> update request name to project name

cypress/integration/systemIntake.spec.js, migrations/V24__Add_Cost_increase_To_intake.sql, pkg/cedar/cedareasi/translated_client.go, pkg/cedar/cedareasi/translated_client_test.go, pkg/models/system_intake.go, pkg/storage/system_intake.go, pkg/testhelpers/system_intake.go, src/components/SystemIntakeReview/index.tsx, src/data/systemIntake.ts, src/types/systemIntake.ts, src/validations/systemIntakeSchema.ts, src/views/SystemIntake/ContractDetails/index.tsx, src/views/SystemIntake/index.scss
This PR allows the use to fill out questions about cost increases on the Contract Details page. This includes the questions being added on the frontend as well as API/backend work to save.
Open Question:
This does not include any work with CEDAR. We'll need to work with CEDAR to make sure they can support the additional fields.
=> Add cost increase questions to the Contract Details page

src/i18n/en-US/intake.ts, src/react-table-config.d.ts, src/views/GovernanceReviewTeam/AllRequests.tsx, src/views/GovernanceReviewTeam/IntakeReview/index.test.tsx, src/views/GovernanceReviewTeam/index.tsx
This PR adds sorting to the GRT request table.
Notes:
- This is not type safe. I used a few `any` because I couldn't figure out how to merge some types. See [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table#example-type-file)
- For now, we are inheriting the default label/title for the header sorting. It will read as `Toggle sort by`.
- It also uses the `aria-sort` attribute. My hope will be that using these two together will be sufficient for assistive technology users.
=> Add sorting to GRT request table

migrations/V25__Add_System_Intake_Lifecycle_Fields.sql, pkg/models/system_intake.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Added 4 new fields to the `SystemIntake`
- Modified the data layer to write these new fields to the database on `Update...`
- DID NOT add these fields to the `Create...` method, as it is my understanding that these fields are not relevant at the beginning of a `SystemIntake` life span
=> data layer for lcid

pkg/local/authorization.go, pkg/server/server.go
Currently, when you want to test something that interacts with the LDAP API (reviewing a system intake, e.g.), you need to change the testEUAID variable in local authorization to an ID that actually exists in CEDAR. This PR adds a new envrc.local variable where you can store a working EUAID (presumably your own) for ease of testing.
=> Add envrc.local variable for ease of testing LDAP

pkg/storage/business_case.go, pkg/storage/business_case_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Ensure we return the actual DB copy of the `SystemIntake` after a `Create...` or `Update...` operation; very subtle bugs, even in test code, are possible if you don't do a full round-trip to the DB to verify what was actually written
- Use modern idiomatic Go `errors.Is(...)` rather than relying on strings to identify errors from the SQL layer
- Decompose filtering "ARCHIVED" `SystemIntakes`; this is probably the most "controversial" assertion I'm making here; generally I feel the data layer should be fully empowered to get any/all entities, and it is up to the business logic layer to explicitly declare what statuses are of interest for any given operation (though the data layer can of course provide helpers, but they should be intentionally …
=> Opinionated proposal

.circleci/config.yml
- Update the versions of the ECS manager lambda used to deploy backend changes to the deployed environments
This change is needed to address an issue caused by a recent update to boto3 that broke deployments of the ECS service.
=> Use updated ECS manager lambdas

.circleci/config.yml
- Update the lambda versions in the ECS restart jobs
This change was inadvertently left out of https://github.com/CMSgov/easi-app/pull/427
=> Update lambda versions in ecs restart jobs

scripts/run-cypress-test-docker
- First iteration on backend logs in Cypress tests: this change would display the logs of the backend container if it fails to start.
=> Backend logs in Cypress tests

pkg/services/auth.go, pkg/services/auth_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- Accept, lightly verify, and store `lifecycleID` related information in the service/biz-logic layer
=> svc layer for lcid assignment

.circleci/config.yml, scripts/dockerhub-login
- Add Docker authentication where CI pulls images from Docker Hub
Starting November 1, 2020, Docker Hub will impose rate limits based on the originating IP.
See the following links for additional information:
* https://circleci.com/docs/2.0/private-images/
* https://discuss.circleci.com/t/updated-authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567
This PR adds the `auth:` configuration to `docker` executors that pull images from Docker Hub. It also adds a separate Docker login step to jobs that use `setup_remote_docker` and pull images from Docker Hub in their steps (for example, if a job has a step that builds a Docker image and the `FROM` command references an image from Docker Hub). The remote docker environment doesn't inherit …
=> Configure Docker authentication for image pulls

pkg/services/auth.go, pkg/services/auth_test.go
- Change authorizers to not throw an error when the user is unauthorized
=> Authorizers don't return errors when not necessary

pkg/handlers/system_intake.go, pkg/handlers/system_intakes_test.go, pkg/local/authorization.go, pkg/server/routes.go
- Create the transport layer translation and associated verifications for assigning a `LifecycleID`
- Wire up a route for using this functionality at `POST /api/v1/system_intake/{intake_id}/lcid`
- For local development, updated the fictional user to have GRT permissions
To test this, I stood up the server and issued the following command (against a SystemIntake that already existed):
```console
$ curl -v -X POST 127.0.0.1:8080/api/v1/system_intake/4d0665d7-83c9-4403-a25e-7c991ea68178/lcid --data-raw '{
"lcidExpiresAt": "2021-09-10",
"lcidNextSteps": "fuhgeddaboutit",
"lcidScope": "telescope"
}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 …
```
=> lcid transport layer

src/reducers/requestRepoReducer.test.ts, src/reducers/requestRepoReducer.ts, src/reducers/rootReducer.ts, src/sagas/requestRepositorySaga.ts, src/sagas/rootSaga.ts, src/types/routines.ts
Before we can generate a CSV of requests that populate in the table for reviewers to download, we need to be able to request that data and store it on the front end. In this PR, I added all the necessary boilerplate to be able to request and store that data on the client. 
Once get endpoint is created for reviewers, I will be able to add it to https://github.com/CMSgov/easi-app/blob/4819d9a96087676eb82334a0a0fdbcdb09d8eaa6/src/sagas/requestRepositorySaga.ts#L9
=> Add request repository reducer

cypress/integration/taskList.spec.js, src/views/GovernanceTaskList/index.tsx, src/views/SystemIntake/ContractDetails/index.tsx
Currently, the form doesn't clear out the source dropdown if the user toggles there is no funding source. This PR "resets" that dropdown so the data is valid.
=> fix minor bug in contract details form inputs

cypress/integration/taskList.spec.js
We have a flakey cypress integration test for the task list. It's unclear why this test is failing, but it seems to think that the start button is "detaching" from the DOM. I don't know why it's happening considering there aren't any requests to wait for. There doesn't appear to be any updating occurring on the page either.
In order to make sure the button is on screen, I'm adding another expectation before it clicks. The hope is that the test will wait for the button to be on screen, then click.
=> Update task list cypress test

pkg/handlers/system_intakes.go, pkg/handlers/system_intakes_test.go, pkg/server/routes.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Created a data-layer accessor for grabbing all (un-archived) `SystemIntakes`
- Moved the decision on whether to deliver ALL or EUA-only `SystemIntakes` to the business logic (`services`) layer
=> Deliver ALL (un-archived) SystemIntakes to GRT members

pkg/cedar/cedarldap/translated_client.go, pkg/services/system_intake_action.go, pkg/services/system_intake_action_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- finish applying the pattern of handing around `context` for handling "cross-cutting concerns" in the CEDAR LDAP wrapper package
=> pass context, not logger

pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- If requesting a `SystemIntake` by ID, return it even if it is in archived state (people should still be able to see historical records when they want to)
=> fetch irrespective of status

migrations/V41__Change_Draft_Submitted_Statuses.sql, pkg/appvalidation/business_case.go, pkg/appvalidation/business_case_test.go, pkg/cedar/cedareasi/translated_client_test.go, pkg/handlers/system_intake_test.go, pkg/integration/business_case_test.go, pkg/integration/system_intakes_test.go, pkg/models/system_intake.go, pkg/services/business_case_test.go, pkg/services/system_intake_action.go, pkg/services/system_intake_action_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/storage/business_case_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go, pkg/testhelpers/system_intake.go, src/data/systemIntake.test.ts, src/data/systemIntake.ts, src/data/taskList.ts, src/reducers/requestRepoReducer.test.ts, src/reducers/systemIntakeReducer.test.ts, src/reducers/systemIntakesReducer.test.ts, src/types/systemIntake.ts, src/views/GovernanceReviewTeam/IntakeReview/index.test.tsx, src/views/GrtSystemIntakeReview/index.tsx, src/views/Home/index.test.tsx, src/views/Home/index.tsx
- Replaces DRAFT and SUBMITTED with INTAKE_DRAFT and INTAKE_SUBMITTED as intake statuses
=> Rename DRAFT and SUBMITTED intake statuses

src/components/shared/RadioField/index.tsx, src/i18n/en-US/intake.ts, src/views/App/index.tsx, src/views/RequestTypeForm/index.test.tsx, src/views/RequestTypeForm/index.tsx
This PR adds:
- the view of the request type form for users to select their request type
- viewable at `/system/request-type`. there was not direction on what the URL should be so i guessed. this is can be changed
This PR does **not** add:
- action on the `Continue` button click
- backend work
- front end navigation or intake creation
This is JUST the view
=> add request type form page

src/data/taskList.ts, src/views/GovernanceTaskList/index.tsx
I'm looking for feedback on this PR because I am having trouble figuring out how to maintain existing functionality with statuses in both intake and business case while we try to transition all the new statuses onto the intake.
This PR does NOT do any backend work or connect to the new actions API. That will come in another PR.
In order to verify this PR, you need to update the status of an intake to `BIZ_CASE_DRAFT_SUBMITTED`, and view the task list.
=> add additional status to business case task list item

pkg/server/routes.go, pkg/services/auth.go, pkg/services/auth_test.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- Stops using specialized auth for business case
- Moves necessary auth to services/auth.go
=> Remove old Business Case auth

.circleci/config.yml
- Remove unused cache steps from the integration_tests job
With the changes made by https://github.com/CMSgov/easi-app/pull/471, the `integration_tests` job doesn't currently use the yarn and node module caches that are handled via `restore_cache` and `save_cache`, and instead relies on the docker layer caching. Since these steps aren't currently being used, we can remove them and save ~ 20-25 seconds from the `integration_tests` job.
=> Remove unused cache steps for integration tests

migrations/V46__LCID_constraints.sql, pkg/storage/system_intake_test.go
- update the db-enforced pattern for acceptable LCIDs... We've found on this ticket that whereas newly generated LCIDs will look like ~"YYdddN", historical ones might have a one-alpha-character prefix ~"PYYdddN" (e.g. "A220019" vs "220019")
=> accept historic lcid

src/components/Header/index.tsx, src/components/shared/HelpText/index.tsx, src/components/shared/RadioField/index.tsx, src/data/systemIntake.ts, src/types/systemIntake.ts, src/validations/systemIntakeSchema.ts, src/views/App/index.tsx, src/views/Home/WelcomeText.tsx, src/views/RequestTypeForm/index.tsx
This PR connects the FE and BE pieces of the request type question.
When visiting `/system/request-type`, a user will be able to select their request type. This form has validations for required ness.
**NOTE**: Once you select an option and hit `Continue`, an intake record will be created, **but you will not be redirected**. I'm working on a separate PR for the redirection. That piece is a little tricky so I wanted to experiment with a different idea.
=> Integrate FE and BE pieces of the request type question

pkg/server/health_check.go, pkg/server/routes.go
- Log at non-`Error` level for CEDAR instability upon startup of EASi
- Don't invoke a dead/no-op codepath
=> lessen severity of CEDAR connection issues

src/types/action.ts, src/views/SystemIntake/Review/index.tsx
- Rename SUBMIT to SUBMIT_INTAKE on the client
=> Fix Submit Intake action type name on client

pkg/handlers/notes.go, pkg/server/routes.go, pkg/services/notes.go, pkg/services/notes_test.go, pkg/testhelpers/authn.go
- Add svc and handler layers for retrieving notes associated with a given `SystemIntake`
- Wire up so that this will be active path: `GET /system_intake/{intake_id}/notes`
=> read-side api for retrieving notes

src/components/RequestRepository/index.tsx
- Don't wrap column headers
Old:
New:
=> Do not wrap the text for table headers.

src/views/Home/SystemIntakeBanners.tsx
Intake banners with the request types `NEW`, `MAJOR_CHAGES`, and `RECOMPETE` should link to the task list (except on prod, because the task list feature flag is off).
Intake banners with the request type `SHUTDOWN` should link directly to the intake for,
=> update links from the home page banners

src/components/RequestRepository/index.tsx
- Changed logic to insert i18n status into table instead of database enum
=> Fix for request repository status sorting issue

pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Attaches an associated biz case ID to a system intake even if that biz case is closed
=> Attach biz case ID to intake even if CLOSED

pkg/handlers/notes.go, pkg/handlers/notes_test.go, pkg/models/note.go, pkg/server/routes.go, pkg/services/notes.go, pkg/services/notes_test.go, pkg/storage/note.go, pkg/storage/note_test.go
- Add an API endpoint for creating a note
- Return the entire note from the create storage function, not just the ID, to avoid making two requests per API interaction.
=> API to create a note

src/components/BusinessCaseReview/RequestDescriptionReview/index.tsx, src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/components/SystemIntakeReview/index.tsx, src/views/BusinessCase/Review/AsIsSolutionReview.tsx, src/views/BusinessCase/Review/ProposedBusinessCaseSolutionReview.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap
- Replace 'text-pre' with 'text-pre-wrap' so the text on review screens wraps properly.
=> Use text-pre-wrap to wrap text.

src/i18n/en-US/businessCase.ts, src/reducers/businessCaseReducer.test.ts, src/reducers/businessCaseReducer.ts, src/types/businessCase.ts, src/views/BusinessCase/Confirmation/index.tsx, src/views/BusinessCase/index.tsx
Since the business case no longer submits (it updates intake status via action api), we need to keep track of the `isPosting` from the Action reducer. The redirect wasn't working because the component was using the deprecated `isSubmitting` from the business case.
This PR makes the old solution work. We can probably improve the redirect after submit mechanism.
NOTE: Haven't tested locally. Local environment having issues.
=> Update redirects after requester submits business case

src/reducers/businessCaseReducer.test.ts, src/reducers/businessCaseReducer.ts, src/sagas/businessCaseSaga.ts
This PR stores the form data **before** the `PUT` business case request is made. There was a race condition between the saving of the data and the data that gets loaded onto the next page.
I am currently brainstorming other ways to avoid this (e.g. navigating to the next page after save is complete), but this is a first swing at solving our problems.
=> Update business case reducer to store payload before the request is made

src/views/GovernanceReviewTeam/Notes/index.tsx, src/views/GovernanceReviewTeam/index.tsx
- Add a new stubbed page for notes
=> Add stubbed page for notes.

pkg/handlers/system_intake.go, pkg/handlers/system_intakes_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- When generating a lifecycle ID, return the intake with the new values
- LCID generation is working swell locally, but not working at all in impl. Trying to get more information to help the debugging process.
- Somewhere, we should probably make it a convention that a POST request returns the thing created
=> Return intake from LCID generation to help debug deployed environments.

src/reducers/systemIntakeReducer.ts, src/sagas/actionSaga.ts, src/sagas/systemIntakeSaga.ts, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx
- Fire the action to change status first and the LCID action after
- Update the intake reducer when the LCID action finishes so user doesn't have to refresh to see new LCID and updated status
Background info:
Before this change, we were firing the action and LCID POST requests at the same time. The LCID often finished first, and returned the proper values. The action request finished second, and the save to the status of the intake would overwrite the values from the LCID response. So this PR changes the frontend code to call these API endpoints sequentially, rather than simultaneously.
=> Fix lcid race condition

src/data/taskList.ts, src/views/GovernanceTaskList/TaskListCta.tsx
- When the reviewer selects the "Provide GRT feedback and move business case to final" in the business case section the tag will be updated to "Completed" and a link to the business case will be displayed.
=> Added additional handling for final draft of business case in task list

src/reducers/authReducer.test.ts, src/reducers/authReducer.ts, src/views/App/index.tsx, src/views/Home/index.test.tsx, src/views/Home/index.tsx, src/views/UserInfoWrapper/index.tsx
For notes, we need to pass in the user's name from the id token since it's not included in the access token that's passed to validate the API request.
We're currently only setting `groups` in the `authReducer`. Since we need at least the user's name, I thought this might be a good time to add in the user's EUA ID to the reducer as well.
In addition to adding these values into the reducer, there's a bit of renaming too.
=> update auth reducer to include name and eua id

src/i18n/en-US/governanceReviewTeam.ts, src/reducers/systemIntakeReducer.test.ts, src/reducers/systemIntakeReducer.ts, src/sagas/systemIntakeSaga.ts, src/types/routines.ts, src/types/systemIntake.ts, src/views/GovernanceReviewTeam/Notes/index.tsx, src/views/GovernanceReviewTeam/index.tsx
This PR hooks up the "Add note" button to create a note. This PR **does not** implement any way to view created notes on the UI.
Two ways to verify notes have been created are to:
1. View the note in the DB
2. View the note in the Redux Dev Tools
Viewing created notes will be handled in a separate ticket/story.
As far as ticket management goes, I will probably finish the list/view of the notes before setting this ticket to "Review"
=> Add functionality to create notes

.spelling, docs/adr/0022-generate-pdfs-with-prince.md, docs/adr/index.md, lambda/prince/index.js, pkg/handlers/pdf.go, pkg/server/routes.go, src/components/PDFExport/index.tsx, src/contexts/flagContext.test.tsx, src/contexts/flagContext.tsx, src/index.scss, src/stylesheets/print.scss, src/types/flags.ts, src/views/GrtSystemIntakeReview/index.tsx, src/views/SystemIntake/ViewOnly/index.tsx
The backend needs to have the `PDF_GENERATOR_LAMBDA_URL` environment variable set. Ping me in Slack and I'll give you a value to use in the short term.
- Add a `/pdf/generate` endpoint that accepts the HTML of a page and passes it to a Lambda function.
- This Lambda function converts the HTML to a PDF using [Prince](https://www.princexml.com)
- The resulting PDF is returned to the frontend, where it is then downloaded to the user's computer.
Please check out the included ADR to see more of the background that went into this particular solution.
Here is an example PDF that is created through this process: [generated.pdf](https://github.com/CMSgov/easi-app/files/5538358/generated.pdf)
=> Proof of Concept for PDF download

migrations/V56__Update_Intake_For_Rejection.sql, migrations/V57__Add_Reject_Action_Type.sql, pkg/handlers/system_intake.go, pkg/handlers/system_intakes_test.go, pkg/models/action.go, pkg/models/system_intake.go, pkg/server/routes.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Add an API endpoint to reject an intake request
- There is one field that is shared between the lifecycle ID and the reject, so I made it more generic. But happy to have two fields if folks see a reason to keep them separate.
- There will be a follow-up PR to remove the old db column once the "rename" PR is deployed to prod.
=> Rejection API

pkg/models/system_intake.go, src/components/RequestRepository/index.tsx, src/sagas/systemIntakesSaga.ts
- Add a filter to the saga for fetching intakes
- Use it for the open requests table
=> Only show open requests in table

migrations/V58__Intake_EUA_Drop_Not_Null.sql, pkg/cedar/cedareasi/translated_client.go, pkg/cedar/cedareasi/translated_client_test.go, pkg/handlers/system_intake.go, pkg/handlers/system_intake_test.go, pkg/integration/business_case_test.go, pkg/integration/system_intakes_test.go, pkg/models/system_intake.go, pkg/services/action.go, pkg/services/auth.go, pkg/services/auth_test.go, pkg/services/business_case_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/storage/business_case_test.go, pkg/storage/note_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go, pkg/testhelpers/rand.go, pkg/testhelpers/system_intake.go
- Remove the db constraint that a SystemIntake has an EUA_ID (to support backfill data that doesn't have EUA_ID available)
=> nullable euaID

src/views/GovernanceTaskList/TaskListItem.test.tsx, src/views/GovernanceTaskList/TaskListItem.tsx, src/views/GovernanceTaskList/index.tsx
This PR slightly restructures the task list item.
It removes `description` as a prop and allows us to add the description as a child of the `TaskListItem`. This is needed because step 3 (Prepare your Business Case for the GRT) requires multiple paragraphs which we didn't support before. This also moves us to a slightly more declarative pattern (rather than passing props).
=> update task list item structure

src/data/taskList.ts, src/views/GovernanceTaskList/index.test.tsx
For a **RECOMPETE** request:
Once a reviewer has made an action to issue an LCID (status: `LCID_ISSUED`):
- Step 3, 4, 5 should turn from `Cannot start yet` to `Not needed`
- Step 6 doesn't have a tag/status
=> updates tags to display not needed for recompete

migrations/V58__Add_File_Uploads_Table.sql, pkg/handlers/file_uploads.go, pkg/models/file_uploads.go, pkg/server/routes.go, pkg/services/file_uploads.go, pkg/storage/file_uploads.go
- Adds the endpoint to store the metadata around uploaded file
- Adds db migration for creating the table
=> Add endpoint to store completed file upload metadata

pkg/models/action.go, pkg/storage/action.go, pkg/storage/action_test.go, src/components/RequestRepository/index.tsx, src/i18n/en-US/governanceReviewTeam.ts, src/reducers/systemIntakesReducer.test.ts, src/reducers/systemIntakesReducer.ts, src/types/systemIntake.ts, src/views/Home/SystemIntakeBanners.tsx, src/views/Home/index.test.tsx, src/views/Home/index.tsx
- updates `systemIntake` reducers to have `openIntakes` and `closedIntakes` instead of just `systemIntakes`
- this allows us to make a single network request and have both open and closed intakes
- move up the dispatch action creator to fetch intakes up one level to the home page
- previously we were fetching intakes from the banners and the request repository component. they both use the same data and appear on the same view
=> Add closed request table to GRT review home page

pkg/handlers/backfill.go, pkg/server/routes.go, pkg/services/backfill.go, pkg/storage/system_intake.go
- Quick and dirty code (only manually tested) for importing the ~172 records from a spreadsheet... Not expected to live long, e.g. will be removed once the data is in.
=> server-side short-lived code for backfilling data from spreadsheet

src/data/systemIntake.ts, src/types/systemIntake.ts
In order to create the decision (approved/rejected) pages, we need to have the data from the API:
This PR adds the following data to our frontend intake model:
- Lifecycle ID Expiration
- Lifecycle ID Scope
- Lifecycle Next Steps
- Decision Next Steps
- Rejection Reason
It's not 100% clear how these should be presented, but all of these attributes are supported on the API already, so I'm guessing we'll use them in one way or another.
=> update frontend model to include new lcid fields

src/types/action.ts, src/types/routines.ts, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx
This PR fixes a few of the non-breaking Typescript errors we were having.
Going forward, we should have separate types for request payloads and response payloads. That's what I did in this PR for Actions. Hopefully this clears up confusion on how to use the types. We should probably also document our types so it's more clear on which to use.
=> fix action types

src/validations/systemIntakeSchema.ts, src/views/App/index.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx
This PR adds validations for the GRT and GRB dates in the reviewer track.
We decided that in order to save, one of the following criteria must be met:
- the date must be **fully** filled out
- the date must be empty
Examples:
There are other permutations, but the general idea is the dates must be fully filled out or not filled at all.
In order to test, you need the GRT job code and visit:
`http://localhost:3000/governance-review-team/:systemId/dates`
Those are the date fields you need to fill out.
=> Add validations for GRT and GRB Dates

pkg/handlers/file_uploads.go, pkg/server/routes.go, pkg/services/file_uploads.go, pkg/upload/upload.go
- Adds the ability to generate pre-signed URLs for S3 GET requests. This lets us go direct to S3 for downloading after auth.
=> Add generation of download pre-signed urls

cmd/backfill/main.go, pkg/server/routes.go, pkg/services/backfill.go
- Use the correct statuses, inferred from the state of whether or not an LCID is present
=> use proper statuses for backfill

pkg/server/routes.go, src/contexts/flagContext.test.tsx, src/contexts/flagContext.tsx, src/types/flags.ts
- Adds three new feature flags: `prototype508`, `prototypeTRB`, and `fileUploads`.
- These flags have already been configured in Launch Darkly
- If you aren't connecting to LD from your dev machine to load flags (`export FLAG_SOURCE=LOCAL`), the defaults have these new flags enabled.
=> Add flags for prototypes and file uploads

src/contexts/flagContext.tsx
Currently, I'm in a situation where `/flags` endpoint is returning `{}`, which is causing some errors. So instead of just replacing the current context with the new, I am spreading the new flags from the API over the existing flags.
=> fix ld flags

pkg/cedar/cedareasi/translated_client.go, pkg/flags/client.go, pkg/integration/cedar_test.go, pkg/server/routes.go, pkg/services/action.go
- Reorders some LD and CEDAR client initializations
- Actually use the LD client for choosing whether or not to emit to CEDAR
- Move the quality check for non-empty AlfabetID (e.g. `ExternalAPIError`) to live in the `cedareasi` client, since it is conditional on whether or not we are actually emitting downstream
- This does not substantively change the use of `flags.NewLocalClient` in non-deployed environments, to support current front-end behaviors (see ES-39 for more info)
=> Use LaunchDarkly for CEDAR conditional

src/views/Home/index.tsx
While implementing some accessibility work for the intake withdrawal confirmation, I came across a bug that needed to be fixed.
To reproduce on `master`:
1. Go to intake task list
2. Withdraw it via button in the side nav
3. Confirm
4. App should redirect you to the home page with the confirmation message.
5. BUG: Refresh and the confirmation text stays and doesn't disappear.
This will be misleading for all users so it's important to have it only show up when necessary.
In this PR, the confirmation text should disappear when the page is refreshed.
=> Clear confirmation text after page is refreshed

.spelling, README.md, docker-compose.yml, pkg/appconfig/config.go, pkg/server/config.go, pkg/server/routes.go, pkg/upload/upload.go
- Adds [MinIO](https://min.io) container for local S3 development
- Changes AWS credentials to use local minio when we detect we're local
We needed a way to test local interactions with S3 without having to interact with any CMS AWS accounts. [MinIO](https://min.io) is an S3 compatible server that is packaged in a Docker container and accepts API/SDK interaction in the same way that regular AWS S3 does. This lets us swap out calls to AWS to the local container when we are in our local environments.
Up for suggestions as this adds a new piece of local dev infrastructure, although nothing in code really changes except for the client session setup.
=> Add local S3 testing workflows

src/components/shared/ActionBanner/index.tsx, src/views/Home/SystemIntakeBanners.tsx
This PR adds decommission banners.
`INTAKE_DRAFT` -> `View intake request`
`INTAKE_SUBMITTED` -> `View submitted intake request` (link)
As far as decisions go, no idea yet; TBD
=> add decomission banner

cmd/backfill/main.go, pkg/handlers/system_intake.go, pkg/server/routes.go, pkg/services/backfill.go, pkg/services/system_intakes.go, pkg/storage/system_intake.go
- Given the correct input to the executable, optionally send an API command to remove the given SystemIntakes by ID
- Server-side code to facilitate deleting the SystemIntake and associated Notes. This is fairly quick & dirty code that is expected to be removed quickly, but it has been tested to work locally.
- Also spotted that `submitted_at` still wasn't updating, and added the code necessary
=> Nelz backfill drop

src/views/GovernanceTaskList/RequestDecision/Approved.tsx, src/views/GovernanceTaskList/RequestDecision/Rejected.tsx
We're using an outdated/wrong field to display next steps for a requester. it should be `decisionNextSteps`, not `lifecycleNextSteps`. That API key will be dropped in a separate PR.
=> update decision pages to use correct data

pkg/models/system_intake.go, src/i18n/en-US/intake.ts, src/views/Home/SystemIntakeBanners.tsx
There's a lot to test for this. I'll try my best to give some rough steps
1. Create a shutdown/decommission request
2. VERIFY: Before submitting verify the requester banner state that an intake draft is incomplete.
3. Submit the request
4: VERIFY: Requester banner state is intake submitted; awaiting response.
5. Switch to a reviewer and do the action of sending an email.
6. Switch to a requester, check that the banner state is now decommission in progress
7. Switch to a reviewer, check that the statuses change accordingly for each of the action radio options
8. As a requester, I shouldn't see any banners for shutdown/decommission requests once the request is closed. This flow is mostly communicated via email. The only banners a requester should see for shutdown/decommission are for intake …
=> add decommission banner stuff

src/data/systemIntake.ts, src/types/systemIntake.ts, src/views/GovernanceTaskList/RequestDecision/Approved.tsx, src/views/GovernanceTaskList/RequestDecision/Rejected.tsx, src/views/GovernanceTaskList/index.tsx
- remove `lifecycleNextSteps` from frontend model
- this is what messed me up. the conditional was still hiding the next steps
- grt/grb dates were displaying incorrectly, we gucci now.
=> fix various task list stuff

pkg/models/system_intake.go
- `ArchivedAt` was the only field on a `SystemIntake` that was being JSON Marshaled with a leading capital letter
=> missing a json field tag

pkg/server/health_check.go, pkg/server/routes.go
- my previous PR in this area had a bug where we accidentally had ALL environments using the Mock version of the CEDAR EASi client, regardless of configuration values; this change ensures we use the intended client in deployed environments
=> EASI-834 use proper client in deployed envs

src/components/RequestRepository/index.tsx, src/components/shared/ActionBanner/index.test.tsx, src/components/shared/ActionBanner/index.tsx, src/i18n/en-US/intake.ts, src/utils/systemIntake.ts, src/views/GovernanceReviewTeam/index.tsx
Previously, the GRT reviewer header had the request type hardcoded as `N/A` because that field didn't exist yet.
Now we're adding the request type in.
- move enum out of the i18n file so we can have a generic i18n key
- add util for translating the request type from enum to human readable value
- replace all use cases of the previous i18n key
- add request type to GRT reviewer header
=> add request type to the grt review header

src/index.tsx, src/views/BusinessCase/index.tsx, src/views/SystemIntake/index.tsx
There've been a few instances in this project where we've done `process.env.SOME_VAR  || ''` to hack our way past some Typescript errors. I thought this might be a good time to fix it.
`process.env` is typed as
```
export interface ProcessEnv {
[key: string]: string | undefined
}`
```
Since environment variables can be `undefined`, the Typescript compiler throws some errors for some methods. The main violator in this application is `Array.prototype.includes()`. `Array.prototype.includes()` expects a `string`, which is why we get the error below:
`Argument of type 'string | undefined' is not assignable to parameter of type 'string'`
However, the following statements don't throw errors. There's some debate within the Typescript community whether the type definition is too narrow.
``` …
```
=> clean up process.env typescript error hack

src/validations/systemIntakeSchema.ts, src/views/GovernanceReviewTeam/Dates/index.tsx
In the bug, we discovered that invalid dates were able to be created.
e.g. Month = 53, Date = 53.
This PR fixes that, it's a little bit messy and there _might_ be a few edge case, but it _works_
I tested for the following cases. Please feel free to do me a favor and verify them too.
- There are some "edge cases". I'm not completely sure if they are edge cases. For example, year can be any number. We are relying on `luxon` to create a valid date based on it's month, day, and year. We check the `DateTime` with `.isValid` (from `luxon`). Date validity is checked by `luxon`.
tl;dr; Date validity is ONLY checked when ALL fields (month, date, year) are filled. Otherwise, the validation is making sure that the fields are filled. Each date is "all or nothing" (e.g. month, date, year filled, or …
=> Update GRT/GRB reviewer date validations

src/validations/actionSchema.ts, src/validations/businessCaseSchema.ts, src/validations/systemIntakeSchema.ts
This PR trims all text/textarea input values before validating them. This PR DOES NOT alter any user input. If a user has any whitespace, those will be preserved. Whitespace with text will pass validation, but ONLY whitespace will fail.
In the example below, `CMS Business/Product Owner's Name` only has whitespace, it fails validation. `CMS Project/Product Manager, or lead` has whitespace, but it also has text, so it passes validation.
If we want to remove leading/trailing whitespace, let's create a story for that and have a discussion how/when/where it should happen.
=> add trim to all validated fields

.circleci/config.yml
- Update ecs-manager revision to 19 in DEV
CircleCI will now invoke the latest lambda revision, which has the default Waiter timeout settings.
=> Update ecs-manager revision to 19 in DEV

docker-compose.yml, package.json, src/components/BusinessCaseReview/index.scss, src/components/BusinessCaseReview/index.tsx, src/components/PDFExport/index.tsx, yarn.lock
- Use a stylesheet's origin to determine if it should be included when generating a PDF.
=> Use document origin instead of protocol to filter stylesheets

src/views/GovernanceTaskList/TaskListCta.tsx, src/views/GovernanceTaskList/index.test.tsx
This PR ensures that a user can still view their submitted intake on task list item 1, no matter where they are in the governance process.
- added tests too to make sure that link is visible.
=> add "view submitted request" to task list item 1 for every status

src/i18n/en-US/intake.ts, src/views/SystemIntake/Confirmation/index.tsx, src/views/SystemIntake/index.tsx
After the requester submits their intake. They should be redirected to a confirmation page that displays their intake request id.
=> add intake submission confirmation page

src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx
- Changed SurveyMonkey URL in GRT decision pages to use correct survey
=> Modified GRT decision pages survey to point to correct url

.circleci/config.yml
Follow-on to https://github.com/CMSgov/easi-app/pull/665.
- Update ecs-manager revision to 7 in IMPL, PROD
CircleCI will now invoke the latest lambda revision, which has the default Waiter timeout settings.
=> EASI-1069 Update ecs-manager revision to 7 in IMPL, PROD

.github/PULL_REQUEST_TEMPLATE.md
- by default, point the PRs to the Scylla project ("ES" as ticket prefix)
=> ES-246 template points to scylla project

package.json, yarn.lock
There is a patch release of react-scripts. This PR bumps the version we're using in our app to be up to date with the latest release.
=> Bump react-scripts to 4.0.1

pkg/cedar/cedareasi/translated_client.go, pkg/flags/client.go, pkg/flags/client_test.go, pkg/integration/cedar_test.go, pkg/server/routes.go, pkg/services/config.go
- in talks with Jimil, it's okay to do per-user targeting of functionality via LaunchDarkly, as long as we're not using raw EUA IDs as identifiers within LD, so we build the LD User object with a key derived from the EUAID by a one-way cryptographic hash
- pass this user object in when doing flag evaluations that that features can be turned on/off per individual user
- simplify the init of the LaunchDarkly client at start-up time
- make the LD Client usable by functions created in the `services` package (by way of the `Config` type)
=> ES-249 LaunchDarkly targeting and simplified init

.eslintrc, src/components/RequestRepository/index.tsx, src/components/shared/ActionBanner/index.tsx, src/components/shared/DateInput/index.tsx, src/components/shared/DropdownField/index.tsx, src/components/shared/RadioField/index.tsx, src/components/shared/SearchBar/index.tsx, src/components/shared/TextAreaField/index.test.tsx, src/components/shared/TextAreaField/index.tsx, src/components/shared/TextField/index.test.tsx, src/components/shared/TextField/index.tsx, src/views/DocumentPrototype/index.tsx
We are consistently disabling the eslint rule that prevents prop spreading. It is most commonly used when we want to apply `aria-*` attributes. It doesn't make sense to explicitly write out each ARIA or HTML attribute.
We have `eslint-disable-next-line react/jsx-props-no-spreading` littered throughout the codebase and I think it's time to put that rule to rest because we are consistently disabling it.
=> remove no spreading props eslint rule

.circleci/config.yml
- Block IMPL deployments on a successful DEV deployment.
We want to ensure that deployments to IMPL are still performed any time we merge to master. I believe `hold_dev` will not get in the way since that step being filtered on the master branch, but I can't confirm that until this is merged in.
=> Block IMPL deploy on successful DEV deploy

craco.config.js, src/stylesheets/_uswdsUtilities.scss
I went down a rabbit hole while configuring storybook and I'm fixing two small things in this PR.
1. Add USWDS design tokens
- Traditionally we've used the USWDS class names.
- I imported some of the variables from USWDS so we can use them in our CSS. For example: `color: color('primary-vivid')` or mixin with `@include u-text('primary-vivid')`. There's a lot more we can do, so reference the [documentation](https://designsystem.digital.gov/) if there are any questions.
- Not sure if I got all the files, but this is a good start. I haven't heard any complaints in the past, so I think we should be good.
2. Disable USWDS changelogs.
- super annoying; finally turning them off
=> Add USWDS design tokens to app

src/components/BusinessCaseReview/index.scss, src/views/BusinessCase/Review/index.scss, src/views/BusinessCase/Review/index.tsx, src/views/BusinessCase/ViewOnly/index.tsx, src/views/GovernanceReviewTeam/IntakeReview/index.tsx, src/views/SystemIntake/ViewOnly/index.tsx
- Adjust the padding of the PDF download link so that it lines up with the left margin of various screens. I added a wrapper div so that we could target the button in a few cases where that page's layout required some adjustments to the general styles.
- Updated the system intake PDF download links to "Download System Intake as PDF" from the generic "Download PDF"
Here are some screenshots of various pages after this PR is applied:
=> Adjust padding of PDF link to align on all screens.

pkg/handlers/systems.go, pkg/models/system.go, pkg/server/routes.go, pkg/services/systems.go, pkg/storage/system.go
- lightweight storage layer API for fetching systems, with a fake in-memory implementation
- quick `services` and `handlers` layers for an endpoint exposing the systems list
- this is intended to be a quickie implementation to just set up some structure, future iteration goals:
- actually wire up to the database
- maybe we want to expose the systems via GraphQL, rather than via RESTful endpoint?
Proved this out via the following:
```console
$ curl -H 'Authorization: Bearer {"euaId":"NELZ"}' 127.0.0.1:8080/api/v1/systems | jq .
[
{
"lcid": "X990000",
"createdAt": "2020-01-01T08:00:00Z",
"updatedAt": "2020-01-01T08:00:00Z",
"issuedAt": "2020-01-01T08:00:00Z",
"expiresAt": "2021-12-31T08:00:00Z",
"projectName": "Three Amigos",
"ownerId": "FAKE0", …
```
=> ES-255 ES-274 list systems

pkg/integration/integration_test.go, pkg/models/system.go, pkg/server/routes.go, pkg/services/services_test.go, pkg/storage/store.go, pkg/storage/store_test.go, pkg/storage/system.go, pkg/storage/system_test.go
- get the LD client available at the `storage` layer
- build retrieval layer for fetching `System`s from the `system_intake` table
- flag-optionally return either fake or "real" data
=> ES-255 feature flag fake vs real data for systems

.circleci/config.yml, .gitignore, scripts/release_storybook_static
- Deploy storybook static assets to dev
The idea here is that building the storybook assets would occur on every branch to try and avoid breaking the build in master, but deploying the storybook assets would only occur on master. Since the built storybook files don't change between `client_test` and `deploy_storybook_dev`, this uses the circleci workspace to copy the files from `client_test` to `deploy_storybook_dev`.
=> ES-292 Deploy storybook static assets to dev

.circleci/config.yml, package.json, src/queries/types/CreateAccessibilityRequest.ts, src/queries/types/GetAccessibilityRequests.ts
We didn't add anything to CI that attempts to generate code from our GraphQL schema, which meant that we were able to check in some code that broke the client app.
This PR fixes the issue with generation and includes a very rough stab at running the code generation as a part of CI. We'll want to have a follow-up story that does a little more (e.g. checks to make sure that the generation didn't result in a difference in any of the files).
=> Fix GraphQL code generation

pkg/models/system.go, pkg/storage/system.go, pkg/storage/system_test.go
- some `SystemIntake` data was imported into PROD w/o an EUA ID assigned, make sure our SQL and types handle that
=> ES-329 some intakes have NULL eauID

pkg/server/routes.go
- moved the GraphQL subrouter to be at `/api/graph` (used to be at top level `/graph`)
- don't re-init another copy of the `storage` layer
- tiny bits of tidying up around middlewares
Tested this by:
- running the server locally
- pulling up `http://localhost:8080/api/graph/playground` 
- making sure it was interacting with the query engine backend as expected
=> ES-274 cloudfront-friendly routes

pkg/server/routes.go
- #719 accidentally forced the healthcheck to require some Auth-related headers in deployed environments, this PR undoes that
=> ES-274 no authn reqd for healthcheck

.spelling, docs/adr/0023_508_systems_list_as_view_of_system_intakes.md, docs/adr/index.md
- ADR to record why we made the choice to drive the Systems List off the `system_intakes` table
=> ES-255 systems list ADR

pkg/models/system.go, pkg/storage/system.go, pkg/storage/system_test.go
- For the ID (uuid) of the `SystemIntake`/`system_intake` row where the given LCID was issued, make it available on the `System` type
Tested locally:
```shell
$ curl -H 'Authorization: Bearer {"euaId":"NELZ"}' 127.0.0.1:8080/api/v1/systems | jq .
[
{
"intakeId": "00000000-9999-0000-0000-000000000000",
"lcid": "X990000",
"createdAt": "2020-01-01T08:00:00Z",
"updatedAt": "2020-01-01T08:00:00Z",
"issuedAt": "2020-01-01T08:00:00Z",
"expiresAt": "2021-12-31T08:00:00Z",
"projectName": "Three Amigos",
"ownerId": "FAKE0",
"ownerName": "Lucky Dusty Ned"
},
{
"intakeId": "00000000-8888-0000-0000-000000000000",
"lcid": "X990001",
"createdAt": "2020-01-01T08:00:00Z",
"updatedAt": "2020-01-01T08:00:00Z",
"issuedAt": "2020-01-01T08:00:00Z",
"expiresAt": …
```
=> ES-274 intake id avail on systems

package.json, yarn.lock
This PR upgrades Typescript to `v3.7.5`
**Why?**
TIL about [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). It'd be great to have/use.
It got support from [Typescript](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) in `v.3.7`. For reference, we are on `v3.6.4`
**How did you pick v3.7.5?**
I just picked the latest patch version on `v3.7`. We should think about getting to the latest version (`v.4.1`), but for now, it's safer to update to a minor version.
=> upgrade typescript to 3.7.5

.circleci/config.yml, scripts/check_ecr_findings
- Revert to version 1 of ecr-scan lambda
The recent refactor appears to have introduced a bug whereby the code
didn't properly handle the situation where the initial call to describe
image scan findings sometimes returns empty results. The error was
intermittent and/or rerunning the job would succeed.
I'll work on a fix the newer version of the lambda, but for now this will revert to a known good state.
=> Revert to version 1 of ecr-scan lambda

.storybook/main.js, src/components/PageHeading/__snapshots__/index.test.tsx.snap, src/components/PageHeading/index.stories.tsx, src/components/PageHeading/index.test.tsx, src/components/PageHeading/index.tsx
In a design sync, design wants to keep spacing/margin consistent.
One of the main elements that appears on every page is the h1. Moving forward, the plan is to use this component for any h1 that appears at the top of the page.
I think using this component in views will be easier than adding className="margin-top-6 margin-bottom-5" to every h1.
Old PR: #737
=> add page heading component

migrations/V65__Pluralize_Tables.sql, pkg/storage/accessibility_request.go, pkg/storage/business_case.go, pkg/storage/note.go, pkg/storage/system.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
Based on [a discussion in Slack](https://trussworks.slack.com/archives/C01BCRE1Q20/p1611607527123300), we'd like to have all tables use the same naming scheme. The team had a mild preference for plural names.
- Add a migration to pluralize table names
- Update SQL to reference new table names
=> Pluralize table names

pkg/storage/business_case_test.go
- Adds a unit test for `storage. FetchOpenBusinessCaseByIntakeID`, which should prevent something like the type fixed in #759 from happening again.
=> Add test for FetchOpenBusinessCaseByIntakeID

pkg/storage/system.go
- default to using the db as the source of truth for `System`
=> ES-274 default to db data for systems

README.md, pkg/server/routes.go
- add a env var triggered output of the routes upon startup, intended for debugging purposes
- as per discussion on (closed) #739 
```shell
$ DEBUG_ROUTES=1 ./bin/easi serve
...
ROUTE: /api/v1/healthcheck
Path regexp: ^/api/v1/healthcheck$
Queries templates:
Queries regexps:
ROUTE: /api/graph/playground
Path regexp: ^/api/graph/playground$
Queries templates:
Queries regexps:
...
```
=> helper to debug route issues

src/i18n/en-US/accessibility.ts, src/i18n/en-US/home.ts, src/stylesheets/custom.scss, src/views/Accessibility/AccessibiltyRequest/List/index.tsx, src/views/Home/index.tsx
This PR adds the accessibility/508 requests table to the home page. It only shows up for 508 testers/admins job code.
The secondary nav is added in #770
=> Add accessibility requests table to home page

src/views/Accessibility/AccessibiltyRequest/List/index.tsx, src/views/Home/index.tsx
For the 508 tester/admin home page view, there is a `SecondaryNav` that fits the entire width of the viewport.
Currently, the `MainContent` has `className="grid-container"` that restricts the width to `1200px`. Since the content inside of `<main>` can vary depending on the user permissions, it's best to move it up a layer.
=> Update home page structure

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/resolver.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/server/routes.go, pkg/upload/upload.go, src/components/FileUpload/index.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx, src/views/App/index.tsx
This is the first PR for ES-266. I will follow up with another that adds the second mutation (for recording the document in our system) and probably one more to tie the UI and API together.
- Adds a new page with a form for uploading a document
- Adds a new resolver and other schema changes needed for the generatePresignedURL mutation.
- I adjusted some of the new routes so they were consistent.
=> Document upload UI and resolver

pkg/graph/schema.resolvers.go, pkg/storage/file_uploads.go, src/queries/GetAccessibilityRequestQuery.ts, src/queries/types/GetAccessibilityRequest.ts, src/types/graphql-global-types.ts, src/views/Accessibility/AccessibiltyRequest/Documents/index.tsx
- Query docs from the db to return to the front end
- Map the props at the db layer to the props we define in the schema
Out of scope for now:
- We're not searching using the Accessibility Request id because that db connection doesn't exist yet. But the plumbing is all there for when we make the connection!
=> First pass at data-backed documents.

.circleci/config.yml
- Add missing "command" to the run steps associated with daily rescanning of deployed images.
=> Add missing command to run step

src/views/Accessibility/AccessibiltyRequest/Create/index.tsx
This PR changes how we store systems locally queried by GraphQL.
Previously, whenever a project was selected on the accessibility request form, we would iterate over the array of systems to find the matching id.
Now we are storing the systems in an object, with the `id` as the key and the data as the value. This is more efficient so we can use dot notation to select the system rather than iteration
=> store systems locally by object key value pair rather than array

README.md, pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, src/components/AccessibilityRequestsTable/index.tsx, src/i18n/en-US/accessibility.ts, src/queries/GetAccessibilityRequestsQuery.ts, src/queries/types/GetAccessibilityRequests.ts
- expose `relevantTestDate`
- put the calculation of what is "relevant" into the resolver (is this the correct place for that logic?)
- stubbed out some fake data for right now, future PR will hook up to actual DB calls
=> ES-344 relevant test date

src/components/shared/Label/index.test.tsx, src/components/shared/Label/index.tsx, src/components/shared/TextField/index.tsx, src/views/SystemIntake/ContactDetails/GovernanceTeamOptions.tsx, src/views/TestDate/index.scss, src/views/TestDate/index.tsx
- Update `Label` to allow intrinsic attributes
- Update `TextField` to allow custom `className`
- Add `aria-label` to test score label
- Remove/update various  classnames to match styles
=> Update spacing/styling issues on the add test date form page

cmd/devdata/main.go, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/models/accessibility_request_document.go, pkg/upload/upload.go, src/components/FileUpload/index.tsx, src/queries/CreateAccessibilityRequestDocumentQuery.ts, src/queries/GeneratePresignedUploadURLQuery.ts, src/queries/types/CreateAccessibilityRequestDocument.ts, src/queries/types/GeneratePresignedUploadURL.ts, src/types/graphql-global-types.ts, src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx
This is a followup to #783.
- Added the UI to create a document
- No longer expose `bucket` to the client
- We're currently passing the entire URL back to the server and extracting the key from that. There might be different ways we want to do this (like having the client just pass the key back), so we should talk about this. I kind of like the from end just taking a URL from the backend, using it, and then passing that same value back as an opaque identifier. Definitely open to other options here.
=> Complete basic end to end for document upload

package.json, yarn.lock
This PR updates USWDS to `v1.12.2`.
See the [release log](https://github.com/trussworks/react-uswds/releases) to see all the new features and bug fixes. We specifically updated to fix the `ComboBox` bug. I've confirmed the `ComboBox` bug is fixed.
=> update uswds to 1.12.2

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
- Adds GraphQL schema for editing a test date. We can do the backend/frontend separately after this.
=> Add graphql for editing test date

src/views/Accessibility/AccessibiltyRequest/Documents/index.tsx
This PR fixes the 508 table list keys error:
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `AccessibilityDocumentsList
```
=> Fix React keys error on 508 document table list

src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx
This PR adds a confirmation message after a 508 document has been uploaded.
1. Visit `/508/requests/508_REQUEST_ID`
2. Click `Upload a document`
3. Add a document and click `Upload document`
See the confirmation message!
=> add confirmation message to document upload

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, src/queries/GetAccessibilityRequestQuery.ts, src/queries/types/GetAccessibilityRequest.ts, src/views/Accessibility/AccessibiltyRequest/Documents/index.tsx
- Replaced `key` in schema with `url` since we want the client to treat the path for documents as opaque.
- Generate a pre-signed URL for each document and return that as the document's URL
- Extend existing resolver tests to query for documents
- Update UI to use URL
- Open new tab/window when viewing documents
- Add accessibility hints so that users know the view link opens in a new window
Here is a recording of Voiceover reading through the page. It says "View document type. Opens in a new tab or window" when it moves over the `View` link (you'll need to turn the video's audio on!):
https://user-images.githubusercontent.com/3331/108778021-59c39c00-752a-11eb-8c38-f88ed44b3cf5.mov
=> View accessibility request documents

pkg/graph/schema.resolvers.go, pkg/storage/test_date.go
- grab actual registered test dates for a given request to be evaluated as "relevant"
=> ES-344 wire up relevant to db

src/views/Accessibility/AccessibiltyRequest/Create/index.tsx
The `ComboBox` has issues with updating when the `options` are dynamic and get "re-initialized". The first render following the change has the old values. It's not clear whether this is a bug in `react-uswds` (my gut says no).
This became an issue because React would render the `ComboBox` while the data was still getting queried, causing the initial render to have no options. That's why the `projectComboBoxOptions.length > 0` was there.
However, it's _technically_ possible that there would be no systems returned from the API. At that point we should see the combo box and see that there aren't any options. The existing code would hide the field all together because there aren't any options. The fix will show the field with 0 options.
=> use loading from graphql query to display the combo box

src/components/AccessibilityRequestsTable/index.tsx
This PR fixes:
- the 508 table date accessor
- uses the type created from graphql instead of rolling our own
=> update accessor in the 508 table data for test dates

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, src/types/graphql-global-types.ts
- GraphQL changes for adding a type to a document
=> Add Document Type Graphql

src/views/Accessibility/AccessibiltyRequest/Documents/index.tsx
- Use a standard `a` tag for the view document link to avoid appending the full URL after the current host in deployed environments.
- Move the "in a tab" text inside the link for assistive technology
=> View document link fixes

src/components/TestDateCard/index.test.tsx, src/components/TestDateCard/index.tsx
This PR fixes a bug where the test score cannot be 0. When a test score is 0, the UI displays "Score not added" because 0 is a  falsy value.
This PR checks for 0 and returns 0%
=> allow 508 test score of 0 

src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/AccessibiltyRequest/Create/index.tsx, src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx, src/views/TestDate/index.tsx
- The subnav should also route to home for now
=> Route to home instead of the current request

pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/storage/accessibility_request_document.go, pkg/upload/upload.go, src/views/Accessibility/AccessibiltyRequest/Documents/index.tsx
_Note: this is sitting on top of #807- only the last two commits are unique to this PR._
This is a stopgap while we sort out how to notify the backend that a virus scan has completed.
We're fetching the object tags from S3 for each document, which is slow, but it'll work in the short term. We could make these requests in parallel, but that's really just a slightly better hack since we shouldn't be making these network calls from within a resolver in the first place.
=> Fetch tags from S3

src/components/FileUpload/index.tsx
- Allows any file to be uploaded if no `accept` prop passed
=> File upload isFileTypeValid allows any file if no accept prop

pkg/upload/upload.go, src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx
- Add the `Content-Type` to the params used when presigning the PUT URL
- Avoid using `FormData` to serialize the upload form so that we can set the correct `Content-Type` HTTP header.
=> Use a raw axios PUT so that we can set the content type of the file.

src/components/AccessibilityDocumentsList/index.tsx, src/i18n/en-US/accessibility.ts, src/queries/GetAccessibilityRequestQuery.ts, src/queries/types/GetAccessibilityRequest.ts, src/utils/accessibilityRequest.ts, src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx
- Shows document type in table
=> Show document type instead of name in table

Dockerfile
- Upgrade base image for easi-app backend to Alpine 3.12
=> Use alpine-3.12 as base image

src/components/AccessibilityRequestsTable/index.tsx, src/utils/formatDate.test.ts, src/utils/formatDate.ts
This PR fixes the sorting issue on the test date column in the AccessibilityRequestsTable component. Sorting that column with a row that does not have a test date crashes the application.
In this PR, I created a new variable called `data` that converts the `requests` to an object that’s acceptable by the table. The sorting was failing because GraphQL returns the date as an ISO string. Test dates can also be `null`.
The sort was getting through the condition
```
if (typeof rowOneElem === 'string') {
return rowOneElem.toUpperCase() > rowTwoElem.toUpperCase() ? 1 : -1;
}
```
instead of
```
if (rowOneElem instanceof DateTime) {
return Number(rowOneElem) > Number(rowTwoElem) ? 1 : -1;
}
```
Sorting via string should work with ISO8601 standard returned from GraphQL. However, i think it’s more …
=> Fix 508 request table sorting

.gitignore, .vscode/extensions.json, .vscode/settings.json, apollo.config.js
This adds some VSCode config to the repo for folks who are using that editor.
If you use VSCode, please checkout this branch, close VSCode, and then open it again. Format-on-save and ESLint errors should be working properly.
If you're using a local `.vscode` folder in the project on your local machine already, LMK and we can figure out how to manage that along with having project-wide config that we share.
=> Add VSCode workspace config

src/views/TimeOutWrapper/index.tsx
- Force renew when a user asks for one, rather than waiting for the time to run out.
=> Force renew when a user clicks the option in the modal.

src/components/Header/index.tsx
After updating the Okta sign in widget, we were getting some console errors because the app was trying to update local state after the component unmounted.
`oktaAuth.getUser()` executes a request to get the user's info, but the component can unmount before the request completes. So I introduced a cleanup method to make sure the application doesn't set local state
=> [Header] fix react set state after component unmount error

package.json, yarn.lock
Removes deprecation warning that comes from the sign in widget
```
[okta-auth-sdk] DEPRECATION: This method has been deprecated, please use signInWithCredentials() instead.
```
=> update okta-signin-widget to 5.4.1

migrations/V72__Add_Admin_Lead_To_System_Intake.sql, pkg/models/system_intake.go, pkg/storage/system_intake.go, src/components/RequestRepository/csvHeaderMap.ts, src/components/RequestRepository/index.tsx, src/data/systemIntake.test.ts, src/data/systemIntake.ts, src/i18n/en-US/governanceReviewTeam.ts, src/i18n/en-US/intake.ts, src/types/systemIntake.ts, src/views/GovernanceReviewTeam/index.scss, src/views/GovernanceReviewTeam/index.tsx
- Add admin lead (string) field to system intake
- Add button / radio button modal to GRT request table to allow for setting and changing of admin lead for each request
- Add admin lead column to GRT request table
=> Add admin lead to GRT request repo

pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/storage/system_intake.go
- do not log at `Error` level when a user asks for a SystemIntake ID that does not exist (to prevent alert fatigue when splunk reports an alert based on an error-level log line: https://cmsgov.slack.com/archives/C01282R8DDK/p1615229152006300)
- a smattering of other minor hygiene and tidy fixes in the associated code path
=> user error != alert

scripts/dev
- Run`graphql-schema-linter` using `yarn run` so that it doesn't need to be installed globally.
=> Run graphql-schema-linter through yarn

Dockerfile
I had issues with the version of air that was in our Dockerfile. Using the latest seems to have fixed the issue. The error I was seeing was:
```
failed to build, error: fork/exec /bin/sh: Setctty set but Ctty not valid in child
```
[Other folks have seen this crop up](https://github.com/cosmtrek/air/issues/114), and since there is some weirdness going on with the tags in that repo, I think locking to a commit is probably the way to go for now.
=> Lock air to a specific commit until a new version is released.

src/views/BusinessCase/index.tsx, src/views/SystemIntake/index.tsx
Now that the governance task list is a completed feature, we can remove the unused breadcrumb navigation on the system intake and business case forms.
=> remove old breadcrumbs when task list lite was still a feature flag

.circleci/config.yml
- Use a newer version of the dev-ecs-manager-docker lambda image that doesn't include dev dependencies. Including the dev dependencies wasn't causing any issues; this was minor cleanup.
=> Use dev-ecs-manager-docker v3

.envrc, package.json, yarn.lock
Ever seen this before?
In `react-scripts v.4.0.3`, developers can disable ESLint dev errors that prevent the application from building. This is done with [advanced configuration](https://create-react-app.dev/docs/advanced-configuration) via `ESLINT_NO_DEV_ERRORS` in `.envrc`.
This doesn't appear to affect linting on save or throwing lint errors during pre commit. Please let me know if any workflows are affected by this. Hopefully this makes our lives easier!
=> upgrade react-scripts to 4.0.3

pkg/models/system_intake.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go, src/components/RequestRepository/csvHeaderMap.ts, src/data/systemIntake.test.ts, src/data/systemIntake.ts, src/i18n/en-US/intake.ts, src/types/systemIntake.ts
- Add `lastAdminNoteContent` and `lastAdminNoteCreatedAt` to the payload returned when loading system intakes
- Add new fields to CSV export
=> ES-1093 add fields to csv

pkg/email/intake_review.go, pkg/email/intake_review_test.go, pkg/email/templates/system_intake_review.gohtml, pkg/services/action.go, pkg/services/action_test.go
- Add a link to the action emails so the requester can remember where their task list is
=> Add a link to the task list when actions are taken on a request.

src/views/GovernanceReviewTeam/RequestOverview.test.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx, src/views/GovernanceReviewTeam/Summary/index.test.tsx, src/views/GovernanceReviewTeam/Summary/index.tsx
- Our tests for the request overview were getting tangled with other bits, but we really only care about the intake
- Separate the summary into its own component so it's easier to test and the overview page is easier to parse by humans
=> Break the summary into its own component.

cmd/devdata/main.go
- Adds a Business Case to the devdata.
- Run `scripts/dev reset` to clear your local database and import the devdata. it should complete without error, and if you log in with EUA `ABCD` as a business owner you should see a new business case in draft mode listed on the home page.
=> Add business case to devdata

.circleci/config.yml, Dockerfile.client, Dockerfile.client_circleci, Dockerfile.cypress
- Update the easi-app CircleCI image to use Node 12.x
- Update the client Dockerfiles to use the same version of Node as the CircleCI image
=> Update CircleCI image to Node 12.x

cypress/integration/businessCase.spec.js, cypress/support/businessCase.js, src/components/BusinessCaseReview/index.test.tsx, src/components/EstimatedLifecycleCost/Review/index.test.tsx, src/components/EstimatedLifecycleCost/Review/index.tsx, src/components/EstimatedLifecycleCost/index.scss, src/components/EstimatedLifecycleCost/index.tsx, src/data/businessCase.test.ts, src/data/businessCase.ts, src/types/businessCase.ts, src/types/estimatedLifecycle.ts, src/validations/businessCaseSchema.ts, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionFields.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/index.test.tsx
This PR updates the Business Case Estimated Lifecycle Costs to leverage checkboxes instead of radio buttons. It also eliminates the need to "Add Phase" or "Remove Phase". There are now a fixed number of lifecycle costs a user could add to a solution.
They can add 5 years of costs. Each year can have development, operations and maintenance, and other costs. So that's a total of 15 lines.
This is a **frontend only** change.
Since there are a fixed number of known options, I updated the frontend estimated lifecycle cost model to look like:
```
estimatedLifecycleCost: {
year1: {
development: {
isPresent: false,
cost: ''
},
operationsMaintenance: {
isPresent: false,
cost: ''
},
other: {
isPresent: false,
cost: ''
}
},
year2: {
development: {
isPresent: false,
cost: ''
},
operationsMaintenance: …
```
=> Update lifecycle costs to be checkboxes

src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx
- Changed redirect after issuing LCID from intake overview to admin notes
=> Redirect GRT admins to admin notes after issuing LCID

src/components/BusinessCaseReview/AlternativeAnalysisReview/index.tsx, src/data/businessCase.ts, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx, src/views/BusinessCase/Review/index.tsx
This PR renames the common `hasAlternativeB` solution to `hasAlternativeSolution`. `hasAlternativeSolution` takes a parameter of alternative solution and checks if it is filled out (or touched).
There is nothing functionally different; just renaming a function
=> Rename hasAlternativeB to hasAlternativeSolution

src/utils/formatDate.test.ts, src/utils/formatDate.ts
In the upcoming business case lifecycle cost revisions, we will need to display the **fiscal year** instead of year 1, 2, 3, etc.
In this PR, I created a function that returns the fiscal year for a `DateTime`
=> add function to return the fiscal year a DateTime belongs to

src/components/shared/DescriptionGroup/index.tsx, src/queries/GetSystemIntakeQuery.ts, src/queries/types/GetSystemIntake.ts, src/views/GovernanceReviewTeam/Decision/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx
- Decision Page (for GRT) now uses the Graph version of the intake
=> Decision Page uses GQL intake

src/views/App/index.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionB.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx, src/views/BusinessCase/Review/index.tsx, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/ContractDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx, src/views/SystemIntake/Review/index.tsx
🎵 _nothing can stop me, i'm all the way up_ 🎵 
This PR adds a hook that will scroll to top on any page change in the application. I removed all unnecessary manual scroll to top (`window.scrollTo(0, 0)`), but left in those that are necessary. The necessary ones are the ones that scroll to top on the same page when there are validation errors.
Still thinking on whether there's a more re-usable way to do it. I don't see one so far.
=> add scroll to top hook for all routes

src/reducers/systemIntakeReducer.ts, src/sagas/systemIntakeSaga.ts
This PR fixes the race condition that was observed on the intake form. This was originally thought to have only affected the business case, but it turns out data is getting lost on the intake as well. It's a bit curious why it took so long for this issue to appear, considering the intake integration tests ensure all the data is present.
=> fix race condition when trying to save a system intake

src/views/GovernanceReviewTeam/Notes/index.tsx
=> Be explicit about refetching after the mutation.

pkg/services/system_intakes.go
- We need to call our email service with the params in the proper order
=> Send these params in the proper order.

pkg/cedar/intake/client.go, pkg/cedar/intake/client_test.go, pkg/server/routes.go
- while I've been doing some of the "bottom-up" work on #891 (where that will also continue), now that I'm pretty confident what the internal client interface is going to look like, I decided to make this smaller PR for defining the interface and wiring it up into the active path code
- you'll notice that other than the LD checks, the client package is pretty empty... this is in pursuit of showing what a feature-flag driven development approach can look like
- I'm pretty chuffed with the functional adapter for adhering to the signature for `ValidateAndSubmitSystemIntake`, so the underlying code in the `services` package didn't need to have any modifications
- I plan to remove the old/deprecated `cedareasi` package and associated cruft in a later PR
=> EASI-1134 new CEDAR API internal interface

src/i18n/en-US/taskList.ts, src/views/GovernanceTaskList/RequestDecision/Approved.tsx, src/views/GovernanceTaskList/SideNavActions/index.test.tsx, src/views/GovernanceTaskList/SideNavActions/index.tsx, src/views/GovernanceTaskList/index.tsx
- hide remove intake button when intake is already closed
button is hidden for intakes with statuses:
```
1.  'LCID_ISSUED'
2.  'WITHDRAWN'
3.  'NOT_IT_REQUEST'
4.  'NOT_APPROVED'
5.  'NO_GOVERNANCE'
6.  'SHUTDOWN_COMPLETE'
```
=> hide withdraw intake button when intake is already closed

src/views/SystemIntake/ContractDetails/index.tsx
small catch. we need to clear out the period of performance day when the option changes and the contract is no longer applicable. i think this was missed when adding the day field.
=> clear out day when contract effort changes

src/utils/formatDate.ts
bandaid - long term fix coming
```
Cannot read property 'length' of null
at formatDate.ts:25
```
So just check if it's truthy before getting length.
=> bandaid for broken formatContractDate function

pkg/server/gqllogging.go, pkg/server/routes.go
- Log all GraphQL queries, including operation name and duration
- When there are errors, also log the query and the errors.
Here is an example of a successful query:
```
easi_1         | 2021-03-30T20:18:43.350Z	INFO	server/gqllogging.go:36	graphql query	{"operation": "GetSystemIntake", "duration": "20.6908ms", "error": false, "complexity": 75}
```
Here is an example of a query that left out a query argument:
```
easi_1         | 2021-03-30T20:48:43.987Z	INFO	server/gqllogging.go:38	graphql query	{"operation": "", "duration": "424.5µs", "error": true, "errorList": "input:2: Field \"systemIntake\" argument \"id\" of type \"UUID!\" is required but not provided.\n", "query": "{\n  systemIntake {\n    lcid\n    __typename\n  }\n}\n"}
```
And here is a …
=> Log graphql queries

pkg/appses/ses.go, pkg/appses/ses_test.go, pkg/cedar/cedarldap/translated_client.go, pkg/email/email.go, pkg/email/email_test.go, pkg/email/intake_review.go, pkg/email/intake_review_test.go, pkg/email/issue_lcid.go, pkg/email/issue_lcid_test.go, pkg/email/reject_request.go, pkg/email/reject_request_test.go, pkg/graph/schema.resolvers.go, pkg/local/cedar_ldap.go, pkg/local/email.go, pkg/models/action.go, pkg/models/email_address.go, pkg/models/user_info.go, pkg/server/config.go, pkg/services/action.go, pkg/services/action_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
This is part of our followup to #931. By using a new `models.EmailAddress` type in the application, we can have the type system help prevent issues like that from happening again.
- Add a new `models.EmailAddress` type
- Update code across the app to use the new type
=> Add EmailAddress type

src/validations/systemIntakeSchema.ts, src/views/SystemIntake/ContractDetails/index.tsx
Actually validate the month, date, year field(s) to ensure that they are valid dates. This is more than just checking month is between 1-12, day between 1-31, and year.
For example, 2/30/2021 is not a valid date.
We do the same thing on GRT dates. I'm still a little uncertain about this, but fixes the current issue and leverages code we are already using.
=> add slightly better validation for the period of performance dates

pkg/graph/schema.resolvers_system_intake_test.go, pkg/graph/schema.resolvers_test.go, pkg/storage/action.go, pkg/storage/note.go, src/views/GovernanceReviewTeam/Notes/index.tsx
This PR fixes a regression that arose during our migration to GraphQL.
The admin notes and actions should now appear with the newest at the top:
=> ES-1140 sort fix

src/components/Header/index.tsx, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/NotFound/__snapshots__/index.test.tsx.snap, src/views/TermsAndConditions/__snapshots__/index.test.tsx.snap
This PR allows the mobile header to open/close the mobile sidenav.
This broke because we removed the USWDS Javascript and forget to update this component.
=> fix mobile sidenav opening/closing

src/components/PageHeading/__snapshots__/index.test.tsx.snap, src/components/PageHeading/index.tsx, src/views/BusinessCase/Confirmation/__snapshots__/index.test.tsx.snap, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap, src/views/NotFound/__snapshots__/index.test.tsx.snap, src/views/TermsAndConditions/__snapshots__/index.test.tsx.snap
This PR adds the attribute `aria-live="polite"`.
Because this component steals focus on load (to indicate the page has changed), it cuts off whatever was previously being read. The `aria-live="polite"` will allow the previous reading to be completed before the heading reads.
For example, while confirmation notifications/alerts are being read, the `PageHeading` steals focus and cuts off the notification. We want the notification to finish reading before reading the `PageHeading`.
=> make PageHeading aria-live polite

src/validations/actionSchema.ts, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx
- Require that users select one of the options when issuing a lifecycle id
- Require that an LCID is entered when using an existing one is selected
- Add a validation for next steps
As a part of testing, we should verify that the changes made in #953 are still working.
=> LCID validation fixes

src/components/EstimatedLifecycleCost/index.tsx
This PR adds an `aria-describedby` to the cost input field. This lets an assistive technology user know the definition of "Development", "Operations & Maintenance", and "Other" costs.
=> add aria-describedby to estimated lifecycle costs input field

src/data/systemIntake.ts, src/utils/date.test.ts, src/utils/date.ts, src/views/GovernanceReviewTeam/Dates/index.tsx
I found this naming more descriptive and it'll help differentiate which/when to use. Open to feedback.
Additionally, I added an extra test. It's possible that the ISO string that's put into `parseDateInUTC` will have an offset. I want to make sure that it's captured behavior. If it shouldn't be like that, we need to make changes accordingly.
=> update parseDate to parseDateInUTC

src/views/SystemIntake/ContractDetails/index.tsx
- Modified wording of cost increase sub question (only appears when 'yes' is selected) to be more clear about expected answer
=> Modified wording of cost increase question in intake form

src/components/Modal/index.scss, src/components/Modal/index.tsx, src/i18n/en-US/governanceReviewTeam.ts, src/i18n/en-US/taskList.ts, src/views/GovernanceReviewTeam/Summary/index.tsx, src/views/GovernanceTaskList/SideNavActions/index.test.tsx, src/views/GovernanceTaskList/SideNavActions/index.tsx, src/views/GovernanceTaskList/index.tsx, src/views/TimeOutWrapper/index.tsx
This PR:
- removes header from all modals (timeout, admin lead, and withdraw request)
- updates styling
- remove unnecessary text from i18n
- tested for accessibility
=> Remove header from modal

src/views/Accessibility/AccessibiltyRequest/Create/index.tsx, src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTFeedbackToBusinessOwner.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTRecommendationsToGRB.tsx, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx, src/views/GovernanceReviewTeam/Notes/index.tsx, src/views/RequestTypeForm/index.tsx, src/views/TestDate/index.tsx
This PR resolves issues with some forms not scrolling to top when there are validation errors.
By default, `Form` from Formik, runs `formikProps.handleSubmit`, which is the `onSubmit` function that's passed into `<Formik />`. In addition to that, I added a `window.scrollTo(0, 0)` to scroll back to the top.
=> add scroll to top when a user submits in case of validation errors

go.mod, go.sum, pkg/cedar/intake/action.go, pkg/cedar/intake/biz.go, pkg/cedar/intake/cedar_intake.yml, pkg/cedar/intake/client.go, pkg/cedar/intake/client_test.go, pkg/cedar/intake/feedback.go, pkg/cedar/intake/gen/models/e_a_s_i_biz_case.go, pkg/cedar/intake/helpers.go, pkg/cedar/intake/lifecycle_cost.go, pkg/cedar/intake/note.go, pkg/cedar/intake/system_intake.go, pkg/testhelpers/action.go, pkg/testhelpers/business_case.go, pkg/testhelpers/grt_feedback.go, pkg/testhelpers/note.go
- this change is mostly the annoying bookkeeping of moving information (~"translating") from EASI internal representation over to the generated code representation that gets sent across the wire
- also added some tests, taking advantage of the validations provided by the generated code... (And actually our EASI models actually do a full round-trip into a JSON representation and come back out the other side to be validated!) This at least helps to make sure we that what we send is structurally in agreement with the Swagger spec.
- as of this PR, validation of the payload is currently in the active path, but I anticipate hiding that behind a feature flag in near-future PRs
=> EASI-1134 ES-525 translation helpers

src/views/Accessibility/AccessibiltyRequest/Create/index.tsx
This PR adds proper props to `ComboBox` to associate the field label with the field.
The `id` prop doesn't pass to the element we thought it did. So instead we need to make sure it's a part of the `inputProps`.
=> add proper props to associate label with the combo box

.spelling, README.md, docker-compose.override.yml, scripts/dev
- Changes the default URL for local MinIO to `http://minio:9000`
- Add a task to `scripts/dev` to verify and optionally setup the `minio` host on a user's machine.
Run `scripts/dev hosts:check` and hit enter once. You should see the following if you haven't configured the minio host yet:
```console
$ scripts/dev hosts:check
host minio can't be resolved. Do you want to configure it now? (Y/n)
echo '127.0.0.1 minio' | sudo tee -a /etc/hosts
127.0.0.1 minio
sudo killall -HUP mDNSResponder
sudo dscacheutil -flushcache
Host 'minio' is resolving correctly.
```
If you have configured the minio host, you should see this:
```console
$ scripts/dev hosts:check
Host 'minio' is resolving correctly.
```
=> Add task to check and configure hosts file

src/components/AccessibilityRequestsTable/index.scss, src/components/AccessibilityRequestsTable/index.tsx
- Column headers are now buttons, which is semantically an improvement since they are controls (you can click on them to do things).
- Add carets to all column headers. The currently sorting column's carets are shown larger so they are more visually distinct.
- Add an audio description of the table's sorting that is read to the user whenever the sort changes.
There is some duplication in what is read out to users still, but I think this is unavoidable to maximize compatibility since not all assistive tech will automatically read out the values of `aria-sort`. We should run this by Mario and get his take on this since we're mostly targeting JAWS and its behavior might be something we can rely on in this app.
https://user-images.githubusercontent.com/3331/115604306-d662c480-a2a6-11eb-88e2-b5 …
=> Improve accessibility of the requests table

scripts/dev
- `scripts/dev up` now waits for the front end to be ready before completing. This should hopefully minimize confusion stemming from its relatively long startup duration.
=> Wait for CRA server to be ready

cmd/devdata/main.go, migrations/V78__Add_508_EUA.sql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_accessibility_request_test.go, pkg/models/accessibility_request.go, pkg/storage/accessibility_request.go, pkg/testhelpers/accessibility_request.go
- Adds EUA ID of 508 request creator to object in database
Add an accessibility request. Check your EUA ID appears in the database in the accessibility request. 
=> Attach EUA ID directly to 508 requests

Dockerfile, docker-compose.circleci.yml, docker-compose.cypress_local.yml
- Add an entrypoint to the main app's Dockerfile and remove it from the docker-compose files. This will eliminate duplication and also allow us to remove the entrypoint from the deployed app's task definition (another point of duplication). I'm leaving the easi entrypoint in https://github.com/CMSgov/easi-app/blob/master/docker-compose.override.yml as-is since that particular docker-compose file uses an earlier stage in the Dockerfile's multi-stage build, and it's not impacted by this change.
Consider using an animated image to show …
=> ES-574 Add entrypoint to Dockerfile

src/components/TestDateCard/index.test.tsx, src/components/TestDateCard/index.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx
This PR simplifies the props that are passed to `TestDateCard`. Previously, it was passing each individual piece of data that comes from a test date.
Since test dates are returned as an object, we can just pass the entire object to `TestDateCard` since every value is being used.
=> consolidate props passed to TestDateCard

src/components/TestDateCard/index.test.tsx, src/components/TestDateCard/index.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/index.tsx
This PR disables the ability for business owners to edit/remove test dates for business owners. Only the 508/accessibility team is able to edit/remove test dates.
This PR **ONLY** does frontend work to hide the edit/remove buttons. I've verified that users **NEED** 508 job codes to perform those actions. Anybody that doesn't have those job codes can't edit/remove test dates.
Minor note: If a business owner _somehow_ attempts to edit/remove a test date (without proper job codes), the request will resolve 200, but nothing will actually happen. I'm not sure if we want to do anything more, but that's how it works now.
Standard code review, but it'd be helpful to add request dates, edit, and remove them. A sample run through can look like:
Business Owner (No job codes)
1. Add 508 Request. You …
=> Disable edit/remove test date card for business owners

src/i18n/en-US/accessibility.ts, src/validations/testDateSchema.test.ts, src/validations/testDateSchema.ts, src/views/TestDate/Form.tsx
- The test score for a test date, if entered, must be between 0 and 100 (inclusive).
- We added help text associated with the input to make this information available before a user encounters a validation error.
I added a unit test for the test date validation code. We don't have a pattern for this yet in the app.
These changes have been tested using only a keyboard and using JAWS.
=> ES-551: Validate test score

src/i18n/en-US/home.ts, src/views/Home/WelcomeText.tsx
- Removed help text / alert on home page that would direct users to the legacy SharePoint intake form
- This is one of the PRs to allow the governance team to make a full transition to EASi
=> Removed legacy SharePoint intake form link on home page

scripts/dev
- Make a generic "up" method with the default settings
- Allow us to invoke it with one or multiple additional arguments
- Make a new task "watch" that let's us watch the containers
- Future work: Maybe up:rebuild ?
=> Allow us to run up and watch it.

src/i18n/en-US/accessibility.ts, src/i18n/en-US/governanceReviewTeam.ts, src/i18n/en-US/taskList.ts
Our internationalization library, [react-18next](https://react.i18next.com), performs HTML escaping by default when interpolating values. This is causing some issues where we are displaying interpolated internationalized copy in the UI, as the resulting values are not interpreted as HTML by React but as literal text. This leads to results like this:
There are [two ways](https://www.i18next.com/translation-function/interpolation#unescape) to disable the auto escaping, and I chose to modify the strings we use for interpolation so that it could be done just for that value and not for the entire string.
- Update any i18n text that interpolates a request name to not perform HTML escaping of that value.
If you want to try it out, create a 508 request with a name that includes `'"<>` and then …
=> Don't escape the requestName when interpolating.

src/views/SystemIntake/ContractDetails/index.tsx
- Changed wording of intake cost increase question to be more specific about expected answers
- Added help text to expected increase question
- This is one of the PRs to allow the governance team to make a full transition to EASi
- Question for reviewer(s): I only changed the wording on the actual form itself, do we want to change the wording in the other places? (i.e. "Do you expect costs for this request to increase?" in components/SystemIntakeReview/index.tsx)
=> Modified wording of cost increase question

src/i18n/en-US/intake.ts, src/views/RequestTypeForm/index.tsx
- Modified help text in request type form to replace 'im not sure' text with link to navigator mailbox
- Moved help text from underneath "What is this request for?" to be below the various options
- Changed "Make a System Request" to "Make a Request"
- This is the last of the three changes requested by the governance team so that they can fully switch over to using EASi and retire the legacy SharePoint form
**Before:**
**After:**
=> Request type form changes

src/components/TestDateCard/index.test.tsx, src/components/TestDateCard/index.tsx, src/i18n/en-US/accessibility.ts, src/i18n/en-US/general.ts, src/utils/accessibilityRequest.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx
This is some refactoring work I've been wanting to do.
This PR reorganizes where some of our logic lives, specifically dealing with test dates and the accessibility request detail view. WIth hooks, it's much easier to put logic in lower-level components. I think we've done too much of that. None of this work is set in stone. I'd like feedback and set better patterns to follow moving forward.
- Move delete test date mutation to parent (`AccessibilityRequestDetailPage`)
- This makes things a bit simpler so we don't need to pass props to handle side effects (refetch and set confirmation text)
Something I'd like us to be more thoughtful about is where we use the query and mutation hooks. With hooks it's easier to put them anywhere in the component hierarchy. I think this might be problematic …
=> move delete test date mutation into 508 request details view

cmd/devdata/main.go, docker-compose.yml, pkg/storage/store.go
This is part of our ongoing saga of having what appears to be an unbounded number of connections to the database.
- Configure Postgres to only accept 15 connections in `docker-compose.yml`
- Add a loop to devdata so we have a lot of 508 requests to work with.
```sh
$ scripts/dev down
$ scripts/dev up
$ scripts/dev db:seed
```
If you log in there should be 508 requests, and reloading the page once or twice will lead you to:
=> Configure the app so that it's easy to repro the connection issue

src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx
The file input previous was ambiguously announced by JAWS. Listen and ask yourself which button does what:
https://user-images.githubusercontent.com/3331/117707358-1cb78f00-b194-11eb-8756-68b60be65d49.mov
- Add additional context that is announced when the file input is tabbed into:
https://user-images.githubusercontent.com/3331/117707414-2fca5f00-b194-11eb-8c2b-bf3037968875.mov
=> Add additional context to document file input

src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx
This PR fixes the bug where users are able to upload a document multiple times by spamming the enter key or clicking on the submit button multiple times.
This PR leveraged `isSubmitting` from `formikProps`. My suspicion is that the `axios.put` for the document upload mutation takes a second too long to start. That's what's causing the button to be clicked again before it gets `disabled`. `formikProps.isSubmitting` should be true closer to when the button has been clicked
If this doesn't work, we can use `useState` and set state immediately on the button click.
If verifying locally, throttle your network in the chrome dev tools.
1. On 508 request document upload, select a document and it's type
2. Click on upload repeatedly OR focus the button via tab button and spam the enter key.
There …
=> fix multiple document uploads bug

src/i18n/en-US/accessibility.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/AccessibilityTestingStepsOverview/__snapshots__/index.test.tsx.snap, src/views/Accessibility/AccessibilityTestingStepsOverview/index.tsx
**_#1040 needs to be merged first so that the page exists._**
This PR adds 2 links that help a user get to the 508 Templates page.
1. 508 Request Details page - Sidebar
2. 508 Testing Overview page - link inside paragraph
- Test that links properly navigate to the page in a new tab
508 request details page
508 testing overview page
=> add links to get to the 508 templates page

src/components/Header/index.tsx, src/views/App/index.tsx, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/GovernanceOverview/index.test.tsx, src/views/GovernanceOverview/index.tsx, src/views/RequestTypeForm/index.tsx
This PR updates the flow for creating an IT governance request and how business owners see the Governance Overview page.
Currently, there are two places to initiate an IT governance request:
1. Dropdown next to user's name
2. Business owner home page ("Start Now" button)
Regardless of where you start, the flow should be the same
1. Request type form
2. If a business owner creates a "new" request, they are taken to the governance overview page
3. Clicking "Get started" takes them to the task list
4. Once they are on the task list, on the right rail/sidebar, there's a link for `Overview for adding a system`.
5. Clicking on that link, opens a new tab for the governance overview page **without the "Get started" button**
https://user-images.githubusercontent.com/8367504/118886548-f1c4ed80-b8ad- …
=> update flow to and from the Governance Overview page

src/i18n/en-US/accessibility.ts, src/views/Accessibility/AccessibiltyRequest/Create/index.tsx
- 508 Request creation now redirects users to the Request Details instead of home
- Update the confirmation message to `508 testing request created. We have sent you a confirmation email.`, as described in Figma
-  [x] Met the acceptance criteria, or will meet them in a subsequent PR
=> change 508 request creation confirmation location

src/i18n/en-US/home.ts, src/views/MyRequests/Table.test.tsx, src/views/MyRequests/Table.tsx
- Add code to cover the state of when the table is empty
- Add tests!
=> Add empty state and tests for my request table

scripts/dev
- Add the `--build` flag to `docker-compose up` to ensure that images are rebuilt when the underlying dockerfiles
have been modified. I've run into situations where the `scripts/dev down` and `scripts/dev up` sequence uses the cached images and doesn't rebuild the images when I've made modifications to the docker files. Adding the `--build` flag only adds a little bit of extra time to the docker-compose up process. Docker compose will only rebuild an image when necessary; this won't cause all the images to be rebuilt every time.
=> Add --build flag to docker-compose up

.github/PULL_REQUEST_TEMPLATE.md
Link the rotor-menu how-to, rather than have it in the PR template
=> Link to the rotor menu how-to.

src/components/shared/Alert/index.test.tsx, src/components/shared/Alert/index.tsx, src/hooks/useMessage.tsx, src/i18n/en-US/accessibility.ts, src/views/Accessibility/AccessibilityRequest/Create/index.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx
This PR updates the 508 request creation confirmation message to include a survey link
- update `useMessage` hook to accept `React.ReactNode` in addition to a `string`
- update `Alert` to recognize whether `children` is a `string` or JSX
- Plan is to make similar changes in the ReactUSWDS Alert component then use the library component
- add proper markup for the confirmation message changes
**Adding the survey link to the email template will come in a separate PR**
=> add updated confirmation text for 508 request creation

src/global.d.ts, src/types/flags.ts
Ever seen this?
LaunchDarkly doesn't support typed flags, so we'll need to do some extra configuration to get that type safety. With the changes in this PR, we're able to get.
- Make sure the app builds
- Make sure your editor is happy (no more red squiggles)
=> fix LD flag types

src/views/Accessibility/AccessibilityRequestDetailPage.tsx
Based on feedback viewed post-merge of this [PR](https://github.com/CMSgov/easi-app/pull/1066#issuecomment-848190318), I'm removing the jsx objects defined as components inside of the parent component and just setting the object to a variable.
change based on this reasoning (via Chris):
"basically, if create a component within a component, every time the parent component re-renders, the child component 
will get recreated. this means any state will be lost.
that’s come back to haunt us a handful of times already. it’s not the easiest bug to figure out either"
none (but to double check the render, go to a request without documents, and then add one)
=> Remove components inside component and use jsx object

pkg/storage/requests.go
- Order query by submitted_at date, which is the data point we use in the table
- Not all records have a created_at date, so this query was causing a bug!
=> Sort by submitted_at, not created_at

src/components/Header/index.tsx, src/i18n/en-US/accessibility.ts, src/views/Accessibility/AccessibilityRequest/List/index.tsx, src/views/Accessibility/AccessibilityTestingStepsOverview/__snapshots__/index.test.tsx.snap, src/views/Accessibility/AccessibilityTestingStepsOverview/index.test.tsx, src/views/Accessibility/AccessibilityTestingStepsOverview/index.tsx, src/views/Home/index.tsx
This PR updates the routing to the 508 overview page.
The following should link a user to `/508/testing-overview?continue=true`. This parameter enables the `Get started with Step 1` button.
- `Make 508 request` via username dropdown
- As a business owner: `Section 508 compliance` link
- As a 508 user: `Add a new request` link
*Note: URL on 508 request details page does **not** have the URL parameter so it does not show the "get started" button
Add breadcrumbs on testing overview page
=> Update routing to 508 overview page

pkg/graph/schema.resolvers_current_user_test.go, scripts/testsuite
- The recent changes to `scripts/testsuite` meant that unit test errors were being ignored. This PR reverts the recent changes to `scripts/testsuite` and fixes a failing unit test in `pkg/graph/schema.resolvers_current_user_test.go`. 
- We'll open another PR to add the backend code coverage back to `scripts/testsuite` and fix the bug to ensure it fails on any unit test errors.
=> Revert backend code coverage changes

scripts/run-cypress-test-docker
- Rebuild the db_seed image for e2e tests to ensure we're using an up-to-date version of db_seed rather than a cached version.
=> Build db_seed image for e2e tests

cmd/devdata/main.go, cypress/integration/accessibility.spec.js, cypress/integration/businessCase.spec.js, cypress/integration/homepage.js, cypress/integration/login.spec.js, cypress/integration/systemIntake.spec.js, cypress/integration/taskList.spec.js, cypress/support/commands.js, cypress/support/login.js, scripts/run-cypress-test-docker
- Removed the POST request in our business case spec and added the data setup to our seeds file
- Created a helper for local login
- Refactored existing tests to use the new local login helper (we still use Okta for one login test)
- Removed unused support code
- Added homepage tests for each of our personas
=> Sb refactor tests to use local login

scripts/dev
These were extracted from my recent work on ES-641
- Add a command to restart a docker compose service: `scripts/dev restart easi`
- Add a command to run the "long" Go tests: `scripts/dev test:go:long`
- Add some pizazz.
=> a few scripts/dev improvements

package.json, yarn.lock
- Update USWDS to 2.10.3
- Checked for major regressions on the System Intake form
It's probably worth some effort to check for any major regressions. I did a quick pass of a handful of pages including the majority of the System Intake flow but nothing serious caught my eye.
**2.10.3 isn't the latest version of USWDS. Why'd you pick that version?**
This is the version [ReactUSWDS](https://github.com/trussworks/react-uswds/blob/4abf315a2734bb15cfd30c870e210fa5903cf0e6/package.json#L130) is on. We are free to update ahead. I don't think we have any needs to fast forward past ReactUSWDS, so I decided to keep pace with that library.
- This does not satisfy the JIRA ticket. I'll also update ReactUSWDS and other components in subsequent PRs
=> update uswds to 2.10.3

src/stylesheets/_settings.scss
Updating USWDS introduced some new styles that made table headings a different color.
This PR updates the SCSS token to make it white (like it was before).
**This will remove it for all tables.**
=> update USWDS sorted table heading color token

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, src/components/PlainInfo/index.scss, src/components/PlainInfo/index.tsx, src/i18n/en-US/accessibility.ts, src/queries/GetAccessibilityRequestForStatusChange.ts, src/queries/UpdateAccessibilityRequestStatusQuery.ts, src/queries/types/UpdateAccessibilityRequestStatus.ts, src/queries/types/accessibilityRequest.ts, src/types/graphql-global-types.ts, src/utils/accessibilityRequest.test.ts, src/utils/accessibilityRequest.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/ChangeRequestStatus/index.test.tsx, src/views/Accessibility/ChangeRequestStatus/index.tsx, src/views/Accessibility/ChangeRequestStatus/types/accessibilityRequest.ts, src/views/Accessibility/index.tsx
Add view at `/508/requests/:requestId/change-status` to allow 508 team update the request status
=> Add view to allow 508 team update request status

src/components/AccessibilityDocumentsList/index.tsx, src/i18n/en-US/accessibility.ts, src/views/Accessibility/AccessibilityRequestDetailPage.test.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx
- Shows the heading "Documents" with a  no documents message for a 508 user or tester (instead of the "Next Steps" message shown to a business owner)
None
Log in as a 508 user or 508 tester.
Go to an accessibility request with no documents.  See the no documents message and not the Next steps message.
=> Show Documents heading with no documents list for 508 user/tester

src/components/AccessibilityRequestsTable/index.test.tsx, src/components/AccessibilityRequestsTable/index.tsx, src/i18n/en-US/accessibility.ts, src/utils/accessibilityRequest.test.ts, src/views/MyRequests/Table.tsx
- Adds a Status column to the table showing accessibility requests to the 508 tester/user
I noticed there are two ways we were accessing the human-readable accessibility request status.  SInce we are trying not to do enum to human-readable in i18n, I replaced it with the util mapping, `accessibilityRequestStatusMap`.
Log in as a 508 user or 508 tester.
You should see the all requests page and a new column "Status".  Check that all three statuses show properly.
=> K1m 704 tester table status

src/views/Accessibility/AccessibilityRequest/Documents/New/index.tsx
Fixes the id mapping between the label and document name field
=> fix 508 document name field label

src/views/Accessibility/AccessibilityRequest/Documents/New/index.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/TestDate/Form.tsx
One of the quietly major changes was introduced  in `v2.9.0`. Here is the [changeset](https://github.com/uswds/uswds/pull/3638/files). The offending file is `src/stylesheets/elements/form-controls/_checkbox-and-radio.scss`.
They changed `margin-bottom` to `margin-top`. This means there's too much margin on top and too little margin on the bottom.
This PR is mainly adding/subtracting margins.
=> Update Accessibility/508 radio/checkbox spacing

src/components/FileUpload/index.tsx, src/views/Accessibility/AccessibilityRequest/Documents/New/index.tsx
- Add an aria alert that is read (by some browsers) when a file is selected. This works in JAWS/Chrome, but not in VO/Safari.
- Move the aria-described-by tag inside the `fileInput` and update its value when a file is selected. This works in all both browser/screen reader combinations I tested.
JAWS/Chrome:
https://user-images.githubusercontent.com/3331/122287763-eff34780-ceb6-11eb-98a8-88372a398b57.mov
VO/Safari:
https://user-images.githubusercontent.com/3331/122287789-f5e92880-ceb6-11eb-9ad7-7ee0ad990338.mov
=> Update file input label when a file has been selected.

src/views/Accessibility/AccessibilityRequestDetailPage.test.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx
- Update `h1` to read out current status of the request
- Update current status info to live in dl, dt, dd tags instead of h2
=> fix 508 detail page headings

src/components/shared/OktaSignInWidget/index.scss, src/components/shared/OktaSignInWidget/index.tsx
In our accessibility testing, we learned that the Okta sign in widget has insufficient color contrast. This PR changes the text inside of the widget to be `#595959`. This color is WCAG AA/AAA compliant against `#ffffff` background.
---
Backstory
Originally we were going to make the text very clear (text: `#fff`, background: `#000`). We learned that the "Remember me" checkbox renders from a sprite sheet. This means we can't actually update the color of the border. The widget looked strange with black text and light grey borders so I looked for a color that was AA/AAA compliant, but also didn't look too different from the background colors. That's how I settled on `#595959`.
With updated colors
=> update okta sign in widget color contrast

src/components/RequestRepository/index.tsx
Update gov team XLS requests download link
- it should one link instead of two.
- fix styling (underline and vertical spacing)
=> fix download requests xls link for gov team

pkg/email/email.go, pkg/email/new_accessibility_request_note.go, pkg/email/templates/new_508_note.gohtml, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, src/types/accessibility.ts, src/types/graphql-global-types.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx
- There is a checkbox on the 'Add 508 note' tab, which, if selected, will email the 508 team about a new note. 
- If the checkbox is not checked, no email is sent. 
=> Send email (optionally) when creating 508 note

cypress/integration/accessibility.spec.js
Add dates to DateTime instead of directly to the string. :doh:
=> fix calculation of adding two days in integration test

cypress/integration/accessibility.spec.js
Recently, we got this error from Cypress. This was confusing because it's pretty clear that the `h1` has the appropriate text Cypress is trying to match.
After some clicking around, I realized that Cypress was watching the `h1` from the "loading" page and was still watching it after the the page was fully loaded. So when the actual page loaded, it didn't pick up the new `h1`.
To resolve that, I told Cypress to make sure the loading indicator is no longer on the screen.
=> fix heading target for test date cypress test

src/components/RequestRepository/index.tsx
- add `aria-label` for the open/closed requests button to indicate which is selected
Note: there's actually already an `h1`, so I didn't need to add one.
=> indicate which tab is selected on get home page

cypress/integration/accessibility.spec.js
We already have a test for creating 508 requests.
For this test, I am checking the page flow when a 508 team user tries to add a 508 request from the home page. I am checking URLs and `h1`'s
Note: I am only partially checking key terms in the `h1` to make these tests more resilient to content/copy changes.
=> add test to check page flow for 508 request

src/components/shared/DateInput/index.tsx, src/i18n/en-US/accessibility.ts, src/validations/systemIntakeSchema.ts, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx, src/views/SystemIntake/ContractDetails/index.tsx, src/views/TestDate/Form.tsx
This PR adds sufficient help text for fields.
- Did not add much for any Dates field
- It should be common sense to enter in a valid date. It doesn't make sense to tell a user a month should be from 1-12. That's common knowledge
- The date input fields have help text that reads when the input field is focused
- Phone number, LCID,  and test score all have added help text.
=> add sufficient help text for fields

cypress/integration/systemIntake.spec.js, src/views/GovernanceReviewTeam/Summary/index.tsx
- Adds a test for an intake request on the office side to change the admin lead
`npx cypress open`
=> Add test for changing admin lead (breaking)

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_system_intake_test.go, src/queries/SystemIntakeQueries.ts, src/queries/types/UpdateSystemIntakeContactDetails.ts, src/types/graphql-global-types.ts, src/types/systemIntake.ts, src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx, src/views/SystemIntake/ContactDetails/GovernanceTeamOptions.tsx, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/index.tsx
- Fetch the system intake using graphql and pass it to the contact details page
- Use a new mutation to save the contact details fields
- Please note that this PR is being merged into a long-running branch. This allows for some interim code review, but also keeps new functionality out of the main codebase until it's ready to be implemented. Tests might be failing until the entire form is migrated to graphql.
=> Sb gql intake form page 1

cypress/integration/accessibility.spec.js, src/components/shared/Label/index.tsx, src/views/Accessibility/AccessibilityRequest/Create/index.tsx, src/views/Accessibility/AccessibilityRequest/Documents/New/index.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.test.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/index.tsx, src/views/TestDate/NewTestDate.tsx
- Puts 508 notes at its own path, /508/requests/{id}/notes
Should the documents view and the notes view be split into separate components?
=> Separate the paths for documents and notes

src/views/Accessibility/AccessibilityRequestDetailPage.test.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/index.tsx, src/views/TestDate/UpdateTestDate.tsx
- Updates routing in `src/views/Accessibility/index.tsx`
- Only known routes `/documents` and `/notes` can be used
- Anything else wil show not found
- Updates tests to be more clear
- `buildProviders` is now `render508DocumentsPage` and `render508NotesPage` depending on which view is being tested
=> clean up 508 request page routing and tests

src/i18n/en-US/accessibility.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx
This PR adds screen reader feedback when a user changes tabs (documents and notes) on the 508 request detail page.
1. Navigate to a 508 request
2. Turn on screen reader
3. Switch to the inactive tab
4. Listen for the screen reader to let you know what tab is active
=> add sr feedback for documents and notes tab

src/components/PageWrapper/index.tsx, src/views/Accessibility/MakingARequest/index.test.tsx, src/views/Accessibility/MakingARequest/index.tsx, src/views/MakingARequest/__snapshots__/index.test.tsx.snap, src/views/MakingARequest/index.test.tsx, src/views/MakingARequest/index.tsx
This PR adds tests for system and 508 making a request pages. This is low hanging fruit.
```
/system/making-a-request
/508/making-a-request
```
The file name space is a little confusing. I'm not sure how to address that yet.
=> add tests for making a request pages

src/views/Accessibility/AccessibilityRequestDetailPage.test.tsx
~This PR disables a flaky test on the 508 view.~
~I ran it with no issues locally 10/10, but ran into a few hiccups when code coverage reports are generated. I don't know why that happens, but it also happens intermittently in CI too.~
~There might be something we can do better in the unit test itself, but I'm not fully sure what that is yet.~
~In the mean time, I want to disable the test to minimize setbacks during development.~
Okay, lets talk about these changes I think will make this test more solid.
**Sequence of events**
1. User types in note
2. User clicks button to add note
3. Note is added and success alert appears
4. Refetch occurs to get the new note list (with new note)
5. New note list renders
**What I suspect is happening**
After the success alert appears, there's a race …
=> update flaky 508 test

src/components/PageWrapper/index.tsx, src/views/GovernanceReviewTeam/Actions/ChooseAction.tsx, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTFeedbackToBusinessOwner.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTRecommendationsToGRB.tsx, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/BusinessCaseReview/index.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx, src/views/GovernanceReviewTeam/Decision/index.tsx, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/IntakeReview/index.tsx, src/views/GovernanceReviewTeam/Notes/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.test.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx, src/views/GovernanceReviewTeam/index.tsx
This PR adds tests for `RequestOverview.tsx`. These are mainly smoke tests to make sure that the correct route/view paints when a user selects an action.
**After this is merged, I will work on follow up PRs to test the form for each action.**
=> Add tests for RequestOverview.tsx (GovTeam request view)

src/views/Accessibility/AccessibilityRequestDetailPage.test.tsx
I think we can change the test to wait for the notes to be populated with the new note. It'll check every 50 ms for 1 second, and fail if the new note is not present by then.
=> Await success of notes check in flaky react test

cypress/integration/governanceReviewTeam.spec.js
This is the error from CircleCI.
There are two links to navigate to the "Action" page from the GovTeam request view.
Currently, the test is trying to find the link that has the text `Take an action`, but that's not always rendered in time. By updating the test to click the first "Actions" link it finds, we'll get more consistent results for this test.
=> update selector so that the test navigates to the actions page 

cypress/integration/governanceReviewTeam.spec.js, src/views/GovernanceReviewTeam/RequestOverview.tsx
#1216 did not work.
It just exposed us to the other side of the coin. By loosening the selector, Cypress didn't know which link to click if both were rendered.
I think that adding a specific test id for the HTML element will ensure that it's rendered and clicked.
=> add test id to specifically target a link on get actions cypress tests

package.json, src/global.d.ts, src/index.tsx, yarn.lock
[react-axe](https://github.com/dequelabs/react-axe) has been deprecated.
It's been giving us false positives. I noticed it's deprecated, so it's time to let go.
=> remove react-axe

pkg/models/accessibility_request.go, pkg/services/metrics.go, pkg/services/metrics_test.go, pkg/storage/accessibility_request.go, src/views/Accessibility/AccessibilityRequest/List/index.tsx
- Adds fields to accessibility request metrics CSV:
- LCID
- Status
- Date opened
- Date closed (only show if last status is closed)
I made the value of `Date closed` to be an empty string if the status is not CLOSED.  Lmk if that's not the right approach.
It's wasn't part of this PR, but I'm wondering if the text of the download link should be in i18n Translation instead of hard-coded
Log in as a 508 tester or 508 user.
Close one of the requests.
From the list of requests, see the button to `download requests as excel file`.
It should download a file.  Check to see that all the values are there, and there is no value for 'Date closed` unless the status is closed.
From previous PR to create button (adjusted styling):
=> K1m 811 add 508 metrics values csv

src/i18n/en-US/accessibility.ts, src/views/Accessibility/TestingTemplates/__snapshots__/index.test.tsx.snap
- Makes all text about opening in the same tab the same ("opens in a new tab")
Can be viewed throughout application, including templates page, "report a problem" link at bottom of request page, under documents when there are no documents, in the right hand column of the request page, in the new request form (survey link), and the testing steps overview page
=> Align text for opening in a new tab

cypress/integration/accessibility.spec.js, src/views/Accessibility/AccessibilityRequest/List/index.test.tsx, src/views/Accessibility/AccessibilityRequest/List/index.tsx
- Removes the "Add a new request" button on the request list page for the 508 admin (job code 508_user)
- Adds tests for that page
- Go to a 508_user home page.  There should be no button with the text "Add a new request"
- Go to a 508_tester home page.  The button should be visible.
508_tester view:
508_user view:
=> K1m 610 hide add request admin

.spelling, docs/frontend.md, package.json, scripts/testsuite
- Increases client-side jest test thresholds 30 points.  Increases Go tests coverage threshold to 55.
- Add documentation about code coverage and how to change thresholds
I made a guess at appropriate thresholds based on where we are at currently.  Lmk if they are too close to our actual coverage.
We do not yet have Cypress coverage thresholds set up.  There is a ticket on Infrasec's backlog for this https://jiraent.cms.gov/browse/ES-711
See doc for how to run coverage if you want to see where we are currently at.
=> K1m 830 increase code coverage thresholds

.github/workflows/build.yml
- Always upload the cypress artifacts, even if a step within the e2e_tests job fails.
- With the current configuration, if the cypress tests fail, the steps for uploading the artifacts are skipped, but it's precisely in those situations when the cypress tests fail, that we most want to view the cypress videos/screenshots.
=> Always upload the cypress artifacts

pkg/services/backfill.go
This PR fixes a bug where systems that were created by the import wouldn't have their admin lead field set.
=> Explicitly set and update the admin lead.

src/views/GovernanceReviewTeam/Actions/ProvideGRTFeedbackToBusinessOwner.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTRecommendationsToGRB.tsx
This PR updates the following GRT admin textareas to 3000 characters
1. `Provide GRT feedback and keep working on draft business case` -> `GRT feedback to the business owner` textarea
2. `Provide GRT feedback and request final business case for GRB` -> `GRT feedback to the business owner` textarea
3. `Mark as ready for GRB` -> `GRT Recommendations to the GRB`
=> update feedback textareas to have a maximum of 3000 characters

pkg/appses/ses.go, pkg/appses/ses_test.go, pkg/email/business_case.go, pkg/email/change_508_status.go, pkg/email/email.go, pkg/email/email_test.go, pkg/email/intake_review.go, pkg/email/issue_lcid.go, pkg/email/new_accessibility_request.go, pkg/email/new_accessibility_request_note.go, pkg/email/new_document.go, pkg/email/reject_request.go, pkg/email/removed_accessibility_request.go, pkg/email/request_withdraw.go, pkg/email/system_intake.go, pkg/local/email.go
This adds the GRT team as a CC to all emails on the governance side.
=> Add GRT email as CC for all actions

src/i18n/en-US/taskList.ts, src/views/App/index.tsx, src/views/GovernanceTaskList/Feedback/index.tsx, src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx
This PR adds a feedback page for business owners to be able to see the feedback that was left by the gov team. The links are located on the governance task list. It displays a "Read feedback" link/button dependent on what the status of the request is.
=> Add governance feedback page

pkg/storage/grt_feedback.go
This makes the gov team feedback return in reverse chronological order
=> reverse order of gov team feedback

cypress/integration/systemIntake.spec.js, pkg/server/routes.go
This PR fixes [a regression that occurred when we merged in the GraphQL intake work](https://github.com/CMSgov/easi-app/commit/6a2e6e5351a2f1854f4c3c6c70b97dd620833bef#diff-096ca5d6226d764718a0e392b1b2f66eadd7098349b2d9cdf1395979f7d7cad2L326-L338). A system intake action definition was removed, preventing new system intakes from being submitted.
* Restore the `models.ActionTypeSUBMITINTAKE` action
* Extend existing cypress test to verify that the intake is actually submitted
=> Add back missing system intake action definition

src/views/TimeOutWrapper/index.tsx
Currently, the timeout modal displays regardless if a user is logged in via Okta auth or our dev/local auth. This PR updates the timeout wrapper so the timeout modal **does not** display when a developer is logged in locally with local auth.
=> update timeout wrapper so local auth is not affected

src/views/AuthenticationWrapper/index.tsx, src/views/TimeOutWrapper/index.tsx
- `autoRenew` isn't working (again). Instead of running around it, this PR forces the token to renew manually
- We discovered an issue with the timeout when a tab is "inactive". This [blog post](https://developer.chrome.com/blog/timer-throttling-in-chrome-88/) describes some of the throttling that happens in Chrome that made our code fail.
- Instead of manually counting down the timer, I updated the session time remaining to be calculated against the real world time. This way, the countdown timer will be consistent with the real world time, even when intervals are throttled down. 
I can talk through this PR in more detail if needed.
=> force renew token and use time to track timeout instead of counter

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, src/queries/types/GetSystemIntake.ts
Make intake `updatedAt` nullable because legacy imported data doesn't have `updatedAt` defined.
=> make intake updatedAt nullable

src/views/GovernanceTaskList/index.tsx, src/views/SystemIntake/index.tsx
Prior to implementing GraphQL, the REST API response would go through a "transform" to convert the meeting dates to a Luxon `DateTime` object. Now that the date is begin returned from a GraphQL query, it's returning the date in the form of an ISO string. That's why the date time math was failing.
This PR fixes the issue by converting the ISO string to a `DateTime` object so the date math can be calculated.
=> fix grb grt meeting date rendering

.pre-commit-config.yaml, README.md, scripts/dev
I noticed while working on another PR that we are still running a task as part of our pre-commit config to verify CircleCI configs. Now that we aren't using that service, there's no need to do that.
- Remove CircleCI check from pre-commit and list of project prerequisites.
=> Remove circleci from precommit

migrations/V93__Add_ExtendLCID_Action_Type.sql, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/resolver.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_system_intake_test.go, pkg/graph/schema.resolvers_test.go, pkg/models/action.go, pkg/server/routes.go, pkg/services/action.go, src/queries/CreateSystemIntakeActionExtendLifecycleIdQuery.ts, src/queries/types/CreateSystemIntakeActionExtendLifecycleId.ts, src/types/graphql-global-types.ts, src/views/GovernanceReviewTeam/Actions/ExtendLifecycleId.tsx
Tasks:
If you run `scripts/dev reset`, there will be a closed request called "With LCID Issued" that can be used to test this workflow.
=> ES-880 Add extendLifecycleId mutation

src/views/GovernanceReviewTeam/Actions/ChooseAction.tsx
Currently, the user is only allowed to extend an LCID if the intake has a business case. In most cases, business owners will need to fill out a business case before getting an LCID.
However there is a rare edge case where business owners can get fast forwarded to an LCID. To account for this edge case, an LCID should be able to be extended as long as the status of the intake is `LCID_ISSUED`.
=> allow extend lcid action even if it doesnt have a business case

scripts/run-cypress-test-docker
Update the local portion of the cypress runner script so that the
ordering of starting the docker services is consistent. Adding the check
for exit code on some services should also help control the start up so
that all dependent services are running before the backend starts. This
should address an intermittent error where the backend would error on
initial connection to the db because it was attempting to the connect to
the db before the db migrations had completed.
Run `./scripts/run-cypress-test-docker` locally to verify that the Cypress tests run successfully on your local machine.
=> Update local cypress run to match CI

.spelling, .vscode/extensions.json, README.md
Add information to main README on setting up the development environment for devs working on Windows+WSL.
* The section for Development Environment Setup is getting somewhat long; should it perhaps be split into another file?
* @ClayBenson94 - does `brew install pre-commit` work out of the box on MacOS if Python 3 hasn't been set up?
* @ClayBenson94 - does VS Code on MacOS prompt for installing the recommended extensions and the Go analysis tools like it does on Windows?
=> Add documentation on setup for Windows+WSL developers

.github/workflows/build.yml, Dockerfile.client, scripts/release_static
- Use the `--frozen-lockfile` flag for `yarn install` in Dockerfile.client and `scripts/release_static` in order to use _exactly_ the same versions of dependencies as specified in `yarn.lock`.
=> Use --frozen-lockfile on yarn install

README.md, docker-compose.override.yml, scripts/dev
No Jira ticket for this; I was just irritated by the frontend making it take significantly longer to bring the Docker containers up locally, even when just working on Dockerfile/docker-compose changes that don't affect the frontend. 
- Add `scripts/dev up:backend` and `scripts/dev up:backend:watch` for bringing the local dev environment up without a frontend container.
=> Add script support for running local dev without frontend

README.md, scripts/dev
No Jira ticket, just some problems with running Go tests locally through `scripts/dev`. It looks like Truss was using the third-party [gotest](https://github.com/rakyll/gotest) package to format/color their test output when running locally; rather than adding that as a dependency, I just switched `scripts/dev` to use the built-in `go test` command. There's also some additional documentation in the README on running Go tests locally.
- Use built-in `go test` instead of `gotest` library.
- Add notes to README on running Go tests locally.
- Run `scripts/dev go:test` and make sure it works without errors.
=> Fix go testing tasks in scripts/dev 

pkg/services/action.go, pkg/services/action_test.go
- Changes to `action.go`'s `NewSubmitSystemIntake()` that make it so that if the validateAndSubmit returns an error, we just log it and move on. Practically, validateAndSubmit is only used to publish changes to CEDAR. I couldn't find any instance of it being used to validate the input. (Please double check my work here!)
=> Changes to enable CEDAR system intake api

pkg/cedar/intake/helpers.go
- Change the date time objects created when converting data to CEDAR Intake format to follow ISO8601 format (essentially, we weren't including the "T" in the string)
=> Fix CEDAR datetime to be ISO8601

.github/workflows/build.yml, craco.config.js, package.json, src/views/Accessibility/AccessibilityRequest/Create/index.test.tsx, tsconfig.json, yarn.lock
- Upgrade TypeScript version
- Add job to workflow to check for TypeScript errors (build continues even if job fails)
- Post TypeScript errors as a comment on pull requests
- Fix a somewhat flaky frontend test
- Make sure type errors don't block frontend builds
Look at the comment that gets posted by the github-actions bot, see if it's sufficient for identifying TypeScript errors. I did my best with the formatting, but I'm open to ideas for improvement.
=> Identify TypeScript type errors as part of CI workflow

scripts/dev
No Jira ticket; this fixes an issue I noticed today where `scripts/dev down` was failing after running `scripts/dev up`. Issue was introduced in [this PR](https://github.com/CMSgov/easi-app/pull/1377); with the `frontend` profile defined in the docker-compose files, all the `docker-compose` commands in `scripts/dev` that operate on the full stack needed to include this profile, so they'd always operate on the frontend container.
=> Use frontend profile in all docker-compose commands in scripts/dev

pkg/cedar/core/client.go, pkg/cedar/core/client_test.go, pkg/graph/generated/generated.go, pkg/graph/resolver.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/models/cedar_system.go, pkg/server/routes.go
- Remove the system info debugging route on the API
- Add a new GraphQL type and resolver for a single CEDAR System or a list of Systems
- Ensure you have a `.envrc.local` file that defines a valid `CEDAR_API_URL` and `CEDAR_API_KEY`. You can get these from the AWS Console (Systems Manager -> Parameter Store), or 1Password
- Modify `pkg/cedar/core/client.go` by setting `cedarCoreEnabledDefault` to `true` (maybe there's a better way to debug this)
- Start the server with `scripts/dev up:backend`
- Ensure you're connected to the CMS VPN
- Visit the GraphQL playground by going to http://localhost:8080/api/graph/playground
- Make some sample queries! Here is one to get started:
```graphql
query {
cedarSystems {
name
id
}
}
```
- Here is another query (that works on CEDAR IMPL)
```graphql …
```
=> [EASI-1444] System Detail GQL

.prettierrc
No Jira ticket, just a quick cleanup.
Prettier settings are specified in our `.eslintrc` file (search for `prettier/prettier`) in that file. 
The two settings in our `.prettierrc` file were `singleQuote: true` and `jsxSingleQuote: false`. `.eslintrc` already specifies `singleQuote: true`, and `jsxSingleQuote` defaults to false. ([Prettier docs](https://prettier.io/docs/en/next/options.html#jsx-quotes))
=> Remove unnecessary prettierrc file

.pre-commit-config.yaml
- Added a copy of `go-fmt-import` from https://github.com/Bahjat/pre-commit-golang.
- This is a supported hook - it can be seen in the [official pre-commit list](https://pre-commit.com/hooks.html)
- Pull this branch
- Attempt to modify `pkg/models/note.go` by moving the `"time"` import beneath the other two import statements
- Save the file
- Note: If using VSCode, open the command palette and choose the "Save without Formatting" option. This ensures the reordering will not be undone by the go formatter.
- Attempt to add and commit the file.
- You should see an error, and the file should be modified. If `goimports` catches any errors, you have to check them in again (this is intended so that you're aware of the changes before committing them) …
=> [NOREF] Added goimports pre-commit hook

pkg/cedar/core/client.go, pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/cedar_deployment.go
- Add method to CEDAR Core client for fetching deployment data from CEDAR
- Add deployment object to GraphQL schema, with associated resolvers
See my comments on individual files.
Also, I didn't add any tests; I'm not sure if I should or not. Maybe there should be some tests for the CEDAR client that check our conversion logic?
Code should work out of the box, assuming CEDAR access. Sample query/response:
```
query {
deployments(systemId:"326-2090-0", deploymentType:"Validation") {
id
name
}
}
{
"data": {
"deployments": [
{
"id": "351-3946-0",
"name": "Advanced Provider Screening v.22 Validation"
}
]
}
}
```
=> Add CEDAR deployments to GraphQL API

src/components/NavigationBar/index.scss, src/components/NavigationBar/index.tsx, src/i18n/en-US/header.ts, src/views/AccessibilityStatement/__snapshots__/index.test.tsx.snap, src/views/Cookies/__snapshots__/index.test.tsx.snap, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/MakingARequest/__snapshots__/index.test.tsx.snap, src/views/NotFound/__snapshots__/index.test.tsx.snap, src/views/PrepareForGRB/__snapshots__/index.test.tsx.snap, src/views/PrepareForGRT/__snapshots__/index.test.tsx.snap, src/views/PrivacyPolicy/__snapshots__/index.test.tsx.snap, src/views/TermsAndConditions/__snapshots__/index.test.tsx.snap
- Adds a tab to the new Navigation bar for when the sandbox flag is enabled. Now you don't have to type `/sandbox` 😁 
- If you don't have a local connection to LaunchDarkly configured, you can (temporarily) edit `src/views/FlagsWrapper/index.tsx` to turn on/off the sandbox.
=> Enable sandbox route to show up as a navigation tab

migrations/V98__Convert_LCID_Extension_Columns_To_NULL.sql, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/action.go, pkg/services/action.go, src/i18n/en-US/governanceReviewTeam.ts, src/queries/types/GetAdminNotesAndActions.ts, src/views/GovernanceReviewTeam/Notes/index.tsx
- lcid_expiration_change_new_scope
- lcid_expiration_change_previous_scope
- lcid_expiration_change_new_next_steps
- lcid_expiration_change_previous_next_steps
- lcid_expiration_change_new_cost_baseline
- lcid_expiration_change_previous_cost_baseline
All of the above columns were NULLable in the database, but the Go structs / GraphQL schema defined them as not nullable, leading to `""` being created when storing actions. This isn't problematic, except for when we deployed this code to IMPL, and the structs tried to convert NULL (which was in IMPL from previous versions of the code) to a string, which results in an error on the backend (the `string` type in Go is not nullable) 
- Make SystemIntakeLCIDExpirationChange "new" and "previous" string fields nullable
- Autogenerated code to …
=> [EASI-1378]/nullable previous and next columns

src/views/SystemProfile/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SystemHome/index.tsx, src/views/SystemProfile/components/index.tsx, src/views/SystemProfile/index.tsx
- Removed right column from static system-profile view
- Included the right column as a part of each unique sub-nav component
- Passing entire system info into the sub-component (this may be more tailored - CEDAR dependent)
- Small tweak to active nav class rendering without exact url match
Made adjustments to structure of system profile sub navigation components so it's easy for two developers to work from without conflicts.  The right-most column is intended to be a unique part of each subcomponent.  Hence it was broken out of the static view, and each developer will render that column with their respective component.
This PR will allow each of us to work on subcomponents with little conflict.
- …
=> System profile sub component structure tweaks

.pre-commit-config.yaml, scripts/pre-commit-check-code-generation
No Jira ticket, just a bug I noticed. The regex for the check-code-generation pre-commit hook wasn't triggering on changes to files under `src/queries`. [pre-commit uses Python regexes](https://pre-commit.com/#regular-expressions) (although this would apply with most regex engines); the previous regex of `src/queries/*.ts` was looking for any number of repetitions of `/`, `.*` is needed to get it to match any character.
- Pull the branch
- Make a change to a query in one of the files directly under `src/queries`
- Attempt to commit; the check-code-generation hook should fail due to changing the corresponding file under `src/queries/types`.
=> Fix regex for check-code-generation hook to properly recognize files under src/queries

src/validations/actionSchema.test.ts, src/validations/actionSchema.ts, tsconfig.json
Updated the validation logic when extending an LCID, preventing a bug that occurred for systems that were imported with invalid LCID expiration dates. Based on discussion, I updated the logic to no longer depend on the previous date at all, removing the check that required the new expiration date to be after the old one.
I also added some automated tests to the schema validation function.
I am pretty new to this automated testing paradigm, so please let me know if I'm approaching it correctly.
You can run this command to test these specific changes:
```
yarn run craco test -t 'extend lifecycle ID schema'
```
the [rotor …
=> EASI-1595/fixed expiration date bug when extending LCID

src/validations/actionSchema.ts
- Added a check for the validity of prior LCID expiration date before attempting to validate the new expiration date when extending an LCID for a system intake
=> EASI-1595/Fixed bug during validation of new LCID expiration date when extending an LCID

migrations/V100__Add_Cedar_System_Id_To_System_Intakes_Table.sql, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/system_intake.go, pkg/storage/system_intake.go, src/types/graphql-global-types.ts
- Added a migration to include CedarSystemID column on the system_intakes table
- Added this new column to the Go model for SystemIntake
- Added an optional cedarSystemId string field on the input to the UpdateSystemIntakeRequestDetails mutation
- If this field is present on the input when updating intake request details, the mutation will validate that it is a system that exists in CEDAR, and if so, set that field on the system intake
=> EASI-1527/Added optional cedar system ID when updating system intake request details

src/components/RequestRepository/index.tsx
- lasAdminNote column was configured to sort on an object instead of a string.  Changed the existing column definition to sort on the 'content' field of the lastAdminNote object.
=> Last admin note fix

cypress/support/login.js, pkg/cedar/core/deployment.go, pkg/cedar/core/role.go, pkg/graph/schema.resolvers.go
No Jira ticket - this is the result of a [Slack discussion](https://cmsgov.slack.com/archives/CNU2B59UH/p1644949782328829).
- CEDAR Core client's method's for fetching roles/deployments return an empty array instead of an error if none are found. The GraphQL endpoints need to return an error, so that check's done in the resolvers instead.
=> Change CEDAR core client to return empty arrays when no roles/deployments found

src/components/BookmarkCard/__snapshots__/index.test.tsx.snap, src/components/BookmarkCard/index.tsx, src/components/NavigationBar/index.tsx, src/views/App/index.tsx, src/views/App/scrollConfig.ts, src/views/SystemList/Table.tsx, src/views/SystemList/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/ATO/index.test.tsx, src/views/SystemProfile/components/FundingAndBudget/index.test.tsx, src/views/SystemProfile/components/SubSystems/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SubSystems/index.test.tsx, src/views/SystemProfile/components/SystemData/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SystemData/index.test.tsx, src/views/SystemProfile/components/SystemDetails/index.test.tsx, src/views/SystemProfile/components/ToolsAndSoftware/index.test.tsx, src/views/SystemProfile/components/index.tsx, src/views/SystemProfile/index.test.tsx, src/views/SystemProfile/index.tsx
- `/508` & `/systems` are new NavLink base paths
- Rename `/system-profile` base path to `/systems`
- `system-profile` still used in styles
- NavLink exact condition check on root path
- NavLinks to associated subpages/paths will become active
=> Sub-Route Navigation Underline

README.md
No Jira ticket, just missing a reference in the main README index that would be helpful for devs getting oriented in the codebase.
=> Link to docs on CEDAR from main README

pkg/server/server.go
- Changed zap logger to always instantiate with `NewProduction()` instead of using `NewDevelopment()`.
- The difference between these two, is that [NewProduction](https://pkg.go.dev/go.uber.org/zap@v1.19.1?utm_source=gopls#NewProduction) produces JSON logs, while [NewDevelopment](https://pkg.go.dev/go.uber.org/zap@v1.19.1?utm_source=gopls#NewDevelopment) produces "human friendly" logs
```
2022-02-25T16:57:29.857Z     INFO    core/system_summary.go:88       Refreshed System Summary cache
```
```json
{"level":"info","ts":1645808468.2489672,"caller":"core/system_summary.go:88","msg":"Refreshed System Summary cache"}
```
- Run `scripts/dev up` to start the application
- Run `docker compose logs -f easi` to tail the application logs
- Ensure that JSON logs are being output
- It's best to pull …
=> [EASI-1657] Change zap to always use NewProduction()

cypress/integration/governanceReviewTeam.spec.js, src/utils/systemIntake.ts, src/views/GovernanceReviewTeam/Summary/index.test.tsx, src/views/GovernanceReviewTeam/Summary/index.tsx, src/views/GovernanceReviewTeam/index.scss
- Add human readable status to the GRT Request Summary page
Ensure that correct status translation shows/updates based on different stages of a request. Example screenshots below:
**Before Change:**
**After Change:**
=> Display current status of request in GRT Summary page

pkg/cedar/core/system_summary.go
I am not convinced this is a pretty solution (hard coding `22` feels odd, even though we're likely to have the long-term solve for this well before we get new version IDs)
- Added hard-coded filters to /system/summary endpoint per [this discussion](https://cmsgov.slack.com/archives/CNU2B59UH/p1646077151888089) on Slack
- Ensure your VPN is enabled
- Navigate to `http://localhost:3000/systems`
- Ensure only ~174 systems load, rather than over 1,000
=> [NOREF] Add filters to the /system/summary endpoint

scripts/testsuite
No Jira ticket. Fixing a bug in `scripts/testsuite`, which is run by the `server_test` job to check backend test coverage. The line for printing an error message when test coverage falls beneath the desired amount had an unresolved variable error, due to `RED` and `NC` not having values assigned.
=> Fix unbound variable bug in scripts/testsuite

pkg/cedar/core/system_summary.go
This is a continuation of #1507
- Removed hard-coded `version=22` filter on `/system/summary`
- This is because `state=active` automatically calculates the most recent version, and we're already applying that!
* Ensure your VPN is enabled
* `scripts/dev up`
* Navigate to http://localhost:3000/systems
* Ensure only ~174 systems load (the same as before!)
=> [NOREF] Remove system summary hard-coded version filter

.github/workflows/build.yml
Small change to the workflow trigger; [this PR](https://github.com/CMSgov/easi-app/pull/1527) didn't trigger actions to be run. The [syntax for Github actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) specifies that `*` does **not** match `/` characters; the `**` glob pattern is needed to match those.
=> Change wildcard pattern to run workflow on *all* branches in PRs

src/components/Spinner/index.scss, src/stylesheets/_variables.module.scss, src/views/GovernanceTaskList/TaskListCta.tsx
- Changed route param variable from `businessCaseId` to `id`
- Dart-sass was failing to compile a deprecated division method - switch method to recommended
The route `/governance-task-list/:systemId/prepare-for-grt` should have a system id rather than a businessCaseId.
Changing the intake status 'Easy Access to System Information' after seeded to 'READY_FOR_GRT' will allow you to hit the view that pertains to this bug.
=> EASI-1703 - Changed route param businessCaseId to id

src/components/shared/ErrorAlert/index.tsx, src/views/Accessibility/AccessibilityRequest/Create/index.tsx, src/views/Accessibility/AccessibilityRequest/Documents/New/index.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/GovernanceReviewTeam/Actions/ExtendLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTFeedbackToBusinessOwner.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTRecommendationsToGRB.tsx, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx, src/views/RequestTypeForm/index.tsx, src/views/TestDate/Form.tsx
- Implemented `setError` method on Formik forms to reset errors before submission
This method exists on some existing forms, but not all.  Extended this for any form that displays errors so that users are notified by scrolling on each attempted submission.
Dylan has a video on how to reproduce this effect in the JIRA ticket.
- Create a GRT intake request.
- Open the intake request (with a GRT team job code).
- Issue a lifecycle ID for the intake request.
- Go to the actions tab -> Extend Lifecycle ID
- Enter an invalid expiration date (but scope and steps are valid).
- Attempt to submit the form. The page should scroll to the date field where the validation error is; this is expected.
- Correct the date to be valid, but remove the text in the scope field to make it invalid.
- Attempt to …
=> Easi 1646 - Scroll validation error fix

cmd/easi/test/test.go, cypress/integration/login.spec.js, pkg/integration/integration_test.go
This adds retry logic to the following tests
- The backend `TestIntegrationTestSuite()` test suite
- The retry logic added is done before any tests are executed, as the Okta Auth Token (and use of the OTP) happens before we run `suite.Run()`
- The Cypress `login.spec.js` spec
- This adds a `retries` parameter to the tests configuration. [Cypress test retries are documented here](https://docs.cypress.io/guides/guides/test-retries)
I'll probably just try to run another branch's tests and this at the same time and see if any of the retry logs are printed for the Cypress or Backend tests. I'll update this comment with my findings!
https://user-images.githubusercontent.com/15203744/160636749-5f1c4b78-6b7e-4f08-886f-e2d44b1b0b40.mp4
- It's best to pull the branch locally and test it, rather …
=> [EASI-1494] Add retry logic to integration tests

docs/dev_environment_setup.md, docs/docker_compose.md, docs/local_testing.md, docs/operations/deployment_process.md
No Jira ticket, just a few bugfixes I saw in the docs.
* Removing an attempt to set an anchor to the "direnv" heading in dev_environment_setup.md; it's possible to link to that heading without explicitly declaring an anchor.
* Changing most links to absolute links rather than relative; some of these were broken when we broke up the single README file at the root of the repo, and having absolute links means they'll still work even if the doc file is moved.
=> Docs - link fixes

scripts/db_lambda_invoke
This change is being introduced to help debug events like [this](https://github.com/CMSgov/easi-app/runs/5740902546?check_suite_focus=true)
- Log the lambda response using JQ
=> [NOREF] Log lambda response inside db_lambda_invoke

src/components/ArticleCard/__snapshots__/index.test.tsx.snap, src/components/ArticleCard/index.tsx, src/components/RelatedArticles/__snapshots__/index.test.tsx.snap
- Change class name for the Article Card so that it becomes `grid-col-4` when its big window sizes
|   |    |
|:-:|---|
|Before|![image](https://user-images.githubusercontent.com/2349702/162266755-d0515a39-1e57-4554-82db-a7f1febab705.png)|
|After|![image](https://user-images.githubusercontent.com/2349702/162266896-f3f1d1d6-5db4-4284-b45e-9b77f5887f75.png)|
=> NOREF -- Add Article Card Component full width when smaller than desktop view

src/components/HelpBreadcrumb/__snapshots__/index.test.tsx.snap, src/components/HelpBreadcrumb/index.test.tsx, src/components/HelpBreadcrumb/index.tsx, src/components/HelpContacts/__snapshots__/index.test.tsx.snap, src/components/HelpContacts/index.test.tsx, src/components/HelpContacts/index.tsx, src/components/HelpPageIntro/__snapshots__/index.test.tsx.snap, src/components/HelpPageIntro/index.test.tsx, src/components/HelpPageIntro/index.tsx, src/components/HelpTag/__snapshots__/index.test.tsx.snap, src/components/HelpTag/index.test.tsx, src/components/HelpTag/index.tsx, src/i18n/en-US/help.ts, src/types/articles.ts
**Reusable components for the Knowledge Center**
- `<HelpBreadcrumb>`
- Accepts type prop ("back" or "close") to render breadcrumb button
- Note: The close tab button functionality does not work yet.
- `<HelpTag>`
- Linked tag to be used in articles and ArticleCard component
- Pass article type as prop to render tag with correct path
- `<HelpPageIntro>`
- Page intro text for help section
- `<HelpContacts>`
- Additional contacts section
- Pass article type (string or or multiple types as array) to display additional contacts
- Always make comments, even if it's minor, or if you don't …
=> [NOREF] - Help Section Shared Components

pkg/graph/resolver.go, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/server/routes.go, pkg/services/action.go
- When an intake's lifecycle ID is extended, send an email notification to the requester, instead of the GRT user who granted the extension.
- Move email code into the `services` package for consistency instead of being in the GraphQL resolver.
- Create an intake request with some user (i.e. ABCD).
- Log off and log in with a different user (i.e. WXYZ) with GRT permissions.
- Issue an LCID for the intake request as WXYZ.
- Extend the LCID as WXYZ.
- Check MailCatcher; a notification should be sent to ABCD about the LCID extension, not WXYZ.
GRT user WXYZ granted LCID extension:
Notification email for LCID extension sent to requester, ABCD:
=> Notify requester on LCID extension instead of GRT user

docs/adr/0034-send-cedar-intake-async.md
- Added an ADR to capture intended approach for how we are going to send data to the CEDAR Intake API.
- *NOTE* - This document does not cover the technical details of the approach, but rather the intended switch from modifying individual actions to send to CEDAR to a scheduled job that sends to CEDAR.
📜  👀 
=> [NOREF] Added ADR for CEDAR Intake API async approach

src/components/TestingTemplates/__snapshots__/index.test.tsx.snap, src/components/TestingTemplates/index.scss, src/components/TestingTemplates/index.test.tsx, src/components/TestingTemplates/index.tsx, src/i18n/en-US/accessibility.ts, src/i18n/en-US/articles/templatesFor508Testing.ts, src/views/Accessibility/TestingTemplates/__snapshots__/index.test.tsx.snap, src/views/Accessibility/TestingTemplates/index.tsx, src/views/FlagsWrapper/index.tsx, src/views/Help/Section508/TestingTemplate/index.tsx, src/views/Help/Section508/articles.ts, src/views/Help/index.tsx
- Created new `TestingTemplateBase` for new article 
- Tweaked existing '508 Templates' view/component
- Tweaked existing component to reuse any area within EASI
- Added tests
1. Navigate to http://localhost:3000/help
2. Find and click on the link:  `View Section 508 articles`
3. Find and click on the link:  `Templates for 508 testing`
4. Ensure new tab opens with the article.
5. Ensure article look and copy reflects figma
- Reuse existing '508 Templates' view/component
- May need to tweak existing component to be reusable in any area within EASI
- Testing where applicable
=> [Easi-1905] Create "Templates for 508 testing" help article

pkg/cedar/core/role.go, pkg/models/cedar_role.go
This is associated with @adamodd's work on [EASI-1936](https://jiraent.cms.gov/browse/EASI-1936), following up a [Slack conversation](https://oddball.slack.com/archives/C037ZNEQ7DH/p1651066570255429).
Changes:
- Have GraphQL return all-caps values for `CedarAssigneeType` fields, to match up with the frontend types that generated from the GraphQL schema.
- Introduce a separate set of constants for the lower-cased AssigneeType values that are returned from CEDAR, which our CEDAR Core client then maps to the all-caps `CedarAssigneeType`.
With these changes:
=> Map lowercase assignee types returned from CEDAR to uppercase GQL values

pkg/graph/schema.resolvers.go
- Quick follow-up to EASI-1971, caught a bug in IMPL with the detailed cedar system info query that was using versionID, changed it to use IctObjectID
=> Fixed incorrect id used in detailed cedar system info query

.pre-commit-config.yaml, pkg/cedar/intake/models/easi_grt_feedback.go, pkg/cedar/intake/models/easi_intake.go, pkg/cedar/intake/schemas/easi_grt_feedback.json, pkg/cedar/intake/schemas/easi_system_intake.json, pkg/cedar/intake/translation/constants.go, pkg/cedar/intake/translation/feedback.go, pkg/cedar/intake/translation/system_intake.go
- Adds an `intakeId` field to the body of system intakes submitted to CEDAR Intake.
- Adds a `feedbackId` field to the body of GRT feedback items submitted to CEDAR Intake.
- [Slack thread with discussion with CEDAR team](https://cmsgov.slack.com/archives/C02KTCN3ADD/p1652812332841499?thread_ts=1652727307.282289&cid=C02KTCN3ADD). 
- This isn't strictly essential, we're using the same value in the `clientId` field that's part of the Intake API, but this makes it easier for the CEDAR team to just map data based on the body.
=> Add IDs to feedback/system intake objects sent to CEDAR Intake

cmd/test_cedar_intake/main.go
No Jira ticket, just a quick fix to the test data we send over to the CEDAR Intake API - making sure the system intake and business case have createdAt/updatedAt set. In our actual system, these should always be set when intakes/business cases are saved to our database.
=> Add createdAt/updatedAt to test data for sending to CEDAR Intake

src/components/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/components/GovernanceOverview/index.test.tsx, src/components/GovernanceOverview/index.tsx, src/i18n/en-US/taskList.ts, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/GovernanceTaskList/TaskListCta.tsx, src/views/GovernanceTaskList/index.tsx
- Display "Prepare for GRB Meeting" and "Prepare for GRT Meeting" help links in IT Governance Task List and IT Governance Steps Overview
- Test IT Governance request in both GRT and GRB meeting phases
- When phase is inactive, link should be unstyled
- When phase is active, link should be primary CTA button 
- Start new IT Governance request to see steps overview links
=> [EASI-1939] - Display prepare for GRT/GRB meeting help links

pkg/cedar/core/client.go, pkg/cedar/core/system_summary.go
This PR introduces 2 changes
- Changes the logging that happens when we get an error refreshing the CEDAR Cache to a `Warn()` instead of an `Error()`
- Modifies `GetSystemSummary` to return an error if an empty response array is returned.
- This change was made as it would seem that the CEDAR cache would occasionally get flushed
=> [NOREF] CEDAR Cache logging / error handling

pkg/cedar/cedarldap/translated_client.go
Removed an error that was being thrown when no valid contacts were retrieved from CEDAR in FetchUserInfos
Query systems to find one to use for testing, make sure it doesn't already have any contacts
```GraphQL
query {
systems(first: 0) {
edges {
node {
id
}
}
}
}
query {
systemIntakeContacts(id: "testID") {
systemIntakeContacts {
euaUserId
component
role
commonName
email
}
}
}
```
Add an invalid contact
```GraphQL
mutation {
createSystemIntakeContact(input: { euaUserId: "XEEX", systemIntakeId: "testID", role: "Supreme Overlord", component: "IT" }) {
systemIntakeContact{
euaUserId
systemIntakeId
component
role
}
}
}
```
Query the intake contacts again and make sure it contains "XEEX" in the invalidEUAIDs list, rather than an error
Add a valid contact and query contacts again, making sure …
=> EASI-2070/Handle errors when system intake contacts include invalid EUAs

migrations/V109__Add_UUID_to_System_Intake_Contacts.sql, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/system_intake_contact.go, pkg/storage/system_intake_contact.go, pkg/storage/system_intake_contact_test.go
- Wiped system_intake_contacts table in order to recreate it with a unique ID
- Added backend logic to update a system_intake_contact using the ID
- Added GraphQL mutation to update a contact
Get a system ID:
```GraphQL
query {
systems(first: 0) {
edges {
node {
id
}
}
}
}
```
Create a contact
```GraphQL
mutation {
createSystemIntakeContact(input: { euaUserId: "SGXL", systemIntakeId: "c0ff43c0-5f0e-4709-bf72-d76b9e2ac3ea", role: "Developer", component: "IT" }) {
systemIntakeContact{
euaUserId
systemIntakeId
component
role
}
}
}
```
Update the contact
```GraphQL
mutation {
updateSystemIntakeContact(input: { id: "bdac5619-f11d-4849-bc23-d32ca531e9df", euaUserId: "SGXL", systemIntakeId: "c0ff43c0-5f0e-4709-bf72-d76b9e2ac3ea", role: "Nitpicker", component: "IT" }) {
systemIntakeContact{
id …
```
=> EASI-2004/Update System Intake Contacts

src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/components/BusinessCaseReview/index.tsx, src/components/PDFExport/index.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap
- Fix for PDF Export button spacing issue introduced in sample business case pr
Before:
After:
- Business case review - Download as PDF button should have space between it and costs review table (3rem top margin on button parent div)
=> [NOREF] - Fix PDF export link spacing issue

pkg/cedar/core/threat.go
No ticket - fixing a bug observed earlier today (Friday 6/17) where the system profile for a system with no ATOs displayed a 404 error. Prod URL to reproduce: https://easi.cms.gov/systems/408-4567-0/home/top
This just adds an early-return to the CEDAR Core client if no ATOs are returned, to avoid calling CEDAR's `/threat` endpoint with no ATO IDs.
Screenshots with this fix implemented:
System Home:
ATO subpage:
=> Add early-return to CEDAR Core client for threats when there's no ATOs

package.json, yarn.lock
No ticket; this is a dependency update to fix an issue I had with Cypress where I couldn't click on the menu bar or open developer tools in Cypress. (See https://github.com/cypress-io/cypress/issues/16323) I'm Windows+WSL, using an X server to run Cypress's GUI; I don't know if the Mac folks have seen this same issue.
Cypress v8.3.0 has the bugfix; I upgraded to the latest 8.x.x minor version, because both [version 9](https://docs.cypress.io/guides/references/changelog#9-0-0) and [version 10](https://docs.cypress.io/guides/references/changelog#10-0-0) look like they have pretty significant breaking changes, and I didn't want to deal with those.
Cypress works well for me on Windows (and the bug's fixed), it works well in CI, but I'm not sure about on Macs. I'd very much appreciate it if …
=> Upgrade Cypress to v8.7.0

.github/workflows/run_tests.yml, docker-compose.ci_server_test.yml, docker-compose.yml, migrations/V112__Remove_app_user.sql, pkg/appconfig/config.go, pkg/server/config.go
This is a follow-up on https://github.com/CMSgov/easi-app/pull/1677
- Remove the use of the `DB_IAM_USER` environment variable
- This was temporary, and only served to help the cutover to IAM in case we needed to roll back to an older version of code.
- Remove the `app_user` with a new migration.
- This means that, when running locally with a user/pass, we should use `postgres/mysecretpassword` instead of the app user, since it will no longer exist.
- I decided to remove the `app_user` entirely. This means that in deployed instances, the only user will be the `app_user_iam` and the master user. Locally, we'll just use `postgres` (master user)
This mainly affects our deployed code, but it should be worth confirming that this works locally by running `scripts/dev up` and ensuring that you …
=> [EASI-2028] Remove cutover environment variables

cypress/integration/systemIntake.spec.js, cypress/integration/taskList.spec.js, cypress/support/systemIntake.js, src/views/SystemIntake/RequestDetails/index.tsx
- Changed the input label for "Project Name" to "Contract/Request Name"
Navigate to the request details page and verify that the label is changed
=> EASI-2117/Rename "Project Name" field to "Contract/Request Name" on Request Details Page

.envrc, .github/workflows/run_tests.yml, cmd/test_email_templates/main.go, docker-compose.yml, pkg/appconfig/config.go, pkg/email/email.go, pkg/server/config.go, pkg/server/routes.go
- Added the parameters to parameter store in dev, impl, and prod as `/{environment}/easi-app/email/it-investment-email`
- Added an environment variable called `IT_INVESTMENT_EMAIL`
I'm up for suggestions...
=> EASI-2024/Add configuration parameter in Parameter Store for IT Investment mailbox address

src/views/SystemProfile/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/ATO/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SystemHome/__snapshots__/index.test.tsx.snap
- Updated snapshots to reflect expired ATO from mock data
https://github.com/CMSgov/easi-app/blob/e96b82a3998500fd76fbf3e231bc811915d6c27c/src/data/mock/systemProfile.ts#L24
There was a line of mock data that had `07-30-2022` as the ATO expiry date, so when we actually passed that date, the snapshots changed to reflect that the ATO was expired. This just updates the snapshots to remedy that, and it shouldn't be an issue going forward in this case!
- `yarn test`
=> [NOREF] Update snapshots for date-based tests

pkg/cedar/core/cedar_core.json, pkg/cedar/core/gen/client/budget/budget_add_parameters.go, pkg/cedar/core/gen/client/budget/budget_update_parameters.go, pkg/cedar/core/gen/client/c_e_d_a_r_core_api_client.go, pkg/cedar/core/gen/client/component/component_add_parameters.go, pkg/cedar/core/gen/client/contract/contract_add_parameters.go, pkg/cedar/core/gen/client/contract/contract_update_parameters.go, pkg/cedar/core/gen/client/deployment/deployment_add_parameters.go, pkg/cedar/core/gen/client/deployment/deployment_update_parameters.go, pkg/cedar/core/gen/client/exchange/exchange_add_parameters.go, pkg/cedar/core/gen/client/exchange/exchange_update_parameters.go, pkg/cedar/core/gen/client/person/person_add_parameters.go, pkg/cedar/core/gen/client/person/person_update_parameters.go, pkg/cedar/core/gen/client/role/role_add_parameters.go, pkg/cedar/core/gen/client/support_contact/support_contact_add_parameters.go, pkg/cedar/core/gen/client/system/system_summary_find_list_parameters.go, pkg/cedar/core/gen/client/user/user_add_parameters.go, pkg/cedar/core/gen/client/user/user_id_update_parameters.go, pkg/cedar/core/gen/client/user/user_name_update_parameters.go, pkg/cedar/core/gen/models/contract.go, pkg/cedar/core/gen/models/software_product_details.go, pkg/cedar/core/gen/models/system_detail.go, pkg/server/server.go
New Swagger introduced in https://github.com/CMSgov/easi-app/pull/1708 has incorrect details for properties on the `SoftwareProductDetails` object; this PR reverts the Swagger file change, the old Swagger should have everything needed for using the CEDAR `/exchange` API for EASI-2167.
=> Revert to using older CEDAR Core Swagger that doesn't have errors for SoftwareProductDetails

.github/workflows/deploy_pipeline.yml, docs/adr/0018-integration-tests-third-party-apis.md, docs/adr/0021-audit-logging.md, docs/frontend.md, docs/operations/deployment_process.md, scripts/github-action-announce-broken-branch
- References to `master` have been modified to also allow references to `main`.
[GitHub docs on renaming `master` to `main`](https://github.com/github/renaming)
1. Merge this ticket
2. Rename the default branch of this repository from `master` to `main`
3. Create a new PR that removes all references to `master`
Once the rename is done, folks will have to do the following locally:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
- Validate that all references to the `master` branch of this repository are properly modified to allow `main` alongside `master`.
- Check that all code is adequately covered by tests - if it isn't feel …
=> [NOREF] Allow builds for both 'master' and 'main'

src/components/RequestRepository/index.tsx, src/components/RequestRepository/tableMap.ts, src/data/systemIntake.ts
- Fixed an issue causing the system intake request object on the frontend from being overwritten by a string when rendering the requests table. This made the CSV export have missing values for requester and component, since the object containing that data was replaced by a string
- Renamed string that the frontend table uses to requesterNameAndComponent, so that no existing properties would be overwritten
Navigate to the requests page on the frontend, confirm that the requester column on the table is the same as it was before (a string, concatenating requester and component). Then click the "Download all requests as excel file" button, and confirm that the CSV file has correct values for the Requester and Component columns.
- It's best to pull the branch locally and test it, rather than …
=> [EASI-2149] fixed bug causing requester obj to be overwritten for csv export

pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_system_intake_test.go
- Modify resolver code to pull from CEDAR instead of the DB when getting a System Intake's requester' email
- A test was modified for validating this behavior
- A new test was written for validating behavior when an intake with no EUAUserID is requested (should error out)
Otherwise:
- Use `scripts/dev up:backend` to start up the app's backend
- Use `scripts/dev db:seed` to seed the data
- Make the following GQL request:
```graphql
query test {
systemIntake(id: "<SOME ID>") {
id,
requester {
name
component
email
}
}
}
```
and validate that the `email` field looks correct.
- Always make …
=> [NOREF] Populate System Intake Requester Email with CEDAR

src/components/Footer/index.test.tsx, src/components/Footer/index.tsx
Patch to put the HelpFooter component behind okta's isAuthenticated.
The help footer is visible after signing in.
Also updates the test to use rtl instead of enzyme.
=> Help footer behind authenticated

src/validations/systemIntakeSchema.test.ts, src/validations/systemIntakeSchema.ts
Proper date validation for contract start & end fields
- Jest run `systemIntakeSchema`
- Qa the form field for dates [seen here](https://jiraent.cms.gov/secure/attachment/536240/Screen%20Shot%202022-06-30%20at%2010.28.00%20AM.png)
- Single digit years used to pass validation. It shouldn't anymore.
=> EASI-2154 Incorrect Date Validation - Contract Start/End

src/views/SystemIntake/ContractDetails/index.tsx
Fix some date fields in system intake contract detail form step so that word characters don't crash the render.
Originally thought to do this with intersecting an onChange handle to only return numbers from a string, but since input elements are tied up with formik, it ended up easier to handle nans in the formatting function that gets called on auto-saves.
Detail of reproduction steps to qa and test in [ticket](https://jiraent.cms.gov/browse/EASI-2311).
=> EASI-2311 Handle nans in `formatContractDetailsPayload`

cmd/devdata/main.go, go.mod, migrations/V116__Add_TRB_Request.sql, pkg/applychanges/apply_changes.go, pkg/applychanges/apply_changes_test.go, pkg/graph/generated/generated.go, pkg/graph/resolvers/base_struct.go, pkg/graph/resolvers/resolver_test.go, pkg/graph/resolvers/trb_request.go, pkg/graph/resolvers/trb_request_test.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/base_struct.go, pkg/models/trb_request.go, pkg/storage/SQL/trb_request_collection_get.sql, pkg/storage/SQL/trb_request_create.sql, pkg/storage/SQL/trb_request_get_by_id.sql, pkg/storage/SQL/trb_request_update.sql, pkg/storage/trb_requestStore.go, pkg/storage/truncate.go, scripts/dev
* trb request migration, sql and model
* introduce apply changes
* Add types for status and type. placeholder store methods. placeholder resolver
* store implemented, GQL implemented.Seed data added
* introducing unit tests
* add unit test for TRB_Request
* introduce base_struct pre-commit
* renamed time fields to use at instead of dts for consistency
* Update BaseStructPreuUpdate comment to be more descriptive
* Add additional clarification to the ApplyChanges method
* move apply changes to separate package, and rename baseStruct pre-update, remove optional apply changes
-- See pull for the initial [TRB work](https://github.com/CMSgov/easi-app/pull/1760)
- Check that all code is adequately …
=> Easi 2323/trb request table and gql (#1760)

cmd/test_cedar_intake/main.go, docs/cedar.md, pkg/cedar/intake/README.md, pkg/cedar/intake/client_test.go, pkg/cedar/intake/models/easi_intake.go, pkg/cedar/intake/schemas/easi_system_intake.json, pkg/cedar/intake/translation/constants.go, pkg/cedar/intake/translation/system_intake.go, pkg/testhelpers/system_intake.go
- Added ContractNumber to the EASIIntake schema, updated logic to set this property when publishing an intake
- Updated IntakeInputSchemaEASIIntakeVersion to EASIIntakeV06
- Ran generation scripts, included updated Swagger file
- Updated outdated doc that was pointing to an old generation script that doesn't exist anymore (generate_cedar_intake_client was replaced by generate_cedar_clients)
Open to feedback here...
=> [EASI-2318] Updated CEDAR Intake API schema to include contract number of system intake

.envrc
- Created a new [local environment in LaunchDarkly](https://app.launchdarkly.com/default/local/features)
- Renamed our old dev/local account to just be for dev
- Modify your `.envrc.local` LaunchDarkly configs to match [what's in 1Password](https://start.1password.com/open/i?a=RYAMO7WYSJHNNCGOFE3Q2TVVUE&v=j3plnuuwh2alqm5hw3pp65afza&i=w72jgnsgx5atveahlt2egu3j4y&h=cmseasi.1password.com)
- `scripts/dev up` to start the service
- Tinker with targeted rules like `Sandbox` and ensure that they only affect your local environment, and only for the user you're signed in as (should work with local auth or Okta auth)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest …
=> [NOREF] Use dedicated 'local' environment in .envrc

.envrc
Small fix to the syntax in `.envrc`, correcting a bug from [this PR earlier](https://github.com/CMSgov/easi-app/pull/1776). The line
```sh
export LD_SDK_KEY=<check 1Password to find this value>
```
caused a syntax error when `direnv` tried to evaluate it (at least using `bash`):
```
direnv: loading ~/source/repos/easi-app/.envrc
./.envrc:70: syntax error near unexpected token `newline'
./.envrc:70: `export LD_SDK_KEY=<check 1Password to find this value>'
```
This PR changes the value to just a regular quoted string, which works fine.
=> Correct syntax in .envrc file

src/views/GovernanceReviewTeam/Actions/ExtendLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTFeedbackToBusinessOwner.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTRecommendationsToGRB.tsx, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx
- Hacky fix for when the `systemIntake.requester.email` field is `null` (should send empty array, rather than `[null]`)
=> [NOREF] Fixing null recipient email when CEDAR LDAP returns null for an email

pkg/cedar/intake/client_test.go, pkg/cedar/intake/translation/system_intake.go
- Modified the logic that translates our system intake into a payload for the CEDAR Intake API to use the funding source ID for `fundingSourceID` instead of the System Intake ID
Stemmed from [this conversation](https://cmsgov.slack.com/archives/C02KTCN3ADD/p1663960022481519) and [this conversation](https://cmsgov.slack.com/archives/CNU2B59UH/p1664200443443389)
1. Start the app with `scripts/dev up:backend`
2. Run `scripts/dev test:go:only github.com/cmsgov/easi-app/pkg/cedar/intake` to run the new tests that were added to test this change
- Always make comments, even if it's minor, or …
=> [NOREF] Fix funding source ID cedar intake

cmd/test_cedar_intake/main.go, go.sum, pkg/cedar/intake/README.md, pkg/cedar/intake/models/easi_biz_case.go, pkg/cedar/intake/schemas/easi_business_case.json, pkg/cedar/intake/translation/biz.go, pkg/cedar/intake/translation/constants.go, pkg/server/routes.go, pkg/services/action.go, pkg/services/action_test.go
- Re-applies changes from https://github.com/CMSgov/easi-app/pull/1785 to submit draft business case data to the CEDAR Intake API.
- Add subcommands to `cmd/test_cedar_intake/main.go` - the `submit` subcommand runs the previous functionality of submitting to CEDAR from your local machine, while the `dump` subcommand creates JSON files locally as examples of the payloads that will be sent to CEDAR.
- ID field removed from lifecycle cost lines - from discussion with the CEDAR team, we decided to remove IDs from sub-entities; CEDAR will delete and regenerate sub-entities on their end when a top-level entity is updated.
First, enable the `emit-to-cedar` feature flag for your EUA ID in the local environment in LaunchDarkly.
The easiest way to test this is to put a log/print statement in …
=> Rework draft business case submission to CEDAR Intake

go.mod, go.sum, pkg/cedar/core/role.go, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/cedar_role.go, scripts/testsuite
CEDAR uses the term "role type" to refer to general concepts like "Business Owner" or "System Maintainer"; "role" refers to an assignment of one of these role types to a person or organization on a particular system in CEDAR. The code in this PR follows this same terminology.
- Add a GraphQL query (and associated CEDAR Core client method) for listing all available role types in CEDAR.
- Add a GraphQL mutation (and associated CEDAR Core client methods) that allows editing the role types for a given user on a given system to a desired list of role types. The implementation for this method will add and/or delete roles in CEDAR as necessary to match the desired role types for the user on the system.
1. Connect to the VPN.
2. Make sure your connection to CEDAR is set to target CEDAR's **impl** …
=> Implement backend support for editing user roles in System Profile

.envrc, .github/workflows/run_tests.yml, docker-compose.yml, pkg/appconfig/config.go, pkg/email/email.go, pkg/email/email_test.go, pkg/email/templates/trb_request_form_submission_admin.gohtml, pkg/email/templates/trb_request_form_submission_requester.gohtml, pkg/email/trb_request_form_submission.go, pkg/email/trb_request_form_submission_test.go, pkg/graph/resolvers/trb_request_form.go, pkg/graph/resolvers/trb_request_form_test.go, pkg/graph/schema.resolvers.go, pkg/server/config.go
- When a TRB request form is submitted, send notification emails to the requester and to the TRB inbox.
- Introduces a new config variable, `TRB_EMAIL`, for the TRB inbox address.
These are screenshots of how Mailcatcher renders the emails:
Run the following GraphQL mutation to create a TRB request:
```gql
mutation {
id
type
form {
id
status
trbRequestId
component
needsAssistanceWith
hasSolutionInMind
proposedSolution
whereInProcess
whereInProcessOther
hasExpectedStartEndDates
expectedStartDate
expectedEndDate
collabGroups
collabDateSecurity
collabDateEnterpriseArchitecture
collabDateCloud
collabDatePrivacyAdvisor
collabDateGovernanceReviewBoard
collabDateOther
collabGroupOther
createdBy
createdAt
modifiedBy
modifiedAt
}
}
}
```
Note down the …
=> Notify requester and TRB admins when TRB request form is submitted

pkg/email/email.go, pkg/email/templates/trb_attendee_added.gohtml, pkg/email/templates/trb_request_form_submission_requester.gohtml, pkg/email/trb_attendee_added.go, pkg/email/trb_attendee_added_test.go, pkg/email/trb_request_form_submission_test.go, pkg/graph/resolvers/trb_request_attendee.go, pkg/graph/resolvers/trb_request_attendee_test.go, pkg/graph/schema.resolvers.go
- When a TRB attendee is added (by calling the `createTRBRequestAttendee` GQL mutation), send them an email notification that they've been added to the attendee list.
- Small change to the email notification for requesters on TRB form submission - add an `<hr>` to match the Figma.
Screenshot of the attendee notification, rendered by Mailcatcher:
Screenshot of the requester notification, with the `<hr>` (compare to [Figma](https://www.figma.com/file/iGatgTnlzTuqW9CQFYHDam/TRB-Intake-e2e?node-id=1060%3A88786&t=QG9ReTyUNL5sNR4B-0)):
Run the following GraphQL mutation to create a TRB request, noting down the returned request ID:
```gql
mutation {
id # use this for the following steps
form {
status
}
taskStatuses {
formStatus
feedbackStatus …
```
=> Notify attendees when they're added to a TRB request

.github/dependabot.yml
Small follow-up to https://github.com/CMSgov/easi-app/pull/1848, preventing the `aws-actions/configure-aws-credentials` github action from receiving dependabot updates that would take us off `v1-node16`, like [this one](https://github.com/CMSgov/easi-app/pull/1855). Per [this issue](https://github.com/aws-actions/configure-aws-credentials/issues/489#issuecomment-1278145876) on the `configure-aws-actions` repository, they're not going to update to Node 16 until v2 (a major version update), so we should keep using `v1-node16`.
Documentation on configuring Dependabot ignore: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
=> Ignore minor/patch upgrades to configure-aws-credentials GH action

pkg/email/trb_request_consult_meeting.go, pkg/email/trb_request_trb_lead.go
- Separated the parameters that are needed for the TRB consult meeting email function from the parameters that are used by the email template
- Separated the parameters that are needed for the TRB lead email function from the parameters that are used by the email template
```GraphQL
mutation {
id # use this for the following steps
form {
status
}
taskStatuses {
formStatus
feedbackStatus
consultPrepStatus
}
}
}
mutation {
updateTRBRequestForm(
input: { isSubmitted: true, trbRequestId: "trbRequestIdFromAbove" }
) {
status
}
}
mutation {
createTRBRequestFeedback(
input: {
trbRequestId: "trbRequestIdFromAbove"
feedbackMessage: "This is TRB request is NICE!"
copyTrbMailbox: true
notifyEuaIds: ["FAKE", "REAL", "LOLZ"]
action: READY_FOR_CONSULT
}
) {
id …
```
=> [EASI-2580] Separate TRB email method parameters from the template parameter structs

pkg/graph/resolvers/trb_advice_letter.go, pkg/graph/resolvers/trb_request_feedback_test.go, pkg/graph/resolvers/trb_task_status.go, pkg/storage/trb_advice_letter.go
- Change `GetTRBAdviceLetterByTRBRequestID()` to return `nil, nil` in the case of no rows. (This is the approach Clay, Jeremy, and I agreed on after discussion, it'll be implemented for all TRB store methods in EASI-2581)
- When checking `adviceLetterStatus`, don't log an error, as there's no need.
- When looking up data for an existing advice letter, _do_ log and return an error.
- Refactor utility methods in `pkg/graph/resolvers/trb_task_status.go` to be private methods; they don't need to be public, they're just used by `GetTRBTaskStatuses()`, which is called from `schema.resolvers.go`.
To detect the spurious error when checking `adviceLetterStatus` - check out `main`, spin up the backend and open the GraphQL playground. Create a TRB request and use its ID in the query
```gql
query { …
```
=> EASI-2388 - correcting spurious error logging, making methods private

src/i18n/en-US/home.ts, src/i18n/en-US/intake.ts, src/i18n/en-US/makingARequest.ts, src/views/MakingARequest/__snapshots__/index.test.tsx.snap, src/views/RequestTypeForm/index.test.tsx, src/views/RequestTypeForm/index.tsx
- Remove request "decommission" text from homepage
- Remove "decommission" text from IT Gov explanation
- Remove "decommission/shutdown" option from the request types
- Remove test case
- Remove request type case in the form submit function in [src/views/RequestTypeForm/index.tsx](https://github.com/CMSgov/easi-app/blob/08104738907b2d32d8193847347b77b8e4950f49/src/views/RequestTypeForm/index.tsx#L63-L65)
- Remove "Decomission a system" translation text in [src/i18n/en-US/intake.ts](https://github.com/CMSgov/easi-app/blob/08104738907b2d32d8193847347b77b8e4950f49/src/i18n/en-US/intake.ts#L83)
QA the IT Gov request flows to make sure there are no regression on the other remaining request types or IT Gov processes.
=> EASI-2568 Remove Decommission System as an option from IT Gov

cypress/e2e/trbRequest.cy.js, cypress/support/trbRequest.js
- Replaces a `cy.wait` paired with `cy.intercept` with a `cy.contains`. This hopefully makes it so that we're able to retry DOM queries instead of hoping a `cy.intercept` fires in the order we expect
- Ensure E2E tests pass locally and on CI!
=> [NOREF] Attempting to fix cypress intercept flake

cypress/e2e/accessibility.cy.js, src/components/NavigationBar/index.tsx, src/types/flags.ts, src/views/App/index.tsx, src/views/FlagsWrapper/index.tsx
- Create new permanent LD feature flag "hide508Workflow" with a default variation of true
- Hide 508 workflow (both UI components and routes) behind the new feature flag
=> [EASI-2845] Hide 508 workflow behind LaunchDarkly feature flag

pkg/appses/ses.go, pkg/appses/ses_test.go, pkg/local/email.go
- Skip sending emails when `toAddresses` is empty
- Check that the CI tests pass (which run the appses suite, specifically this file)
https://github.com/CMSgov/easi-app/blob/4209f5be9cc6b7f89e547fa5f4bfad9e6c0bcb87/pkg/appses/ses_test.go#L77-L87
=> [NOREF] Skip sending emails when no toAddressses is provided

pkg/graph/generated/generated.go, pkg/graph/resolvers/trb_request.go, pkg/graph/resolvers/trb_request_test.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
- Adds `isRecent` to TRB Request type in GQL
- Currently only looks to see if a request was created in the past week, and doesn't do anything else.
- Added unit tests to [trb_request_test.go](./pkg/graph/resolvers/trb_request_test.go)
- Look at the unit tests and ensure they both pass and make sense
- Create a TRB request locally and use PSQL/Postico/PGAdmin to modify the "created at" date to see if the query comes back as expected.
=> [NOREF] Add `isRecent` property to TRB Requests

pkg/cedar/cedarldap/translated_client.go
- Reduce (occasionally) expected cases for CEDAR LDAP client to `logger.Warn` from `logger.Error`
- Some of these cases were being hit by the LCID alerting code, and were logging as errors when they more likely should be warnings.
- Not much to test here, other than checking the translated client code to see if there's other cases that should be modified!
=> [NOREF] Lower some Error logs to Warnings

src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/components/PDFExport/index.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap
- Moved the download PDF link and icon outside of the scope of PDF generated content
Issue was caused by the `svg` without an `alt` text.  
For future reference in PDF generation, and images will need this attribute
=> [EASI-2721] - PDF export intake resolution

cypress/e2e/accessibility.cy.js, cypress/e2e/homepage.cy.js, src/components/LinkCard/index.stories.tsx, src/components/LinkCard/index.test.tsx, src/components/LinkCard/index.tsx, src/components/shared/Divider/index.scss, src/i18n/en-US/home.ts, src/i18n/en-US/systemProfile.ts, src/i18n/en-US/technicalAssistance.ts, src/queries/GetRequestsQuery.ts, src/queries/types/GetRequests.ts, src/views/Home/index.test.tsx, src/views/Home/index.tsx, src/views/MyRequests/Table/__snapshots__/index.test.tsx.snap, src/views/MyRequests/Table/index.test.tsx, src/views/MyRequests/Table/index.tsx, src/views/MyRequests/Table/tableMap.ts, src/views/SystemList/Table.tsx
[Figma](https://www.figma.com/file/iGatgTnlzTuqW9CQFYHDam/TRB-Intake-e2e?node-id=390%3A46545&t=TZLHJ3hHkjJ0dBpz-0)
This PR is a combination of `EASI-2583` and `EASI-1806`, as I think it made sense to handle these together.  Adding the system list table was really straightforward.
- Added TRB requests to GetRequestsQuery
- Added type handling and data mapping for new combined query
-  This is most likely temporary until the BE offloads this complexity
- Updated Basic user home page UI per Figma
- Adjusted `LinkCard` to better suit new UI
- Changed default table to 10 rows and only render table footer elements if more than 10
- Verify TRB requests are now rendered in basic user home page
- Figma matches
- Tests succeed
- Can't break
- It's best to pull the branch …
=> [EASI-2583, 1806] - Basic User TRB request and Systems List integration

src/types/flags.ts, src/utils/user.test.ts, src/utils/user.ts, src/views/FlagsWrapper/index.tsx, src/views/Home/index.test.tsx, src/views/Navigation/index.scss, src/views/TechnicalAssistance/AdminHome/index.tsx, src/views/TechnicalAssistance/Homepage.tsx, src/views/User/index.tsx
- Added LD flag for downgrading TRB Admin - `downgradeTrbAdmin`
- Added unit test
Additional minor change
- Added scss to ensure footer stays at bottom
Log in as TRB admin with user targeting set in LD.  Verify the experience is downgraded to regular TRB user
Visit `/user-diagnostics` to verify
=> [EASI-2504] - TRB downgrade flag

pkg/graph/resolvers/trb_request_status.go
- Changed calculation of TRB feedback status to properly reflect when a form has been re-submitted for review after edits were requested
Refer to https://github.com/CMSgov/easi-app/pull/1824 for detailed testing instructions
=> [NOREF] Updated calculation of TRB feedback status when edits are requested

src/components/AccessibilityRequestsTable/index.test.tsx, src/components/RequestRepository/index.tsx, src/components/TableFilter/__snapshots__/index.test.tsx.snap, src/components/TableFilter/index.tsx, src/hooks/useTableState.ts, src/views/App/index.tsx, src/views/MyRequests/Table/__snapshots__/index.test.tsx.snap, src/views/SystemList/__snapshots__/index.test.tsx.snap, src/views/TableStateWrapper/index.tsx, src/views/TechnicalAssistance/__snapshots__/index.test.tsx.snap
- Added context for storing/removing table state
- Context state is refreshed on absence of IT Gov routes `/governance-review-team`
- Added method to persist page size in local storage for more permanent persistence
- Added hook `useTableState` for setting and storing state for react-table
- Updated test
Persisted Context State:
Active table (open/closed)
Page index
Column Sort
Query/global filter
Persisted Local Storage State:
Page size
As is, local storage page size is set to a single string key, may want to develop this further if we find users want different page sizes for difference tables.  
This state management is only configured for IT Gov admin home table, but can be expanded in the future if needed
- Log in as IT Gov admin
- Change page index, sort, query, or active table
- …
=> [EASI-2754] - Table state persistence

src/hooks/useCacheQuery.ts
- Added hook for accurate loading state of cache-and-network fetchPolicy
https://oddball.slack.com/archives/C037ZNEQ7DH/p1679922179511309
Use this hook in the exact same way as you would `useQuery` for any fetchPolicy
Should accurately reflect loading state despite cache or network requests
=> [NOREF] - useCacheQuery hook for 'cache-and-network' fetchPolicy

src/components/EmailRecipientFields/__snapshots__/index.test.tsx.snap, src/i18n/en-US/technicalAssistance.ts
`Contracting Officer’s Representative (COR)` (contactRoles translation)role selection on TRB attendees was not mapped properly to enum `PersonRoles` and failing schema validation that was expecting `PersonRoles`
- Corrected contactRole enum mapping
- Updated snap
Verify you can set `Contracting Officer’s Representative (COR)` role on the requester or attenddee
=> [NOREF] - Corrected contactRole enum mapping

pkg/graph/generated/generated.go, pkg/graph/resolvers/trb_request.go, pkg/graph/resolvers/trb_request_test.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/storage/SQL/trb_request_collection_get_my.sql, pkg/storage/trb_request.go, src/queries/GetRequestsQuery.ts, src/queries/GetTrbRequestsQuery.ts, src/queries/types/GetRequests.ts, src/queries/types/GetTrbRequests.ts, src/views/MyRequests/Table/index.test.tsx, src/views/MyRequests/Table/tableMap.ts, src/views/TechnicalAssistance/Homepage.tsx, src/views/TechnicalAssistance/index.test.tsx
- Introduce query that only retrieves a users TRB requests
We only had a single query that was always fetching ALL trb requests. This meant that I was seeing other people's requests show up in my TRB tab - oops!
- Start the app
- Log in as `TEST`
- Make some TRB requests
- Make sure they show up in the TRB Tab table
- Log in as `ABCD`
- Make sure you don't see the other requests
- Make some more TRB requests
- Ensure you only see yours in the TRB Table
- Login as an admin
- Ensure you can see ALL trb requests on the admin home
- Always make comments, even if it's minor, or if you …
=> [NOREF] Make 'my' TRB request query

cypress/e2e/governanceReviewTeam.cy.js, src/i18n/en-US/articles/governanceReviewTeam.ts, src/queries/GetAdminNotesAndActionsQuery.ts, src/queries/UpdateSystemIntakeNoteQuery.ts, src/queries/types/GetAdminNotesAndActions.ts, src/queries/types/UpdateSystemIntakeNote.ts, src/types/graphql-global-types.ts, src/views/GovernanceReviewTeam/Notes/index.scss, src/views/GovernanceReviewTeam/Notes/index.tsx
- Modify GovernanceReviewTeam Notes component to allow for editing and removal of admin notes
- Add new GraphQL mutation for editing/removing note and edit GraphQL query for retrieving notes to add new edit fields
- Add Cypress test cases for new functionality
- This implementation varies slightly from the Figma mockups (https://www.figma.com/file/JE39JNLbCSha4fk1m9ayPP/IT-Governance-Updates?node-id=1647-102385) - in that the error messages are displayed in the notes component itself rather than the overarching GovernanceReviewTeam page. Zoe cleared and is ok with this change.
- …
=> [EASI-2567] Frontend for Editing System Intake Admin Notes

.golangci.yml, .pre-commit-config.yaml, pkg/models/base_struct.go, pkg/models/trb_admin_note.go, pkg/models/trb_advice_letter.go, pkg/models/trb_advice_letter_recommendation.go, pkg/models/trb_lead_option.go, pkg/models/trb_request.go, pkg/models/trb_request_attendee.go, pkg/models/trb_request_document.go, pkg/models/trb_request_feedback.go, pkg/models/trb_request_form.go, pkg/models/trb_request_funding_source.go, pkg/models/trb_request_lcid.go
- Updates [golangci-lint](https://github.com/golangci/golangci-lint) to its [latest version](https://github.com/golangci/golangci-lint/releases/tag/v1.52.2).
I've had lots of trouble on version 1.48, but 1.52.2 seems to run fine for me.
Pull, then checkout to `NOREF/update-golangci-lint-version` and run
```
pre-commit run golangci-lint --all-files
```
=> [NOREF] - update golangci version number

src/queries/GetAdminNotesAndActionsQuery.ts, src/queries/types/GetAdminNotesAndActions.ts, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Notes/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx
- Addressed the `TODO` on [1979](https://github.com/CMSgov/easi-app/pull/1979)
- Added a refetch on the parent query after issuing an LCID
- Issue an LCID
- Navigate to `Decision` side nav
- Verified that the decision is approved/ parent query data refreshed
=> [NOREF] - Added a refetch to parent intake query after lcid issued

cmd/devdata/main.go, cmd/devdata/trb_request.go
I was reading some [go docs on the context package](https://pkg.go.dev/context) and found this quote:
```Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx```
The TRB seeding code breaks this best practice, so I fixed that in this PR.
Run the seed script with `./scripts/dev db:seed` and confirm that it's seeding the data correctly.
=> [NOREF] Removed context from the TRB seederConfig struct to conform with Go recommendation

src/types/systemIntake.ts, src/views/SystemIntake/ContractDetails/FundingSources.tsx, src/views/SystemIntake/ContractDetails/useIntakeFundingSources.tsx, src/views/TechnicalAssistance/RequestForm/Basic.tsx
- Disabled next button if funding sources form is open
- Create TRB request and navigate to request form
- Click "Add funding source"
- Confirm next button is disabled
=> [EASI-2907] Disable next button if adding funding source

src/i18n/en-US/technicalAssistance.ts, src/views/TechnicalAssistance/AdminHome/InitialRequestForm.tsx, src/views/TechnicalAssistance/AdminHome/RequestHome.tsx, src/views/TechnicalAssistance/AdminHome/__snapshots__/RequestHome.test.tsx.snap, src/views/TechnicalAssistance/AdminHome/__snapshots__/index.test.tsx.snap
- Added alert for Admin Initial Request Form when state is `READy_TO_START` or `IN_PROGRESS`
- Create a new request without submitting IRF
- View request as admin (will need to paste/replace ID in URL)
- Verify Figma alerts
- Request Edits
- Repeat
=> [EASI-2944] - Action alert for admin IRF state = draft/ready

src/i18n/en-US/technicalAssistance.ts, src/views/TechnicalAssistance/RequestType.tsx, src/views/TechnicalAssistance/__snapshots__/index.test.tsx.snap
- Fixed missing translation for "other" type requests on the Admin Home
- Fixed changing an existing request type to "other" instead making a new request
- Make a TRB request of any type besides "other"
- After making the request, change the request type to other (ensure that it modifies the existing request instead of making a new one)
- Go to the TRB Admin home and ensure the request type renders properly
=> [EASI-2903] Fix TRB "Other" type issues

pkg/email/trb_request_consult_meeting.go, pkg/email/trb_request_consult_meeting_test.go
- Convert time objects (stored as UTC) to EST before sending emails
- Log in as `ABCD` with EASI and TRB Admin permissions
- Find Case #3 in the admin home
- Set a consult date
- Ensure the time looks correct in EST
=> [NOREF] Use EST when sending TRB Email times

.github/workflows/build_application_images.yml, Dockerfile.db_clean, Dockerfile.db_migrations, docker-compose.cypress_local.yml, docker-compose.override.yml, docker-compose.yml
- Update Flyway image from v7 to v9.
- These versions of the docker image allow for multi-arch support, which should address containers occasionally failing to start locally (and consuming lots of resources) on certain machines, namely M1/M2 Macs
- Update mailcatcher to use an updated image that has multi-arch support
This change was made in MINT here. We've noticed success with the change, and haven't had any issues!
https://github.com/CMSgov/mint-app/pull/555/files
- `scripts/dev up`, and ensure all services start locally
- Ensure db migrations run as expected
- Ensure that breaking changes are honored.
- [v7 to v8](https://github.com/flyway/flyway/issues/3247)
- Couldn't find anything here that would affect us!
- [v8 to v9](https://flywaydb.org/blog/version-9-is-coming-what-developers-n …
=> [NOREF] Update docker image tags for multi-arch support

src/components/NavigationBar/index.tsx, src/i18n/en-US/technicalAssistance.ts, src/queries/GetTrbRequestsQuery.ts, src/queries/types/GetTrbRequests.ts, src/views/TechnicalAssistance/AdminHome/AddNote.tsx, src/views/TechnicalAssistance/AdminHome/Consult.tsx, src/views/TechnicalAssistance/AdminHome/InitialRequestForm.tsx, src/views/TechnicalAssistance/AdminHome/Notes.test.tsx, src/views/TechnicalAssistance/AdminHome/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/AdminHome/components/InformationCard/index.tsx, src/views/TechnicalAssistance/AdminHome/components/NoteBox/index.test.tsx, src/views/TechnicalAssistance/AdminHome/components/NoteBox/index.tsx, src/views/TechnicalAssistance/AdminHome/components/NoteModal/index.tsx, src/views/TechnicalAssistance/AdminHome/components/Summary/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/AdminHome/components/Summary/index.tsx, src/views/TechnicalAssistance/AdminHome/components/TrbAdminWrapper/index.tsx, src/views/TechnicalAssistance/AdminHome/components/TrbAdminWrapper/useTrbAdminActionButtons.tsx, src/views/TechnicalAssistance/Homepage.tsx, src/views/TechnicalAssistance/RequestForm/Attendees.tsx, src/views/TechnicalAssistance/RequestForm/Basic.tsx, src/views/TechnicalAssistance/RequestForm/DocumentUpload.tsx, src/views/TechnicalAssistance/RequestForm/Documents.test.tsx, src/views/TechnicalAssistance/RequestForm/Feedback.tsx, src/views/TechnicalAssistance/RequestForm/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/RequestForm/index.tsx, src/views/TechnicalAssistance/TrbAdminTeamHome.tsx, src/views/TechnicalAssistance/TrbRequestFeedbackList.tsx, src/views/TechnicalAssistance/__snapshots__/TrbRequestFeedbackList.test.tsx.snap, src/views/TechnicalAssistance/index.test.tsx
Accidentally kept working past 4 and pushed changes into 5
All of these changes are a part of the "Should haves" of the UX Findings [DOC](https://docs.google.com/document/d/1HSmSXe6Wg7emBg59s3qFn7lINZnComsbpyVBlEJHb3Y/edit#heading=h.7kn6yyrth8d7)
- Empty/invisible buttons observed when using 508 testing tool
- Edits requested/feedback requester experience back button
- Assign lead button should not appear in admin action box if lead is assigned
- Admin actions for initial request form sub-page
- “When did you meet” sub-fields should be date pickers
- Closed request tab styling
- Text areas not honoring line breaks after saving
- View button should show outlined when Advice letter is complete
- Closed request statuses
- Empty state when adding new attendees from task list step 3
- Add doc …
=> [EASI-2983] UX should haves part 4 & 5

src/components/StepHeader/index.tsx, src/hooks/useEasiForm.ts, src/views/TechnicalAssistance/AdviceLetterForm/NextSteps.tsx, src/views/TechnicalAssistance/AdviceLetterForm/Summary.tsx, src/views/TechnicalAssistance/AdviceLetterForm/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/AdviceLetterForm/index.tsx, src/views/TechnicalAssistance/RequestForm/Pager.tsx, src/views/TechnicalAssistance/RequestForm/index.tsx
- Created `useEasiForm` hook that extends React Hook Form's `useForm` to add a `partialSubmit` function
- `partialSubmit` clears error messages and updates only valid changed fields before executing callback
- Implemented `partialSubmit` on Advice Letter Form's "Save and Exit" button
- Removed submit handler from "back" buttons
- Fixed bug in step validation (form was redirecting user when navigating to Summary step from further in form)
- Test advice letter form
- Confirm that valid fields are updated and errors do not show when clicking "back" or "save and exit" buttons
- Confirm that step navigation works as expected
- Check that all code is adequately covered by tests - if it isn't feel …
=> [EASI-2948] Advice letter form save and exit

src/views/TechnicalAssistance/AdviceLetterForm/Review.tsx, src/views/TechnicalAssistance/AdviceLetterForm/index.tsx
- Fixed issue where submitting the advice letter would not redirect correctly to success page
- Added the state setter to mark step as complete
=> [NOREF] - Fixed advice letter send redirect

cmd/test_email_templates/main.go, pkg/email/templates/trb_request_closed.gohtml, pkg/email/templates/trb_request_reopened.gohtml, pkg/email/trb_reopened_email_test.go, pkg/email/trb_request_closed_test.go
- Only render the "Reason for" reopening/closing a request when it's provided
- Fix tests
=> [NOREF] Only render reason for closing/reopening when it is provided

cmd/test_email_templates/main.go, pkg/email/templates/trb_advice_letter_submitted.gohtml, pkg/email/templates/trb_request_consult_meeting.gohtml, src/views/TechnicalAssistance/AdminHome/AddNote.tsx, src/views/TechnicalAssistance/AdminHome/components/NoteModal/index.tsx
[Note side panel via advice letter admin action does not allow for saving of note](https://docs.google.com/document/d/1HSmSXe6Wg7emBg59s3qFn7lINZnComsbpyVBlEJHb3Y/edit#heading=h.if3euto9zf3p)
[Advice letter returns to advice letter page when user clicks send](https://docs.google.com/document/d/1HSmSXe6Wg7emBg59s3qFn7lINZnComsbpyVBlEJHb3Y/edit#heading=h.eneayqfkstqf)
=> [NOREF] - Fixed notes disabled when dirty/empty note email

src/components/Modal/index.scss
Some css changes to adjust the modal height and overflow
Open an admin note with lots of text content
=> Fix admin notes modal scroll

src/views/SystemProfile/index.tsx
- This makes the Edit Team callout visible so that we can launch System Profile editing
- #2081 needs to be merged first
1. Connect to VPN
2. View system Team page (/systems/:ID/team)
3. Verify that "Edit Team" callout is visible below side navigation
4. Verify that callout button goes to Edit Team page
=> [NOREF] Remove comment block for system profile edit team

pkg/models/system_intake.go, pkg/storage/system_intake.go
- Add a condition to the JOIN statement that's made when selecting the `last_admin_note`-related fields on the System Intake
I opted not to wholly refactor this code to use it's own resolver, and instead just marked a `TODO` item to maybe do that at some point. Right now, these fields are selected by a JOIN statement and tacked onto the System Intake object, which is a bit messy and misleading, but this fix was quick enough to warrant just addressing as-is.
- Start the server with `scripts/dev up`
- Seed the DB with `scripts/dev db:seed`
- Sign in using local auth as a GRT Admin
- Look in the closed requests tab (there should be an intake with a note)
- Delete the note on that intake
- Ensure it no longer shows up in the home page (the row should be there, but no admin note)
- Do the same …
=> [EASI-3045] Fix deleted admin notes showing in IT Gov home page

src/stylesheets/print.scss
- Hide `<svg>` elements with `@media print` so that Prince doesn't try to print SVGs (which commonly have issues unless they're specifically handled for accessibility)
- Log in to the app as a GRT Admin
- Attempt to print a PDF of a System Intake form
- Ensure PDF print works (and SVGs are hidden in document table)
=> [EASI-3076] Hide all SVGs when printing Prince PDFs

cmd/devdata/main.go, pkg/alerts/lcid_expiration.go
- Add a check to skip sending notifications for intakes with `EUAUserID` set to nil, which causes issues when calling `fetchUserInfo()`.
1. Make sure `USE_OKTA_API` is set to true.
2. Comment out the block in `pkg/server/routes.go` setting `userSearchClient = local.NewCedarLdapClient(s.logger)` if `s.environment.Local() || s.environment.Test()`, so instead it'll use the Okta API.
3. Start the backend locally.
4. Run `scripts/dev db:seed`, which will add an intake with an expiring LCID and no `EUAUserID` set.
5. Comment out the check I added in `pkg/alerts/lcid_expiration.go`. This will cause the backend to restart.
6. Look at the logs from the LCID expiration checker running on startup with `docker-compose logs --no-log-prefix easi` - they should show an error from Okta, including the …
=> [EASI-3083] Have LCID expiration checker ignore intakes without an EUA User ID

src/components/TaskList/index.tsx, src/constants/externalUrls.ts, src/data/mock/govTaskList.ts, src/i18n/en-US/itGov.ts, src/i18n/en-US/taskList.ts, src/queries/GetGovernanceTaskListQuery.ts, src/queries/types/GetGovernanceTaskList.ts, src/types/graphql-global-types.ts, src/types/itGov.ts, src/views/GovernanceTaskList/GovTaskFeedbackFromInitialReview/index.test.tsx, src/views/GovernanceTaskList/GovTaskFeedbackFromInitialReview/index.tsx, src/views/GovernanceTaskList/GovTaskIntakeForm/index.tsx, src/views/GovernanceTaskList/index.tsx
[Task status states figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=14-23189&mode=design&t=mtbPb6ljoFYmU5Tz-0)
- New `GovTaskFeedbackFromInitialReview`
- Mock data type `GetGovernanceTaskListWithMockData` with properties ahead of what the backend provides
- Mock `governanceRequestFeedbackCompletedAt` for the completed date
- Jest tests of the status states
- Preview on local dev
- Check out the preview branch `NOREF/gov-task-mock-preview` which pulls in mock data for all status states within the parent task list component
- Turn on the `itGovV2Enabled` flag
- Seed data or create a new IT Gov request to get to the task list view
=> Task List Section Status Logic - Feedback from initial review(2) FE

.golangci.yml, pkg/appconfig/config.go, pkg/email/change_508_status.go
No associated ticket; just a thought I had while working on EASI-3058. 
This adds the [exhaustive](https://pkg.go.dev/github.com/nishanths/exhaustive#section-documentation) lint, which checks whether `switch` statements over "enum" constants cover all cases. I think this should be helpful for work on the IT Gov v2 workflow; the queries for status and mutations for handling actions will probably have a lot of `switch`'s over an intake's step, a task's state, or similar; see [this example in Steven's PR for EASI-3048](https://github.com/CMSgov/easi-app/pull/2096/files#diff-f999aa28296603eb0f6d4b0ce0bd05ea2d07103c0419f627373b069ab651e1e7R21). Given that, having a linter to check that all possible values of the step/state are checked seems useful.
The two other changes in this PR are bits of …
=> Add Go linter for exhaustiveness checking of pseudo-enums

.pre-commit-config.yaml
- Remove branch naming check in favor of using GitHub rules
https://github.com/CMSgov/mint-app/pull/634
- Try to create a branch in GitHub that doesn't match our expected naming patterns!
=> [NOREF] Remove branch name pattern pre-commit check

src/queries/SystemIntakeDocumentQueries.ts, src/queries/types/GetSystemIntakeDocumentUrls.ts, src/views/SystemIntake/Documents/DocumentsTable.tsx
- Instead of getting the presigned URL from the backend when the page with a <DocumentsTable> is loaded (which runs into issues if the user waits on the page long enough for the presigned URL to expire), have the "View" button query the backend for the URL when clicked, then immediately download the file from it.
- This is very similar to https://github.com/CMSgov/easi-app/pull/2095 (for EASI-3047), but with system intake documents instead of TRB request documents.
1. Create a system intake with an attached document.
2. Run `scripts/dev minio:clean` to mark the attachment as clean (virus-free), making it available to view/download.
3. In the admin view for that request, go to the "Uploaded documents" sub-page.
4. Click "View" for the document - you should be able to download the attached …
=> [EASI-3081] Generate URLs on demand for documents attached to system intakes

pkg/server/gqllogging.go
- Added small function to help identify if errors exist that should be ignored.
- `error: true` in the response qualifies the criteria for our Splunk alerting, so this change just makes that field be `false` in cases where we're only returning errors of an ignored type
- Open the GQL Playground, use the following auth headers `{ "Authorization":"Local {\"EUAID\":\"GRTB\",\"favorLocalAuth\":true, \"jobCodes\":[\"EASI_TRB_ADMIN_D\"]}"}`
- Make a query to fetch an intake
```graphql
query bazinga {
systemIntake(id: "78485ec1-035d-46f6-b524-68616f7f99e4") {
id
}
}
```
- Check the logs - make sure `error: false`!
- Try generating other errors to make sure `error: true` in those cases!
- It's best to pull the branch locally and test it, rather than just …
=> [EASI-3105] Ignore certain types of errors in GQL Response Middleware

src/components/TaskList/index.tsx, src/data/mock/govTaskList.ts, src/i18n/en-US/itGov.ts, src/i18n/en-US/taskList.ts, src/types/itGov.ts, src/types/taskList.ts, src/utils/fnErrorCapture.ts, src/utils/testing/helpers.ts, src/views/GovernanceTaskList/GovTaskBizCaseDraft/index.test.tsx, src/views/GovernanceTaskList/GovTaskBizCaseDraft/index.tsx, src/views/GovernanceTaskList/GovTaskFeedbackFromInitialReview/index.test.tsx, src/views/GovernanceTaskList/GovTaskFeedbackFromInitialReview/index.tsx, src/views/GovernanceTaskList/GovTaskIntakeForm/index.test.tsx, src/views/GovernanceTaskList/GovTaskIntakeForm/index.tsx, src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx
[Draft biz case status states in figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=16-23702&mode=design&t=udGDyzTdfuSQYz7z-0)
- New `GovTaskBizCaseDraft`
- [Done statuses are on hold](https://cmsgov.slack.com/archives/CNU2B59UH/p1689279895424799)
- Property param adjustments on `TaskListItem` for status info
- Util function decorator `fnCaptureError()` based on 
https://kentcdodds.com/blog/improve-test-error-messages-of-your-abstractions 
- Test helpers in `src/utils/testing/helpers.ts`
- Jest tests of the status states
- Preview on local dev
- Check out the preview branch `NOREF/gov-task-mock-preview` which pulls in mock data for all status states within the parent task list component
- Turn on the `itGovV2Enabled` flag
- Seed data or create …
=> Task List Section Status Logic - Prepare a draft business case(3) FE

pkg/graph/schema.resolvers.go, src/views/SystemIntake/Documents/DocumentsTable.tsx, src/views/TechnicalAssistance/RequestForm/DocumentsTable.tsx
No ticket, just a small fix I did following up on https://github.com/CMSgov/easi-app/pull/2109 (for EASI-3081) and https://github.com/CMSgov/easi-app/pull/2095 (for EASI-3047). Those bugfixes introduced a brief delay (~300ms) between clicking "View" in a list of documents and the file dialog opening, without any indicator that anything was happening during the daly. See the video in [this Slack post](https://cmsgov.slack.com/archives/CNU2B59UH/p1689709709125719) for a demonstration.
- Set the `disabled` prop on the `<Button>` component in the System Intake and TRB document tables when the query to fetch a document's URL is running, until it returns. This serves as a loading indicator, so users are aware that something's happening, instead of the app appearing unresponsive. See the video …
=> Disable view button when fetching document URLs as a loading indicator

cmd/test_email_templates/main.go, pkg/email/cedar_roles_changed.go, pkg/email/templates/cedar_roles_changed.gohtml, pkg/graph/schema.resolvers.go
This was an ask from last weeks CEDAR meeting. Again, this is not a permanent auditing solution, but something to hold out while CEDAR builds more robust auditing on their side.
- Adds the full name of the requester to the email sent when changing CEDAR System roles
- If you just want to validate the email content and templating, `scripts/dev up:backend` followed by `go run cmd/test_email_templates/main.go`, and navigating to http://localhost:1080 to check emails should work
- If you want to test the whole flow:
- Ensure you're on the VPN
- Modify [this line](https://github.com/CMSgov/easi-app/blob/b890784582e104ca354032a0e99561f549d1b9c3/pkg/server/routes.go#L107) to be `if !s.environment.Local() || s.environment.Test() {`, to begin using the REAL okta client (as the requester AND the …
=> [NOREF] Added requester name to CEDAR email when changing roles

pkg/oktaapi/client_wrapper.go, pkg/server/gqllogging.go
- Add better error handling in Okta API Client methods
- Ignore any context canceled errors that get forwarded up to the GQL Logging middleware to prevent them from automatically alerting
- You can force a `return nil, context.Canceled` in this function to test out the logging behavior locally. https://github.com/CMSgov/easi-app/blob/f805ded627e337d8db1094e66665bc38dd63db7b/pkg/local/cedar_ldap.go#L343-L365
- Seeding the DB and trying to fetch a TRB Request as an admin is a surefire way to trigger this function call, but lots of code calls this.
- Always make comments, even if it's …
=> [NOREF] Improve handling of context canceled errors

pkg/apperrors/errors.go, pkg/graph/resolvers/it_gov_task_statuses.go, pkg/graph/resolvers/it_gov_task_statuses_test.go, pkg/graph/schema.resolvers.go
- Introduce Status Calculations for the Intake Form Status
- Note, the function could be simplified, but I favored clarity instead of brevity. Please feel free to note if you disagree with the approach
- Introduce Unit tests for possible permutations of state and status
1. Run all the unit tests
If you desire to test this manually, you can use the postman collection to do the following
1. Create a system Intake
2. Retrieve a system intake
3. Use SQL to update the system intakes step and intake form state to verify that the correct status is displayed.
a. Note, currently the intake form state is not updated by current actions. That functionality will be added  in a future ticket. 
- Check that …
=> EASI-2957: Intake Form Status Implementation

src/views/GovernanceReviewTeam/Actions/ActionForm.tsx, src/views/GovernanceReviewTeam/Actions/EmailRecipientsFields.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx
On the IT gov admin action form, clicking the "show more recipients" toggle button is causing the `RequestOverview` component to rerender ([see video in slack thread](https://cmsgov.slack.com/archives/C0305U1014Y/p1690472416983899)).
I wasn't able to reproduce this locally, in dev, or in impl - it only happens in prod. I'm assuming this was introduced by #2121, so I refactored and/or reverted some changes that were made to the routes and the `EmailRecipientsFields` component.
- Refactored routes to undo changes in `RequestOverview` (src/views/GovernanceReviewTeam/RequestOverview.tsx)
- Reverted changes to `EmailRecipientsFields` component
Test IT Gov admin action form to ensure everything is working correctly.
Since this bug only happens in prod, we can't locally test whether or not these …
=> [NOREF] IT Gov admin actions bug fix

pkg/graph/resolvers/it_gov_task_statuses.go, pkg/graph/resolvers/it_gov_task_statuses_test.go, pkg/graph/schema.resolvers.go
- Introduce Status Calculations for the Intake Form Feedback Status
- Note figma shows a date feedback was submitted, but it was determined that will be a future iteration. As such, the status is solely implemented based on the state of the intake form.
- Introduce Unit tests for possible permutations of state and status
If you desire to test this manually, you can use the postman collection to do the following
1. Create a system Intake
2. Retrieve a system intake
3. Use SQL to update the system intakes step and intake form state to verify that the correct status is displayed.
a. Note, currently the intake form state is not updated by current actions. That functionality will be added  in a future ticket. 
- It's best to pull the branch locally and test it, rather than just looking at the …
=> [Easi 2958] - feedback from initial review status calculation

pkg/graph/resolvers/it_gov_task_statuses.go, pkg/graph/resolvers/it_gov_task_statuses_test.go, pkg/graph/schema.resolvers.go
- Introduce Status Calculations for the Decision and Next Steps Status
- Technically, this (and the other calculations) doesn't verify that the intake.Step is a valid enum. We could add that additional verification, but I don't think that level of granularity is needed at this level
- Introduce Unit tests for possible permutations of state and status
If you desire to test this manually, you can use the postman collection to do the following
1. Create a system Intake
2. Retrieve a system intake
3. Use SQL to update the system intakes step, GRB Date, and decision state to verify that the correct status is displayed.
a. Note, state is not updated by current actions. That functionality will be added  in a future ticket. 
- It's best to pull the branch locally and test it, rather than just …
=> [EASI-2886] - Decision and Next Steps status implementation

cmd/devdata/trb_request.go, pkg/graph/resolvers/trb_advice_letter_recommendation_test.go, pkg/graph/resolvers/trb_request.go, pkg/graph/resolvers/trb_request_attendee_test.go, pkg/graph/resolvers/trb_request_document_test.go, pkg/graph/resolvers/trb_request_feedback_test.go, pkg/graph/resolvers/trb_request_form_funding_sources_test.go, pkg/graph/resolvers/trb_request_form_test.go, pkg/graph/resolvers/trb_request_status_test.go, pkg/graph/resolvers/trb_request_system_intake_test.go, pkg/graph/resolvers/trb_request_test.go, pkg/graph/schema.resolvers.go
- Remove calls to `fetchUserInfo` when creating TRB Requests
- Remove extra call to fetch principal from context, instead using existing principal object in resolver
- `scripts/dev up` to start the server
- Log in to the UI
- Create a TRB request
- Ensure that requester information (and default attendee) is correct - check in the DB directly if you want!
=> [NOREF] Remove fetchUserInfo from CreateTRBRequest resolver

src/queries/GetTrbRequestDocumentUrlsQuery.ts, src/queries/SystemIntakeDocumentQueries.ts, src/queries/types/GetSystemIntakeDocumentUrls.ts, src/queries/types/GetTrbRequestDocumentUrls.ts, src/utils/downloadFile.ts, src/views/SystemIntake/Documents/DocumentsTable.tsx, src/views/TechnicalAssistance/RequestForm/DocumentsTable.tsx
- Update GQL queries to fetch file names alongside download URLs
- Update `downloadFileFromURLOnly` to `downloadFileFromURL`, which now takes a `filename`
- Update download code to sue existing `downloadBlob` function, which allows a filename to be passed
- Start a request (TRB, or IT Gov)
- Upload a document
- `scripts/dev minio:clean` to mark it as virus scanned
- Refresh the page that shows the documents table
- Click "view"
- Ensure the downloaded file matches the name as it was uploaded
- Always make comments, even if it's minor, or if you don't understand why …
=> [EASI-3177] Fix downloaded file names in TRB and IT Gov

.github/workflows/build_and_test.yml, .github/workflows/build_frontend_assets.yml, .github/workflows/deploy_pipeline.yml, .github/workflows/manual_deploy.yml, .github/workflows/run_tests.yml, scripts/build_static.sh
- Introduce test APP_ENV case for build_static.sh script, which will build the frontend using test variables
- Build_Test_Frontend_Assets steps will then use the build_static.sh script with test env to build frontend assets and store them as artifacts to be pulled later in E2E testing
Github Actions pipeline change
=> EASI-3160: Use pre-built frontend assets in E2E test step

pkg/server/gqllogging.go, pkg/server/routes.go
NOREF PR so that when the `hasRole` directive in our GraphQL schema returns false, it doesn't alert us, similar to how https://github.com/CMSgov/easi-app/pull/2112 addressed issues when a user tried to view a system intake that they're not authorized to view (see EASI-3105). I noticed this about a week ago; [an alert triggered in Prod](https://cmsgov.slack.com/archives/C0486DX6884/p1692731893705289) because a user didn't have the right job code, and thus the `hasRole` check failed when querying TRB requests.
**I'm not 100% positive that we want to stop alerting on these checks.** The alerts might still be valuable if a user has issues with their job code and tries to view something that they should be allowed to view; we'd get an alert instead of having to wait for a user to report an …
=> Remove alerts when hasRole returns false

pkg/models/html.go
- Add code to GQL Marshalling of HTML scalar type that uses `html.UnescapeString()` to ensure that we don't get unexpected characters being rendered in the frontend.
- Create and submit a system intake (or seed the DB)
- Create an admin note that has special characters in it (`'`, `<`, or any other [HTML special characters](https://www.html.am/reference/html-special-characters.cfm))
- Ensure the note renders as it was entered
=> [EASI-3119] Add hotfix for marshalling HTML scalar types

pkg/handlers/system_intakes.go
- Manually unescape `LastAdminNoteContent` when fetching system intakes via REST API
- Add an admin note containing HTML special characters
- Close the request
- Ensure the `Last Admin Note` renders properly
=> [EASI-3119] Fixed last admin notes having escaped characters in REST endpoints

.github/workflows/manual_deploy.yml
- because of the conditional "if" of skip tests, it would cause the "Build_Test_Frontend_Assets" step to be completely skipped; however this could cause "Run_Tests" to also be skipped, which could cause cascading dependencies to be skipped INCLUDING Deploy steps. Removing the conditional to ensure these dependencies are met.
=> remove conditional "if" for building test_frontend_assets

.github/dependabot.yml
- Use dependabot groups ([docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)) to reduce the number of PRs that we need to dig through for each package manager.
- Groups minor/patch PRs in one group and major upgrades in another
- Ensure that the dependabot config matches what would be expected based on the linked documentation
=> [NOREF] Use dependabot groups

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
- Add `lcidIssuedAt` schema field
- Returns a mock date, remainder of the implementation to be done in EASI-3319
- Create a system intake
- Query the lcidIssuedAt field
- Ensure a date returns (it's mocked, it'll always be the same thing!)
=> [NOREF] Add `lcidIssuedAt` schema field

package.json, src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/components/PDFExport/index.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap, yarn.lock
Generate pdfs on the client with react-to-print
- The old generate endpoint `{VITE_API_ADDRESS}/pdf/generate` is no longer used
- `js-base64` is no longer used
- Print page level styles such as timestamp, title, url, pagination, are all defaults of window.print()
Download a pdf from a view such as
`http://localhost:3000/governance-review-team/{uuid}/intake-request`
=> Replace PrinceXML with Client-side PDF rendering FE

EASI.postman_collection.json
Currently, the Postman collection is only really setup for local dev. However, it's useful to be able to quickly test the backend in LLEs. This PR modifies the Postman Env Vars slightly so they can be overridden to target `dev`, `impl`, or `prod` environments.
- Makes the auth header an env var
- Isolates the base URL so it can be replaced with the live URLs.
1. Import the new collection
2. Click the EASI collection and go to the Variables tab.
3. Replace `EUAID` in the "Current Value" column (do this for all overrides) with your EUA.
4. Replace `host` with https://dev.easi.cms.gov (don't add the trailing slash)
5. Log into `dev` on the real site, then copy the Auth header on GQL queries that starts with "Bearer"
6. Paste the auth header value into `authHeader`.
7. Run some queries …
=> [NOREF] Update Postman Env Vars

src/validations/actionSchema.ts, src/views/GovernanceReviewTeam/Actions/Resolutions/IssueLcid.tsx, src/views/GovernanceReviewTeam/Actions/components/ActionForm.tsx
- Fixes two bugs with Issue/Confirm LCID form:
- Issue LCID mutation
- LCID value in mutation input was set to empty string even when "use existing LCID" was selected, so new LCID was always generated
- Confirm LCID form
- If more than one intake used the same LCID, fields were always showing values from first intake
- Refactored `onSubmit` function in `IssueLcid` component for clarity
- Added comments
Log in with `itGovV2Enabled` flag enabled, and go to /governance-review-team/:systemId/actions.
1. Test Issue LCID mutation bug fix
- Select "Issue a decision or close this request"
- Select "Issue a Life Cycle ID"
- Select "Use an existing Life Cycle ID"
- Select LCID from dropdown
- Update other LCID fields (important for testing next bug)
- Ensure LCID in gql mutation response matches …
=> [NOREF] Issue LCID bug fix

go.mod, pkg/email/request_edits_test.go, pkg/email/system_intake_close_test.go, pkg/email/system_intake_reopen_test.go
- Remove /x/net package. We only used it for tests for the `context` it provided, and we can just use the base `context` package instead.
- Should make https://github.com/CMSgov/easi-app/pull/2228 no longer needed once merged
Ensure all unit tests pass in CI! That should be all that's needed
=> [NOREF] remove x net

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, src/data/systemIntake.ts, src/queries/types/GetSystemIntake.ts, src/queries/types/GetSystemIntakesTable.ts, src/queries/types/SystemIntake.ts
- Makes createdAt nullable in the GQL schema. This is because data in IMPL and PROD has nullable CreatedAt's, so rather than trying to fix that, we're going to update the schema to reflect the DB restrictions (which make the column nullable)
The only reason this showed up now is we recently migrated from using REST endpoints on the admin home page to using GQL queries.
- Start the app locally, make sure nothing breaks
- Seed the DB, use `psql` or a postgres tool to null out an intakes `createdAt` and make sure the app still works as expected.
- Always make comments, even if it's …
=> [NOREF] Make intake created nullable

.github/workflows/pr_label_checks.yml
- Added job that fails a check if `do not merge` is present in the labels
This is (hopefully) useful for cases where approvals exist on a PR, but there's some external reason we don't yet want to merge the changes
Try adding the `do not merge` label to this PR, see that it fails, try removing it, see that it passes!
=> [NOREF] Add check to fail PR on presence of 'do not merge' label

src/components/RequestRepository/index.tsx
The system intakes table on the homepage currently shows "results loading" until both the open and closed queries have completed. This causes the open tab to show "results loading" after the open intake results are already being displayed (there is a significant delay in prod).
This PR updates `RequestRepository` to use the loading state of only the active tab.
Make sure the admin home system intakes table only shows "results loading" until the active tab results are displayed.
=> [NOREF] System intakes table loading fix

src/views/GovernanceReviewTeam/Actions/RequestEdits.tsx, src/views/GovernanceReviewTeam/Actions/index.test.tsx, src/views/GovernanceReviewTeam/Actions/index.tsx
- The admin actions v2 request edits form defaults to the current form step of the intake.
- If the intake is not in a form step, it shows the "Select" option.
I just noticed while manually testing admin actions that the end user doesn't know the current form step when looking at the request edits page, so thought it would be nice for us to default to the current step. It might prevent a user from thinking a business case is in draft when it's really in final or vice versa and unintentionally progressing the intake for example.
I added some tests to the current Req Edits form file that can be run with:
```sh
scripts/dev test:js
```
The changes can also be tested by creating an intake and setting it to a certain form step and then requesting edits through the UI.
- It's best to pull the …
=> [NOREF] - Default to current form step on request edits action page

src/views/TechnicalAssistance/AdminHome/AddNote/index.test.tsx, src/views/TechnicalAssistance/AdminHome/AddNote/index.tsx, src/views/TechnicalAssistance/AdminHome/__snapshots__/Notes.test.tsx.snap, src/views/TechnicalAssistance/AdminHome/components/Note/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/AdminHome/components/Note/index.tsx
Similar to the other recent RTE prs. This time for trb admin notes.
Unit tests pass but a new warning
`Warning: Can't perform a React state update on an unmounted component.`
shows up for
`src/views/TechnicalAssistance/AdminHome/AddNote/index.test.tsx > Trb Admin Notes: Add Note > shows an error notice when submission fails`
This happened when the rich text type test interaction was updated. It may have conflicts with the wrapping act(). Not sure why that would be or why the wrap needed to be in the first place.
=> Enable Rich text (FE) – TRB Admin notes

src/views/GovernanceReviewTeam/Actions/RequestEdits.tsx, src/views/GovernanceReviewTeam/Actions/index.test.tsx
In the edits requested action form, the default value for "Which form needs edits" was being set in the field component but not in the actual field values object. This resulted in a field error if you tried submitting the form without touching that field, because the 'intakeFormStep' value was still undefined.
**Changes:**
- Converted the `currentStep` prop from the `SystemIntakeStep` type to `SystemIntakeFormStep`
- Moved setting  the default value from the field component to the form's `defaultValues` prop
- Complete Request Edits form and make sure existing step is set as default
- Default value should be set for initial request form, draft business case, and final business case steps. If request is in GRB or GRT meeting steps, field should default to `- Select -` …
=> [NOREF] Fix edits requested default step bug

cmd/migrate_intakes/main.go
- This PR introduces a script that, for each System Intake, runs `SetV2FieldsBasedOnV1Status`
This should effectively place every Intake in the correct state to migrate to V2, now that https://github.com/CMSgov/easi-app/pull/2270 is in `main` and deployed
- `scripts/dev db:seed` -- This will seed the DB with a _lot_ of V1-specific Intakes
- `go run cmd/migrate_intakes/main.go migrate`
- Check the DB / App UI to see if the V1 intakes look correct in V2
- Note: This script assumes V1 fields are to be trusted across the board, meaning any V2 intakes that do NOT have V1 fields set will improperly get reset back to the initial task list. This is acceptable, as all intakes in prod should have proper v1 statuses.
- It's best to pull the branch locally and test it, rather than …
=> [EASI-2887] Create V1 to V2 migration script

src/data/mock/govTaskList.ts, src/data/mock/systemIntake.ts, src/queries/GetGovernanceTaskListQuery.ts, src/queries/types/GetGovernanceTaskList.ts, src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx
- Fixed "Remove your request" link in sidebar of v2 task list
- Link triggers modal and archives request (same as v1)
1. Create new intake request
2. Go to task list
3. Click "Remove your request" link in sidebar
4. Click "Remove request" button in modal
5. Confirm that request shows up in "closed requests" tab of system intakes table
=> [EASI-3656] Remove intake request functionality

src/validations/actionSchema.ts, src/views/GovernanceReviewTeam/Actions/ProgressToNewStep.tsx, src/views/GovernanceReviewTeam/Actions/index.test.tsx
From UX Doc: [Meeting dates in new step action should not be required](https://docs.google.com/document/d/1oZBAphS7VgoFIjcTXMSyXfb6LbAQMylTqPxMxlzHnyU/edit#heading=h.66tz3dgfhgrf)
- Updated Progress to New Step action field validation to make GRB/GRT meeting date fields optional
- Verify that GRB and GRT meeting date fields are optional in Progress to a New Step v2 action form (/governance-review-team/:systemIntakeId/actions/new-step)
=> [EASI-3716] Optional meeting dates

src/views/GovernanceReviewTeam/Actions/RequestEdits.tsx
From UX QA doc
- [Decision warning modal not appearing](https://docs.google.com/document/d/1oZBAphS7VgoFIjcTXMSyXfb6LbAQMylTqPxMxlzHnyU/edit#heading=h.9td6b9f0towf)
- Modal was not showing up because forms were using cached `taskStatuses` to determine if edits had been requested
- Updated Edits Requested component to refetch `GetGovernanceTaskList` after mutation
- Request edits to a form
- Test decision action forms to confirm modal appears after clicking submit button
- Not approved by GRB 
- Issue a Life Cycle ID
- Not an IT Governance request
**Note:** submitting the decision action forms removes the "edits requested" status. To test on all three forms without having to go through additional steps, don't submit the form after confirming the modal appears.
- It's best to pull the …
=> [EASI-3716] Decision actions edits requested modal

src/views/GovernanceReviewTeam/Actions/ManageLcid/ExpireLcid.tsx, src/views/GovernanceReviewTeam/Actions/ManageLcid/RetireLcid.tsx, src/views/GovernanceReviewTeam/Actions/ManageLcid/UpdateLcid.tsx
Manage LCID action forms rich text fields were returning `wysiwyg` as the field value. See [Slack thread](https://cmsgov.slack.com/archives/CNU2B59UH/p1702316265976989) for details.
- Updated `RichTextEditor` component `field` props in Manage LCID action forms
- Issue LCID to intake request
- Complete Update LCID form with all fields filled
- Ensure correct new field values are showing on Lifecycle ID admin page
=> [EASI-3176] Fix Manage LCID action form rich text fields

pkg/graph/resolvers/system_intake_actions.go, pkg/graph/resolvers/system_intake_actions_test.go
- Stores the `reason` input from the "Not an IT Gov Request" decision action under `RejectionReason` on intakes.
Create an intake, close it as "Not an IT Gov Request", retrieve the intake using GQL to verify the reason is retrieved as `rejectionReason`.
=> [NOREF] Store reason for rejection from Not IT Gov decision

EASI.postman_collection.json, pkg/models/system_intake.go, pkg/storage/system_intake.go
- This changes filters out `WITHDRAWN` status intakes from the table views of requesters and admins.
- Postman collection updated.
- After launch, we should run a migration to delete the intakes with this status or timestamp, modify the delete methods to truly delete the intakes, and remove these filters from the queries.
Use Postman to create/delete (archive) requests. Postman request for the admin home page table view of requests also added.
=> [EASI-3715] Filter out archived intakes from fetch queries

src/views/GovernanceReviewTeam/Actions/ManageLcid/ExpireLcid.tsx, src/views/GovernanceReviewTeam/Actions/ManageLcid/RetireLcid.tsx, src/views/GovernanceReviewTeam/Actions/ManageLcid/UpdateLcid.tsx, src/views/GovernanceReviewTeam/Actions/Resolutions/CloseRequest.tsx, src/views/GovernanceReviewTeam/Actions/Resolutions/ReopenRequest.tsx, src/views/GovernanceReviewTeam/Actions/components/ActionForm.tsx
"Different email section alert/banner for certain action UIs" from [the ux qa doc](https://docs.google.com/document/d/1oZBAphS7VgoFIjcTXMSyXfb6LbAQMylTqPxMxlzHnyU/edit)
- ActionForm `notificationAlertWarn` property set on the actions forms for
- expire
- retire
- update LCID
- close
- and re-open
Go through the request actions and make sure that only the forms from the above list have the Notification email section's alert box as the warning type.
=> EASI-3716 Different email section alert for certain action UIs

.github/dependabot.yml
- This PR aims to disable major NPM upgrades being suggested from dependabot, as it was often suggesting PRs with 40+ package upgrades, which is unreasonable for a single PR.
https://github.com/CMSgov/easi-app/pull/2324 is an example of one of those PRs!
- Just ensure that this is still a valid dependabot file!
=> [NOREF] Disable NPM major upgrades from dependabot

src/components/AccessibilityDocumentsList/index.tsx, src/components/AccessibilityRequestsTable/index.tsx, src/components/RequestRepository/index.tsx, src/views/MyRequests/Table/index.tsx, src/views/SystemIntake/Documents/DocumentsTable.tsx, src/views/SystemList/Table.tsx, src/views/TechnicalAssistance/Homepage.tsx, src/views/TechnicalAssistance/RequestForm/DocumentsTable.tsx, src/views/TechnicalAssistance/TrbAdminTeamHome.tsx
useTable autoResetPage set to true (fix method copied from mint)
Follow reproduction steps in the ticket to make sure that what is described is no longer the case
1. Go to Systems tab in IMPL
2. Navigate to page 2 of the results
3. Search for "ACO"
4. See that pagination resets to page 1, where the ACO result shows up
=> EASI-3438 Various search fixes (EASi)

cypress/e2e/governanceReviewTeam.cy.js
Skipping the failing e2e test for now to unblock PRs and deploy pipeline. Will work on a fix this morning.
=> [EASI-3718] Skip update retirement date test

cypress/e2e/governanceReviewTeam.cy.js
- Fixes failing e2e test for updating an LCID retirement date
- "Manage a Life Cycle ID" action was selected before page was done loading, so options were resetting and Continue button was disabled
- Removed unnecessary step to navigate to actions page - test is already on page after initial form is submitted
=> [EASI-3718] Update retirement date test fix

cypress/e2e/governanceReviewTeam.cy.js
Cypress test for updating an LCID retirement date is still flaky ([failing here](https://github.com/CMSgov/easi-app/actions/runs/7453919361/job/20280737556?pr=2369)), so commenting out that part of the test until we have a fix.
The `Actions` component is rerendering after "Manage a Life Cycle ID" is selected for the second time. This clears the option and disables the Continue button, which causes the test to fail.
=> [NOREF] Comment out flaky e2e test code

.pre-commit-config.yaml, .spelling, Dockerfile.backend_k8s, Dockerfile.client_k8s, deploy/base/db-migrate.yaml, deploy/base/db.yaml, deploy/base/easi-client.yaml, deploy/base/easi.yaml, deploy/base/email.yaml, deploy/base/kustomization.yaml, deploy/base/namespace.yaml, docs/k8s_dev_script_usage.md, scripts/k8s_dev.sh
This pull request includes updates to the Kubernetes manifests and development script. The changes include:
1. kustomize base manifests for:
- db-migrate job
- postgres db
- easi-client (frontend)
- easi (backend)
- mailcatcher
- **MINIO IS CURRENTLY NOT FUNCTIONAL** still working on implementation
2. 2 new dockerfiles for easi and easi-client to help with k8s local development
3. first iteration of the k8s_dev.sh script to ease deploying EASi to your local k8s cluster
1. see `k8s_dev_script_usage.md` in the docs folder for further instructions - reach out @Jdwoodson for any assistance needed
1. **Rancher Desktop** is recommended at this time for ease of understanding Kubernetes Ingress!
1. Functionality that requires MINIO will NOT work as I will still need to work thru implementation. …
=> EASI-3483: k8s manifests for local development

src/i18n/en-US/intake.ts, src/utils/systemIntake.ts, src/views/MyRequests/Table/__snapshots__/index.test.tsx.snap, src/views/MyRequests/Table/index.tsx, src/views/MyRequests/Table/tableMap.ts
- Only reference it gov v2 statuses in the requester table, remove flag switches and other references to old v1 statuses
- `GetRequests.status` is left in since it is a generic property that still has references to the Accessibility request type
- Removed the Governance Request status case switch from tableMap, since it looked redundant with what the Table Column Cell definition has. Searching seems to work fine. @patrickseguraoddball Since this might have been your original code can you check that this edit is ok?
Take a look at the requester home page table after seeding data
- Make sure the status columns are ok
- Make sure table features like searching and sorting are ok
Unit test snapshots are updated
=> EASI-3783 v1 references on Requester home page

src/components/HelpBreadcrumb/__snapshots__/index.test.tsx.snap, src/components/HelpBreadcrumb/index.test.tsx, src/components/HelpBreadcrumb/index.tsx, src/i18n/en-US/help.ts, src/views/Help/All/__snapshots__/index.test.tsx.snap, src/views/Help/All/index.tsx, src/views/Help/ITGovernance/NewSystem/index.tsx, src/views/Help/ITGovernance/PrepareForGRB/index.tsx, src/views/Help/ITGovernance/PrepareForGRT/index.tsx, src/views/Help/ITGovernance/SampleBusinessCase/index.tsx, src/views/Help/ITGovernance/__snapshots__/index.test.tsx.snap, src/views/Help/ITGovernance/index.tsx, src/views/Help/SendFeedback/index.tsx, src/views/Help/TechnicalReviewBoard/PrepareTrbConsultMeeting.tsx, src/views/Help/TechnicalReviewBoard/StepsInProcess.tsx, src/views/Help/TechnicalReviewBoard/index.tsx
- Updated help center back button text to "Back to help center"
- Back button returns to main help center instead of previous page
- Go to /help/all-articles
- Check back button text
- Button click should take you to /help
=> [EASI-2101] Help center back button

src/data/businessCase.ts, src/views/BusinessCase/index.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap
- Prevents queries from being made to fetch the Governance Task List when we don't have the ID of the intake to query by, yet.
This helps prevent an accidental query with `"id":""` when the page is loading the business case.
https://cmsgov.slack.com/archives/C0486DX6884/p1706300155882699
- Seed the DB
- Visit the requester task list for `Edits requested on draft biz case` (Signed in as `USR1`)
- Ensure that when you edit the form, the network tab only shows valid requests with ID's (pictures below of valid and not valid)
- Always make comments, even if it's minor, or if you don't …
=> [NOREF] Ignore query for gov task list if there's no system intake ID

src/data/businessCase.ts, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.test.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionB.test.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/BusinessCaseReview/index.test.tsx
- Move definition of default `systemIntakeId` to individual tests, rather than in `src/data`, which is actually used in the app (not just in test)
Same testing instructions as https://github.com/CMSgov/easi-app/pull/2396
- Seed the DB
- Visit the requester task list for `Edits requested on draft biz case` (Signed in as `USR1`)
- Ensure that when you edit the form, the network tab only shows valid requests with ID's (pictures below of valid and not valid)
=> [NOREF] Fix business case initial ID

src/views/TechnicalAssistance/RequestType.tsx
- This fixes a bug with case sensitive paths messing up the TRB Request Type component
- Start the app
- Navigate to http://localhost:3000/TRB/start (notice the capitalized `TRB`. Make sure Chrome/Browser didn't replace it with `trb` from your history! Use Incognito mode to help prevent that)
- Ensure that when you try and set the request type, you're directed to the flow for creating a new TRB request
- Ensure that when you click "back" at the top of the page, you're directed back to the homepage, and don't receive an error
- Always make comments, even if it's minor, or if you don't …
=> [NOREF] Fix location matching for TRB request type component

EASI.postman_collection.json, cmd/devdata/main.go, cmd/devdata/system_intake.go, migrations/V171__Add_Contract_Name.sql, pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake_relation.go, pkg/graph/resolvers/system_intake_relation_test.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/system_intake.go, pkg/storage/system_intake.go, pkg/storage/system_intake_relation.go
- Introduces a new `ContractName` field that intends to capture the free-text input that users will select when linking a System Intake to an existing Contract or Service
This PR does _not_ fully implement any of the stubbed resolvers introduced in https://github.com/CMSgov/easi-app/pull/2385, but just creates the necessary DB migrations, model updates, and resolver code that sets the new `ContractName` field. What still needs to be implemented in the `setSystemIntakeRelationExistingService()` resolver is the remainder of the resolver code that should set contract numbers and also clear existing relationships between CEDAR Systems and System Intakes, if set.
You can use `scripts/dev db:seed` to see the database and use the postman collection to validate that the field is `null` for most …
=> [EASI-3755] [EASI-3872] Add new "ContractName" field and partially implement resolver

src/views/TechnicalAssistance/TrbAdminTeamHome.tsx
Trb request tables will initially sort by a consult meeting date.
Requests without a consult date will be at the end of a descending list.
Check that general table features such as the global filter still work
=> EASI-3558 TRB - Change Default Sort Order

.air.conf, .airDebug.conf, .airDebugWait.conf
We use AIR for hot reloading our BE dev server. This updates the config to rebuild the app not just for GO file changes, but also if the SQL file changes. This makes it so you don't have to rebuild the container manually when you update a SQL script
SEE mint PR [here](https://github.com/CMSgov/mint-app/pull/938)
1. Bring the app up `scripts/dev up:backend:debug`
2. Modify a SQL file
3. Inspect the backend docker container to make sure that the server re-builds.
=> NOREF: Watch SQL files in backend DEV Server

pkg/email/system_intake_change_lcid_retirement_date_test.go, pkg/email/system_intake_expire_lcid_test.go
- This PR just cleans up some of the tests related to changes in [2411](https://github.com/CMSgov/easi-app/pull/2411).
```sh
go test ./pkg/email -run TestEmailTestSuite/TestIntakeChangeLCIDRetirementDateNotification
```
and 
```sh
go test ./pkg/email -run TestEmailTestSuite/TestIntakeExpireLCIDNotification
```
=> [NOREF] Clean up change retire date and expire LCID email tests

EASI.postman_collection.json, pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake_relation.go, pkg/graph/resolvers/system_intake_relation_test.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
- Adds a new mutation to unlink / clear all System Intake relation data
- `scripts/dev db:seed` should create a System Intake that has a contract name & contract numbers
- Calling this mutation with that Intake's ID should result in that data (contract name & contract numbers) being cleared
=> [EASI-3755 / EASI-3935] Add mutation to unlink system intake relation data

src/validations/businessCaseSchema.ts
Patch for an uncaught error found here https://github.com/CMSgov/easi-app/pull/2436#pullrequestreview-1885332658
If you're looking in detail, it seems that only alta needs the nullable. the other forms and schemas with `hasUserInterface` don't behave quite the same and don't have that dev warn.
=> [NOREF] Fix radio text schema with nullable() as suggested by lib warn

src/types/flags.ts, src/views/FlagsWrapper/index.tsx
- Adds `trbLinkRequestsRequester` flag to match new flag in LaunchDarkly
This flag isn't used anywhere, and is just being made in preparation for upcoming TRB Request linking work on the frontend
- Make sure that the flag name in the code matches the key in LaunchDarkly
- Ensure EASi is configured locally to point to LaunchDarkly
- Sign in with your EUA account
- Navigate to http://localhost:3000/user-diagnostics, ensure the flag matches what's in LD
- Modify the targeting in the `local` LD environment to target your user with a different value for the flag
- Ensure the flag value has been updated on the /user-diagnostics page
- Check that all code is adequately covered by …
=> [EASI-3878] Add trbLinkRequestsRequester flag

cmd/devdata/main.go, pkg/cedar/core/role.go, pkg/cedar/core/system_detail.go, pkg/cedar/core/system_summary.go, pkg/cedar/core/system_summary_test.go, pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/local/cedar_core.go
- Adds the ability to return `businessOwnerRoles` on a `CedarSystem`.
- Note: Asking for business owner roles on `cedarSystems` causes CEDAR to time out.
- Adds mock data for easier local development.
1. Seed/start the App
2. Query for a Cedar System and `businessOwnerRoles`
=> [EASI-4069] - Add business owner info to cedar system

src/i18n/en-US/systemProfile.ts, src/views/Home/index.test.tsx, src/views/SystemList/Table.tsx, src/views/SystemList/__snapshots__/index.test.tsx.snap, src/views/SystemList/index.scss, src/views/SystemList/index.test.tsx, src/views/SystemList/index.tsx
- Added `<ButtonGroup />` component to toggle table type state
- Added switch/filter function to swap data sets based on table type
- Added url query param in preparation for fetching table type from url when menu bar is complete 
- Updated unit test
- Navigate to Systems tab
- Verify the toggle works (only for all systems and bookmarked systems.  My systems will come later)
=> [EASI-4067] All CMS systems table and button group

src/views/SystemIntake/ContractDetails/index.tsx
[Doc](https://docs.google.com/document/d/1rbiG21FIO51F-JUKgPZ6UYF2vwwD9ht0RZsTHeaQkAs/edit#heading=h.1xd88vdpols3)
- Moved the form onChange handler that clears contract data
- Contract information is now cleared on submit, rather than on change
- Add a contract number on the linking form
- Progress to thrid page of intake
- Verify contract number renders on form selections
- Verify that clicking `I haven't started acquisition planning yet` or `I don't anticipate needing contractor support` does not clear out the form values.  Should only clear after submission
- Verify data persistence of selection
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the …
=> [NOREF] Moved onchange handler to submit handler for contract intake

src/components/NavigationBar/index.scss
A style applied for the Systems navigation bar element was not properly scoped, and affected the system profile side nav.  This adjustment fixes the unintended style change
=> [NOREF] Fixed navigationbar style

pkg/dataloaders/user_info_loader.go, pkg/graph/resolvers/system_intake_system.go, pkg/graph/resolvers/trb_request_system.go, pkg/oktaapi/client_wrapper.go, pkg/storage/system_intake_contract_number.go, pkg/storage/system_intake_contract_number_test.go, pkg/storage/system_intake_system.go, pkg/storage/system_intake_system_test.go, pkg/storage/trb_request_contract_number.go, pkg/storage/trb_request_contract_number_test.go, pkg/storage/trb_request_system.go, pkg/storage/trb_request_system_test.go
- Replaced some calls that used `Context` with ones that don't. This can have some (IMO) minor performance downsides, but I think for our application is probably a cleaner approach
- Added some extra logging of `err` objects to ensure we have clear error content
The point of this PR is to hopefully reduce the number of errors that we seem to get alerted on that have to deal with `Context Canceled` which, generally speaking, aren't worthy of an alert (and aren't even really considered an error for us)
TBD
- Always make comments, even if it's minor, or if you don't understand why …
=> [NOREF] Replace Context calls

src/components/LinkCard/index.stories.tsx, src/components/LinkCard/index.test.tsx, src/components/LinkCard/index.tsx, src/i18n/en-US/home.ts, src/views/AdditionalInformation/index.tsx, src/views/Home/index.tsx
An attempt to consolidate "Request Types" for the frontend to switch between "TRB" and "System Intake" contexts for abstract component modes.
`types/requestType#RequestType` is the recent thought for this, but is there a better name for this? This pr can simply be a rename for this new reference.
There are some name collisions that we may want to sort out between FE and BE types
- [graphql-global-types.ts#RequestType](https://github.com/CMSgov/easi-app/blob/main/src/types/graphql-global-types.ts#L181-L184) exists but the options are only: `ACCESSIBILITY_REQUEST`, `GOVERNANCE_REQUEST`
- `types/systemIntake#RequestType` already exists on the FE, do we leave this? Or maybe rename to `SystemIntakeRequestType`? And then do the same for the other `TRBRequestType`?
=> [NOREF] Higher level "RequestType" attempt

src/components/NavigationBar/index.scss
Not sure where this was recently introduced, but a navbar style was overridden, causing the hover/current underline to not be in the correct position for all tabs, except for System.
- Fixed style on `NavigationBar` to align underline positions
Verify on hover, that all navigation bar underlines are in correct position
=> Fixed navbar hover style

pkg/graph/resolvers/system_intake_relation.go, pkg/graph/resolvers/system_intake_relation_test.go, src/views/AdditionalInformation/index.tsx, src/views/GovernanceTaskList/AdditionalRequestInfo.tsx, src/views/RequestLinkForm/index.tsx
This hides the **Contract number** fields on the `itgov` link form. Since the field was already optional, hiding the ui was good enough.
=> EASI-4160 Remove Contract number from ITGO linking flows

cmd/devdata/system_intake.go
- manually link/unlink contract numbers while disabled in UI
- `Note [EASI-4160 Disable Contract Number Linking]`
=> [EASI-4160] manually update/unlink contract numbers with note reference

.github/workflows/run_tests.yml, src/views/SystemProfile/mockSystemData.ts
Make the CI typescript check error failures consistent with the local dev pre-commit typescript check requirement.
=> CI client_typecheck continue-on-error true (default)

.github/workflows/build_application_images.yml
- Disable functionality that blocked the GHA pipeline if an ECR finding was caught during an image scan. See comment for more details
Ensure pipeline still passes. See examples below:
- [Failing job from another branch](https://github.com/CMSgov/easi-app/actions/runs/8619337558/job/23623792549?pr=2539)
- [Passing job from _this_ branch](https://github.com/CMSgov/easi-app/actions/runs/8620647886/job/23627880298?pr=2541#step:9:21)
=> [NOREF] Disable ECR findings blocking the GHA pipeline

src/views/RequestTypeForm/index.test.tsx
Following up on https://github.com/CMSgov/easi-app/pull/2533
Restored unit tests which check the switch of IT Gov request types. Other bits of the units test weren't actually used and removed. The request creation flow is covered a couple times in cypress.
=> NOREF Restore itgov request type unit tests

pkg/cedar/core/client.go
- Adds logging to the CEDAR core client
I added generic logging to the CEDAR core client using a custom Transport/RoundTrip and included a response time alongside a few other fields.
Make some requests to CEDAR core with mocking disabled and look at the container logs.
=> [EASI-4129] Add logging to CEDAR core calls

src/components/NavigationBar/index.scss, src/components/NavigationBar/index.tsx, src/components/shared/SectionWrapper/index.tsx, src/views/SystemList/__snapshots__/index.test.tsx.snap, src/views/SystemList/index.tsx
- Updated systems tab dropdown links
- Fixed Systems tab active and hover states
1. Verify systems tab dropdown links go to table
2. When on systems page, navigation tab text should be blue
=> [EASI-4131, EASI-4132] Systems tab UX fixes

.envrc, cedarproxy/nginx.conf, deploy/base/cedarproxy.yaml, deploy/base/easi.yaml, docker-compose.yml, pkg/appconfig/config.go, pkg/cedar/core/client.go, pkg/cedar/core/client_test.go, pkg/cedar/core/system_summary_test.go, pkg/graph/schema.resolvers_test.go, pkg/server/routes.go
- Adds the `CEDAR_CACHE_EXPIRE_TIME` environmental variable to allow for setting the length of time the nginx proxy caches requests without directly modifying the nginx config. Setting a new cache time will require a manual redeploy of the nginx proxy though due to [GitHub action](https://github.com/CMSgov/easi-app/blob/main/.github/workflows/deploy_to_environment.yml#L44-L53) only monitoring for changes to the `/cedarproxy` folder or the swagger client.
- Adds the `CEDAR_CORE_SKIP_PROXY` env var that allows for bypassing the nginx proxy if desired.
- Note: This would require a manual redeploy though since the variable is read in on server start. It might make sense to revisit how we implement env vars or use launchdarkly instead.
- Adds a [`proxy_cache_use_stale` rule to …
=> [NOREF] Add env vars for cache time and to bypass cache

cmd/test_cedar_intake/main.go, pkg/cedar/intake/client_test.go, pkg/dataloaders/cedar_system_loader.go, pkg/dataloaders/data_loaders.go, pkg/graph/resolvers/resolver_test.go, pkg/graph/resolvers/system_intake_relation_test.go, pkg/graph/resolvers/system_intake_system.go, pkg/graph/resolvers/system_intake_system_test.go, pkg/graph/resolvers/trb_request_relation_test.go, pkg/graph/resolvers/trb_request_system.go, pkg/graph/resolvers/trb_request_system_test.go, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/server/routes.go
- Adds a dataloader for fetching multiple CEDAR systems from the system summary endpoint.
Load the TRB admin homepage. It should be faster!
=> [NOREF] cedar system dataloader

cedarproxy/nginx.conf
- I forgot a semicolon. Whoops! This will allow the nginx service to start locally.
=> [NOREF] add semicolon to allow cedarproxy to start

.github/workflows/build_cedarproxy_image.yml, .github/workflows/deploy_cedarproxy.yml, .github/workflows/deploy_pipeline.yml, scripts/deploy_ecs_service.sh
- **Always** build and deploy cedarproxy
- call `aws ecs wait` after updating deployment to ensure service is healthy
Pipeline changes, no local testing required. 
=> EASI-4374: improve cedarproxy deployment stability

Dockerfile, Dockerfile.backend_k8s, Dockerfile.cypress, Dockerfile.db_seed, docs/dev_environment_setup.md, go.mod, scripts/testsuite
- Mimicking changes from https://github.com/CMSgov/mint-app/pull/1137
- Upgrade Go version from 1.21 to 1.22.3
- Upgrade go.mod
- Upgrade Dockerfile
- `scripts/dev up` should run/install the new version of Go in Docker, and E2E tests in CI should capture most changes.
- Follow install instructions at https://go.dev/dl/ to download Go 1.22.3
- Ensure `go version` returns the correct go version
=> Upgrade go from 1.21 to 1.22.3

EASI.postman_collection.json, cmd/devdata/main.go, cmd/devdata/trb_request.go, pkg/cedar/core/role.go, pkg/cedar/core/system_summary.go, pkg/cedar/core/system_summary_test.go, pkg/graph/resolvers/cedar_system_bookmarks_test.go, pkg/graph/schema.resolvers.go, pkg/local/cedarcoremock/system_summary.go, pkg/models/cedar_system.go, pkg/server/routes.go
Current `GetSystem` by ID CEDAR client calls rely on the system summary endpoint and filter the returned data set down by the requested system ID. However, if the system is inactive, this will break since the default behavior of the client was to only ask for active systems.
- Creates an option for CEDAR client system summary calls to not filter by active systems.
- Uses aforementioned option for GetSystem calls, including in the dataloader on startup.
- Adjusts local mocks to allow for the new filter and adds two inactive systems.
- Tests dependent on those mock calls were also updated.
- Intake request with an inactive system relation also added to seed data.
- Updates Postman collection to include direct call to CEDAR for all systems (including inactive).
- Also fixes …
=> [EASI-4390] Stop filtering for active CEDAR systems when searching by ID

src/components/NavigationBar/index.scss
For some reason the previous fix isn't needed anymore. Not sure what it was meant to be applied for at the time, but it seems to be okay on my end without any more style settings.
After changes:
=> EASI-4337 Alignment update for "Systems" heading

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/cedar_system.go
- Adds a boolean property to the systemDetails resolver so the FE can easily tell if the current user belongs to a given system.
Run the following query against a given system to see if you're a member or not (remember to turn off CEDAR mocking):
```graphql
query cedarSystemDetails($cedarSystemId: String!) {
cedarSystemDetails(cedarSystemId: $cedarSystemId){
isMySystem
}
}
```
=> [EASI-4104] Add isMySystem to system details resolver

src/components/RichTextEditor/index.scss
Firefox didn't like toast's original css of `counter-reset: li`. Instead `list-item` seems like a more standard value for browsers.
1. Seed data
2. The trb request **Case 6 - Draft advice letter** is a decent starting point to create the **What we recommend** `ol` `li`s
3. Check that the list item counter is correct through multiple ols and nested lis
Example before
After
=> EASI-4415 TRB Advice Letter - Numbered list displaying incorrectly

EASI.postman_collection.json, pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake.go, pkg/graph/resolvers/system_intake_test.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
- Adds a new mutation to update an existing system intakes request type.
This was built to support frontend work being completed in EASI-4053 (https://github.com/CMSgov/easi-app/tree/EASI-4053/fix_change_request_type)
- There's a new request in postman that can be used to test this!
- You can create a new request with a certain type in the frontend (or use postman)
- Call `updateSystemIntakeRequestType()` with the intake's ID and a new type
- Assert the new type is set in the DB (or submit the intake and look at it in the admin view)
- Always make comments, even if it's minor, or if …
=> [EASI-4053] Add mutation for modifying system intake request types

src/views/SystemProfile/components/Contracts/index.tsx
- System Profile has a bug where items in the Contracts subpage are repeated ([original slack thread](https://cmsgov.slack.com/archives/C03BWN7SJD9/p1718643885958489))
- This is because the react key is the same for every item
- The original key was just the id
- Now it also has contractNumber + orderNumber for more uniqueness
=> [NOREF] Fix the ContractCard key with more unique values

pkg/cedar/core/client.go, pkg/server/logger.go
Same change as made in MINT, here https://github.com/CMSgov/mint-app/pull/1184
In support of diagnosing potential areas that we might want to address for performance (largely with regards to where we might want to introduce more dataloaders), this PR adds functionality that automatically logs the response time of each request in milliseconds, allowing us to aggregate and analyze that data in Splunk.
**OF NOTE:** This PR _does_ move the `logger.Info` call _after_ the next.ServeHTTP call. This is (probably) how it should be anyways, since we don't necessarily want to hold up making the HTTP response with a logger call (and now it's needed, since we need to make the HTTP response happen before we can truly log how long it took)
- Load the UI in your browser
- `docker …
=> [NOREF] Automatically log HTTP response times

src/components/TableFilter/index.scss, src/index.scss, src/views/SystemWorkspace/components/AtoCard/index.tsx
Check that an [empty `isso`](https://github.com/CMSgov/easi-app/blob/main/src/views/SystemWorkspace/index.tsx#L136) will render a disabled Contact ISSO button _without_ a `mailto:undefined` link appearing.
=> Fix Contact button so that it doesn't show an undefined href

pkg/graph/resolvers/system_intake_grb_reviewer.go, pkg/graph/resolvers/system_intake_grb_reviewer_test.go, pkg/storage/cedar_system_bookmark.go, pkg/storage/store.go, pkg/storage/system_intake_contract_number.go, pkg/storage/system_intake_grb_reviewer.go, pkg/storage/system_intake_system.go, pkg/storage/trb_request_contract_number.go, pkg/storage/trb_request_system.go, pkg/storage/user_account_store.go
- Adds some helper methods similar to the existing `namedSelect` method (previously named `selectNamed`)
- Updates the arguments used by these methods from `type args map[string]any` to `any`
- This still allows the _caller_ of these methods to use `type args` to construct argument maps, but also opens up code like [this](https://github.com/CMSgov/easi-app/blob/0b7dc65e56f366451d9ec2ee3e4053b25523de6d/pkg/storage/system_intake_grb_reviewer.go#L21-L24), where we're passing in a `package models` struct as an argument, rather than a `map[string]any`
- `store.CreateSystemIntakeGRBReviewer` had what appeared to be an unused parameter in its function definition, so I removed it!
These methods serve to act as helpers for executing named statements without needing to prepare a statement and …
=> [NOREF] package storage helpers

.envrc, .github/workflows/run_tests.yml, .vscode/settings.json, deploy/base/easi.yaml, deploy/base/minio.yaml, docker-compose.ci_server_test.yml, docker-compose.cypress_ci.yml, docker-compose.yml, minio_config.json, src/data/mock/systemIntake.ts
- Update internal (within container) and external (outside of container) port used by the MinIO server from `9000` to `9004`
This change was needed as starting up our backend with the ZScaler VPN client running already would cause a port conflict on `9000` (ZScaler uses this for a web UI it hosts for debugging connections)
Ideally, this wouldn't happen, but it's far easier to just change the MinIO port to something that doesn't conflict than try and address this any other way.
- Start ZScaler
- Run `scripts/dev up`
- Ensure all services start
- Ensure file upload works within the application
- Ensure `scripts/dev minio:*` commands work as expected.
- Check that all code is adequately covered …
=> [NOREF] Update minio server port

src/views/SystemWorkspace/components/HelpLinks/SystemCardGroup.tsx, src/views/SystemWorkspace/components/HelpLinks/__snapshots__/index.test.tsx.snap, src/views/SystemWorkspace/components/HelpLinks/index.test.tsx, src/views/SystemWorkspace/components/HelpLinks/index.tsx, src/views/SystemWorkspace/components/RequestsCard/index.tsx, src/views/SystemWorkspace/index.tsx
Adds missing `linkSearchQuery` to starting request links found in the first 2 help cards.
=> [NOREF] Fix start request links in workspace help cards

cmd/devdata/trb_request.go, pkg/dataloaders/dataloaders.go, pkg/dataloaders/trb_request_feedback.go, pkg/graph/resolvers/trb_request_feedback.go, pkg/graph/resolvers/trb_request_feedback_test.go, pkg/graph/resolvers/trb_request_status.go, pkg/graph/resolvers/trb_request_status_test.go, pkg/models/trb_request_feedback.go, pkg/sqlqueries/SQL/trb_request_feedback/get_by_ID.sql, pkg/sqlqueries/SQL/trb_request_feedback/get_by_IDs.sql, pkg/sqlqueries/SQL/trb_request_feedback/get_newest_by_ID.sql, pkg/sqlqueries/SQL/trb_request_feedback/get_newest_by_IDs.sql, pkg/sqlqueries/trb_request_feedback.go, pkg/storage/trb_request_feedback.go
- Adds dataloaders for getting all TRB Request feedback for a request as well as newest TRB Feedback for a request.
- Adds some more checks and refactors the resolver tests.
- Adds more feedback to TRB Request seed data to support testing latest feedback.
- Updates Status Resolvers to use the new dataloaders.
- Pull all TRB Requests with the `status` or `feedback` fields. 
- Don't be afraid to leave comments or ask questions, especially if you don't understand why …
=> [EASI 4457] - TRB Request Feedback dataloaders

scripts/dev
Updates the `scripts/dev db:clean` script to also call the `minio_mc` docker container (which uses [mc](https://min.io/docs/minio/linux/reference/minio-mc.html)) to delete all files.
We _could_ make other changes to have this cleaned on application startup, but this change works in isolation and was simple enough to add, so I'm keeping this PR simple!
- Ensure nothing exists in `./tmp/minio/easi-app-file-uploads/`
- Start the backend with `scripts/dev up:backend`
- Run `scripts/dev db:seed`
- You should now see a bunch of folders populated in `./tmp/minio/easi-app-file-uploads/`
- Run `scripts/dev db:clean`
- You should see the `./tmp/minio/easi-app-file-uploads/` folder is now cleared
- When …
=> [NOREF] Clean Minio files when using db:clean

.envrc, docs/cedar.md, src/data/mock/systemIntake.ts
- `host.docker.internal` is a little bit of a pain on WSL, but also we can't use this with `k8s`, so I'm trying to strip the occurrences from our app. After this we just have the dev scripts that reference it.
- Run automated tests, test the document uploads locally.
- Check that …
=> [NOREF] Remove host.docker.internal

cmd/devdata/trb_request.go, pkg/dataloaders/dataloaders.go, pkg/dataloaders/trb_request_advice_letter.go, pkg/dataloaders/trb_request_attendees.go, pkg/graph/resolvers/trb_request.go, pkg/graph/resolvers/trb_request_attendee.go, pkg/graph/resolvers/trb_request_attendee_test.go, pkg/graph/schema.resolvers.go, pkg/models/trb_request_attendee.go, pkg/sqlqueries/SQL/trb_request_attendees/get_attendee_by_EUA_ID_and_TRB_ID.sql, pkg/sqlqueries/SQL/trb_request_attendees/get_attendees_by_EUA_IDs_and_TRB_IDs.sql, pkg/sqlqueries/SQL/trb_request_attendees/get_by_trb_ID.sql, pkg/sqlqueries/SQL/trb_request_attendees/get_by_trb_IDs.sql, pkg/sqlqueries/trb_request_attendee.go, pkg/storage/trb_request_attendee.go
- Adds a dataloader for TRB Attendees, this isn't on the admin home page query currently, but you can ask for attendees as part of pulling all TRB Requests.
- Adds a dataloader for TRB Attendees by EUA and TRB ID. We currently only use this to pull the `requesterComponent` field on TRB Requests.
- Run the test suite or query for `attendees` on TRB Requests.
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! …
=> [EASI-4457] TRB attendees dataloaders

src/views/TechnicalAssistance/RequestForm/Basic.tsx
- Fixes bug where "other" field in TRB request form resets value
- See[ easi-potluck](https://oddball.slack.com/archives/C06RSLZ4UKF/p1721079195635119) for video of bug
1. Start a new TRB request
2. Go to "basic request details" page of form
3. Fill out fields:
1. For "where are you in your process", select "other"
2. Fill value for "please specify"
3. Change "where are you in your process" to different value
4. Change "where are you in your process" back to "other"
5. "Please specify" should still have original value
4. Click "next"
5. Go back to "basic request details" page
6. "Please specify" field should still have value
- …
=> [NOREF] TRB form other field bug

cmd/devdata/main.go, cmd/devdata/mock/mock.go, cmd/devdata/system_intake.go, cmd/devdata/system_intake_actions.go, cmd/devdata/system_intake_business_case_v1.go, cmd/devdata/system_intake_decision_actions.go, cmd/devdata/system_intake_grb_reviewers.go, cmd/devdata/trb_request.go, cypress/e2e/governanceReviewTeam.cy.js, pkg/storage/system_intake_grb_reviewer.go
- Prod has roughly 600 closed system intakes that are getting queried on the admin home page. To simulate that, this PR adds the ability to load up closed TRB and System Intake requests as seed data for local development.
- This also refactors the seed data script to use context properly.
- `scripts/dev db:clean && scripts/dev db:seed`
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a …
=> [EASI-4457] Add closed requests for testing

.github/workflows/run_tests.yml, scripts/dev, scripts/run-cypress-test-docker, scripts/tag_minio_file
Docker Compose uses `docker compose` as the command, and `docker-compose` is the standalone plugin command as of Compose V2.
It appears that some Github Actions runners are missing the standalone plugin version, which causes issues when running the `docker-compose` command. This change will simplify and consolidate all Docker Compose actions to using `docker compose`
https://github.com/actions/runner-images/issues/9692
Confirmed V1 is removed as of July 29.
- 
- Don't …
=> NOREF: Replace docker-compose with docker compose

src/components/RequestRepository/useRequestTableColumns.tsx, src/views/MyRequests/Table/index.tsx
This fixes the status column on ITGOV tables so that it sorts alphabetically.
The table is found on the ITGOV admin home page and the IT Gov tab > My IT Gov requests table.
=> [NOREF] Fix status column sorting on requests tables

src/types/flags.ts, src/views/AdditionalInformation/index.tsx, src/views/FlagsWrapper/index.tsx
- add back flag that is still in use
- 
=> add back flag

src/components/RequestRepository/useRequestTableColumns.tsx, src/utils/tableRequestStatusIndex.ts, src/views/MyRequests/Table/index.tsx, src/views/MyRequests/Table/tableMap.ts, src/views/TechnicalAssistance/Homepage.tsx, src/views/TechnicalAssistance/TrbAdminTeamHome.tsx
Table's status column needs to sort by status enums.
This also introduces `utils/tableRequestStatusIndex.ts` to maintain sort indexes.
Tables were initially made to leave status columns up to alphabetical sorting, if at all.
Bug originally found on the ITGOV table.
**Before**
<hr>
<hr>
**After**
<hr>
<hr>
- Check table instances on local dev seeded
- Make sure that the request status columns follow the order of the original enums
- [SystemIntakeStatusRequester](https://github.com/CMS-Enterprise/easi-app/blob/EASI-4589/status_sort/pkg/graph/schema.graphql#L2879)
- [SystemIntakeStatusAdmin](https://github.com/CMS-Enterprise/easi-app/blob/EASI-4589/status_sort/pkg/graph/schema.graphql#L2857)
- [TRBRequestStatus](https://github.com/CMS-Enterprise/easi-app/blob/EASI-4589/status_sort/pkg/graph/s …
=> EASI-4589 Fix the requests table's status column sorting method

src/i18n/en-US/systemProfile.ts
Fixes this broken i18n key for Contract Information
> [!NOTE]
> The Contract Info section is behind the `systemProfileHiddenFields` flag, and vendors is static mock data.
=> Restore Contract Information text

.envrc, .github/workflows/run_tests.yml, deploy/base/easi.yaml, docker-compose.yml, pkg/appconfig/config.go, pkg/appses/ses.go, pkg/appses/ses_test.go, pkg/server/config.go, pkg/server/routes.go
- Adds a new configuration variable titled `SES_RECIPIENT_REGEX`. It must either be an empty string (i.e. not configured/set), or a valid regex string
- `routes.go` now pulls this configuration variable, parses the regex using `regexp.MustParse()`, and forwards it to the SES Sender
- The SES Sender now accepts this regex and will, in non-production environments, filter out recipient email addresses that don't match the regex
This change allows us to configure our lower level environments (or any environment, technically) to have an effective "whitelist" of domains that we're allowed to use SES to send emails to. This will prevent us from sending emails to users with `.gov` (or otherwise any external email to our team)
This is a _bit_ tough to validate locally, since the logic only occurs …
=> [EASI-4654] Added dynamic regex-based filtering to email client recipients

src/components/RichTextEditor/index.scss
- When adding an admin note to a TRB request, the rich text editor was blocking selecting a guidance option from the dropdown
- See [slack thread](https://oddball.slack.com/archives/C059N01AYGM/p1731077682370609?thread_ts=1731074413.177179&cid=C059N01AYGM)
- Set editor z-index to 0 to fix bug …
=> [NOREF] RTE z-index bug

src/views/TechnicalAssistance/GuidanceLetterForm/NextSteps.tsx, src/views/TechnicalAssistance/GuidanceLetterForm/Summary.tsx
- Guidance letter "next steps" step seemed to not save values
- See [slack thread](https://oddball.slack.com/archives/C059N01AYGM/p1731081683189919?thread_ts=1731074413.177179&cid=C059N01AYGM)
- Guidance letter query needed to be refetched after executing `updateTRBGuidanceLettern` mutation
1. Create guidance letter
2. Fill guidance letter fields
3. Click "Save and return to request"
4. Go back to guidance letter
5. Make changes on "Next Steps" fields
6. Changes should save and show correct values in "Internal review" step
- e.g. "Approving …
=> [NOREF] Guidance letter save bug

src/i18n/en-US/discussions.ts
- Add new i18n file that contains language needed for new GRB Review Discussions feature
- Verify that spelling matches wireframes
- Evaluate proposed structure of i18n file and propose any changes. There are TODOs in the file that call out things that need to be answered
- Check …
=> Add new discussions i18n file

.github/workflows/deploy_to_eks.yml
- Adds support for `eks_ignore` label. When present, EKS deploys on that PR will not execute.
- I tested this change on this PR by creating it with the `eks_ignore` label, and we can see the job failure [here](https://github.com/CMS-Enterprise/easi-app/actions/runs/12300027752/attempts/1?pr=2919)
- When re-running, the same event information is used, so it will [also fail](https://github.com/CMS-Enterprise/easi-app/actions/runs/12300027752/attempts/2) (you'll need to push a new commit to trigger a deployment)
- e.g. "Approving because the …
=> [NOREF] Add support for EKS ignore label

pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake_grb_reviewer.go, pkg/graph/resolvers/system_intake_grb_reviewer_test.go, pkg/graph/schema.resolvers.go, pkg/models/system_intake_grb_discussions.go, pkg/models/system_intake_grb_reviewers.go
Removes some duplication of enum types related to GRB Roles (Reviewer Role & Voting Role).
> [!IMPORTANT]
> The main thing to consider when we're using these auto-generated types is that they're not used in any `map[string]interface{}`-style resolvers (i.e. anything that uses `ApplyChanges`)
> This doesn't appear to be the case here, but reviewers should confirm that this is the case!
- Taking UI actions to add GRB reviewers, fetch the list of reviewers, and create GRB discussions should be enough to validate that these role types work
- Additionally, since these changes involved a lot of find & replace, ensure that all references were properly updated
- When approving a PR, provide a reason …
=> [EASI-4614] Fix duplicate GRB Role types

EASI.postman_collection.json, migrations/V198__Add_async_GRB_presentation_links.sql, migrations/V199__Add_async_GRB_presentation_links.sql, pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/models_gen.go, pkg/models/system_intake_document.go, pkg/models/system_intake_grb_presentation_links.go, pkg/storage/truncate.go, scripts/dev, src/gql/gen/graphql.ts
- Adds GraphQL and DB schema for GRB presentation links
- N/A
=> [EASI-4527] add presentation links schema

cmd/test_email_templates/main.go, pkg/email/email.go, pkg/email/grb_review_discussion_group_tagged.go, pkg/email/grb_review_discussion_individual_tagged.go, pkg/email/grb_review_presentation_links_updated.go, pkg/email/grb_review_presentation_links_updated_test.go, pkg/email/system_intake_admin_upload_doc.go, pkg/email/system_intake_admin_upload_doc_test.go, pkg/email/templates/grb_review_presentation_links_updated.gohtml, pkg/email/templates/system_intake_admin_upload_doc.gohtml
- build out template + template code for notification emails when links are updated
- for now, run tests and confirm pass
- later, we will test this once resolvers are hooked up
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition …
=> [EASI-4529] notification emails

cmd/devdata/system_intake_grb_presentation_links.go, pkg/dataloaders/dataloaders.go, pkg/dataloaders/system_intake_grb_presentation_links.go, pkg/graph/schema.resolvers.go, pkg/models/system_intake_grb_presentation_links.go, pkg/sqlqueries/SQL/system_intake_grb_presentation_links/get_by_intake_IDs.sql, pkg/sqlqueries/system_intake_grb_presentation_links.go, pkg/storage/system_intake_grb_presentation_links.go, pkg/storage/system_intake_grb_presentation_links_test.go
- adds query endpoint/resolver
- adds storage method
- adds dataloader
- stubs out initial storage test for later expansion
- run tests - confirm pass
=> Easi 4528/query links

src/views/TechnicalAssistance/Homepage.tsx
Not sure what upgrade affected the style on the TRB alert (doesn't seem to be super obvious).  This fix addressed that css style change.  I've did an audit and only found this instance.  The affected dependabot is in the pipeline but will hold off on deploy so this can overwrite it.
- Verify no other visible changes from previous dependabot
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a …
=> [NOREF] Fixed alert style from previous dependabot

src/stylesheets/custom.scss
Fixes bugs from upgrading `@trussworks/react-uswds` (see [Slack thread](https://cmsgov.slack.com/archives/CNU2B59UH/p1739483727864639))
- Fixes font in all instances where Trussworks component or USWDS utility class is used
- Fixes footer `max-width` css property
-
- Check that …
=> [NOREF] Fix font and footer width

src/components/TaskStatusTag/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Requester/TaskList/GovTaskGrbMeeting/index.test.tsx, src/features/ITGovernance/Requester/TaskList/GovTaskGrbMeeting/index.tsx, src/gql/legacyGQL/GetGovernanceTaskListQuery.ts, src/gql/legacyGQL/types/GetGovernanceTaskList.ts, src/i18n/en-US/itGov.ts, src/i18n/en-US/taskList.ts, src/tests/mock/govTaskList.ts, src/tests/mock/systemIntake.ts
- update `GovTaskGrbMeeing` test
- add `grbReviewType`, `grbReviewStartedAt`, `grbReviewAsyncRecordingTime`, `grbReviewAsyncEndDate`, `grbReviewStandardGRBMeetingTime`, `grbReviewAsyncGRBMeetingTime` to the query
- update copy
- update mocks to account for new values needed 
- Navigate to the IT Goverance page and find step 6
- Manipulate variables like review type and grbMeetingStatus to see the different variations 
- check to see variations match figma
- Don't be …
=> [EASI-4723] Requester Task List Updates

cypress/e2e/governanceReviewTeam.cy.js, src/features/ITGovernance/Admin/GRBReview/PresentationLinksCard.test.tsx, src/features/ITGovernance/Admin/GRBReview/PresentationLinksCard.tsx
- Fixed downloaded file names when clicking "View transcript" and "View slide deck" links from presentation links card
- Files were downloading as {id}.pdf instead of {filename}.pdf
- Go to presentation links form (/it-governance/:systemId/grb-review/presentation-links)
- Upload files for both presentation deck and transcript fields
- Submit form
- Run `scripts/dev minio:clean` to complete virus scan so you can download files
- Test "View transcript" and "View slide deck" buttons on presentation links card
- Downloaded file names should match uploaded files
- e.g. "Approving because I tested it locally and all functionality …
=> [EASI-4794] Fix presentation link downloaded file names

.eslintrc, package.json, tsconfig.json, vite.config.ts, vitest.config.ts, yarn.lock
This was initially #3089, but after making more edits to the files than just bumping the version, I wanted to separate it out to its own PR.
- Upgrades Vite to v6.2.6
- Upgrades Vitest to v3.1.1
- Updates related dependencies (rollup, esbuild, etc.)
- Removes unused dependencies, such as `@apollo/federation`, and the `resolutions` written in the `package.json`
1. `git pull` 
2. `yarn install`
3. start environment and esnure things are working fine
4. run `yarn test` and ensure tests pass
- e.g. "Approving because the change is simple and …
=> [NOREF] Update Vite and Vitest and removed apollo/federatio

src/features/ITGovernance/Requester/TaskList/GovTaskGrbMeeting/_components/RequesterDiscussionsCard/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Requester/TaskList/GovTaskGrbMeeting/_components/RequesterDiscussionsCard/index.test.tsx, src/features/ITGovernance/Requester/TaskList/GovTaskGrbMeeting/_components/RequesterDiscussionsCard/index.tsx, src/features/ITGovernance/Requester/TaskList/GovTaskGrbMeeting/index.test.tsx, src/features/ITGovernance/Requester/TaskList/GovTaskGrbMeeting/index.tsx, src/i18n/en-US/discussions.ts, src/tests/mock/discussions.ts, src/tests/mock/govTaskList.ts
[Figma](https://www.figma.com/design/G0UN35V7SY0g9nkTIESxsY/EASi-GRB-Experience?node-id=2763-101981&t=s5adJm96HC1Ba1Pl-0)
- Updated GRB Review task list step to include requester discussions card
- Only renders when GRB meeting status is `REVIEW_IN_PROGRESS` or `AWAITING_DECISION`
- Button functionality to view discussion board and start discussion will be completed in EASI-4857
- Unit tests 
- Log in locally as `USR1` with `EASI_P_USER` code
- Go to task list of seeded request titled "System Intake with some different GRB Reviewers (and discussions)"
- Verify that the discussions card matches the Figma at different GRB meeting statuses
- Update [this line](https://github.com/CMS-Enterprise/easi-app/blob/007449fb2008c27832c0d0d68e263f81b3ff198e/src/features/ITGovernance/Requester/TaskList/ …
=> [EASI-4858] Requester discussions task list updates

pkg/graph/resolvers/system_intake_grb_reviewer.go, src/features/ITGovernance/Admin/GRBReview/GRBReviewAdminTask/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewAdminTask/index.tsx, src/features/ITGovernance/Admin/GRBReview/SendReviewReminder/index.tsx
- Removed code on frontend that disables "Send reminder" button for 24 hours after reminder is sent
- Unit tests
- Removed code on backend that prevents users from sending additional reminders for 24 hours
- Log in as user with `EASI_P_GOVTEAM` job code
- Go to GRB review tab of any seeded request
- Complete GRB review set up form to start review
- Click "Send reminder" button in admin task box
- Confirm that "Send reminder" button is still enabled and "Most recent reminder" text renders with correct date/time
- Click "Send reminder" button to send second reminder
- Wait at least one minute between reminders so time will update
- Confirm that "Most recent reminder" text reflects new date/time …
=> [EASI-4860] Enable send reminder button

src/utils/date.test.ts, src/utils/date.ts
- Fixed calculation for time until async GRB end date
- Updated unit test
- Log in as user with admin job codes
- Go to seeded request titled "grb meeting without date set"
- Complete GRB review form for async review type
- Replace [this code](https://github.com/CMS-Enterprise/easi-app/blob/ba76d54e35a033442b3a2690915be14f5bfc3f4a/src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.tsx#L105-L107) with the code below, updated to reflect current date
- This sets the end date to today at 5pm eastern, and is a workaround for the time issue explained in EASI-4900
```jsx
const { days, hours, minutes } = formatDaysHoursMinutes(
'2025-06-04T21:00:00.000Z'
);
```
- Confirm that countdown renders correctly (should read 0 days since end date is today)
- It's best to pull the branch …
=> [EASI-4901] Fix async GRB end date countdown

cmd/devdata/main.go, cmd/devdata/system_intake_grb_review_cast_vote.go, cmd/devdata/system_intake_grb_review_setup.go, cypress/e2e/discussionBoard.cy.js
- Updated seed data for GRB review step
- Added support for GRB review [set up form](https://github.com/CMS-Enterprise/easi-app/blob/EASI-4861/async-grb-seed-data/cmd/devdata/system_intake_grb_review_setup.go) and [voting](https://github.com/CMS-Enterprise/easi-app/blob/EASI-4861/async-grb-seed-data/cmd/devdata/system_intake_grb_review_cast_vote.go) in mock data
- Skipped failing Cypress tests - will address in followup PR
- List of seeded GRB review step intakes below
- `intakeId` - admin status (description)
**Ready for review, form not started**
`d9c931c6-0858-494d-b991-e02a94a42f38` - Ready for GRB review (no GRB date set)
`8f0b8dfc-acb2-4cd3-a79e-241c355f551c` - Ready for GRB review (no GRB date set)
`8ef9d0fb-e673-441c-9876-f874b179f89c` - Ready for GRB review (GRB date set in …
=> [EASI-4861] GRB review seed data

src/features/ITGovernance/Admin/Actions/ProgressToNewStep.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.tsx, src/features/ITGovernance/Admin/GRBReview/PresentationLinksCard/PresentationLinksCard.test.tsx, src/features/ITGovernance/Admin/GRBReview/PresentationLinksCard/PresentationLinksCard.tsx, src/features/ITGovernance/Admin/GRBReview/index.tsx, src/i18n/en-US/grbReview.ts
[Figma](https://www.figma.com/design/jo2KOvJWY4YDSYfmfW3adR/EASi-System-Library?node-id=2931-594&t=cYTTW1uDdIgAmN4i-1)
- Added async presentation date to card header
- Hidden for standard meetings
-  Text updates to match Figma
- [QA doc #10](https://docs.google.com/document/d/1r5vLwLEwFG94PKviSUzw1TT_HiNqzR8nTwfkkeImmFc/edit?tab=t.0#heading=h.9k0w4spkfgra) - fixed broken "Set up review" link
> [!IMPORTANT]  
> This does NOT include changes to add the async presentation recording date field to the add/edit presentation links form. Those changes will be in a separate PR.
- Log in as user with admin job code
- Go to GRB review tab of request "GRB meeting without date set"
- Testing steps below are to check presentation date. Confirm that card matches Figma for different states.
- …
=> [EASI-4922] Async presentation links card updates

src/features/ITGovernance/Admin/Actions/ProgressToNewStep.tsx, src/features/ITGovernance/Admin/GRBReview/PresentationLinksForm/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/PresentationLinksForm/index.tsx, src/features/ITGovernance/Admin/RequestOverview/RequestOverview.tsx, src/features/ITGovernance/Admin/index.tsx, src/i18n/en-US/grbReview.ts, src/validations/grbReviewSchema.ts
- Added async presentation recording date field to add/edit presentation links form
- Updated to match page in set up GRB review form (dividers, subheaders, etc)
- Unit tests
- Log in as user with admin job code
- Go to GRB review tab of request "Async GRB review (with discussions)"
- Click "Edit presentation links" button in presentation links card
- Fill async presentation recording date field
- Submit form
- Click "Edit presentation links" button
- Field should display default value
- Go to GRB review tab of request "GRB meeting scheduled"
- Click "Add asynchronous presentation links" button
- Async presentation recording date field should be hidden
- Fill and submit form
- When approving a …
=> [EASI-4922] Presentation links form updates

src/components/AdminAction/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewAdminTask/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewAdminTask/index.tsx, src/features/ITGovernance/Admin/GRBReview/RestartReviewModal/index.tsx, src/features/ITGovernance/Admin/GRBReview/SendReviewReminder/index.tsx
[Fixes QA item #13](https://docs.google.com/document/d/1r5vLwLEwFG94PKviSUzw1TT_HiNqzR8nTwfkkeImmFc/edit?tab=t.0#heading=h.gi1tgeo2o47m)
- Added code to clear error message on modal close
- Unit test to check that error message is cleared
- Log in as user with admin job code
- Go to GRB review tab of request "Async GRB review (voting complete)"
- Click "Restart review" button and submit form to restart voting
- Click "Send reminder" button and submit modal
- Error message should display in modal
- Close modal
- Click "Send reminder" button again to check that modal error message was cleared
- Close modal
- Click "End voting" button and submit modal to end review
- Click "Restart review" button
- Error message should not display in modal
- It's best to pull the branch locally and test it, …
=> [NOREF] GRB review modal error fix

src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.tsx, src/i18n/en-US/grbReview.ts
- Address https://cmsgov.slack.com/archives/CNU2B59UH/p1754311836390489
- Search and nav to `GRB meeting without date set` 
- Start an ASYNC GRB Review with a date in the past
- Verify that the copy has been updated to "Time past due", instead of "Time remaining for review"
- 
- …
=> [NOREF] Add 'Time Past Due' Copy When GRBReviewStatus Is Past Due

migrations/V217__Add_Other_Intake_Request_Type.sql, pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/models/system_intake.go, src/gql/generated/graphql.ts, src/i18n/en-US/intake.ts, src/types/systemIntake.ts
- Backend work to add `OTHER` to the `SystemIntakeRequestType` enum
1.  Review code changes
=> [EASI-4963] Add OTHER to SystemIntakeRequestType

src/components/SystemIntakeReview/SystemIntakeAnnualCosts.test.tsx, src/components/SystemIntakeReview/SystemIntakeAnnualCosts.tsx, src/components/SystemIntakeReview/index.tsx, src/features/ITGovernance/Admin/IntakeReview/index.test.tsx, src/validations/systemIntakeSchema.ts
- Updated form validation to allow zero in "What is the current spending" and "What is the planned annual spending" intake fields
- Updated formatting to render values as plain text if not a number
- Created `SystemIntakeAnnualCosts` component and moved costs logic there
- Unit tests for rendering costs data
1.  Create new system intake
2. Entering zero should not show error for "What is the current annual spending" and "What is the planned annual spending" fields
3. Go to `/it-governance/a2fa0d4b-909f-45d8-ad8c-90f22cf0db19/intake-request` to view seeded intake with legacy data
4. Annual spending fields should render correctly …
=> [EASI-4966] System intake spending fields bug fixes

src/components/MentionTextArea/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Admin/IntakeReview/__snapshots__/index.test.tsx.snap, src/tests/mock/systemIntake.ts, src/utils/date.test.ts, src/utils/date.ts
- Fixes e2e test failure affecting all PRs (example here) caused by contract date formatting
- Test is looking for `11/01/2025` but date was displayed `11/1/2025`
- Updated `formatContractDate` to return date formatted as `MM/dd/yyyy` to match other date instances
1.  e2e and unit tests should pass 
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to …
=> [NOREF] Contract dates e2e fix
