.pre-commit-config.yaml, Dockerfile
- Add dockerfilelint pre-commit hook
- Fix dockerfilelint error in `Dockerfile` 
- Autoupgrade the markdownlint hook
=> Add dockerfilelint pre-commit hook

.spelling, docs/adr/0014-use-mux-for-routing.md, docs/adr/index.md, go.mod, go.sum, pkg/server/server.go
- Switches router to use gorilla/mux
- Adds ADR explaining changes about router
=> Add router and adr for routing

.github/PULL_REQUEST_TEMPLATE.md, .pre-commit-config.yaml
- Simplify pull request template since github magic now auto-links these
=> Simplify PR template

.circleci/config.yml
- Add environment variables for static assets when building in CI
=> Add static assets env vars in CI

pkg/handlers/health_check.go, pkg/handlers/health_check_test.go, pkg/server/routes.go
- Add a health check endpoint to return a json and 200
- Move routes to `api/v1`
=> Mw add healthcheck

.circleci/config.yml
- Update REACT_APP_OKTA_REDIRECT_URI with new dev domain name
=> Update redirect uri with new domain name

go.mod, go.sum, pkg/okta/okta.go, pkg/server/cors.go, pkg/server/routes.go, pkg/server/server.go
- This pulls out the internal auth function to make the middleware chain a little cleaner
=> clean up auth function chain

.circleci/config.yml
- Temporarily disable code updates to IMPL during testing
=> Temporarily disable deployments to impl

.envrc, .spelling, README.md
- Add basic instructions to the README for running postgres in docker
=> Setup instructions for postgres in Docker

pkg/okta/okta.go, pkg/server/server.go
- Add a log statement when requests fail to okta
=> Log failures from okta

migrations/V2__Remove_Has_ISSO_From_Intake.sql
- Removes the has_isso column after discussion with Monica about the hardest user part in the form around ISSO and collaborators is adding the name. We should assume which buttons are selected based on if there is a name for each.
=> Remove hasisso

.spelling, docs/adr/0017-go-orm.md, docs/adr/index.md
- ADR for choosing sqlx as EASi ORM
=> add ADR for ORM

README.md, docker-compose.yml
- Add `docker-compose.yml` for running app & db locally in docker
- Document how to use the above & remove old docs
=> Add docker compose config & docs

src/components/Header/index.scss, src/components/Header/index.tsx, src/components/UsGovBanner/index.tsx, src/components/shared/SearchBar/index.scss, src/stylesheets/_variables.scss, src/stylesheets/custom.scss, src/validations/systemIntakeSchema.ts, src/views/App/index.tsx, src/views/SystemIntake/ContactDetails/GovernanceTeamOptions.tsx, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx, src/views/SystemIntake/Review/index.tsx, src/views/SystemIntake/index.scss, src/views/SystemIntake/index.tsx, src/views/SystemProfile/index.tsx
=> Fix System Intake form design alignment

.circleci/config.yml
- Update CircleCI config to add assume role to dev deployment
=> Add assume role to dev deploy

src/components/shared/TextField/index.tsx, src/validations/businessCaseSchema.ts, src/views/BusinessCase/GeneralProjectInfo/index.tsx, src/views/BusinessCase/index.tsx
This PR adds validations for the general project information page of the business case. Validations are fairly standard with the exception of the phone number field. We have pretty loose validation requirements to give the user freedom to enter the phone number as they choose.
=> Add Business Case Validations - General Project Information (pg1)

src/components/shared/TextField/index.tsx, src/validations/businessCaseSchema.ts, src/views/BusinessCase/GeneralProjectInfo/index.tsx, src/views/BusinessCase/ProjectDescription/index.tsx, src/views/BusinessCase/index.tsx
This PR adds the validations for the project description page of the business case. The only validations present are for required-ness.
=> Add Business Case Validations - Project Description (pg2)

.envrc, go.mod, go.sum, pkg/handlers/system_intake.go, pkg/handlers/system_intake_test.go, pkg/server/routes.go, pkg/server/server.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/storage/store_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Adds an endpoint to fetch system intake by uuid.
=> Get Intake by ID endpoint

src/components/EstimatedLifecycleCost/index.scss, src/types/businessCase.ts, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/index.tsx
This PR adds the Preferred Solution page for the Business Case. There are some minor copy updates from design that were easier to make now rather than splitting out to another ticket.
=> Add Business Case - Preferred Solution (pg4)

src/types/businessCase.ts, src/types/systemIntake.ts, src/validations/businessCaseSchema.ts, src/validations/systemIntakeSchema.ts, src/views/BusinessCase/GeneralProjectInfo/index.tsx, src/views/BusinessCase/index.tsx, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/Review/index.tsx, src/views/SystemIntake/index.tsx
- Replace `requestor` with `requester`.
=> Update to requester

.spelling, README.md, pkg/README.md
- Documentation of what is in `pkg`
=> add backend readme

pkg/apperrors/errors.go, pkg/integration/integration_test.go, pkg/integration/system_intakes_test.go, pkg/server/routes.go, pkg/server/server.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/testhelpers/okta.go
- Adds integrations tests for the PUT
- Mocks out the fetch and TODOs for the GET, until rebasing
=> Add integration tests for system intake endpoint

src/views/SystemIntake/Review/index.tsx, src/views/SystemIntake/index.tsx
- Fix "Goverannce" -> "Governance"
- Change "Review and send" -> "Send to GRT"
=> Update button language and spelling error

pkg/handlers/catch_all.go, pkg/handlers/catch_all_test.go, pkg/integration/catch_all_test.go, pkg/server/routes.go, pkg/server/server.go, yarn.lock
- Adds 404 Not Found routing for endpoints we've not defined.
=> Fix default routing

pkg/handlers/catch_all.go
- Use info logging instead of error logging on unexpected path
=> Switch error to info logging

cmd/easi/test.go
=> Set APP_ENV when tests run, not when they initialize.

scripts/db_lambda_invoke
- Add master alias attribute in db invocation script
=> Invoke master alias on db lambdas

src/views/App/index.tsx
=> remove system profiles page

src/sagas/systemIntakeSaga.ts
- Revert a change I was trying out but did not test in systemIntakeSaga
=> Revert accidental change in systemIntakeSaga

src/components/EstimatedLifecycleCost/Review/index.test.tsx, src/components/EstimatedLifecycleCost/Review/index.tsx, src/components/EstimatedLifecycleCost/index.tsx, src/data/businessCase.ts, src/types/businessCase.ts, src/validations/businessCaseSchema.ts, src/views/BusinessCase/AlternativeSolution/index.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx, src/views/BusinessCase/Review/ProposedBusinessCaseSolutionReview.tsx, src/views/BusinessCase/Review/index.tsx, src/views/BusinessCase/index.tsx
- Changes `projectName` to `requestName`
- Removes `budgetNumber`
- form field is deleted as well as its presence in any models and validations
- `GeneralProjectInfo` component renamed to `GeneralRequestInfo`
- `ProjectDescription` component renamed to `RequestDescription`
All other content changes are things I walked through with Sai. Mostly capitalization of text and/or writing out acronyms.
=> Content sweep changes on Business Case

.circleci/config.yml, scripts/check_ecr_findings
- Check the ECR scan findings after building the application image
=> Check ECR scan findings after building image

src/components/shared/UpcomingActions/index.tsx, src/reducers/systemIntakesReducer.test.ts, src/reducers/systemIntakesReducer.ts, src/types/systemIntake.ts, src/views/Home/index.scss, src/views/Home/index.test.tsx, src/views/Home/index.tsx
- Adds banners on Home page for System Intakes in `DRAFT`
- Adds tests for Home page
- Adds tests for System Intakes reducer
_probably should wait for #162 to get merged to we can update to `requestName`_
=> Adds banners for System Intakes on the Home page

pkg/handlers/system_intakes.go, pkg/handlers/system_intakes_test.go, pkg/server/routes.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Moves DB call for FetchSystemIntakesByEuaID to storage package
=> Update FetchSystemIntakesByEuaID to access DB in storage

pkg/handlers/business_case.go, pkg/handlers/business_case_test.go, pkg/models/business_case.go, pkg/server/routes.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/services/system_intakes.go, pkg/storage/business_case.go, pkg/storage/business_case_test.go, pkg/storage/system_intake_test.go
- Adds endpoint for fetching business case
=> Fetch Business Case endpoint

.envrc, pkg/appses/ses_test.go, pkg/local/email.go, pkg/server/routes.go
- Add mock email sender
- Log when an email is sent
=> Mock email and log locally

pkg/cedar/translated_client.go, pkg/cedar/translated_client_test.go
bug from 329
- Only validate funding source format if existing funding is true
=> Fix funding source validation bug

src/data/businessCase.ts
This PR formats business case data from the API for the app to be consumed
=> Update prepare business case API data for app

pkg/appvalidation/business_case.go, pkg/appvalidation/business_case_test.go, pkg/handlers/business_case.go, pkg/handlers/business_case_test.go, pkg/integration/business_case_test.go, pkg/server/routes.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/storage/business_case.go, pkg/storage/business_case_test.go, pkg/testhelpers/business_case.go
- Updates a business case that already exists
- Validates lifecycle costs to ensure each is unique across solution, phase, and year
- Includes updated at changes
- Explicitly does not allow the user to update ID, system intake or eua id on biz case
=> Update biz case

src/reducers/authReducer.test.ts, src/reducers/authReducer.ts, src/reducers/rootReducer.ts, src/sagas/businessCaseSaga.ts, src/sagas/systemIntakeSaga.ts, src/views/App/index.tsx, src/views/Login/index.test.tsx, src/views/Login/index.tsx, src/views/Sandbox/index.tsx, src/views/TimeOutWrapper/index.tsx
- Add a reducer to keep track of things related to the auth session
- Dispatch actions to update the lastActiveAt timestamp when we save a system intake or business case
- Auto-renew the token as long as the user was last active in the past 15 minutes
=> Sb add auto renew for tokens

migrations/V11__Update_Lifecycle_Costs.sql, pkg/appvalidation/business_case.go, pkg/models/business_case.go, pkg/storage/business_case.go, pkg/testhelpers/business_case.go
- Allows costs and phases to be null in db
=> Allow nullable costs and phases

migrations/V13__Rename_Operations_and_Maintenance_Lifecyle_Phase.sql, pkg/models/business_case.go
- Rename `Operations & Maintenance` to `Operations and Maintenance`
=> Rename operations and maintenance lifecycle

pkg/handlers/business_case.go, pkg/handlers/system_intake.go
- Add decoder message to generic log
=> print error from decoder in log

src/data/businessCase.ts
- Sends SystemIntakeId field to API
=> Sends systemIntakeId instead of systemIntake to API

pkg/cedar/gen/client/e_a_si_core_client.go, pkg/cedar/swagger-prod.json
- Update to use CEDAR prod swagger file
Generation showed that nothing changed other than default host name, which we don't use.
=> add cedar swagger prod file

src/data/businessCase.ts
- Fixes banner issue where SI banner was displaying even after business case had been started.
=> Receives SystemIntakeId instead of SystemIntake from API

pkg/apperrors/errors.go
- Add wrapped errors to custom error output
=> add wrapped error to custom error output

src/reducers/businessCaseReducer.test.ts, src/reducers/businessCaseReducer.ts, src/sagas/businessCaseSaga.ts, src/types/businessCase.ts, src/types/routines.ts, src/views/BusinessCase/index.tsx
This PR marks the business case as submitted.
=> Submit Business Case

pkg/appcontext/context.go, pkg/handlers/business_case.go, pkg/handlers/business_case_test.go, pkg/handlers/business_cases.go, pkg/handlers/business_cases_test.go, pkg/handlers/system_intake.go, pkg/handlers/system_intake_test.go, pkg/handlers/system_intakes.go, pkg/handlers/system_intakes_test.go, pkg/local/authorization.go, pkg/models/user.go, pkg/okta/okta.go, pkg/okta/okta_test.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- Add `User` struct
- Change EUA context to User
- Slight refactor of okta middleware to make this easier to parse
=> Use user struct in context

migrations/V14__Add_SubmittedAt_To_Business_Case.sql, pkg/appvalidation/business_case.go, pkg/appvalidation/business_case_test.go, pkg/models/business_case.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/testhelpers/business_case.go, pkg/validate/types.go, pkg/validate/types_test.go
- Adds `submitted_at` column
- Adds validations for business case on submit
- Adds submitted at time in services (but only for validations, not in db)
=> biz case submit validations

pkg/server/routes.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/services/config.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- Move logger and clock in service layer to a shared config
- Move them to first param to stop future git diffs for changes
=> Move logger and clock to shared config

pkg/integration/business_case_test.go, pkg/storage/business_case.go, pkg/storage/business_case_test.go
- Correct oversight to updating status on business case
=> Add status to db update

src/reducers/businessCaseReducer.test.ts, src/reducers/businessCaseReducer.ts, src/views/BusinessCase/index.tsx
This PR invokes the POST request when the business case loads. This will load autofilled data from the system intake.
=> [FRONTEND] Invoke POST request on Business Case load for autofill

package.json, src/components/BusinessCaseReview/index.tsx, src/components/SystemIntakeReview/index.tsx, src/views/BusinessCase/Review/AsIsSolutionReview.tsx, src/views/BusinessCase/Review/ProposedBusinessCaseSolutionReview.tsx, src/views/SystemIntake/RequestDetails/index.tsx, yarn.lock
This PR displays the white space that is entered by users. Previously white-space was collapsed and not displayed to users. This made text difficult to format and read.
In this PR, I've added `className="text-pre"` to all of the text rendered from `textarea` fields. This class name is from USWDS and adds the `white-space: pre` rule, which preserves white space. See more about the CSS rule [here](https://www.w3schools.com/cssref/pr_text_white-space.asp).
=> Preserve whitespace that is entered by the user in textareas

scripts/release_static, src/views/App/index.tsx
This PR exposes the `REACT_APP_APP_ENV` to the application in deployed environments.
=> Expose REACT_APP_APP_ENV to application

docs/operations/metrics.md
- Add doc to help anyone getting our metrics
=> Add doc for prod metrics

pkg/okta/okta.go
- Wrap a few errors in auth middleware
=> wrap errors in authorization middleware

src/components/Modal/index.scss, src/views/TimeOutWrapper/index.tsx
=> add console.logs for debugging and minor css fix

pkg/storage/business_case.go, pkg/storage/business_case_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go, src/data/systemIntake.ts, src/views/Home/index.test.tsx, src/views/Home/index.tsx
- Adds biz case id to GET system intakes 
- Uses that attribute for banner logic
Open question about all the other statuses is waiting for product and design: https://cmsgov.slack.com/archives/CNU2B59UH/p1595376008323500
So this is not ready to be merged.
=> Use biz case id in intake

src/views/GovernanceTaskList/TaskListItem.tsx
My last attempt at 523, forgot one change to the biz case status around closed and approved intake statuses. This fixes it.
- Add not needed status label to task list item
=> Add not needed changes

.circleci/config.yml, scripts/db_lambda_invoke
- Updates the ecs lambdas called by circleCI to call revisions where the logging level has been changed from `DEBUG` to `INFO`
=> Update ecs lambas in circleCI config to fix log level

src/i18n/en-US/businessCase.ts, src/reducers/businessCaseReducer.test.ts, src/reducers/businessCaseReducer.ts, src/sagas/businessCaseSaga.ts, src/views/BusinessCase/Confirmation/__snapshots__/index.test.tsx.snap, src/views/BusinessCase/Confirmation/index.test.tsx, src/views/BusinessCase/Confirmation/index.tsx, src/views/BusinessCase/index.tsx, yarn.lock
This PR adds an additional confirmation page to the business case
=> Add business confirmation page with link to feedback survey

.circleci/config.yml, scripts/deploy_service
I missed a few in #303.
- Updates the ecs lambdas called by circleCI to call revisions where the logging level has been changed from `DEBUG` to `INFO`
=> Update more ecs lambas in circleCI config to fix log level

pkg/storage/business_case.go, pkg/storage/business_case_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Change default uuid for biz case to nil for system intake
=> Change default biz case id

cypress/integration/systemIntake.spec.js, src/reducers/systemIntakeReducer.test.ts, src/reducers/systemIntakeReducer.ts, src/views/SystemIntake/ContactDetails/GovernanceTeamOptions.tsx, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx, src/views/SystemIntake/Review/index.tsx, src/views/SystemIntake/index.tsx
- Refactor the system intake form logic to exist across the three pages instead of consolidated just on one
=> Sb system intake form refactor

README.md
- Add documentation around setting up the `direnv` utility for local development
=> EASI-96 doc direnv [skip ci]

.circleci/config.yml, docker-compose.circleci.yml, docker-compose.local.yml, scripts/run-cypress-test-docker
- Store the system intake cypress video in CI
- Fix the docker-compose networking in the CircleCI cypress tests
=> Store system intake cypress artifact in CI, fix cypress docker networking

docker-compose.circleci.yml
- Remove Mikena's email from the docker-compose.circleci.yml file (this was the only instance found in any of the CI files)
=> Update GRT_EMAIL in circleci docker test file

src/reducers/authReducer.test.ts, src/reducers/authReducer.ts, src/views/AuthenticationWrapper/index.tsx, src/views/Login/index.test.tsx, src/views/Login/index.tsx, src/views/TimeOutWrapper/index.tsx
- Add a reducer for keeping track of the last time we renewed a token
- Use the comparison of last renew time to last active at time when deciding whether or not to renew a token
=> Sb remove hardcoded time

.circleci/config.yml, Dockerfile, Dockerfile.client, go.mod, scripts/build_db_image, scripts/build_docker_image, scripts/check_ecr_findings, scripts/db_lambda_invoke, scripts/deploy_service, scripts/run-cypress-test-docker
- Update CI to use the latest Truss CircleCI image
- Update backend and frontend Docker files to match Go and Node versions in the new CircleCI image
- Update go.mod
- Update deployment scripts based on changes in AWS CLI v2
=> Upgrade to latest Truss CircleCI image

cypress/integration/businessCase.spec.js, cypress/plugins/index.js, cypress/support/businessCase.js, cypress/support/commands.js, cypress/support/index.js, cypress/support/login.js, docker-compose.circleci.yml, src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/components/BusinessCaseReview/index.test.tsx, src/components/shared/ActionBanner/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx, src/views/Home/index.tsx
This PR adds a basic business case smoke test.
=> add business case integration smoke test

src/views/BusinessCase/AlternativeSolution/index.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/Confirmation/__snapshots__/index.test.tsx.snap, src/views/BusinessCase/Confirmation/index.tsx, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx, src/views/BusinessCase/Review/index.tsx, src/views/BusinessCase/index.tsx, src/views/SystemIntake/index.tsx
- Add conditional breadcrumbs to the intake pages
- Add conditional breadcrumbs to the business case pages
=> Sb 580 breadcrumbs

cypress/integration/systemIntake.spec.js, src/views/SystemIntake/RequestDetails/index.tsx
This PR adds saving when a user tries to go "Back" on the system intake.
=> Save System Intake on "back"

src/views/BusinessCase/index.tsx, src/views/SystemIntake/index.tsx
I needed to add a `Switch` so that only the first matching route displays.
=> add switch so that 404 page only shows up on missing routes

.circleci/config.yml, scripts/run-cypress-test-docker
- Store cypress videos and screenshots in CircleCI artifacts
=> Store cypress videos and screenshots in CircleCI artifacts

src/i18n/en-US/index.ts, src/i18n/en-US/termsAndConditions.ts, src/views/App/index.tsx, src/views/TermsAndConditions/__snapshots__/index.test.tsx.snap, src/views/TermsAndConditions/index.test.tsx, src/views/TermsAndConditions/index.tsx
This PR adds the Terms & Conditions page. It does not have wireframes, but it does have required text mentioned in the story/content strategy guide.
=> Add Terms & Conditions

src/i18n/en-US/cookies.ts
- Addressed readability issue in Cookies page, changed reference to section in Privacy Policy to be more direct
=> Addressed readability issue in Cookies page

pkg/cedar/cedareasi/swagger-dev.json
- Add the previous version of the CEDAR EASi API from DEV, so that we have a base to compare new proposed changes against
=> add previous state for DEV API

pkg/cedar/cedareasi/swagger-dev.json
- Update the DEV Swagger spec to reflect the most recent state as of 24 Aug
=> recent state of dev as of 24 Aug

src/i18n/en-US/general.ts, src/i18n/en-US/governanceReviewTeam.ts, src/stylesheets/_colors.scss, src/views/App/index.tsx, src/views/GovernanceReviewTeam/index.scss, src/views/GovernanceReviewTeam/index.tsx
This PR adds the side nav to the GRT page
=> Add GRT side nav

src/components/Header/index.scss, src/data/systemIntake.ts, src/i18n/en-US/general.ts, src/i18n/en-US/governanceReviewTeam.ts, src/i18n/en-US/index.ts, src/i18n/en-US/intake.ts, src/i18n/en-US/systemIntake.ts, src/stylesheets/_colors.scss, src/types/systemIntake.ts, src/views/App/index.tsx, src/views/GovernanceReviewTeam/index.scss, src/views/GovernanceReviewTeam/index.tsx
This adds the basic page structure to the GRT reviewer page.
- Adds header and footer
- Adds blue banner with breadcrumbs, request name , requester name and component acronym, submission date
=> Add GRT Reviewer page layout

pkg/email/email.go, pkg/email/request_withdraw.go, pkg/email/request_withdraw_test.go, pkg/email/templates/named_request_withdrawal.gohtml, pkg/email/templates/unnamed_request_withdrawal.gohtml, pkg/server/routes.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- Emails the reviewer when the requester withdraws a request.
=> Send email on withdraw request

src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/IntakeReview/index.test.tsx, src/views/GovernanceReviewTeam/IntakeReview/index.tsx, src/views/GovernanceReviewTeam/index.tsx
http://localhost:3000/governance-review-team/:systemId/intake-request
This PR adds the GRT intake request reviewer view
- Uses a shared review component that has all the data
=> Add GRT intake request reviewer view

src/i18n/en-US/error.ts, src/views/NotFound/__snapshots__/index.test.tsx.snap
- Cleanup typos in page not found text
- Update the related snapshot test
=> Cleanup typos in page not found text

package.json
- Workaround to allow cypress tests to run locally.
See https://github.com/cypress-io/code-coverage/issues/216.
=> Set nyc reporter to html

cypress/integration/systemIntake.spec.js, cypress/support/systemIntake.js, src/components/SystemIntakeReview/index.tsx, src/types/systemIntake.ts, src/validations/systemIntakeSchema.ts, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/ContractDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx, src/views/SystemIntake/Review/index.tsx, src/views/SystemIntake/index.tsx
This PR moves the following questions from the Request Details to the new Contract Details page.
```
Do you currently have a contract in place?
Does the project have funding?
```
It also updates all relevant tests.
Note: The JIRA tickets mentions more questions that are currently on the Intake form. Those questions are not in the intake form yet and will be added directly to the Contract Details page.
=> Add contract details page to intake form

src/i18n/en-US/governanceReviewTeam.ts, src/views/GovernanceReviewTeam/AllRequests.tsx
- Add the header to the requests table
- Add the record count
=> Sb 802 total record count

cypress/integration/systemIntake.spec.js, cypress/support/systemIntake.js, src/components/SystemIntakeReview/index.tsx, src/types/systemIntake.ts, src/validations/systemIntakeSchema.ts, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap, src/views/SystemIntake/ContractDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx
I forgot to move this question. This PR moves this question to the new page.
=> Move 'Where are you in the process" to Contract Details

cypress/integration/systemIntake.spec.js, src/views/SystemIntake/ContractDetails/index.tsx
We recently expanded upon the contract questions, but I forgot to remove the old contract question. This PR removes that.
See below. This PR removes the old question in the top red box.
=> Remove extra has contract question

Dockerfile, pkg/services/services_test.go, pkg/storage/business_case.go, pkg/storage/store.go, pkg/storage/store_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Build the code that can generate a lifecycleID as specified in the JIRA ticket
- verify that incorrectly formatted, or exhausted lifecycleIDs are rejected
=> generate lcid

pkg/storage/action.go
- Update so new code no longer references a historical variable name
=> interleaved merges

.eslintrc, src/contexts/flagContext.test.tsx, src/views/App/index.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionB.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/GovernanceOverview/index.tsx, src/views/Home/index.tsx, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/ContractDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx
This PR adds
- feature flag routing for various Save & Exit links throughout the Intake and Business case
- Adds new `context` directory into `.eslintrc` for import sorting (and fixes some import ordering)
- Update routing on Governance Overview page
=> Update routing with governance task list feature flag.

src/data/systemIntake.ts, src/i18n/en-US/governanceReviewTeam.ts, src/i18n/en-US/intake.ts, src/types/systemIntake.ts, src/utils/systemIntake.test.ts, src/utils/systemIntake.ts, src/views/GovernanceReviewTeam/index.scss, src/views/GovernanceReviewTeam/index.test.tsx, src/views/GovernanceReviewTeam/index.tsx
This PR adds the review status banner to the GRT review page. Because of the mismatch of the intake status, this will be difficult to verify. Please reference the comments in the PR for clarification or ask me!
=> Add request status banner to GRT review page

pkg/storage/business_case.go, pkg/storage/business_case_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Idiomatically, return `nil` instead of empty types
=> idiomatic nil returns

cypress/integration/businessCase.spec.js, cypress/support/commands.js, cypress/support/login.js
Attempt #1 to fix CI integration tests
=> Attempt to fix Okta logging in CI

.circleci/config.yml
First pass at making some CircleCI workflow optimizations:
* The main improvement comes from fixing some of our dependency caching. We weren't caching the node_modules or the go module dependencies, so this PR adds the relevant cache steps to several jobs.
* Refactor the current `lint` job into three separate jobs: `pre_deps` to install yarn and go dependencies; `client_test` for front-end tests; `lint` to do the pre-commit checks.
=> CircleCI workflow optimizations

src/i18n/en-US/governanceReviewTeam.ts, src/views/App/index.tsx, src/views/RequestRepository/index.tsx
This PR is a small update to match our eng terms to match product terms. This page is currently being called the "Request Repository" and I made the update throughout the app to reflect that. We want to have consistent terms between practices.
=> Rename "All Requests" to "Request Repository"

cypress/integration/systemIntake.spec.js, src/components/shared/AutoSave/index.tsx, src/global.d.ts, src/index.tsx, src/views/BusinessCase/index.tsx, src/views/SystemIntake/index.tsx
This PR fixes they autosave in EASi. Please see inline comments for more details.
Things to check for:
There's an added assertion in the intake integration test. I am reading the Redux store and deep matching the intake form values. This is a lot simpler than manually checking the HTML since the outputted HTML depends on the values in Redux.
=> Fix autosave

src/data/taskList.ts, src/views/App/index.tsx, src/views/Home/index.tsx
This fixes some of the task list issues that were reported.
- home page banners had failed requests
- clicking on links in the task lists also had failed requests
=> Fix task list routing issues

migrations/V29__Add_Feedback.sql, migrations/V30__Add_NOTITREQUEST_Action.sql, migrations/V31__Add_Not_IT_Request_Intake_Status.sql, migrations/V31__Change_Closed_To_Not_IT_Request.sql, pkg/handlers/system_intake_action.go, pkg/handlers/system_intake_action_test.go, pkg/models/action.go, pkg/models/system_intake.go, pkg/server/routes.go, pkg/services/auth.go, pkg/services/auth_test.go, pkg/services/system_intake_action.go, pkg/services/system_intake_action_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- Adds action to review intake as "not an IT request"
- Removes this functionality from the Update System Intake endpoint (is that a problem?)
=> NOT_IT_REQUEST action API

src/i18n/en-US/action.ts, src/i18n/en-US/index.ts, src/types/action.ts, src/validations/actionSchema.ts, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx, src/views/GovernanceReviewTeam/index.tsx
- Configure form for submitting actions (most of them)
- Move strings to translation doc
Still left to do:
- Connect the form to the saga once we have the API done
=> Sb 930 new react component for actions

migrations/V32__Copy_Funding_Source_To_Number.sql, pkg/models/system_intake.go
Copy `funding_source` to `funding_number`
=> copy funding_source over to funding_number

src/reducers/authReducer.test.ts, src/reducers/authReducer.ts, src/utils/user.tsx, src/views/App/index.tsx, src/views/GovernanceReviewTeam/index.test.tsx, src/views/GovernanceReviewTeam/index.tsx, src/views/UserInfoWrapper/index.tsx
- Add reducer methods for storing a user's groups
- Add a new wrapper for storing user info
- Use that user info to redirect to a 404 if the user is not part of the review team
=> Sb 841 hide reviewer workflow

cypress/integration/businessCase.spec.js, src/views/GovernanceTaskList/index.tsx, src/views/Home/index.tsx
This PR links to "Start Business Case" banner to the task list instead of directly to the business case.
=> Fix "Start Business Case" banner to link to task list

pkg/handlers/system_intake_action.go, pkg/handlers/system_intake_action_test.go, pkg/server/routes.go, src/sagas/actionSaga.ts
- Changes the route from /system_intake/{id}/actions/{action_type}
- puts the action type instead in the request body
=> Put Action Type in /action/ request body

src/components/shared/CollapsableLink/index.scss, src/components/shared/CollapsableLink/index.tsx, src/i18n/en-US/action.ts, src/views/GovernanceReviewTeam/Actions/ChooseAction.tsx
- Adds frontend and e2e capabilities for reviewing an intake as Ready For GRT
- Adds some CSS styles to match the wireframe
=> ReadyForGRT dropdown

src/views/UserInfoWrapper/index.tsx
- Fix where we pull our groups to determine which job codes are present
=> We need groups from the decoded bearer token.

src/i18n/en-US/action.ts, src/types/action.ts, src/validations/actionSchema.ts, src/views/GovernanceReviewTeam/Actions/ChooseAction.tsx, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx, src/views/GovernanceReviewTeam/index.tsx
- New routing for LCID
- New form for LCID
Not in this PR:
- Any API changes needed
- Making an actual API call
=> Form for Issuing LCID

src/views/UserInfoWrapper/index.tsx
- Don't try and decode stuff that isn't there when the user is logged out
=> Handle issue when user is not logged in.

cypress/integration/taskList.spec.js
Things are fine locally, but we continue to have issues in CI. I've tried a few selectors, but nothing seems to budge.
I'm been filtering through [this](https://github.com/cypress-io/cypress/issues/7306) Github issue and there doesn't seem to be a great answer. I liked [this](https://github.com/cypress-io/cypress/issues/7306#issuecomment-640089395) reply the most. I wanna give this a try. 500ms seems like enough, I'll try 1000ms if things are still flakey.
=> attempt to fix integration ci issues

src/i18n/en-US/action.ts, src/sagas/systemIntakeSaga.ts, src/types/action.ts, src/types/routines.ts, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx
- Add new action for issuing LCID
- Call the actions API, too
=> Add api calls for issuing lcid

migrations/V40_Issue_LCID_Action_Type.sql, pkg/models/action.go, pkg/models/system_intake.go, pkg/server/routes.go, pkg/services/system_intake_action.go, pkg/services/system_intake_action_test.go, src/i18n/en-US/action.ts, src/types/action.ts
=> Add ISSUE_LCID Action

src/i18n/en-US/governanceReviewTeam.ts, src/views/RequestRepository/csvHeaderMap.ts, src/views/RequestRepository/index.tsx
- Connect the table to actual requests
- Adjust some date formatting
- Small refactors
=> Sb 955 connect api to table

src/i18n/en-US/action.ts, src/views/GovernanceReviewTeam/Actions/ChooseAction.tsx, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx
- Make LCID part of the dropdown
- Redirect to the intake page after we're done
=> LCID cleanup

pkg/cedar/cedareasi/translated_client.go
- Add protections against `nil` values coming from CEDAR
=> more defensive around cedar data

src/views/GovernanceTaskList/index.tsx
=> update task list business case step description

cypress/integration/businessCase.spec.js, migrations/V42_Change_Accepted_Approved_Closed_Intakes.sql, migrations/V42__Rename_To_Withdrawn_Status.sql, migrations/V43_Change_Accepted_Approved_Closed_Intakes.sql, pkg/models/system_intake.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/storage/business_case_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go, src/data/taskList.ts, src/types/systemIntake.ts, src/views/GovernanceTaskList/index.tsx, src/views/GrtSystemIntakeReview/index.tsx
- Stop using APPROVED, ACCEPTED, and CLOSED intake statuses
- Replace them with LCID_ISSUED, NEED_BIZ_CASE, and NOT_IT_REQUEST, respectively
=> Deprecate APPROVED, ACCEPTED, and CLOSED Intake statuses

migrations/V44__Remove_Decided_GRT_Email_Columns.sql, pkg/server/routes.go, pkg/services/action.go, pkg/services/action_test.go
Makes some changes to the actions API, including
- renaming some functions
- removing constraints around status of existing intake before action is taken
=> Small updates to Actions API

src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx
- Redirect a user after we submit
=> Redirect a user when we click submit.

src/views/Home/BusinessCaseBanners.tsx, src/views/Home/SystemIntakeBanners.tsx, src/views/Home/WelcomeText.tsx, src/views/Home/index.tsx
- Move homepage text to its own component
- Banners to their own components
This is all in prep for changing the homepage based on the roles a user has.
=> Sb 967 refactor current homepage

src/i18n/en-US/intake.ts, src/views/RequestRepository/index.tsx
- Added status column to request repository table
- Added translation map to i18n file to map database status enums to human readable statuses
=> Added status column to request repository table

pkg/services/action.go
- Help better track issues with LDAP requests
=> More specific error message for logs.

src/views/GovernanceReviewTeam/Actions/ChooseAction.tsx
- We already have the GRT and GRB actions! Let's use them!
=> Use same actions if we have a business case.

migrations/V45__Add_Notes_Table.sql, pkg/models/note.go, pkg/storage/note.go, pkg/storage/note_test.go
- new `Note` model object for "admin notes"
- new storage layer for Create and Read (no Update/Delete) of `Note` types
=> notes model and storage layer

src/views/GovernanceReviewTeam/index.tsx
- We had two route declarations for GRT
=> Too many reviews for GRT

src/data/taskList.ts, src/views/GovernanceTaskList/index.tsx
Update button and description according to the new statuses.
=> update business case task list item description and button

src/views/GovernanceReviewTeam/index.tsx
=> Add route for this action.

pkg/services/action.go, pkg/services/action_test.go, src/types/action.ts, src/views/SystemIntake/Review/index.tsx
- Fixes a bug where feedback from the reviewer was not in the email to requesters
=> Send feedback in Review email

migrations/V53__Add_backfill_fields.sql, pkg/models/system_intake.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Add the 3 new fields required for backfilling information from historical records
=> add new fields for backfill

src/views/GovernanceReviewTeam/Actions/ChooseAction.tsx
- Issue LCID for business case
=> Add LCID to actions for business case.

src/components/shared/ActionBanner/index.scss, src/components/shared/ActionBanner/index.tsx, src/views/Home/SystemIntakeBanners.tsx, src/views/Sandbox/index.tsx, src/views/SystemProfiles/index.tsx
This PR adds the request type to the home page banners.
=> Add the request type to the hope page banners

cypress/integration/businessCase.spec.js, migrations/V54__Add_Create_Biz_Case_Action.sql, pkg/integration/business_case_test.go, pkg/models/action.go, pkg/models/system_intake.go, pkg/server/routes.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/storage/business_case.go, pkg/storage/business_case_test.go
- Update intake status to BIZ_CASE_DRAFT when creating a business case
- Log an action to this effect
=> Update intake status on create biz case

src/components/shared/AutoSave/index.tsx
=> remove dependencies from autosave's useMemo so it doesn't continuously run

pkg/server/routes.go, pkg/services/action.go, pkg/services/action_test.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/services/system_intakes.go
- On certain system intake actions, close the associated biz case
=> Close biz case on certain actions

src/views/GovernanceReviewTeam/Actions/ChooseAction.tsx, src/views/GovernanceReviewTeam/index.tsx
=> Fix copy pasta.

cypress/integration/businessCase.spec.js, pkg/cedar/cedareasi/translated_client.go, pkg/cedar/cedarldap/translated_client.go, pkg/local/cedar_easi.go, pkg/local/cedar_ldap.go, pkg/server/routes.go
- Adds local CEDAR clients we can swap out in dev or in test
- Re-enables cypress tests that require CEDAR
=> Local CEDAR clients

src/data/businessCase.ts, src/validations/businessCaseSchema.ts, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionFields.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/Home/SystemIntakeBanners.tsx, src/views/Home/index.test.tsx
1. The business case does not return lifecycle cost lines for alternative B. If there aren't any returned, we should give it some by default.
2. The changes to the security questions don't have an actually affect the user's experience. There are React generated error logs about uncontrolled/controlled components. The code I added fixes them.
=> Fix miscellaneous issues on the business case

src/data/taskList.ts, src/views/App/index.tsx, src/views/GovernanceTaskList/RequestDecision/index.tsx, src/views/GovernanceTaskList/TaskListCta.tsx, src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx
- Updates the task list item based on intake status
- add basic template of the decision page
=> Add details into task list decision item

src/views/GovernanceReviewTeam/Notes/index.tsx, src/views/GovernanceReviewTeam/index.scss
This PR adds the note field onto the UI. This does not include FE and BE API connection. That'll show up in the next PR.
=> add form for notes on the notes page

pkg/handlers/system_intakes.go, pkg/handlers/system_intakes_test.go, pkg/models/system_intake.go, pkg/server/routes.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go
- Adds capability to filter intakes in GET request by being open or closed.
=> Open/Closed GET intakes filters

.circleci/config.yml
- Update the deployment lambda qualifier to use the new pagination code.
=> Use new pagination code in circleCI dev deploy

pkg/models/system_intake.go
- Two of us added this. Remove one.
=> Remove second declaration of same value.

src/reducers/systemIntakeReducer.test.ts, src/reducers/systemIntakeReducer.ts, src/sagas/systemIntakeSaga.ts, src/types/routines.ts, src/views/GovernanceReviewTeam/Notes/index.tsx, src/views/GovernanceReviewTeam/index.scss
- Adds request to fetch intake notes
- sorts request with the most recent being first
- prepends the saved note (instead of appending to the end) (although it doesn't 100% matter because we are manually sorting)
- styling!
=> View intake notes

pkg/server/routes.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- Remove support for sending emails through the system intake update service
- We have actions now! Let's use those
=> Remove old method of updating status and sending emails.

.circleci/config.yml
- Update lambda qualifiers to use the new ecs-manager version.
I'll check the taskdef revisions just before I merge this so I can compare before and after to verify nothing changed.
=> Update CircleCI config to use ecs-manager pagination code in IMPL and PROD

src/reducers/systemIntakeReducer.test.ts
test was in the wrong describe block so it wasn't getting the mocked time.
=> move note test to correct describe block

src/data/taskList.ts, src/views/GovernanceTaskList/TaskListCta.tsx, src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx
- Modified Task List to handle the READY_FOR_GRT task list status.
=> Add handling for READY_FOR_GRT in the task list

src/i18n/en-US/action.ts, src/sagas/systemIntakeSaga.ts, src/types/action.ts, src/types/routines.ts, src/validations/actionSchema.ts, src/views/GovernanceReviewTeam/Actions/ChooseAction.tsx, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx, src/views/GovernanceReviewTeam/index.tsx
- Add new form for rejecting a request
=> Sb 893 rejection front end

pkg/server/routes.go, pkg/services/auth.go, pkg/services/auth_test.go, src/data/systemIntake.ts, src/i18n/en-US/general.ts, src/i18n/en-US/governanceReviewTeam.ts, src/reducers/requestRepoReducer.test.ts, src/types/systemIntake.ts, src/views/GovernanceReviewTeam/Dates/index.tsx, src/views/GovernanceReviewTeam/index.tsx
- Change auth for PUT intake so reviewers can make updates
- Add a front end for the grt and grb dates
=> Sb 1018 reviewer can add grt grb dates

src/components/shared/CollapsableLink/index.tsx, src/i18n/en-US/governanceReviewTeam.ts, src/reducers/actionReducer.ts, src/reducers/systemIntakeReducer.ts, src/sagas/actionSaga.ts, src/sagas/systemIntakeSaga.ts, src/types/action.ts, src/types/routines.ts, src/views/BusinessCase/Review/index.tsx, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx, src/views/GovernanceReviewTeam/Notes/index.tsx, src/views/GovernanceReviewTeam/index.scss, src/views/SystemIntake/Review/index.tsx
- Shows actions along with notes in notes history
=> Show action history in notes view

src/i18n/en-US/footer.ts, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/NotFound/__snapshots__/index.test.tsx.snap, src/views/TermsAndConditions/__snapshots__/index.test.tsx.snap
- Fixed typo in footer i18n file, changed zip code from 2124 to 21244
=> Fix zip code typo in footer

pkg/models/action.go, pkg/storage/action.go, pkg/storage/action_test.go
=> Stores action feedback in DB

src/i18n/en-US/action.ts, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx
This PR adds the proper help and guidance text under the text label `This email will be sent to the requester` for issuing an LCID and rejecting a request.
=> Add help and guidance to reject request and issue lcid submission

src/components/RequestRepository/index.tsx, src/i18n/en-US/governanceReviewTeam.ts, src/i18n/en-US/intake.ts
- Add GRT and GRB date columns to request repository
- Allow reviewer to set date when it is null / not set
=> Add GRT and GRB dates to request repository

pkg/cedar/cedareasi/translated_client.go, pkg/services/action.go
- Skip submitting SystemIntakes to CEDAR by pretending that the submission worked.
=> do not submit to cedar

src/i18n/en-US/governanceReviewTeam.ts
- Fix i18n issue in displaying action names
=> Fix i18n issue in displaying action names

src/data/systemIntake.ts
- If submitted at exists, make sure we parse it back to a date before we update the intake
=> Parse submitted at back to a date.

cmd/backfill/main.go, cmd/backfill/main_test.go
- This is quick & dirty code for a stand-alone executable that reads in a CSV of data that we want to backfill into the EASi system. This PR is really just for getting the code in for posterity's sake, and is expected to be removed almost immediately once the data has been uploaded to PROD.
=> backfill exec

src/components/SystemIntakeReview/index.tsx, src/views/GovernanceReviewTeam/IntakeReview/index.test.tsx
This PR enables use of the intake submission date if it exists. If it doesn't exists, it uses the current date.
=> use intake submission date if it exists

src/constants/enums/contractStatus.ts, src/views/SystemIntake/ContractDetails/index.tsx
=> fix typo on intake contract question

pkg/services/action.go, pkg/services/action_test.go, src/validations/businessCaseSchema.ts, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionB.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx
- Apply different FE validations based on whether the biz case is draft or final
- Don't do backend validations until we have the final business case
=> Sb 769 biz case validations

pkg/handlers/system_intake.go, pkg/handlers/system_intakes_test.go, pkg/local/cedar_ldap.go, pkg/server/routes.go, pkg/services/action.go, pkg/services/action_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, src/sagas/systemIntakeSaga.ts, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx
- Creates action within LCID endpoint service
=> Include action creation in LCID endpoint

pkg/email/email.go, pkg/email/issue_lcid.go, pkg/email/issue_lcid_test.go, pkg/email/templates/issue_lcid.gohtml, pkg/server/routes.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- Include LCID details in LCID email
=> Add separate email for issuing LCID

cmd/backfill/main.go
- final finishing touches as per discussions in this thread: https://trussworks.slack.com/archives/CLCFT3EPM/p1607024900034100
=> last fine tuning for data import

src/components/RequestRepository/index.tsx
- Added custom sorting method that handles dates and strings with different capitalization.
=> Fix for Request Repo sorting issues

migrations/V61__Add_Shutdown_Intake_Statuses.sql, pkg/models/system_intake.go, pkg/server/routes.go, src/i18n/en-US/intake.ts, src/types/systemIntake.ts, src/views/Home/SystemIntakeBanners.tsx
- Add new statuses for intakes
- Make sure that we update some of the FE code that uses those statuses
=> Sb decommission statuses

src/types/flags.ts, src/views/App/index.tsx, src/views/DocumentPrototype/index.tsx
- Spin up a section of the app, hidden behind a feature flag, to use for our doc upload prototype
=> Sb doc proto space

cmd/backfill/main.go
- Found a couple of fields that need to be set for the UI to show all the data
=> EASI-973 couple of conditional fields

src/components/EstimatedLifecycleCost/index.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionFields.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx
=> add aria-describedby to business case help text

src/views/BusinessCase/AlternativeSolution/AlternativeSolutionFields.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx
I forgot to make the character counter first. It should be in the order:
1. Character Counter
2. Help Text
=> reorder aria-describedby on business case fields

cmd/backfill/main.go
- Was putting a free-form data column into a field that was expecting a limited set of responses
- Alternately, put the free-form information about cost into a Note
=> EASI-973 free form cost to a note

.circleci/config.yml, scripts/release_prototype_static
- CI updates to deploy the clickable prototype static assets to S3
These are intended as short-lived updates, not intended to be merged into master.
=> ES-37 CircleCI updates for clickable prototype

cypress/integration/businessCase.spec.js, cypress/support/businessCase.js, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionFields.tsx
This Pr updates our existing business case integration test to fill out all of the business case fields and check for the values to persist on the review page.
=> update business case test to fill out all fields and check values

src/i18n/en-US/governanceReviewTeam.ts, src/views/GovernanceReviewTeam/Decision/index.tsx, src/views/GovernanceReviewTeam/index.tsx
- Add a decision page to the reviewer workflow
- Add content based on the decision that was made about the request
=> Sb 1074 decision for reviewers

src/views/AuthenticationWrapper/DevLogin.tsx, src/views/AuthenticationWrapper/DevSecurity.tsx
=> Fix error with dev auth not propagating to homepage

src/views/GovernanceTaskList/TaskListCta.tsx, src/views/GovernanceTaskList/index.test.tsx
Update task list so that a user is able to view their submitted business case anytime.
=> update task list view business case

pkg/cedar/cedareasi/translated_client.go
- Make the internal->external representation transformation an isolated func (could even build a test around this in the future)
- make sure we are sending some of the datetime fields, and use the proper formatting
=> EASI-834 isolate transform, datetime format

src/views/GovernanceReviewTeam/BusinessCaseReview/index.tsx, src/views/GovernanceReviewTeam/IntakeReview/index.tsx
- Add PDF download for the intake review
- Add PDF download for the business case review
=> Add download wrapper to grt review pages.'

README.md
=> Update Readme with better info on local cypress testing

pkg/integration/integration_test.go
- invert the conditional short, do an early return with a skip signal, rather than an empty pass
(this diff is best viewed [without whitespace changes](https://github.com/CMSgov/easi-app/pull/690/files?w=1)).
=> skip tests, not silent pass

.storybook/main.js, package.json, src/components/shared/ActionBanner/index.stories.tsx, src/components/shared/TextField/index.stories.tsx, yarn.lock
This further configures storybook to align more with how we use/import SCSS is our application.
- SCSS Transpile
- Resolving absolute paths
- Add basic story for `TextField`
=> configure scss for storybook

src/components/BusinessCaseReview/AlternativeAnalysisReview/index.tsx, src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap
- Fixed business case review, it was displaying alternative A's data for both alternative A and B
=> Fixed business case review to properly display alternative b

src/components/AccessibilityRequestsTable/index.tsx
Remove Point of Contact column from table. The column is present on the prototype, but is not a part of this story's acceptance criteria.
=> remove point of contact from accessibility requests table

pkg/storage/system.go, pkg/storage/system_test.go
- update the SQL I previously implemented incorrectly from this [StackOverflow](https://stackoverflow.com/a/23767625)
=> ES-255 sql error

.envrc, docker-compose.circleci.yml, go.mod, go.sum, pkg/integration/integration_test.go, pkg/server/server.go, scripts/run-cypress-test-docker
- Initial pass at adding a TLS listener to the backend
=> First pass at adding tls to the backend

pkg/services/system_intakes.go
- Changed intake withdrawn logic to not send emails to GRT if intake was in draft
=> Don't send withdrawn email to GRT if intake is in draft

.circleci/config.yml, scripts/check_ecr_findings
- Invoke a specific version of the ecr-scan lambda so that new versions can be deployed without affecting existing CI workflows
=> Invoke version of ecr-scan lambda

.circleci/config.yml
- Pause impl and prod changes during code freeze
=> Pause impl and prod changes during code freeze

pkg/graph/model/uuid.go
- Fixes the UUID unmarshaler to work correctly
=> Fix uuid unmarshaler, now errors correctly

.circleci/config.yml, scripts/check_ecr_findings
- Update CI to use a new version of the ecr-scan lambda published via https://jiraent.cms.gov/browse/ES-332
=> Use new version of ecr-scan lambda

src/components/FileUpload/index.scss, src/components/FileUpload/index.stories.tsx, src/components/FileUpload/index.test.tsx, src/components/FileUpload/index.tsx
- Add File Upload component
- Add stories for File Upload
- Default
- Disabled
- Error
- Example usage with Formik
=> add file upload component

gqlgen.yml, pkg/graph/generated/generated.go, pkg/graph/model/accessibility_request.go, pkg/graph/schema.graphql
- Adds submittedAt field to accessibility request object in graphql
=> Add SubmittedAt field to GQL

docs/adr/0024-soft-deleting.md, docs/adr/index.md
- Adds an ADR for how we're doing soft delete of data from the database
=> Soft Delete ADR

.circleci/config.yml
- Resume impl, prod deploys after the code freeze
=> Resume impl, prod deploys post code-freeze

pkg/apperrors/errors.go
=> ES-274 ContextError was infinitely recursive

README.md
Update playground URL in `README.md`
=> Update GraphQL Playground docs

.spelling, docs/adr/0025-provide-testing-environments.md, docs/adr/index.md
- Add ADR for how to best allow non-engineers to test code
=> Add ADR for testing environments.

pkg/storage/business_case.go
=> accidental typo

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, src/i18n/en-US/accessibility.ts, src/index.tsx, src/queries/GetAccessibilityRequestQuery.ts, src/queries/types/GetAccessibilityRequest.ts, src/utils/formatDate.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/AccessibiltyRequest/Documents/index.tsx
- Mock some data for documents
- Add a table displaying that mocked data that we should be able to reuse elsewhere
This code has gone through a design review and an accessibility review!
=> Sb 268 mock docs table

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
- A smaller PR, this only changes the graphql schema for adding a new test date
=> Schema changes to add test date

.circleci/config.yml, scripts/check_ecr_findings
- Update CI to use latest version of ecr-scan lambda
=> Use ecr-scan lambda version 4

pkg/storage/system.go
Add business owner to systems query
=> add business owner to systems sql query

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, src/components/AccessibilityRequestsTable/index.tsx, src/queries/GetAccessibilityRequestQuery.ts, src/queries/GetAccessibilityRequestsQuery.ts, src/queries/types/GetAccessibilityRequest.ts, src/queries/types/GetAccessibilityRequests.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/AccessibiltyRequest/Documents/index.tsx, src/views/Home/index.tsx
- Make the 508 requests higher in the homepage if statement for testing purposes
- 508 page should show request name, not system name, in the header
- Show system name in the right sidebar
- Use date formatter on the requests table
- Comment out delete link for now
=> Sb bug fixes

migrations/V66__Rename_Files.sql, migrations/V67__Add_RequestID_To_Accessibility_Request_Files.sql, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/file_uploads.go, pkg/storage/file_uploads.go
- Rename files table to be more specific
- Foreign key files to accessibility requests
- Use request id to filter docs
=> Sb 376 connect files to requests

src/views/TestDate/index.tsx
- Use request name and not system name in the confirmation message
=> Use request name and not system name

src/components/AccessibilityRequestsTable/index.tsx
- Use our date formatter instead of the raw date from GraphQL
=> Format date using our date formatter

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
- Adds GraphQL for viewing test dates
Is it okay that this doesn't include pagination? We shouldn't expect to see more than a couple test dates for any request, so I don't know that pagination is necessary
=> Add graphql for fetching test dates

src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx
- On the doc upload page, use the request name instead of the system name
=> Use request name instead of system name

src/hooks/useConfirmationText.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/GovernanceTaskList/index.tsx, src/views/Home/index.tsx
This PR adds a hook to get the confirmation text. We have the same code duplicated in a number of places.
Also found a bug in the i18n for withdrawing an intake while doing this.
=> add confirmation text hook

src/views/Accessibility/AccessibiltyRequest/List/index.tsx
- Update Add a new request to use react router for a smoother/faster experience
- Update the fetch policy so that the cached data gets re-queried
=> Update "Add a new request" to be react-router Link and update fetch policy

src/components/TestDateCard/index.test.tsx, src/components/TestDateCard/index.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx
- remove edit/remove test date links
- format test date without comma
=> format date and remove edit/remove links

.circleci/config.yml
- Comment out the image scan check
There appears to be an intermittent issue with image scan failures.
Comment out for now until the root cause is addressed.
=> Comment out the image scan check

migrations/V71__Add_Document_Type_Field.sql, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/models/accessibility_request_document.go, pkg/storage/accessibility_request_document.go
- Adds document type field(s) to db, backend
=> Add document type backend

pkg/graph/schema.resolvers_test.go
- Master is broken, this fixes the relevant test
=> Fix weird merge test issue

src/utils/user.ts
=> enable 508 flow for testing

src/types/files.ts, src/validations/documentUploadSchema.ts, src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx
- Frontend changes for adding a doctype. 
- Still needs validation, among other things
- I will probably just skip i18n work right now in the interest of time
=> Add doc type frontend

.circleci/config.yml
- Reenable the image scan check
=> Reenable the image scan check

src/constants/enums/cmsDivisionsAndOffices.ts
- Updated CMS Divisions and Offices list to reflect latest reorg (list provided Feb 2021 by Matt Schmid)
=> Updated CMS Divisions and Offices

pkg/email/business_case.go, pkg/email/business_case_test.go, pkg/email/system_intake.go, pkg/email/system_intake_test.go, pkg/email/templates/business_case_submission.gohtml, pkg/email/templates/system_intake_submission.gohtml, pkg/services/action.go
- Added request names to system intake and business case submission email subject and bodies
=> Add request name to emails

src/views/SystemIntake/ContractDetails/index.tsx
- Modified funding source question in contract details section of intake request, change was due to GRT feedback of needing to clarify question for business owners
=> Modified funding source question in system intake

.circleci/config.yml
- Update the daily restart of the IMPL and PROD ECS services to include the lambda function name. This change is needed due to a recent refactoring of the deploy_service script (https://github.com/CMSgov/easi-app/pull/786).
=> Update deploy_service call for daily restart jobs

.circleci/config.yml
- Use the dockerized ecs-manager Lambda function in IMPL and PROD
=> Use ecs-manager-docker - impl, prod

cypress/integration/businessCase.spec.js, cypress/support/businessCase.js, migrations/V72__Add_Other_Lifecycle_Cost_Phase_Type.sql, pkg/models/business_case.go, pkg/testhelpers/business_case.go, src/components/EstimatedLifecycleCost/Review/index.test.tsx, src/components/EstimatedLifecycleCost/Review/index.tsx, src/components/EstimatedLifecycleCost/index.tsx
- Adds a third phase, "Other", to lifecycle cost phases
=> Add "Other" lifecycle cost phase

src/utils/systemIntake.ts, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionB.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx
- Changed business case functionality to not display the "all fields are mandatory" alert when the business case is in draft
=> Business case mandatory fields alert fix

src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx
- fields that get into emails upped to 3k characters
=> EASI-1110 3k chars for email fields

src/utils/user.ts
This PR reverts the work we did to allow 508 test our application without job codes
=> re-enable 508 job codes

package.json, src/reducers/authReducer.test.ts, src/reducers/authReducer.ts, src/sagas/actionSaga.ts, src/sagas/businessCaseSaga.ts, src/sagas/businessCasesSaga.ts, src/sagas/searchSaga.ts, src/sagas/systemIntakeSaga.ts, src/sagas/systemIntakesSaga.ts, src/views/TimeOutWrapper/index.tsx, yarn.lock
- Use better event tracking to make sure we don't prompt users prematurely
=> Sb 1092 keep user session alive

src/views/Accessibility/AccessibilityRequestDetailPage.tsx
=> add role alert to 508 details confirmation

pkg/email/intake_review_test.go, pkg/email/issue_lcid_test.go, pkg/email/reject_request_test.go, pkg/email/templates/issue_lcid.gohtml, pkg/email/templates/reject_request.gohtml, pkg/email/templates/system_intake_review.gohtml
- Use html preformatted section, with line wrapping, when sending GRT-supplied info in email
=> EASI-1110 email preformat and wrapping

src/types/flags.ts, src/views/App/index.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionB.tsx, src/views/BusinessCase/AsIsSolution/index.tsx, src/views/BusinessCase/Confirmation/__snapshots__/index.test.tsx.snap, src/views/BusinessCase/Confirmation/index.test.tsx, src/views/BusinessCase/Confirmation/index.tsx, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx, src/views/FlagsWrapper/index.tsx, src/views/Home/SystemIntakeBanners.tsx, src/views/RequestTypeForm/index.tsx, src/views/SystemIntake/Confirmation/index.tsx, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/ContractDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx
Task List is deployed to prod 🎉
=> Remove task list lite flag

src/views/App/index.tsx
=> Revert "re-organize application routes"

src/views/Login/index.tsx
- Redirect a user after login if a redirect param exists
=> Redirect to the redirect param after login if one exists.

src/utils/user.ts, src/views/Accessibility/index.tsx, src/views/App/index.tsx, src/views/GovernanceReviewTeam/index.test.tsx, src/views/GovernanceReviewTeam/index.tsx, src/views/Home/index.tsx
- Move the conditional logic for returning pages into the components themselves
- Set a pattern-ish for how we show/hide pages
- Implement a stupid loading component for now
=> Sb 1109 change route draw

migrations/V74__Remove_LCID_Next_Steps_From_Intake.sql, pkg/handlers/system_intake.go, pkg/handlers/system_intakes_test.go, pkg/models/system_intake.go, pkg/services/system_intakes.go, src/sagas/systemIntakeSaga.ts, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx
- Replaced remnants of deprecated LCID next steps with decision next steps to properly store value in case of LCID issued
- DB migration to move all remaining lcid_next_steps data to decision_next_steps and remove lcid_next_steps from DB
=> Fixed LCID next steps

docs/adr/0026-cedar-data-definition.md, docs/adr/index.md
- document how we will be interacting with the new CEDAR API
=> EASI-1134 adr for cedar changes

README.md, docker-compose.override.yml
- Update the Prince XML Lambda instructions in the README
=> Docker-compose and readme updates for prince

package.json, yarn.lock
=> update react-uswds to v1.13.2

src/views/App/index.tsx, src/views/User/index.tsx
- Add a user-diagnostics page to learn more about a user's groups
=> Add user diagnostics page for getting info about job codes.

src/views/User/index.tsx
=> add claims to user page

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go
- Add business case to the graph schema
=> Sb add business case to schema

.circleci/config.yml
- Update the ecs-manager-docker versions in impl and prod. This change is similar to https://github.com/CMSgov/easi-app/pull/868 and will update the CircleCI config to use a newer version of the ecs-manager-docker lambda image that doesn't include dev dependencies.
=> Update ecs-manager-docker versions - impl, prod

.circleci/config.yml
- Version bump for scripts using ecr-scan-findings lambda to coincide with https://github.com/CMSgov/easi-infra-modules/pull/54
=> Version change for scripts calling ecr-scan-findings

src/hooks/useConfirmationText.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/AccessibiltyRequest/Create/index.tsx, src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx, src/views/Accessibility/index.tsx, src/views/TestDate/index.tsx
- Move common headers to the main 508 page
- Modify our confirmation text hook to clear text on the next page visit
=> Sb move common page elements

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go, src/queries/UpdateSystemIntakeAdminLeadQuery.ts, src/queries/types/UpdateSystemIntakeAdminLead.ts, src/types/graphql-global-types.ts, src/views/GovernanceReviewTeam/RequestOverview.tsx, src/views/GovernanceReviewTeam/Summary/index.test.tsx, src/views/GovernanceReviewTeam/Summary/index.tsx
- Use a mutation for admin lead
=> Sb admin mutation

src/components/Modal/index.tsx, src/components/PageHeading/__snapshots__/index.test.tsx.snap, src/components/PageHeading/index.scss, src/components/PageHeading/index.tsx, src/views/BusinessCase/Confirmation/__snapshots__/index.test.tsx.snap, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/GovernanceTaskList/SideNavActions/index.tsx, src/views/NotFound/__snapshots__/index.test.tsx.snap, src/views/SystemIntake/ViewOnly/index.tsx, src/views/TermsAndConditions/__snapshots__/index.test.tsx.snap
This PR focuses the heading in the withdraw intake modal
=> Focus withdraw intake modal heading

src/views/GovernanceReviewTeam/Actions/ChooseAction.tsx, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/BusinessCaseReview/index.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx, src/views/GovernanceReviewTeam/Decision/index.tsx, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/IntakeReview/index.tsx, src/views/GovernanceReviewTeam/Notes/index.tsx, src/views/SystemIntake/Confirmation/index.tsx, src/views/UnsupportedBrowser/index.tsx, src/views/User/index.tsx
I missed all the GRT `h1` headings. Updating all `h1`'s to `PageHeading` so that they can be read on assistive technology.
=> update h1 to PageHeading

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go
- Expose admin notes in the GraphQL API
- Future work will update the UI to load the notes in this way.
=> Add notes to graph.

.circleci/config.yml
- update ecs-manager-docker to latest version
=> update ecs-manager-docker to latest version

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/storage/system_intake.go, pkg/storage/system_intake_test.go, src/queries/GetSystemIntakeQuery.ts, src/queries/UpdateSystemIntakeReviewDatesQuery.ts, src/queries/types/GetSystemIntake.ts, src/queries/types/UpdateSystemIntakeReviewDates.ts, src/types/graphql-global-types.ts, src/views/GovernanceReviewTeam/Dates/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx
- Use a query mutation to update review dates
=> Sb dates mutation

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/resolver.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/server/routes.go, pkg/services/action.go, pkg/storage/system_intake.go, src/queries/CreateSystemIntakeActionNotItRequest.ts, src/queries/types/CreateSystemIntakeActionNotItRequest.ts, src/types/graphql-global-types.ts, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx, src/views/GovernanceReviewTeam/Actions/SubmitActionDeprecated.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx
- Move not an it request to a mutation pattern
=> Sb 1145 not it request as mutation

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/resolver.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/server/routes.go, src/queries/IssueLifecycleIdQuery.ts, src/queries/types/IssueLifecycleId.ts, src/queries/types/UpdateSystemIntakeAdminLead.ts, src/types/graphql-global-types.ts, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx
- Replace issue LCID call with a mutation
=> Sb issue lcid mutation

pkg/graph/generated/generated.go, pkg/graph/resolver.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/server/routes.go, src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/components/BusinessCaseReview/index.tsx, src/components/GRTFeedbackView/index.tsx, src/i18n/en-US/businessCase.ts, src/index.tsx, src/queries/GetGRTFeedbackQuery.ts, src/queries/GetSystemIntakeQuery.ts, src/queries/types/GetGRTFeedback.ts, src/queries/types/GetSystemIntake.ts, src/types/graphql-global-types.ts, src/views/BusinessCase/ViewOnly/index.tsx, src/views/BusinessCase/index.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTFeedbackToBusinessOwner.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTRecommendationsToGRB.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx
- Business Owner and Review Team can see business owner feedback below business cases
=> View GRT Feedback

cmd/devdata/main.go, src/queries/GetAdminNotesQuery.ts, src/queries/types/GetAdminNotes.ts, src/types/systemIntake.ts, src/views/GovernanceReviewTeam/Notes/index.tsx
- Load admin notes via GraphQL
- Display an alert when notes loading fails for some reason
=> ES-1140 - Load notes from graph

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/resolver.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/server/routes.go, src/queries/RejectIntakeQuery.ts, src/queries/types/RejectIntake.ts, src/types/graphql-global-types.ts, src/views/GovernanceReviewTeam/Actions/RejectIntake.tsx
- Reject intake uses a mutation
=> Sb reject intake

src/views/SystemIntake/ContractDetails/index.tsx
Fix radio button contracting question reading behavior on assistive technology
=> add proper radio button name to contract question

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, src/queries/CreateSystemIntakeNoteQuery.ts, src/queries/types/CreateSystemIntakeNote.ts, src/types/graphql-global-types.ts, src/views/GovernanceReviewTeam/Notes/index.tsx
- Transfer create note to a mutation
=> Sb create note mutation

cmd/devdata/main.go
This is the first of a series of improvements we are going to make to the devdata to make it more useful and accurate.
=> Align devdata with data generated by real user flows.

src/views/SystemIntake/ContractDetails/index.tsx
- Modified intake funding question formatting to improve accessibility based on feedback from Monica seen here:
=> Slightly modified formatting of intake funding question

src/views/GovernanceReviewTeam/Summary/index.tsx
=> misc changes and fix radio focus issues

src/views/SystemIntake/ContactDetails/index.tsx
Adds checkbox to make the product manager fields to match the requester
=> add checkbox to make product manager same as requester

src/components/EstimatedLifecycleCost/index.tsx
This PR moves some definitions (dl/dd/dt) into a single definition list for better assistive technology reading.
=> move phase definitions into one definition list

src/components/AccessibilityDocumentsList/index.tsx, src/components/AccessibilityRequestsTable/index.tsx, src/components/BusinessCaseReview/index.tsx, src/components/EstimatedLifecycleCost/index.tsx, src/components/SystemIntakeReview/index.tsx, src/components/TestDateCard/index.tsx, src/data/systemIntake.ts, src/utils/date.test.ts, src/utils/date.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/index.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx, src/views/GovernanceReviewTeam/Summary/index.tsx
- Remove the default export from our date utils
- Rename formatDate to date
- Add a new util for parsing ISO times from the API
=> Sb convert to dates

pkg/cedar/intake/cedar_intake.yml, pkg/cedar/intake/gen/client/c_e_d_a_r_intake_client.go, pkg/cedar/intake/gen/client/operations/health_check_get_responses.go, pkg/cedar/intake/gen/client/operations/intake_add_responses.go, pkg/cedar/intake/gen/client/operations/operations_client.go, pkg/cedar/intake/gen/models/health_check_response.go
- Don, of the CEDAR team, made some minor tweaks to the API
=> EASI-1134 api updates

src/components/RequestRepository/index.tsx, src/components/shared/TruncatedText/index.tsx, src/i18n/en-US/intake.ts, src/views/GovernanceReviewTeam/index.tsx, src/views/Home/index.tsx
- Added new component (TruncatedText) that allows for longer text fields to be displayed w/ a button to expand and unexpand the text if the user desires
- Modified the columns. Removed request type and funding number. Added LCID expiration date and last admin note. Added LCID scope to status column (where applicable i.e. LCID has been issued)
=> Request Repository Column Changes

src/views/SystemIntake/ContractDetails/index.tsx
EASI-1096
- Moved help text link to under funding number
- Removed aria label from help text link
=> Funding Source Accessibility Changes

src/validations/actionSchema.ts
- Changed LCID validation schema to allow for current LCID formats I6 digits) and legacy formats (6 digits w/ preceding character)
=> LCID validation fix

cypress/integration/systemIntake.spec.js, src/components/SystemIntakeReview/index.tsx, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap, src/views/SystemIntake/ContactDetails/index.tsx
- Change business owner labels from CMS Business/Product Owner to just CMS Business Owner
=> Update business owner field labels in the system intake form

src/i18n/en-US/action.ts
- Changed language for governance team actions to match their feedback
=> Modified wording of governance team actions

cypress/integration/systemIntake.spec.js, src/components/SystemIntakeReview/index.tsx, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap
- Changed Business Owner Component to CMS Business Owner Component in system intake review
=> Modified business owner component text

graphql-schema-linter.config.js, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, src/types/graphql-global-types.ts
- After relaxing the schema linter rules in a previous PR, this removes some of the useless comments.
=> Remove unnecessary comments in gql schema

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/models/system_intake.go, src/types/graphql-global-types.ts
- We're not using the ACCEPTED intake status, and since migration V48, it shouldn't appear anywhere in the database.
=> Remove outdated ACCEPTED status

src/components/shared/DateInput/index.tsx, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx
This PR:
- Updates some forms to use the Date components we have
- Updates the Date components to have screen reader help text for each field
=> Add help text for date fields

src/data/taskList.ts, src/i18n/en-US/taskList.ts, src/views/GovernanceTaskList/RequestDecision/index.tsx, src/views/GovernanceTaskList/TaskListCta.tsx, src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx
- Modified task list when status is NOT_IT_REQUEST or NO_GOVERNANCE
- Fix for bug where Business Case Not Approved would incorrectly be displayed as the decision
- Task list will now have an alert banner at the top when those decisions are made notifying users of decision and informing them to check email for more info
=> Closed request task list fixes

.github/PULL_REQUEST_TEMPLATE.md
- Add a more robust PR template!
=> Add more to our PR template

pkg/server/routes.go, pkg/services/auth.go, pkg/services/auth_test.go, pkg/services/notes_test.go, pkg/services/system_intakes_test.go
- Consolidates some simple role-based-authorization
- Change 2
=> Consolidate some role auth

src/components/RequestRepository/index.tsx, src/i18n/en-US/intake.ts, src/views/GovernanceReviewTeam/Summary/index.tsx, src/views/SystemIntake/ContactDetails/index.tsx
- Added i18n translation to the contact details form in the system intake
=> Modified contact details form in system intake to use i18n

src/utils/user.test.ts, src/utils/user.ts, src/views/Accessibility/index.tsx, src/views/FlagsWrapper/index.tsx, src/views/GovernanceReviewTeam/index.tsx, src/views/Home/index.tsx, src/views/User/index.tsx
- Allow us to turn off certain job codes at the environment level
Eventually, we'll be able to do this at the user level, but this gets us closer to the goal than we are now
=> Downgrade permissions on an environment level

src/views/Accessibility/index.tsx
- Make sure the appropriate routes are open to users without the 508 job codes
It looks like we didn't actually guard the API for some of these things....
The routes you need for testing: /508/requests/new and /508/requests/:uuid
=> Reconfigure routes on page so that some are available without the 508 job code

src/types/flags.ts, src/utils/user.ts, src/views/User/index.tsx
- Add more debugging info for our LD flags
- More robust type definition in case that's causing the issue of flags not being read
=> Sb add more debugging

src/views/Accessibility/index.tsx
=> Reorder routes so child URLs come first

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/services/auth.go, src/views/TestDate/NewTestDate.tsx
- Make sure we see errors when trying to add test dates
- Add a new role for 508 user or tester
=> Sb 549 api auth check

pkg/graph/schema.resolvers.go, src/views/Accessibility/AccessibiltyRequest/Documents/New/index.tsx
- Add an auth check for users uploading docs
This is basically impossible to test because the doc uploads page won't even load. I think this check is a good one to have at the graph level, but real-world users should never get to this point.
=> Sb 498 biz owner upload docs

migrations/V79__Deleted_At_Colunn_Accessibility_Request.sql, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/accessibility_request.go, pkg/services/auth.go, pkg/storage/accessibility_request.go, src/i18n/en-US/accessibility.ts, src/queries/AccessibilityRequestQueries.ts, src/queries/types/DeleteAccessibilityRequest.ts, src/types/graphql-global-types.ts, src/views/Accessibility/AccessibilityRequestDetailPage.tsx, src/views/Accessibility/AccessibiltyRequest/Create/index.tsx
- A request owner can now delete their request
=> A biz owner can delete their 508 request

scripts/dev
=> This is ruby. Not javascript.

src/components/StepList/index.scss, src/components/StepList/index.stories.tsx, src/components/StepList/index.test.tsx, src/components/StepList/index.tsx
This PR adds Step List with sub components:
1. `StepList`
2. `Step`
3. `StepHeading`
4. `StepBody`
- includes tests
- includes storybook story
Test by running `yarn storybook` and viewing the corresponding story
=> add step list component

src/components/Header/index.tsx, src/i18n/en-US/header.ts, src/types/flags.ts, src/views/FlagsWrapper/index.tsx
- Add a new link to create a 508 request in the user dropdown
- Add a feature flag for the link
Make sure that the feature flag is toggled appropriately for the environment you're testing in, and also that you can access LaunchDarkly in that environment. The default for the flag is false.
=> Sb 564 add 508 link user dropdown

pkg/storage/store.go
- Pull the SSL mode for the database connection from the config struct so that the SSL mode can be set dynamically and enabled in the deployed environments.
=> Pull the db sslmode from the config object

pkg/storage/store.go
Set the database adapter to only open 90 connections.
=> set max connections to 90

.circleci/config.yml, .envrc, docker-compose.yml, pkg/appconfig/config.go, pkg/email/email.go, pkg/email/new_accessibility_request.go, pkg/email/templates/new_508_request.gohtml, pkg/graph/resolver.go, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/server/config.go, pkg/server/routes.go
- Emails the 508 team when a new 508 request is added
=> Send email on new 508 request

.github/PULL_REQUEST_TEMPLATE.md
- Separate check lists to make it clear who is responsible for which bits
- Add some additional bits per guidance from design
- Do we need to break the rotor menu how-to into a different part of the docs? I don't know where to put it.
=> Update the template for clarity on roles.

.envrc
- Set PGPASSWORD in .envrc. In https://github.com/CMSgov/easi-app/pull/1021, we added a POSTGRES_PASSWORD for the local postgres container. Adding PGPASSWORD in .envrc is needed to make it easier to work with other tools (e.g., psql) locally.
A before image is optional and can …
=> Set PGPASSWORD in .envrc

src/components/AccessibilityNotes/index.scss, src/components/AccessibilityNotes/index.stories.tsx, src/components/AccessibilityNotes/index.tsx
- Adds component in storybook to view 508 notes
The props for this component may not be in quite the right format for its eventual use. It should be easy to change that to fit our needs when we start using this component. 
`yarn storybook`
A before image is optional and can be …
=> storybook component to view 508 notes

pkg/storage/my_requests_test.go
=> Add reason for this deletion.

src/views/GovernanceTaskList/index.tsx
Minor update to Task List copy
=> update missing word in task list copy

src/i18n/en-US/accessibility.ts, src/views/Accessibility/TestingTemplates/__snapshots__/index.test.tsx.snap
- Adds missing VPAT compliance item "Not Applicable"
- Fixes typo
Addresses comments regarding copy errors found during acceptance
As a business owner, go to `508/templates`
Consider using an animated …
=> Add missing copy and fix typo in templates page

docker-compose.override.yml
Remember how happy you were when #873 got merged? Well, we gotta do it again for the Docker-ized version.
=> Disable eslint development errors locally

.golangci.yml, pkg/email/issue_lcid_test.go, pkg/graph/schema.resolvers.go, pkg/server/gqllogging.go, pkg/services/business_case.go
- Enables the Staticcheck linter
_Please frame images to show useful context but also …
=> Enable staticcheck linter

pkg/services/auth.go
- Simplifies an authorizer for the 508 team
=> Simplify authorizer for 508 team

.golangci.yml, .pre-commit-config.yaml, README.md, pkg/email/issue_lcid_test.go, pkg/graph/schema.resolvers.go, pkg/server/gqllogging.go, pkg/services/business_case.go, pkg/storage/business_case.go, pkg/storage/system_intake_test.go, pkg/storage/system_test.go, pkg/testhelpers/rand.go
- Upgrades golangci-lint from 1.24 to 1.40
=> Upgrade golangci-lint

.circleci/config.yml
- add test code coverage to frontend in CI
=> add test code coverage to frontend

docker-compose.yml, src/i18n/en-US/home.ts, src/views/MyRequests/Table.tsx, src/views/MyRequests/index.tsx
- Add a table to the my requests page!
- You're going to need a few requests created specifically by your user for anything to show up on this page. Add some 508 requests! Add an intake or two! I also recommend starting an intake and only getting through page 1 of the form to see what an incomplete state looks like for an intake.
=> Sb 504 my requests table

.golangci.yml, pkg/appconfig/config.go, pkg/appconfig/config_test.go, pkg/handlers/catch_all.go, pkg/okta/okta_test.go, pkg/server/gqllogging.go, pkg/validate/types.go
- Enables `gosimple` and `unused` linters
=> Turn on go linters

src/views/Accessibility/AccessibilityRequestDetailPage.tsx
It's a loud PR so let me describe what happened
- Add BreadCrumb nav
- Remove "horizontal nav" thing
- By removing the horizontal nav, we can remove the Fragment that wraps the entire view.
=> add breadcrumbs to 508 request details page

src/views/Home/index.scss, src/views/Home/index.test.tsx, src/views/Home/index.tsx
- Add a horizontal rule and the requests table to the homepage
=> Sb 607 request on homepage

src/utils/user.test.ts, src/utils/user.ts
- If we've downgraded all permissions, treat a user like a "basic" user
=> Update logic for basic user

src/components/ScyllaPage/index.tsx
don't think we're using this. byeeeeee
=> remove ScyllaPage component

.circleci/config.yml, cmd/easi/test/test.go, scripts/testsuite
- add backend code coverage metrics to tests.
- [ x] Met the acceptance criteria, or will meet them in a subsequent PR
=> Back-end code coverage

pkg/email/templates/new_508_request_to_requester.gohtml
Adds survey link to 508 request creation confirmation email
=> Add 508 request creation confirmation survey link to email

package.json
- add Jest configuration to package.json for front-end Code Coverage.
=> Add front-end code coverage threshold

.circleci/config.yml, .envrc, cmd/devdata/main.go, docker-compose.yml, pkg/appconfig/config.go, pkg/graph/schema.resolvers_test.go, pkg/integration/integration_test.go, pkg/server/config.go, pkg/services/services_test.go, pkg/storage/store.go, pkg/storage/store_test.go
- Make the Max DB connections value an environment variable
=> Make Max DB connections an environment variable

src/i18n/en-US/accessibility.ts, src/views/Accessibility/AccessibilityRequest/Create/index.tsx
- Remove most fields on the create request form
- Update the content to match the latest design
- Default the name of the request to the name of the system
=> Sb 668 simplified request form

src/views/Home/index.tsx
Update home page business owner view Section 508 link to navigate to `/508/testing-overview?continue=true`
=> update home page entry point to 508 flow

src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/BusinessCase/Review/ProposedBusinessCaseSolutionReview.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap
- Added IT security questions and answers to business case review
=> Added IT security questions and answers to business case review

docs/adr/0027-code-coverage.md, docs/adr/index.md
- Adds an ADR for the initial approach to adding code coverage thresholds in CI
=> Add code coverage ADR

.circleci/config.yml
- update version of ecs-manager-docker to latest pushed version
- https://github.com/CMSgov/easi-infra-modules/commit/199fa1a58e2c16fb5ccf4feb5245a75cfb4ceb9d
=> ES-681 update ecs-manager version

package.json, yarn.lock
- Update ReactUSWDS to 1.17.0
Currently our main usage with ReactUSWDS is for `Link` and `Button` components. Those look fine.
The most **critical** component is `ComboBox`. That also appears to be fine.
I didn't realize how little we were leveraging ReactUSWDS. Subsequent PRs to come so we aren't doing as much on our own.
**Please check for regressions, especially ComboBox**
=> Update ReactUSWDS to 1.17.0

src/i18n/en-US/accessibility.ts, src/views/Accessibility/TestingTemplates/__snapshots__/index.test.tsx.snap, src/views/Accessibility/TestingTemplates/index.tsx
- Opens Templates Page PDFs in a new tab
=> Open PDFs in new tab

src/components/AccessibilityDocumentsList/index.stories.tsx, src/components/AccessibilityDocumentsList/index.tsx, src/components/TestDateCard/index.stories.tsx, src/utils/accessibilityRequest.ts, src/views/Accessibility/AccessibilityRequest/Documents/New/index.tsx, src/views/Accessibility/AccessibilityRequestDetailPage.tsx
- Fixes AccessibilityDocumentList and TestDateCard storybook stories
=> Fix broken storybook stories

cypress/integration/accessibility.spec.js, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/storage/requests.go, pkg/storage/requests_test.go, src/i18n/en-US/accessibility.ts, src/i18n/en-US/home.ts, src/i18n/en-US/intake.ts, src/queries/GetRequestsQuery.ts, src/queries/types/GetRequests.ts, src/views/MyRequests/Table.test.tsx, src/views/MyRequests/Table.tsx
- Add statuses to the combined requests query
- Show the statuses on the business owner homepage table
Yo. This custom SQL is more complicated than anything I have ever written. Please let me know if something looks real wonky.
=> Sb 705 status for biz owners

package.json
This PR removes storybook stories from our test coverage reporting.
=> remove storybook stories from code coverage

.circleci/config.yml
- update prod-ecs-manager-docker version
=> update prod-ecs-manager-docker version

.circleci/config.yml, Dockerfile.client, Dockerfile.client_circleci
- update to latest circleCI image
- update node to 12.22.1
=> Update node to 12.22.1 in circleCI

.circleci/config.yml
- update easi-app circle ci image to latest
- pre-commit 2.13.0 update.
=> Update easi-app CircleCI image to latest

cypress/integration/systemIntake.spec.js, cypress/integration/taskList.spec.js, pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_system_intake_test.go, pkg/handlers/system_intake.go, pkg/handlers/system_intake_test.go, pkg/integration/system_intakes_test.go, pkg/server/routes.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go, src/queries/SystemIntakeQueries.ts, src/queries/types/CreateSystemIntake.ts, src/reducers/systemIntakeReducer.test.ts, src/reducers/systemIntakeReducer.ts, src/sagas/systemIntakeSaga.ts, src/types/graphql-global-types.ts, src/types/routines.ts, src/views/GovernanceTaskList/index.tsx, src/views/RequestTypeForm/index.tsx, src/views/SystemIntake/index.tsx
- Migrate creating an intake to use a graphql mutation
=> Create intake using graphql

src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/ContractDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx
One of the quietly major changes was introduced  in `v2.9.0`. Here is the [changeset](https://github.com/uswds/uswds/pull/3638/files). The offending file is `src/stylesheets/elements/form-controls/_checkbox-and-radio.scss`.
They changed `margin-bottom` to `margin-top`. This means there's too much margin on top and too little margin on the bottom.
This PR is mainly adding/subtracting margins.
=> Update Intake Form Radio/Checkbox spacing

src/components/EstimatedLifecycleCost/index.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionFields.tsx, src/views/BusinessCase/PreferredSolution/index.tsx
One of the quietly major changes was introduced  in `v2.9.0`. Here is the [changeset](https://github.com/uswds/uswds/pull/3638/files). The offending file is `src/stylesheets/elements/form-controls/_checkbox-and-radio.scss`.
They changed `margin-bottom` to `margin-top`. This means there's too much margin on top and too little margin on the bottom.
This PR is mainly adding/subtracting margins.
=> Update Business Case Radio/Checkbox spacing

src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx
One of the quietly major changes was introduced  in `v2.9.0`. Here is the [changeset](https://github.com/uswds/uswds/pull/3638/files). The offending file is `src/stylesheets/elements/form-controls/_checkbox-and-radio.scss`.
They changed `margin-bottom` to `margin-top`. This means there's too much margin on top and too little margin on the bottom.
This PR is mainly adding/subtracting margins.
=> Update GRT view for radio/checkbox spacing

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/storage/requests.go, pkg/storage/requests_test.go, src/queries/GetRequestsQuery.ts, src/queries/types/GetRequests.ts, src/views/MyRequests/Table.test.tsx, src/views/MyRequests/Table.tsx
- Add LCID to the status column if one exists
=> Sb 723 lifecycle id for biz owner

src/i18n/en-US/accessibility.ts, src/views/Accessibility/AccessibilityRequest/Documents/New/index.tsx
- Only allows pdf, docx, and xlsx to be uploaded
=> lock down allowed upload filetypes

src/i18n/en-US/home.ts, src/views/Home/WelcomeText.tsx
Update home page for logged out user
=> update home page

.circleci/config.yml
- update check_ecr_findings version 5<6
=> update check_ecr_findings version

src/i18n/en-US/governanceReviewTeam.ts
- Removed Surya Potu
- Added Kyle Miller
=> Modified gov team admin member list

pkg/storage/requests.go, pkg/storage/requests_test.go
- Fix a bug where a request was showing once per status record associated with it
=> Only join the one status we care about.

pkg/email/change_508_status.go, pkg/email/email.go, pkg/email/templates/change_508_status.gohtml, pkg/graph/schema.resolvers.go
- When the status of a 508 request is changed, email the 508 team. 
=> Send email on status change

.gitignore, docs/operations/metrics.md
- Updating the Metrics readme with simplified instructions
*No code changes, so the below is not applicable.*
=> Update metrics readme to be a little easier to use

src/views/User/index.tsx
- Pass the flags to the basic user util for the diagnostics page
=> Make sure we're passing the flags to the util

src/i18n/en-US/accessibility.ts, src/i18n/en-US/intake.ts, src/i18n/en-US/makingARequest.ts, src/views/Accessibility/AccessibilityRequest/Create/index.tsx, src/views/Accessibility/MakingARequest/index.tsx, src/views/GovernanceTaskList/RequestDecision/index.tsx, src/views/MakingARequest/__snapshots__/index.test.tsx.snap, src/views/PrepareForGRB/index.tsx, src/views/PrepareForGRT/index.tsx
- FIxed governance team email address in several locations
=> Fixed governance team email addresses

src/components/RequestRepository/index.tsx, src/i18n/en-US/intake.ts, src/views/MyRequests/Table.test.tsx, src/views/MyRequests/Table.tsx
- Use a more descriptive human-readable status.
=> Use a more descriptive human-readable status for LCID

cmd/devdata/main.go, cypress/integration/accessibility.spec.js, src/components/TestDateCard/index.tsx
- add tests for adding, updating, and deleting 508 test dates
- add dev data for 508 test date
=> Add cypress test for adding, updating, and deleting 508 test date

docs/operations/metrics.md, pkg/models/accessibility_request.go, pkg/models/metrics.go, pkg/server/routes.go, pkg/services/metrics.go, pkg/services/metrics_test.go, pkg/storage/accessibility_request.go, pkg/storage/accessibility_request_test.go
- Adds metrics to find number of accessibility requests created in a given time frame. 
Follow the instructions in metrics.md. I am curious whether changes I made there are clear
=> add first metrics for accessibility requests

cypress/integration/accessibility.spec.js
We previously already had a test to add a note. I updated it to check the relevant information.
=> add cypress test for adding a note

src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.tsx, src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTFeedbackToBusinessOwner.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTRecommendationsToGRB.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx, src/views/TestDate/Form.tsx
Added mandatory fields info for the following forms
```
/governance-review-team/:id/dates
/governance-review-team/:id/actions/issue-lcid
/governance-review-team/:id/actions/ready-for-grb
/governance-review-team/:id/actions/provide-feedback-need-biz-case
/governance-review-team/:id/actions/issue-lcid
/508/requests/:id/test-date
```
=> Add mandatory fields info to forms

src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/components/Header/index.tsx, src/components/PDFExport/index.tsx, src/types/flags.ts, src/views/FlagsWrapper/index.tsx, src/views/GovernanceReviewTeam/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap, src/views/Home/index.test.tsx, src/views/Home/index.tsx
This PR cleans up some of our LD flags.
**STILL NEED TO REMOVE FLAGS IN LD UI AFTER THIS PR IS MERGED**
=> remove old ld flags that we don't need anymore

.github/PULL_REQUEST_TEMPLATE.md
Added items to the developer checklist and the reviewer checklist to remind us to write and look for adequate tests.
I'm totally open to edits!
=> Add checklist items for testing to develop and reviewer lists

.envrc, .spelling, README.md, scripts/dev
This PR updates the documentation to reflect the current developer setup process.
- Update the README
- Add or adjust default environment variables to allow for a fresh clone of the app to boot up locally
[I created a new story](https://jiraent.cms.gov/browse/ES-785) to add additional documentation about configuring Launch Darkly and Okta.
I recommend cloning the git repo to a new directory and attempting to run through the app setup. If you can get the app to start and login with local auth, that is success.
=> ES-729 readme update

cypress/integration/governanceReviewTeam.spec.js, src/components/NotesList/index.tsx, src/views/GovernanceReviewTeam/Notes/index.tsx
This PR adds a Cypress test for the gov team adding new admin notes.
=> add cypress test for adding gov team notes

src/views/PrepareForGRB/__snapshots__/index.test.tsx.snap, src/views/PrepareForGRB/index.test.tsx, src/views/PrepareForGRT/__snapshots__/index.test.tsx.snap, src/views/PrepareForGRT/index.test.tsx
This PR adds tests for the "Prepare for GRT" and "Prepare for GRB" information pages. These tests are minimal because it's just static content/information to help the user understand the process.
=> add tests for prepare for grt/grb pages

src/views/Accessibility/AccessibilityRequest/Create/index.test.tsx, src/views/Accessibility/AccessibilityRequest/Create/index.tsx
This PR adds test for the 508 request create page.
This PR tests the main functionality of the page, but the coverage report isn't reporting the `onChange` of the `ComboBox` being tested. I'm not sure why, but it's a 7 line discrepancy so I don't want to get caught in that rabbit hole.
=> add tests to create 508 request page

pkg/email/new_accessibility_request_note.go, pkg/email/new_document.go
- Followup story for separating notes/documents URLs. Changes links in emails to match new patterns.
=> Change email links for notes/documents

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_system_intake_test.go, src/components/shared/AutoSave/index.tsx, src/queries/SystemIntakeQueries.ts, src/queries/types/UpdateSystemIntakeContactDetails.ts, src/queries/types/UpdateSystemIntakeRequestDetails.ts, src/types/graphql-global-types.ts, src/views/SystemIntake/RequestDetails/index.tsx, src/views/SystemIntake/index.tsx
- Convert the main request details page to a graph mutation
- Still need to fix some unit tests
- Autosave isn't working properly, so that needs to be addressed in a future PR
=> Sb gql intake form page 2

src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.test.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionB.test.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionB.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionFields.test.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionFields.tsx, src/views/BusinessCase/PreferredSolution/index.test.tsx, src/views/BusinessCase/Review/index.tsx
This PR adds unit test for the business case alternative solutions
=> add tests for business case alternative solutions

src/queries/UpdateSystemIntakeReviewDatesQuery.ts, src/queries/types/UpdateSystemIntakeReviewDates.ts, src/views/GovernanceReviewTeam/Actions/SubmitAction.test.tsx, src/views/GovernanceReviewTeam/Actions/SubmitAction.tsx, src/views/GovernanceReviewTeam/Dates/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.test.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx, src/views/GovernanceReviewTeam/index.tsx
There are different mutations that execute in `SubmitAction` depending on which URL/action a user selects. These tests exist to make sure that the correct mutations are running.
=> add tests to make sure the correct mutation is firing for SubmitAction

src/views/GovernanceReviewTeam/Actions/ProvideGRTFeedbackToBusinessOwner.test.tsx, src/views/GovernanceReviewTeam/Actions/ProvideGRTFeedbackToBusinessOwner.tsx
This PR tests `src/views/GovernanceReviewTeam/Actions/ProvideGRTFeedbackToBusinessOwner.tsx`.
It tests the mutation and route combinations that are passed to the component in `src/views/GovernanceReviewTeam/RequestOverview.tsx`.
=> test provide grt feedback to business owner

.pre-commit-config.yaml
- add git secrets to pre-commit
- pinning to commit https://github.com/awslabs/git-secrets/commit/80230afa8c8bdeac766a0fece36f95ffaa0be778
- pinning because there has not been an actual release since 2019.
=> add git secrets to pre-commit

.circleci/config.yml
- Update CircleCI roll name
- https://github.com/CMSgov/easi-infra-modules/pull/122
=> change circleci role name

src/queries/SystemIntakeQueries.ts, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/GovernanceOverview/index.tsx, src/views/GovernanceTaskList/index.tsx, src/views/RequestTypeForm/index.test.tsx, src/views/RequestTypeForm/index.tsx, src/views/SystemIntake/index.tsx
This PR adds tests for filling out a intake request type.
`/system/request-type`
=> add tests for filling out intake request type

cypress/integration/accessibility.spec.js
- Adds a cypress test for changing the status of a 508 request.
=> Add cypress test for changing 508 status

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_system_intake_test.go, src/queries/SystemIntakeQueries.ts, src/queries/types/UpdateSystemIntakeContractDetails.ts, src/types/graphql-global-types.ts, src/types/systemIntake.ts, src/views/SystemIntake/ContractDetails/index.tsx, src/views/SystemIntake/index.tsx
- Mutation and such for the third page of the system intake form
Still to come:
- Fixing validations
- Fixing auto-save
- Fix the review page
=> Sb gql intake form page 3

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/resolver.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_system_intake_test.go, pkg/graph/schema.resolvers_test.go, pkg/server/routes.go, src/queries/SystemIntakeQueries.ts, src/queries/types/submitIntake.ts, src/types/graphql-global-types.ts, src/views/SystemIntake/Review/index.tsx, src/views/SystemIntake/index.tsx
- Review page using graphql to submit intake
- Remove some REST queries for the system intake
- Remove action support for the submit intake action
Still to come:
- Validations cleanup
- Autosave
- Fixing tests
=> Sb gql intake form review

.github/workflows/rescan_deployed_image.yml, scripts/check_deployed_image_findings
- Convert the rescan_deployed_image CircleCI job to a GitHub Action workflow.
- changes to check_deployed_image_findings to accommodate github actions
=> github actions rescan_deployed-image

src/views/GovernanceTaskList/SideNavActions/index.tsx, src/views/GovernanceTaskList/TaskListItem.tsx, src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx
- Convert governance task list tests to react testing library
- Hoping this will make it easier to fix tests in the graphql cutover branch
=> Sb tests to react library

src/views/GovernanceTaskList/index.tsx, src/views/SystemIntake/ContactDetails/GovernanceTeamOptions.tsx, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/ContractDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx, src/views/SystemIntake/index.tsx
- Fix autosave (thanks, Chris!)
To come in a future PR:
- fix unit tests
=> Fix autosave.

pkg/storage/system.go
Remove the things
**I will remove the flag from LD after this PR has been merged**
=> remove intake table flag from backend

.github/workflows/build_db_clean_image.yml
- Convert the build_db_clean_image CircleCI job to a GitHub Action workflow.
=> build_db_clean_iamge github action

src/views/GovernanceReviewTeam/Actions/IssueLifecycleId.tsx
=> fix issue lifecycle date error message format

.github/workflows/build.yml, Dockerfile, Dockerfile.cypress, Dockerfile.db_seed, go.mod
=> upgrade go version to 1.16.5

cmd/easi/test/test.go
- Add parallelism flag to `easi test` CLI command to test whether this fixes failing backend tests in CI.
=> Add parallelism flag to test command

.spelling, docs/operations/backfill.md, pkg/server/routes.go
- Comment out backfill handler so it can't be used but is easy to re-enable
- Add documentation that describes how to use backfill program
=> ES-819 Add documentation for backfilling systems

.github/workflows/build.yml
- add dependabot branch as ignored on push 
=> exclude dependabot branch from triggering on push

.github/workflows/build.yml
- revert Github Actions build workflow change
=> dependabot revert workflow change

.github/workflows/deploy_dev.yml
- Initial manual deployment yml file. This file needs to be present before able to test manual deployment process through github actions.
=> Initial workflow_dispatch manual deploy yml

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/resolver.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_system_intake_test.go, pkg/graph/schema.resolvers_test.go, pkg/server/routes.go
This PR pulls in the backend changes as defined in [this process](https://trussworks.slack.com/archives/C01BCRE1Q20/p1630097706060800).
We will follow up with additional PRs that move parts of the UI over to these new queries and mutations.
- Pull in changes to `schema.gql` and backend code
=> Pull in schema and backend changes from system intake gql work

src/views/App/index.tsx, src/views/AuthenticationWrapper/index.tsx, src/views/TimeOutWrapper/index.tsx
This PR fixes session timeout. **This does not fix behavior across tabs** 
`tokenManager.autoRenew` doesn't work as expected. `tokenManager.on('expired')` also doesn't work like it did before. This means renewing the token(s) is a bit flakey and unreliable. Instead of relying on those implementations, we are going to manually renew the token on our own. The token is continuously renewed (few minutes before they expire) until the user is logged out.
**If the token(s) are continuously renewed, how does a user get logged out?**
The token(s) are renewed a little before their expiration. A user is logged out 15 minutes after their last activity (mouse click or keyboard press). **This idle time is tracked independently from the token expiration**. A user will see a session timeout warning …
=> fix session timeout

.github/workflows/build.yml, .github/workflows/deploy_dev.yml
- Use new versions of ecs-manager-docker
=> Use new versions of ecs-manager-docker

docker-compose.ci_server_test.yml, docker-compose.yml
- upgrade Postgres version to 11.12
=> upgrade postgres version

cypress/integration/systemIntake.spec.js, src/queries/SystemIntakeQueries.ts, src/queries/types/UpdateSystemIntakeRequestDetails.ts, src/types/graphql-global-types.ts, src/views/SystemIntake/RequestDetails/index.tsx, src/views/SystemIntake/index.tsx
Update Intake Request Details form to use GraphQL mutation
=> update request details to use graphql mutation

src/queries/SystemIntakeQueries.ts, src/queries/types/SubmitIntake.ts, src/types/graphql-global-types.ts, src/views/SystemIntake/Review/index.tsx
**This PR builds off of #1273**
- Change 1
- Change 2
=> update intake submission to use graphql

.github/workflows/build.yml, .github/workflows/build_db_clean_image.yml
- adding docker_buildkit var to test build speed increase.
- https://docs.docker.com/develop/develop-images/build_enhancements/
=> docker_buildkit

src/views/Login/index.tsx, src/views/UserInfoWrapper/index.tsx
- Update the way we determine information about the current user to use the Okta SDK
- Fix a bug where there isn't a previous URL to go to by defaulting to redirecting to the homepage.
=> ES-875 auth bug

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, src/components/SystemIntakeReview/index.tsx, src/queries/types/GetSystemIntake.ts, src/queries/types/UpdateSystemIntakeContactDetails.ts, src/queries/types/UpdateSystemIntakeContractDetails.ts, src/utils/date.ts, src/views/GovernanceReviewTeam/IntakeReview/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx, src/views/GovernanceReviewTeam/Summary/index.test.tsx, src/views/GovernanceReviewTeam/Summary/index.tsx, src/views/GovernanceTaskList/RequestDecision/Approved.tsx, src/views/GovernanceTaskList/RequestDecision/Rejected.tsx, src/views/GovernanceTaskList/RequestDecision/index.tsx, src/views/SystemIntake/ContactDetails/GovernanceTeamOptions.tsx, src/views/SystemIntake/ContactDetails/index.tsx, src/views/SystemIntake/ContractDetails/index.tsx, src/views/SystemIntake/RequestDetails/index.tsx, src/views/SystemIntake/Review/index.tsx, src/views/SystemIntake/ViewOnly/index.tsx, src/views/SystemIntake/index.tsx
This PR updates the following pages to use GraphQL query over REST API and fixes the associated Typescript errors.
```
src/views/GovernanceTaskList/RequestDecision/index.tsx
src/views/GovernanceReviewTeam/RequestOverview.tsx
```
`src/views/GovernanceTaskList/index.tsx` will be addressed in a separate PR because it is more lengthy.
Changes can be a little daunting, but they're not as bad once you close out any generated code.
I would recommend starting in `pkg/graph/schema.graphql` to see what I changed. Most of the changes are making certain keys required so we don't need to do any optional chaining. For example:
```
{
...
productManager: null
}
vs
{
...
productManager: {
name: null,
component: null
}
}
```
=> intake gql typescript stuff

src/i18n/en-US/action.ts, src/types/flags.ts, src/validations/actionSchema.ts, src/views/FlagsWrapper/index.tsx, src/views/GovernanceReviewTeam/Actions/ExtendLifecycleId.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx
This PR adds the extend LCID form.
`/governance-review-team/INTAKE_ID/actions/extend-lcid`
- Verify the Extend LCID route is only accessible if the intake status is `LCID_ISSUED`
- Verify validations work. Especially that the new expiration is more recent than the current expiration date
=> Add extend LCID form

.github/dependabot.yml
- change dependabot schedule to weekly on Mondays
=> Dependabot schedule update to weekly

scripts/deploy_service
- replace CIRCLE_SHA var with GITHUB_SHA
=> remove reference to circle_sha env var

.github/workflows/antivirus.yml
=> add antivirus scan workflow

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, .pre-commit-config.yaml
- Touched up PR request template
- Added CODEOWNERS file
=> Touching up PR request template and CODEOWNERS

.github/workflows/build.yml, .github/workflows/deploy_dev.yml
- https://github.com/CMSgov/easi-infra/pull/524 created new versions of the {env}-ecs-manager-docker lambdas, and the GitHub actions workflows need to be updated to point to those new versions.
- [This action](https://github.com/CMSgov/easi-app/actions/runs/1546548066) was executed using this new version.
=> Update {env}-ecs-manger-docker versions

.github/workflows/build.yml, .github/workflows/build_db_clean_image.yml, .github/workflows/deploy_dev.yml, .github/workflows/rescan_deployed_image.yml
- Remove hard-coded comments that described what version an action was. These didn't provide much value, and got outdated whenever Dependabot updated those actions.
- Nothing to test here - this is all non-functional!
=> Remove hard-coded version comments for imported github actions

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
- Add @patrickseguraoddball and @jstrang-oddball 🎉 
- Touch up some areas of the PR template that aren't used.
=> Add Jeremy and Patrick to CODEOWNERS. Touch up PR template

pkg/apperrors/errors.go, pkg/cedar/core/client.go, pkg/storage/accessibility_request_test.go
- Fix runtime error when no matching system is returned from querying CEDAR
=> [EASI-1444] Fix bug when system doesn't exist in CEDAR

src/views/SystemIntake/ContractDetails/index.tsx
- Changed help text in contract details form in response to governance admin feedback
=> Modified help text for system intake cost increase questions

.github/CODEOWNERS
- Add @adamodd to the CODEOWNERS
=> Add Adam S. to the CODEOWNERS

src/components/BookmarkCard/BookmarkCardIcon/index.scss, src/components/BookmarkCard/__snapshots__/index.test.tsx.snap, src/components/BookmarkCard/index.test.tsx, src/components/BookmarkCard/index.tsx, src/components/shared/Divider/index.scss, src/i18n/en-US/systemProfile.ts, src/views/SystemList/__snapshots__/index.test.tsx.snap, src/views/SystemList/index.test.tsx, src/views/SystemList/index.tsx
- Updated the 'CMS component' bookmark/table field and relevant tests
- Add 'All Systems' title and subtitle to table
- Hide the table if there is CEDAR error/ display only error
- Minor margin/border tweaks
No functional changes, minor UI tweaks and text updates
=> System List UI Updates (per meeting of System List UX review)

.spelling, docs/adr/0029-server-side-caching.md
- Introduce an ADR that covers various caching solutions
- Propose a suggested implementation for caching
=> [EASI-1505] Add ADR for caching solutions

.spelling, docs/adr/0032-use-svg-icons.md
- ADR for decision outcome of Icon type and library
=> Added ADR for decision outcome of icon library/implementation

README.md, docs/operations/deployment_process.md
- Small changes to the deployment doc to cover approvals for impl and prod deploys.
=> Small updates to deployment doc

.github/CODEOWNERS
- Add @StevenWadeOddball to the CODEOWNERS file! 🎉 
=> [NOREF] Add Steven Wade

src/i18n/en-US/systemProfile.ts, src/views/Sandbox/mockSystemData.ts, src/views/SystemProfile/components/ToolsAndSoftware/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/ToolsAndSoftware/index.scss, src/views/SystemProfile/components/ToolsAndSoftware/index.test.tsx, src/views/SystemProfile/components/ToolsAndSoftware/index.tsx, src/views/SystemProfile/components/index.tsx, src/views/SystemProfile/index.tsx
System Profile: Tools and Software subpage layout
- Api data is inline hardcoded
- Unit tests outstanding
=> Tools and Software Subpage

docs/graphql_playground.md
No Jira ticket, just adding some documentation.
=> Add notes on using EUA ID in local graphQL playground

scripts/dev, src/i18n/en-US/systemProfile.ts, src/views/Sandbox/mockSystemData.ts, src/views/SystemProfile/components/SystemData/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SystemData/index.test.tsx, src/views/SystemProfile/components/SystemData/index.tsx, src/views/SystemProfile/components/index.tsx, src/views/SystemProfile/index.tsx
- Added subpage for System Data
Similar UI and work to the previous subpages.  Pretty straightforward
Icons are still using FA until we make the crossover - will not match Figma for now
=> Easi 1590/system data subpage

.github/CODEOWNERS
- Added Gary Zhao to the CODEOWNERS file! :tada:
=> [NOREF] Added Gary Zhao to the CODEOWNERS.

pkg/graph/generated/generated.go
- Quick Branch to resolve linting issue in master as part of pull [#1481](https://github.com/CMSgov/easi-app/pull/1481)
Just made new branch off of master, ran the pre-commits and committed the generated go code.
=> EASI-1628 correct linting issue introduced from #1481

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
- Updated CODEOWNERS file to use the [EASi Backend](https://github.com/orgs/CMSgov/teams/easi-backend) and [EASi Frontend](https://github.com/orgs/CMSgov/teams/easi-frontend) child teams.
- These teams will be used to populate reviews automatically
- Updated PR template to be a little less hectic. (This PR is using it! Let me know what you think!!)
- Read, read with your human eyes!! 👀 
- Really, though - you can test out these new CODEOWNER and PR Template changes by making a branch and PR that use _this_ branch (`NOREF/codeowners-and-pr-template`) as the base!
- Always make …
=> [NOREF] Updated CODEOWNERS and PR Template

src/views/BusinessCase/PreferredSolution/index.test.tsx, src/views/BusinessCase/RequestDescription/index.test.tsx
Formik test cases were failing as an effect because `await waitFor()` wasn't used properly with events and dom changes.
=> Fix formik test cases

.github/CODEOWNERS
- Fixed using package-lock instead of yarn.lock
- Added some wildcards to catch any random files of expected file types
If you really want to test this change manually, make a draft PR that merges _into_ this branch that touches files you'd like to touch, and see who it would request a review from.
I think these changes are pretty safe though, and should be reviewable by just overviewing the changes!
I made a PR that targeted this branch, with a file called `/.github/this_is_a_test.tsx` (not in the root) and review was automatically requested by @CMSgov/easi-frontend!
- Always make …
=> [NOREF] Updated CODEOWNERS file associations

src/i18n/en-US/systemProfile.ts, src/index.scss, src/views/Sandbox/mockSystemData.ts, src/views/SystemProfile/components/ATO/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/ATO/index.tsx, src/views/SystemProfile/components/FundingAndBudget/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/FundingAndBudget/index.tsx, src/views/SystemProfile/components/SubSystems/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SystemData/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SystemData/index.tsx, src/views/SystemProfile/components/SystemDetails/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SystemDetails/index.tsx, src/views/SystemProfile/components/SystemHome/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SystemHome/index.test.tsx, src/views/SystemProfile/components/SystemHome/index.tsx, src/views/SystemProfile/components/TeamAndContract/index.tsx
- Added System Profile Home view
- Minor style tweaks to sub nav components for uniformity
- Snapshot test captured
- As with the other System Profile sub navigation components, lots of cedar data is mocked
- Each home card should have some navigation to the relevant sub nav component
=> Easi 1675/home system profile

.github/workflows/build.yml
=> Changing ECR-manager image version

.github/workflows/build.yml
Preparing for work on EASI-1614; this should require PR checks to run on every PR, not just ones targeting master.
=> Run GitHub Actions checks on any PR, regardless of target branch

src/i18n/en-US/governanceReviewBoard.ts, src/i18n/en-US/governanceReviewTeam.ts, src/i18n/en-US/intake.ts, src/i18n/en-US/taskList.ts, src/views/BusinessCase/index.tsx, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/GovernanceOverview/index.tsx, src/views/GovernanceTaskList/Feedback/index.tsx, src/views/GovernanceTaskList/LcidInfo/index.tsx, src/views/GovernanceTaskList/RequestDecision/index.tsx, src/views/GovernanceTaskList/index.tsx, src/views/PrepareForGRB/__snapshots__/index.test.tsx.snap, src/views/PrepareForGRB/index.tsx, src/views/PrepareForGRT/__snapshots__/index.test.tsx.snap, src/views/PrepareForGRT/index.tsx, src/views/RequestTypeForm/index.tsx, src/views/SystemIntake/index.tsx, src/views/SystemProfile/components/SubSystems/__snapshots__/index.test.tsx.snap
- Updated breadcrumbs for IT Governance requester views
Complete IT Governance requester workflow and ensure breadcrumbs match [Figma](https://www.figma.com/file/JE39JNLbCSha4fk1m9ayPP/System-Intake-Updates?node-id=309%3A4482)
=> Updated IT Governance requester breadcrumbs

scripts/testsuite
- This is a temporary fix while we re-evaluate our backend testing processes.
- This was causing failures in master.
=> [NOREF] Drop backend test coverage amount from 55% to 50%

pkg/cedar/intake/models/easi_intake.go, pkg/cedar/intake/schemas/easi_system_intake.json
- Modified CEDAR SystemIntake object to include LCID Cost Baseline field (with description and example)
=> Add LCID Cost Baseline to CEDAR SystemIntake object

cypress/integration/systemIntake.spec.js, src/components/SystemIntakeReview/index.tsx, src/validations/systemIntakeSchema.ts, src/views/SystemIntake/ContractDetails/index.tsx
- The field will not be grey if the funding source is unknown
=> Don't grey out funding number question on Intake Form

.github/workflows/deployments.yml
=> Updating Lambda version variable

.github/workflows/deployments.yml
=> Adding logic to define the deployment of Impl and prod

.github/workflows/deployments.yml, scripts/release_static
=> changed the environment to invoke the lambda function

scripts/release_static
=> [EASI-1748] Updates to deploy workflow

cypress/integration/accessibility.spec.js, src/i18n/en-US/accessibility.ts, src/views/Accessibility/MakingARequest/index.test.tsx, src/views/Accessibility/MakingARequest/index.tsx, src/views/MyRequests/Table/__snapshots__/index.test.tsx.snap, src/views/MyRequests/Table/index.tsx, src/views/MyRequests/Table/tableMap.ts
- Make view fit into grid-12 instead of grid-10
- Include a My 508 requests table beneath standard info
- Update verbiage per [Figma](https://www.figma.com/file/kNsCJCCRvGJCWwPQO6Gqfr/GRT-Admin-Experience?node-id=9%3A2162)
- Tests where applicable
=> Easi 1730/ Updating Section 508 Tabs

src/validations/businessCaseSchema.test.ts, src/validations/businessCaseSchema.ts, src/views/BusinessCase/GeneralRequestInfo/index.tsx
- Updated the regex to properly check phone numbers
- Updated error message 
|Status|🖼️|
|:--:|:--|
|Before|![image](https://user-images.githubusercontent.com/2349702/159972099-63ab97fd-bb9e-4c07-b3fa-c385916ea7d8.png)|
|After|![image](https://user-images.githubusercontent.com/2349702/159970867-e8ef55cc-6f74-4cde-a57d-ad43b8b576a5.png)|
1. Navigate to the Business case section to enter in phone numbers
2. Ensure the following phone numbers works:
1. 1234567890
1. 123-456-7890
3. Ensure the following phone numbers **do not** work 
1. 1234
2. 1234567890034563456435
3. 123-456-789
4. Ensure phone number in error message has the correct number of digits
- Before it was `123-456-789`, it should now be `123-456-7890`
- It's best to pull the branch locally and test it, rather than just looking …
=> [EASI-1696] Updated Phone Number template and regex are wrong for Business Case

.github/workflows/deploy_pipeline.yml, .github/workflows/deploy_to_environment.yml
This changes what we allow to run concurrently as part of our GitHub actions workflows. Before this change, application image builds and test executions on merges to master could all run concurrently, and only the individual deploys to each of dev, impl, and prod were restricted concurrently.
This left a few things to be desired in a few examples:
- If multiple merges to master are made, do we really need to be building and testing those application images if we're only going to be deploying one of them?
- If multiple instances of the `deploy_pipeline.yaml` job were being run, it's possible that deploys could still run out of order, as a queued job on an older commit could "sneak in front of" a running deploy on a newer commit.
This change _should_ fix both of these issues. The only …
=> [NOREF] Move concurrency group from deploy_to_environment to deploy_pipeline

pkg/cedar/intake/models/easi_biz_case.go, pkg/cedar/intake/schemas/easi_business_case.json, pkg/cedar/intake/translation/biz.go
- Add business case ID to top level business case CEDAR intake object
- Modify translation logic to account for new required ID field
=> Add business case ID to top level business case CEDAR intake object

.github/workflows/build_and_test.yml, .github/workflows/build_application_images.yml, .github/workflows/deploy_pipeline.yml, .github/workflows/deploy_to_environment.yml, .github/workflows/manual_deploy.yml, .github/workflows/run_tests.yml, .github/workflows/scan_deployed_image.yml, docker-compose.ci_server_test.yml, docker-compose.cypress_ci.yml
- Remove `env` blocks for jobs that don't require them
- [The GitHub docs backs this up](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations) - "Any environment variables set in an env context defined at the workflow level in the caller workflow are not propagated to the called workflow."
- Rename `IMAGE_TAG` to `GIT_HASH` and use it in a few more places, rather than hardcoding references to GitHub actions context objects
=> [NOREF] Simplify GH Actions Jobs

.github/workflows/build_and_test.yml
- Sets a concurrency group on `build_and_test.yml` so that only the most recent commit on a given branch runs (and older ones are cancelled as soon as a new commit is pushed)
- Docs for the `github` [context can be found here](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
- Docs for the `cancel-in-progress` and `concurrency` [can be found here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) ([with a nice and similar example!](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run))
Multiple commits to this branch in quick succession should trigger this workflow's concurrency behavior. I will post a screenshot …
=> [NOREF] Added concurrency group to build_and_test.yml

pkg/cedar/intake/models/easi_biz_case.go, pkg/cedar/intake/schemas/easi_business_case.json, pkg/cedar/intake/translation/biz.go
- Modify CEDAR Intake business case so that each business case contains multiple business solutions, and each business solution contains multiple an array of lifecycle cost lines
- Modify CEDAR translation unit to handle new business case structure
=> [EASI-1537] Modify CEDAR Business Solution struct to contain Lifecycle Cost objects

pkg/cedar/intake/models/easi_biz_case.go, pkg/cedar/intake/schemas/easi_business_case.json, pkg/cedar/intake/translation/biz.go
- Remove business case id from lifecycle cost CEDAR struct
=> [EASi-1887] Remove business case ID from LifecycleCost struct

migrations/V103__Rename_Intake_Process_Statuses.sql
- Add a SQL migration to map system intake process statuses to new values.
=> Add migration to rename system intake process statuses

.github/workflows/build_application_images.yml, scripts/find_ecr_image.sh
- Skip image builds if the image already exists. Should save time mainly on action re-runs or manual deploys, since they're (theoretically) the only time one of these workflows will run on an already existing git hash.
- Actually use the `yarn` and `go` caches that are set up in `pre_deps`
Re-run this workflow on this PR, and check to see if the image build step is skipped!
=> [NOREF] Caching / build skipping changes

.spelling, docs/operations/rotate_okta_password.md
A monthly slack reminder will be created that will point to this doc once it's merged into master.
- Added docs for how to reset the Okta Test password.
=> [NOREF] Docs for resetting Okta test password

src/components/RelatedArticles/__snapshots__/index.test.tsx.snap, src/components/RelatedArticles/index.tsx, src/views/Help/HelpHome/__snapshots__/index.test.tsx.snap, src/views/Help/HelpHome/index.tsx, src/views/Help/ITGovernance/PrepareForGRT/index.tsx, src/views/Help/ITGovernance/__snapshots__/index.test.tsx.snap, src/views/Help/ITGovernance/index.tsx, src/views/Help/Section508/__snapshots__/index.test.tsx.snap, src/views/Help/Section508/index.tsx, src/views/Help/index.tsx
- Removed the grid container from parent Help component, and into the children. 
- Added `isLink` prop to the related articles components
=> NOREF - Help - wrapper adjustments, related article adjustments

src/views/GovernanceReviewTeam/RequestOverview.tsx
Fix system intake to show its business case.
Visit some intake business cases through the ui and see that the display is correct.
=> EASI-1714 Wrong Business Case for Intakes without Business Case

src/components/PrepareForGRB/__snapshots__/index.test.tsx.snap, src/components/PrepareForGRB/index.scss, src/components/PrepareForGRB/index.test.tsx, src/components/PrepareForGRB/index.tsx, src/i18n/en-US/articles/governanceReviewBoard.ts, src/views/FlagsWrapper/index.tsx, src/views/Help/ITGovernance/PrepareForGRB/index.tsx, src/views/Help/index.tsx, src/views/PrepareForGRB/__snapshots__/index.test.tsx.snap, src/views/PrepareForGRB/index.tsx
- Add new `PrepareforGRB` component in the help sections
- Add new routes for `PrepareforGRB`
- Add new copy to the i18n.ts files
1. Navigate to http://localhost:3000/help
2. Find and click on article titled: `Prepare for the Review Board meeting`
3. Ensure new tab opens with the article.
4. Ensure article look and copy reflects figma
- Reuse existing 'Prepare for GRB Meeting' view/component
- May need to tweak existing component to be reusable in any area within EASI
- Testing where applicable
=> [Easi-1902] Create "Prepare for the Governance Review Board meeting" help article

src/components/AccessibilityTestingSteps/__snapshots__/index.test.tsx.snap, src/components/AccessibilityTestingSteps/index.test.tsx, src/components/AccessibilityTestingSteps/index.tsx, src/i18n/en-US/accessibility.ts, src/views/Accessibility/AccessibilityTestingStepsOverview/__snapshots__/index.test.tsx.snap, src/views/Accessibility/AccessibilityTestingStepsOverview/index.tsx, src/views/Help/Section508/StepsInvolved/__snapshots__/index.test.tsx.snap, src/views/Help/Section508/StepsInvolved/index.test.tsx, src/views/Help/Section508/StepsInvolved/index.tsx
- Created Section 508 Steps Involved article
- Converted testing steps into `<AccessibilityTestingSteps />` reusable component
- Added tests
- Help article is located at http://localhost:3000/help/section-508/steps-involved
- Original Steps Involved view/component is located at http://localhost:3000/508/testing-overview?continue=true
=> [EASI 1904] Help 508 steps involved

src/components/RelatedArticles/__snapshots__/index.test.tsx.snap, src/views/Help/All/__snapshots__/index.test.tsx.snap, src/views/Help/HelpHome/__snapshots__/index.test.tsx.snap, src/views/Help/ITGovernance/NewSystem/__snapshots__/index.test.tsx.snap, src/views/Help/ITGovernance/__snapshots__/index.test.tsx.snap, src/views/Help/ITGovernance/articles.ts
- Commented out sample business case route and card
This is in preparation for toggling the `help` feature flag off for production
=> Disabled Sample Business Case Route and Card

.pre-commit-config.yaml
Echoing the change from https://github.com/CMSgov/mint-app/pull/71
I'm sure you've all seen it, but sometimes the [go-fmt-import](https://github.com/CMSgov/easi-app/blob/d53d67ca26b7927e83d66a01313048835acffa23/.pre-commit-config.yaml#L28-L31) statement would complain that the "file was not 'goimport'ed with -local". This should fix that by introducing the -local flag to the linting step that was complaining about it. Not really sure why this wasn't there before! (Perhaps some folks editors did this automatically?)
1. Open a .go file that imports packages from `easi-app` and other sources (like `/pkg/server/config.go`)
2. Edit the file to put some `easi-app` imports between others, like so
```go
import (
"fmt"
"github.com/cmsgov/easi-app/pkg/appconfig" …
```
=> [NOREF] Added args and exclude statement to go-fmt-import

src/components/NavigationBar/index.tsx, src/types/flags.ts, src/views/App/index.tsx, src/views/FlagsWrapper/index.tsx
- Sunset `help` feature flag
- https://app.launchdarkly.com/default/dev/features/help will go away after approved
=> EASI-2007 Remove "Help" feature flag and code

src/components/RequestRepository/index.tsx
- Date display in the Last Admin Note column
- The Closed Reports table tab is sortable by the Last Admin Note date
=> EASI-2029 EASI-2046 Closed Report sort based on Last Admin Note

.github/workflows/deploy_pipeline.yml, .github/workflows/manual_deploy.yml
- Update ECS manager lambda versions
=> [NOREF] Update ECS manager lambda versions

.github/workflows/deploy_pipeline.yml
=> EASI-2108/Removing Dev Environment from workflow

src/types/systemProfile.ts, src/views/SystemProfile/index.tsx
Regarding https://github.com/CMSgov/easi-app/pull/1671#discussion_r897143854
@DylanSpOddball
=> Check hostenv null on deployment match

src/views/SystemList/Table.tsx
The System table is searchable by all visible fields.
Add CMS component name and system name.
Remove react-table column property `disableGlobalFilter: true` to allow search on that field.
=> EASI-2119 EASi Search by Visible System Profile Fields

.pre-commit-config.yaml
- Introduce `no-commit-to-branch` hook
This PR introduces a new pre-commit hook, [no-commit-to-branch](https://github.com/pre-commit/pre-commit-hooks#no-commit-to-branch). This is an official pre-commit hook which effectively fails a commit if it is on a branch that matches a name or pattern.
The regex used for this are, at time of writing:
```regex
^(?!((main|master)|(EASI-\d{0,5}|NOREF|dependabot|feat\/EASI-\d{0,5})\/[a-zA-Z0-9\-]+)$).*
```
There is a negative lookbehind (`?!`) because the hook is looking for branches which are not allowed to be committed to, but we want to specify ones we _are_ allowed to commit to, so we negate the regular expression. This means the following branch patterns are allowed:
- `main` & `master`
- These are set so when we run this in CI it doesn't break …
=> [NOREF] Add pre-commit hook for enforcing branch naming patterns

cypress/integration/systemIntake.spec.js, src/views/SystemIntake/ContactDetails/index.tsx
- Fixes conditional statement for showing additional contacts button
=> [EASI-1685] - Additional contacts button fix

.github/workflows/deploy_pipeline.yml, .pre-commit-config.yaml, scripts/github-action-announce-broken-branch
This is a follow up to https://github.com/CMSgov/easi-app/pull/1723
- Remove references to `master`, now that it has been renamed to `main`
=> [NOREF] Remove old references to master

src/components/HelpFooter/__snapshots__/index.test.tsx.snap, src/components/HelpFooter/index.tsx
Temporarily comment out the slack chat link
=> Hide slack chat link in help footer

.pre-commit-config.yaml
See `mint-app` PR here: https://github.com/CMSgov/mint-app/pull/186
- Update regex to require `feature` instead of `feat`.
- Update regex to require feature branches look like `feature/EASI-2021`. Branches that merge into it will be ticket branches, like `EASI-2021/backend` or `EASI-2021/fix-type-error`
https://regex101.com/r/gl4XGb/2
Click "unit tests" on the left, and ensure it's set to "python" for the flavor.
=> [NOREF] Update regex for branch naming

src/views/SystemIntake/ContractDetails/FundingSources.tsx
- Modify h4 to h3 in ContractDetails component so that it follows a sequential heading order.
Previously, we were going straight from <h2> to <h4>, which freaks out Prince due to accessibility requirements. This just changes the <h4> to an <h3> and styles it like an <h4> for the time being (just to make stuff work in prod)
=> [NOREF] Change h4 to h3 in SystemIntake ContractDetails

src/hooks/useSystemIntakeContacts.tsx
- Temporary frontend fix to capitalize system intake contact EUA id - lowercase ids were causing error
- Backend fix will be implemented in [EASI-2239](https://jiraent.cms.gov/browse/EASI-2239)
=> [NOREF] Capitalize system intake contacts EUA id

pkg/cedar/intake/models/easi_biz_case.go, pkg/cedar/intake/schemas/easi_business_case.json, pkg/cedar/intake/translation/biz.go, pkg/cedar/intake/translation/constants.go, pkg/server/routes.go, pkg/services/action.go, pkg/services/action_test.go
This reverts commit c9b1b00118420e9353368d52a9784972bcdf637b.
Reverts initial work on EASI-1538, which submitted bugged business case data to CEDAR.
=> Revert "Submit draft business cases to CEDAR Intake API (#1785)"

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
- Add `userInfo` property to TRBRequestAttendee type
@StevenWadeOddball help? 😬
=> [NOREF] Add userInfo to TRB attendees

pkg/cedar/intake/models/easi_biz_case.go, pkg/cedar/intake/models/easi_intake.go, pkg/cedar/intake/schemas/easi_system_intake.json
- Update examples of date/time values to match what we're actually sending
=> [NOREF] Fix schema examples for System Intakes

pkg/graph/schema.resolvers_accessibility_request_test.go, pkg/graph/schema.resolvers_system_intake_test.go, pkg/local/cedar_ldap.go, src/views/AuthenticationWrapper/DevLogin.tsx
- Adds improved LDAP data to the local CEDAR LDAP Mock.
- Adds ~50 randomly generated names with "valid" EUA IDs (i.e. 4 characters, first character of ID is first character of last name)
- Adds manually created names that match test data that is required by the go test suite, seeded data, and cypress tests (e.g. `A11Y`, `ADMN`, `ABCD`, `TEST`)
- Modify how the `FetchUserInfo`, `FetchUserInfos`, and `SearchByCommonName` functions work. Rather than returning fixed data, they actually fetch/search from the mock data array appropriately. This means that the functionality should be closer to what you'd see from CEDAR LDAP.
Since this change modifies the `FetchUserInfo` function to fetch info from the mock data source, it means if you log in as a user who's NOT in the local mock data, you'll …
=> [NOREF] Add better local LDAP data

cypress/e2e/trbRequest.cy.js, src/views/TechnicalAssistance/RequestForm/Basic.tsx, src/views/TechnicalAssistance/RequestForm/Pager.tsx, src/views/TechnicalAssistance/RequestForm/__snapshots__/Basic.test.tsx.snap
Fixes the regression that caused form submits on first attempts to stall. Removes irrelevant condition. [Original pr](https://github.com/CMSgov/easi-app/pull/1820).
=> EASI-2327 Trb basic details submit fix

src/views/TimeOutWrapper/index.tsx
See https://github.com/CMSgov/mint-app/pull/376 for the MINT implementation.
- Properly disable the TimeOut Wrapper when using local dev authentication
- Properly sync the status of the `prompt` (or `modal`) across multiple tabs by using `idleTimer.isPrompted()` instead of a custom state variable.
- Start EASi locally
- Set the timeout in `src/views/TimeOutWrapper/index.tsx` to something manageable for local development
```javascript
// const fiveMinutes = Duration.fromObject({ minutes: 5 }).as('milliseconds');
const fiveMinutes = Duration.fromObject({ seconds: 15 }).as('milliseconds');
```
- Log in with local dev
- Let the timeout modal pop up
- Close the modal to continue using EASi
- Ensure no errors pop up
- It's best to pull the branch locally and test it, rather than just looking at …
=> [NOREF] Additional TimeOutWrapper fixes

cypress/e2e/governanceReviewTeam.cy.js
Original https://github.com/CMSgov/easi-app/pull/1862/commits/2e238170a2b85c4799c724d871d9c8b6f148c8c4
=> Update expiration date in cypress test

src/validations/actionSchema.test.ts
- New year caused action schema to throw different error when entering year 2022
- See Slack thread [here](https://cmsgov.slack.com/archives/CNU2B59UH/p1672758749278969)
- Updated action schema test error message
=> [NOREF] Update action schema test error message

src/i18n/en-US/technicalAssistance.ts, src/views/TechnicalAssistance/ProcessFlow.tsx, src/views/TechnicalAssistance/__snapshots__/index.test.tsx.snap
- Removed IT tech lounge text from TRB task list steps
- Updated text in [Figma](https://www.figma.com/file/iGatgTnlzTuqW9CQFYHDam/TRB-Intake-e2e?node-id=61%3A8824&t=hzkdx3fKlJH2ZMNu-0)
- Create new TRB request and review text in task list
=> [EASI-2493] Remove TRB IT tech lounge text

src/i18n/en-US/technicalAssistance.ts, src/views/TechnicalAssistance/Homepage.tsx, src/views/TechnicalAssistance/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/index.scss, src/views/TechnicalAssistance/index.test.tsx, src/views/TechnicalAssistance/index.tsx
- View for TRB home (Technical Assistance navigation tab)
- [src/views/TechnicalAssistance/Homepage.tsx](https://github.com/CMSgov/easi-app/blob/a1b9890f67a399ddf08235b79ddaf0f883ead9a9/src/views/TechnicalAssistance/Homepage.tsx)
- Site alert if user has TRB Admin job code
- TRB requests table updates
- Updated text
- Unit testing
- Updated tests in [src/views/TechnicalAssistance/index.test.tsx](https://github.com/CMSgov/easi-app/blob/EASI-2419/technical-assistance-tab-view/src/views/TechnicalAssistance/index.test.tsx) to reflect changes and added test for admin site alert
- Go to Technical Assistance tab and compare to [Figma](https://www.figma.com/file/iGatgTnlzTuqW9CQFYHDam/TRB-Intake-e2e?node-id=627%3A55400)
- The table search component is smaller than in Figma. I confirmed with Zoe …
=> [EASI-2419] Technical assistance tab view

docs/dev_environment_setup.md
- Added docs to cover running `brew install diffutils` on OSX.
Read the docs!
=> [NOREF] Update docs for diffutils install for OSX

src/i18n/en-US/articles/governanceReviewTeam.ts, src/i18n/en-US/home.ts, src/i18n/en-US/technicalAssistance.ts, src/views/Home/index.test.tsx, src/views/TechnicalAssistance/__snapshots__/index.test.tsx.snap
- Removed occurrences of 'compliance' and 'compliant'
Reviewed with Zoe - some occurrences were okay to leave, mostly related to 508
=> [NOREF] - Removed references to compliance and compliant

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
- Add `author` property to `TRBRequestFeedback` to provide more information about who made the feedback
Check the `author` type on the return of `createTRBRequestFeedback`!
```GraphQL
mutation {
id # use this for the following steps
form {
status
}
taskStatuses {
formStatus
feedbackStatus
consultPrepStatus
}
}
}
mutation createTRBRequestFeedback {
createTRBRequestFeedback(input: {
trbRequestId: "f8a797c4-ddf5-48e5-b4ad-12da435c76db",
feedbackMessage: "This is TRB request is NICE!",
copyTrbMailbox: false,
notifyEuaIds: ["USR1", "USR2", "USR3"],
action: REQUEST_EDITS,
}) {
id
author {
commonName
}
}
}
```
- Check that all code is adequately covered by …
=> [NOREF] Add author info in TRB Feedback

src/validations/systemIntakeSchema.ts, src/views/SystemIntake/RequestDetails/index.tsx
This change is for the Request details page of the IT Gov intake request form
Updated field label: Contract/Request Title
Updated/added field help text: Your request title should match the title of your Acquisition Plan or Interagency Agreement.
=> EASI-2661 Text Change for IT Gov Intake Request Name question

cypress/e2e/trbRequest.cy.js
=> NOREF Skip trb e2e

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
=> [NOREF] Add author: UserInfo! to TRBAdviceLetterRecommendation type

pkg/email/lcid_expiration_alert.go, pkg/email/lcid_expiration_alert_test.go, pkg/email/templates/lcid_expiration_alert.gohtml
- Fix spacing and formatting in email
- Fix URL/links in email
=> [NOREF] Fix LCID expiration alert formatting and URL issues

src/components/Header/index.scss, src/components/Header/index.tsx, src/components/NavigationBar/index.scss, src/components/NavigationBar/index.tsx, src/components/Tabs/Tabs.test.tsx, src/stylesheets/custom.scss, src/views/App/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.test.tsx, src/views/Navigation/index.scss, src/views/Navigation/index.tsx, src/views/SystemProfile/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/index.scss, src/views/SystemProfile/index.tsx, src/views/TechnicalAssistance/RequestForm/Attendees.test.tsx, src/views/TechnicalAssistance/RequestForm/Documents.test.tsx
- Added sticky navigation and mobile navigation to EASI
- Restructured/fragmented Header hierarchy to allow sticky to be effective
- Needed to address stacking stickiness with System profile that is a little css hacky
- Fixed a few test warnings
- Check stickiness on desktop and mobile
=> [EASI-2517] - Sticky navigation

pkg/email/lcid_expiration_alert.go, pkg/email/lcid_expiration_alert_test.go
- Remove requester from email recipients for LCID expiration alerts
- Modify tests to reflect change
=> Temporarily remove requester from LCID expiration email alerts

src/components/HelpTag/index.tsx, src/components/RelatedArticles/index.tsx, src/constants/externalUrls.ts, src/i18n/en-US/articles/prepareTrbConsultMeeting.ts, src/i18n/en-US/help.ts, src/i18n/en-US/index.ts, src/i18n/en-US/technicalAssistance.ts, src/stylesheets/custom.scss, src/types/articles.ts, src/views/Help/All/__snapshots__/index.test.tsx.snap, src/views/Help/All/index.tsx, src/views/Help/HelpHome/__snapshots__/index.test.tsx.snap, src/views/Help/HelpHome/index.tsx, src/views/Help/InfoBox/NeedHelpBox.tsx, src/views/Help/TechnicalReviewBoard/PrepareTrbConsultMeeting.test.tsx, src/views/Help/TechnicalReviewBoard/PrepareTrbConsultMeeting.tsx, src/views/Help/TechnicalReviewBoard/__snapshots__/PrepareTrbConsultMeeting.test.tsx.snap, src/views/Help/TechnicalReviewBoard/articles.ts, src/views/Help/TechnicalReviewBoard/index.tsx, src/views/Help/index.tsx, src/views/TechnicalAssistance/ProcessFlow.tsx, src/views/TechnicalAssistance/TaskList.tsx, src/views/TechnicalAssistance/__snapshots__/index.test.tsx.snap
Help article at /help/trb/prepare-consult-meeting
=> EASI-2440 Help Article - Prepare for TRB

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql
- Adding missing props for some TRB action mutations
This doesn't add any functionality, only some props so the frontend can use these types as expected. Implementation will follow in another PR
=> [NOREF] Add initial props to close and reopen

src/views/TechnicalAssistance/AdminHome/Consult.test.tsx, src/views/TechnicalAssistance/AdminHome/InitialRequestForm.test.tsx, src/views/TechnicalAssistance/AdminHome/RequestContext/index.tsx, src/views/TechnicalAssistance/AdminHome/RequestEdits.test.tsx, src/views/TechnicalAssistance/AdminHome/index.test.tsx, src/views/TechnicalAssistance/AdminHome/index.tsx, src/views/TechnicalAssistance/index.tsx
- Added context provider to query and pass data to any TRB admin child routes
- Removed query from AdminHome and used context to get TRB data
=> [NOREF] - Added context provider for queried TRB request base data

src/components/BookmarkCard/index.scss, src/components/CharacterCounter/index.scss, src/components/EstimatedLifecycleCost/index.scss, src/components/Footer/index.scss, src/components/PageNumber/index.scss, src/components/shared/CollapsableLink/index.scss, src/components/shared/DropdownField/index.scss, src/components/shared/HelpText/index.scss, src/components/shared/MultiSelect/index.scss, src/components/shared/OktaSignInWidget/index.scss, src/components/shared/SearchBar/index.scss
- `color()` function in some stylesheets was causing errors and styles weren't being applied
- Added `@use 'uswds-core' as *` to top of stylesheets to fix
=> [NOREF] Fix USWDS color errors in stylesheets

src/hooks/useTRBAttendees.tsx
Fixed useEffect loop error in `<Attendees>` caused by `useTrbAttendees` hook by wrapping mutation functions in useCallback
- Create new TRB request
- Make sure Attendees step renders without error and works as expected
=> [NOREF] Fix attendees useEffect loop

.github/workflows/deploy_to_environment.yml, .github/workflows/manual_deploy.yml
- Added `vars.ENABLE_DEV_DB_CLEAN` check when cleaning the database in `deploy_to_environment.yml`
- If you want to test this code, you can manually run a deploy targeting dev and this branch. In order to change the variable, you'll need to go to [this page
](https://github.com/CMSgov/easi-app/settings/environments/265837931/edit)
- [Run 1: Enabled](https://github.com/CMSgov/easi-app/actions/runs/4679257119)
- [Run 2: Disabled](https://github.com/CMSgov/easi-app/actions/runs/4679615828)
=> Make DB Clean configurable in dev

pkg/email/templates/trb_request_consult_meeting.gohtml, pkg/email/trb_request_consult_meeting.go, pkg/email/trb_request_consult_meeting_test.go, pkg/graph/resolvers/trb_request_feedback.go
- Added the TRB help link to the TRB consult meeting email
- Updated test
```GraphQL
mutation {
id # use this for the following steps
form {
status
}
taskStatuses {
formStatus
feedbackStatus
consultPrepStatus
}
}
}
mutation {
updateTRBRequestForm(
input: { isSubmitted: true, trbRequestId: "trbRequestIdFromAbove" }
) {
status
}
}
mutation {
createTRBRequestFeedback(
input: {
trbRequestId: "trbRequestIdFromAbove"
feedbackMessage: "This is TRB request is NICE!"
copyTrbMailbox: true
notifyEuaIds: ["FAKE", "REAL", "LOLZ"]
action: READY_FOR_CONSULT
}
) {
id
trbRequestId
feedbackMessage
copyTrbMailbox
notifyEuaIds
action
createdBy
createdAt
modifiedBy
modifiedAt
}
}
mutation {
updateTRBRequestConsultMeetingTime(
input: {
trbRequestId: …
```
=> [EASI-2519] Added TRB help link to TRB consult meeting email

src/i18n/en-US/technicalAssistance.ts, src/queries/TrbAdviceLetterQueries.ts, src/queries/types/RequestReviewForTRBAdviceLetter.ts, src/queries/types/SendTRBAdviceLetter.ts, src/stylesheets/custom.scss, src/types/graphql-global-types.ts, src/types/technicalAssistance.ts, src/validations/trbRequestSchema.ts, src/views/TechnicalAssistance/AdminHome/AdviceLetter.tsx, src/views/TechnicalAssistance/AdminHome/components/ReviewAdviceLetter/RecommendationsList.tsx, src/views/TechnicalAssistance/AdminHome/components/ReviewAdviceLetter/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/AdminHome/components/ReviewAdviceLetter/index.test.tsx, src/views/TechnicalAssistance/AdminHome/components/ReviewAdviceLetter/index.tsx, src/views/TechnicalAssistance/AdviceLetterForm/Done.tsx, src/views/TechnicalAssistance/AdviceLetterForm/InternalReview.tsx, src/views/TechnicalAssistance/AdviceLetterForm/RecommendationsForm.tsx, src/views/TechnicalAssistance/AdviceLetterForm/Review.tsx, src/views/TechnicalAssistance/AdviceLetterForm/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/AdviceLetterForm/index.test.tsx, src/views/TechnicalAssistance/AdviceLetterForm/index.tsx, src/views/TechnicalAssistance/PublicAdviceLetter.tsx, src/views/TechnicalAssistance/RequestForm/Pager.tsx, src/views/TechnicalAssistance/RequestForm/__snapshots__/Basic.test.tsx.snap, src/views/TechnicalAssistance/RequestForm/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/__snapshots__/PublicAdviceLetter.test.tsx.snap
[Figma](https://www.figma.com/file/iGatgTnlzTuqW9CQFYHDam/TRB-Intake-e2e?node-id=284%3A36525)
- Internal review form step
- src/views/TechnicalAssistance/AdviceLetterForm/Review.tsx
- Check and send form step
- src/views/TechnicalAssistance/AdviceLetterForm/InternalReview.tsx
- Mutations to request review and submit advice letter
=> [EASI-2438] Advice letter overview/send

pkg/email/templates/trb_advice_letter_internal_review.gohtml, pkg/email/templates/trb_advice_letter_submitted.gohtml, pkg/email/templates/trb_edits_needed_on_form.gohtml, pkg/email/templates/trb_ready_for_consult.gohtml, pkg/email/templates/trb_request_closed.gohtml, pkg/email/templates/trb_request_reopened.gohtml, pkg/email/translation/constants.go, pkg/email/trb_advice_letter_internal_review.go, pkg/email/trb_advice_letter_internal_review_test.go, pkg/email/trb_advice_letter_submitted.go, pkg/email/trb_advice_letter_submitted_test.go, pkg/email/trb_edits_needed_on_form.go, pkg/email/trb_ready_for_consult.go, pkg/email/trb_reopened_email_test.go, pkg/email/trb_request_closed.go, pkg/email/trb_request_closed_test.go, pkg/email/trb_request_reopened.go, src/views/App/index.tsx
I synced with Zoe S on all these link changes, some not initially described in the AC of the ticket
- Fixed links not going to a valid route for advice letter
- Standardized link footer template variables and link
- These should be standard/same across all emails with this footer.  First link should go to requester task list.  Second link should go to Admin request home
- Remove unneeded link for this email template per Zoe's request
- Created a translation file used for email templating
- Component acronym
- Request response type
- Update tests
- Translated the ENUM value for requestType
- Render components as acronyms
- Trigger emails at various stages of the TRB request and ensure that the links in the emails are valid and reflect UX
- Use mailcatcher here - …
=> [EASI-2951, EASI-2952, EASI-2953, EASI-2954] Email link fixes

src/components/HelpContacts/__snapshots__/index.test.tsx.snap, src/components/shared/Alert/index.tsx, src/i18n/en-US/articles/stepsInTRBProcess.ts, src/i18n/en-US/help.ts, src/i18n/en-US/index.ts, src/i18n/en-US/technicalAssistance.ts, src/views/Help/All/__snapshots__/index.test.tsx.snap, src/views/Help/HelpHome/__snapshots__/index.test.tsx.snap, src/views/Help/HelpHome/index.tsx, src/views/Help/ITGovernance/__snapshots__/index.test.tsx.snap, src/views/Help/TechnicalReviewBoard/StepsInProcess.tsx, src/views/Help/TechnicalReviewBoard/__snapshots__/PrepareTrbConsultMeeting.test.tsx.snap, src/views/Help/TechnicalReviewBoard/articles.ts, src/views/Help/TechnicalReviewBoard/index.tsx, src/views/Help/index.tsx, src/views/TechnicalAssistance/AdviceLetterForm/Recommendations.tsx, src/views/TechnicalAssistance/AdviceLetterForm/index.tsx, src/views/TechnicalAssistance/ProcessFlow.tsx, src/views/TechnicalAssistance/RequestForm/Attendees.tsx, src/views/TechnicalAssistance/RequestForm/AttendeesForm/components.tsx, src/views/TechnicalAssistance/RequestForm/DocumentUpload.tsx, src/views/TechnicalAssistance/RequestForm/ViewSubmittedRequest.tsx, src/views/TechnicalAssistance/RequestForm/index.tsx, src/views/TechnicalAssistance/TaskList.tsx
All of these changes are a part of the "Should haves" of the UX Findings [DOC](https://docs.google.com/document/d/1HSmSXe6Wg7emBg59s3qFn7lINZnComsbpyVBlEJHb3Y/edit#heading=h.7kn6yyrth8d7)
- Required fields on add attendee page
- Required fields on attendee step
- Attendee removal success message
- Recommendation removal success message
- Document uploader should show supported file types
- Close tab link when viewing already-submitted forms
- Missing Process help article
- TRB Help center category
- TRB Help Center point of contact
- Always make comments, even if it's minor, or if you …
=> [EASI-2967] - Should have findings part 2

cmd/devdata/main.go, cmd/seed/main.go, pkg/authorization/require_principal_middleware.go, pkg/authorization/require_principal_middleware_test.go, pkg/graph/resolvers/resolver_test.go, pkg/graph/schema.resolvers_test.go, pkg/handlers/business_case.go, pkg/handlers/handler_base.go, pkg/handlers/handlers_test.go, pkg/integration/integration_test.go, pkg/local/authentication_middleware.go, pkg/okta/authentication_middleware_test.go, pkg/server/logger.go, pkg/server/logger_test.go, pkg/server/routes.go, pkg/server/server.go, pkg/server/trace.go, pkg/server/trace_test.go, pkg/services/services_test.go, pkg/storage/store.go, pkg/storage/store_test.go
See https://github.com/CMSgov/mint-app/pull/582 for reference
- Added `app-env` and `app-name` log fields. These should be present on all logs!
- Start the server and ensure that logger fields are present
=> [NOREF] Added app-env and app-name log fields

pkg/email/trb_reopened_email_test.go, pkg/email/trb_request_closed.go, pkg/email/trb_request_closed_test.go, pkg/email/trb_request_reopened.go, pkg/graph/resolvers/trb_request.go, pkg/graph/schema.resolvers.go
- Properly pass `copyTrbMailbox` input to resolvers that send emails
- Create a new TRB request
- Close the request from the admin side (don't copy the TRB mailbox)
- Check mailcatcher to make sure the mailbox wasn't CC'd
- Do the same for a new request, but select the option to copy the mailbox (and ensure it __is__ copied)
- Do the same tests for re-opening a request
=> [NOREF] Fix email trb mailbox

src/validations/trbRequestSchema.ts, src/views/TechnicalAssistance/AdviceLetterForm/Summary.tsx, src/views/TechnicalAssistance/RequestForm/Attendees.tsx, src/views/TechnicalAssistance/RequestForm/Basic.tsx, src/views/TechnicalAssistance/RequestForm/index.tsx
- Partial submit for basic and attendee fields in initial request form
- Updated schema to make attendee component not required
=> [EASI-2940] TRB request form save and exit

pkg/cedar/cedarldap/translated_client.go, pkg/graph/resolvers/trb_request.go, src/views/TechnicalAssistance/AdminHome/components/ReviewAdviceLetter/index.tsx, src/views/TechnicalAssistance/__snapshots__/PublicAdviceLetter.test.tsx.snap
- Fixed issue on admin actions where not including any recipients fails
- Fixed advice letter review question where no follow up is needed renders correct text
https://cmsgov.slack.com/archives/CNU2B59UH/p1685724540170099
https://cmsgov.slack.com/archives/CNU2B59UH/p1685726265101209
=> [NOREF] - TRB actions not need recipients

src/views/TechnicalAssistance/AdminHome/components/ActionFormWrapper/Recipients.tsx
- Fixes bug where TRB action submit button was disabled after clicking "cancel" button on add recipient form
=> [NOREF] Fix disabled submit button

src/hooks/useScrollToLocation.ts, src/views/Help/TechnicalReviewBoard/PrepareTrbConsultMeeting.tsx, src/views/Help/TechnicalReviewBoard/__snapshots__/PrepareTrbConsultMeeting.test.tsx.snap, src/views/TechnicalAssistance/TaskList.tsx
[Download presentation templates link in Task List step 3](https://docs.google.com/document/d/1HSmSXe6Wg7emBg59s3qFn7lINZnComsbpyVBlEJHb3Y/edit#heading=h.8ubs7zkojudu)
Attempts with the lib `react-router-hash-link` did not work so I copied a snippet into hooks/useScrollToLocation.ts
=> Download presentation templates link in Task List step 3

src/views/TechnicalAssistance/RequestForm/SubjectAreas.tsx, src/views/TechnicalAssistance/RequestForm/__snapshots__/SubjectAreas.test.tsx.snap, src/views/TechnicalAssistance/index.scss
[Checkbox tile selected state styling should align with USWDS styling](https://docs.google.com/document/d/1HSmSXe6Wg7emBg59s3qFn7lINZnComsbpyVBlEJHb3Y/edit#heading=h.i314vmy9th41)
=> Checkbox tile selected state styling should align with USWDS styling

src/validations/trbRequestSchema.ts, src/views/TechnicalAssistance/RequestForm/AttendeesForm/components.tsx, src/views/TechnicalAssistance/RequestForm/AttendeesForm/index.tsx
- Allowed for `component` on attendee form optional
- Updated schema validation
=> [NOREF] - Make attendee component optional

src/views/TechnicalAssistance/AdviceLetterForm/index.tsx
- Fixed advice letter redirect
[https://docs.google.com/document/d/1HSmSXe6Wg7emBg59s3qFn7lINZnComsbpyVBlEJHb3Y/edit#heading=h.eneayqfkstqf](https://docs.google.com/document/d/1HSmSXe6Wg7emBg59s3qFn7lINZnComsbpyVBlEJHb3Y/edit#heading=h.eneayqfkstqf)
=> [NOREF] - Fixed advice letter redirect

src/types/flags.ts, src/views/FlagsWrapper/index.tsx
- [add itGovV2Enabled feature flag](https://github.com/CMSgov/easi-app/commit/32b5d203b6d0c549edf52ff326a9a9dedf944664)
- Introduce feature flag in [Launch Darkly](https://app.launchdarkly.com/default/production/features/itGovV2Enabled/targeting)
1. Verify the flag is configured as expected in Launch Darkly
2. Verify that flag is introduced appropriately in the front end code.
=> EASI-2884 add itGovV2Enabled feature flag

src/constants/helpFeedback.ts, src/views/Help/SendFeedback/__snapshots__/index.test.tsx.snap
- Added Technical Assistance as an option for both Send Feedback and Report a Problem footer forms
- Removed Section 508 from footer forms
=> [EASI-3002] Update footer forms

src/views/Home/AdminHome.tsx
- Center aligned home admin view dropdown and label (change requested by Zoe)
Before:
After:
=> [NOREF] Fix home admin view dropdown alignment

src/i18n/en-US/articles/governanceReviewTeam.ts
- Remove Valerie Hartz and add Savannah Huttenberger
=> [NOREF] Modify Governance Review Team Admin List

src/views/TimeOutWrapper/index.tsx
See MINT PR https://github.com/CMSgov/mint-app/pull/602
See MINT PR https://github.com/CMSgov/mint-app/pull/602
=> [EASI-3044] Increase activity timeout to 90m total

pkg/cedar/core/role.go
* Simplify the logic for calculating `roleTypesAfter` by just looking them up in the `roleTypesByID` map.
* Set `.DidAdd` and `.DidDelete` outside goroutines to avoid some potential weird data race.
I've tested this with CEDAR Impl, the logic looks correct.
Some formatting notes on email, based on these two examples:
> Change:
> Before: Dylan Sprague; Subject Matter Expert (SME),System Developer,System Developer
> After: Dylan Sprague;
> Change:
> Before: Dylan Sprague;
> After: Dylan Sprague; Program Manager
* We may want to join the role type names with `, ` (with a space) instead of just a comma
* Not sure if we want to have some special handling for the case where someone doesn't have any roles
=> Simplify logic in calculating changed roles

.github/workflows/deploy_to_environment.yml
- Will pin to use $LATEST db_clean lamda version in deploy pipeline
Manual deploy has already confirmed functionality
=> [NOREF] fix db clean lamda version

src/i18n/en-US/articles/governanceReviewTeam.ts, src/i18n/en-US/intake.ts, src/views/GovernanceReviewTeam/Actions/__snapshots__/SubmitAction.test.tsx.snap, src/views/GovernanceReviewTeam/Documents/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx, src/views/GovernanceReviewTeam/subNavItems.ts, src/views/GovernanceTaskList/index.test.tsx, src/views/RequestTypeForm/index.test.tsx, src/views/SystemIntake/Documents/DocumentsTable.tsx
[Figma](https://www.figma.com/file/JE39JNLbCSha4fk1m9ayPP/IT-Governance-Updates?type=design&node-id=317-6018&mode=design&t=eQLBClA8RBXfGpy7-0)
- Added Uploaded Documents side nav link
- Created Uploaded Documents admin view with documents table
- Updated tests
1. Sign in as GRT admin
2. Create system intake with document(s)
3. View intake documents page as admin (/governance-review-team/:ID/documents)
=> [EASI-1782] System intake admin documents

.gitignore, migrations/V144__Create_System_Intake_Task_states.sql, pkg/graph/generated/generated.go, pkg/graph/resolvers/it_gov_task_statuses.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/it_gov_task_statuses.go, pkg/models/system_intake.go
- Introduce a state for each step that needs to be persisted in SQL and GQL.
- requestFormState
- draftBusinessCaseState
- finalBusinessCaseState
- decisionState
- Introduce a computed property for columns that already determine state and don't need another column persisted
- grtMeetingState
- grbMeetingState
I didn't add another column for the meeting states because it effectively denormalizes the data. We can say if a meeting was scheduled or not by the presence of a date. There was mention of what should happen if a meeting gets rescheduled, but this should fit in with the current paradigm. If additional state does need to be saved for the future, we can implement this in the ticket to implement the trb meeting state.
I also chose to store one shared type for the form state. Each form …
=> Easi 3054/it gov task states

src/views/SystemProfile/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/index.tsx
Follow-up on [a ux find](https://oddball.slack.com/archives/C059N01AYGM/p1688673294615399)
=> No border radius on system profile summary box

src/data/mock/trbRequest.ts, src/i18n/en-US/technicalAssistance.ts, src/views/TechnicalAssistance/AdminHome/Consult.test.tsx, src/views/TechnicalAssistance/AdminHome/Consult.tsx, src/views/TechnicalAssistance/AdminHome/RequestEdits.test.tsx, src/views/TechnicalAssistance/AdminHome/RequestEdits.tsx, src/views/TechnicalAssistance/AdminHome/components/ActionFormWrapper/index.tsx
- Fixes bugs caused by Request Edits, Ready for Consult, and Schedule Consult forms being completed outside of correct step
- Disables Request Edits and Ready for Consult forms if form is in draft or feedback has already been completed
- Disables Schedule Consult form if request has not yet been marked as ready for consult
- Check that form fields are hidden and alert is displayed if request is not in correct step
- Request Edits: /trb/:trbRequestId/initial-request-form/request-edits
- Ready for Consult: /trb/:trbRequestId/initial-request-form/ready-for-consult
- Schedule Consult: /trb/:trbRequestId/initial-request-form/schedule-consult
- Check that all code is adequately covered by tests - if …
=> [NOREF] TRB actions form fix

docker-compose.ci_server_test.yml, docker-compose.yml
- updated the postgres engine version to 14.4
=> updated the postgres engine version to 14.4

pkg/oktaapi/client_wrapper.go
- Capitalize EUAs that get returned from Okta.
=> [NOREF] Capitalize logins coming back from Okta

src/components/AccessibilityRequestsTable/index.test.tsx, src/i18n/en-US/accessibility.ts, src/i18n/en-US/home.ts, src/i18n/en-US/systemProfile.ts, src/i18n/en-US/technicalAssistance.ts, src/views/MyRequests/Table/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/AdviceLetterForm/Done.tsx, src/views/TechnicalAssistance/RequestForm/__snapshots__/Basic.test.tsx.snap, src/views/TechnicalAssistance/RequestForm/__snapshots__/Check.test.tsx.snap, src/views/TechnicalAssistance/__snapshots__/PublicAdviceLetter.test.tsx.snap, src/views/TechnicalAssistance/__snapshots__/index.test.tsx.snap
Replaces all field labels of "Request name" with "Project title" across the site.
=> Rename "Request name" field titles to "Project title"

.github/dependabot.yml
- Added `npm` to Dependabot config at the same interval/limit as the other ecosystems.
Thanks to @dynamike for the heads up!
- There's nothing really to test here, other than that the dependabot config itself is valid, which is called out in the checks for this PR!
=> [NOREF] Add npm to dependabot

.github/workflows/run_tests.yml
- remove extra node setup, yarn install, and yarn build steps as we already build frontend assets for test in earlier workflow.
=> E2E CI pipeline Improvements p1

scripts/rds-snapshot-app-db
- retain 10 manual snapshots by deleting anything older than the newest 10 snapshots per env. runs as part of snapshot creation process during deploy.
=> [NOREF] Delete RDS manual snapshots

src/i18n/en-US/systemProfile.ts, src/views/SystemProfile/index.tsx
- Add temporary "edits requested" banner to all non-editable System Profile sub pages
=> [EASI-3126] Edits Requested System Profile Banner

pkg/graph/resolvers/itgovactions/lcidactions/expire_lcid.go, pkg/graph/resolvers/itgovactions/lcidactions/expire_lcid_test.go, pkg/graph/resolvers/system_intake_actions.go, src/i18n/en-US/action.ts, src/queries/CreateSystemIntakeActionExpireLcidQuery.ts, src/queries/types/CreateSystemIntakeActionExpireLcid.ts, src/types/graphql-global-types.ts, src/validations/actionSchema.ts, src/views/GovernanceReviewTeam/Actions/ManageLcid/ExpireLcid.tsx
[Figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=429-114014&mode=design&t=9mQLI3qT60QApN7q-0)
- Expire LCID action form
1. Log in as IT Gov admin with `itGovV2Enabled` flag turned on
2. Run `scripts/dev db:seed`
3. Go to /governance-review-team/1c770109-37ff-442c-8312-69e2c0c19b33/actions
5. Select "Manage a Life Cycle ID (LCID)"
6. Select "Expire a Life Cycle ID"
7. Ensure form works as expected
=> [EASI-3186] - Expire LCID action

src/components/RequestRepository/csvHeaderMap.ts, src/components/RequestRepository/csvPortfolioReportHeaderMap.ts
- Fixed CSV export column header mapping for requester
- Updated `requester.name` to `requesterName`
- Updated `requester.component` to `requesterComponent`
- Check that requester name and component shows up in CSV exports and Portfolio Update Report
=> [NOREF] Fix CSV export requester column

src/utils/csv.ts
This relates to a bug brought up in [this Slack thread](https://cmsgov.slack.com/archives/C0305U1014Y/p1697489021384909?thread_ts=1697478221.559489&cid=C0305U1014Y)
- Problem: text that includes quotation marks is being split into multiple columns/rows ([github issue](https://github.com/react-csv/react-csv/issues/252))
- Fix: replacing quotation marks with double quotation marks before exporting to CSV ([solution with explanation](https://stackoverflow.com/a/46638833))
- Fill out and submit intake request form
- For Business Solution, enter this text (from intake that caused reported issue in prod):
>he PM/COR along with the CO/CS have determined that no known constraints apply.
>  
>The above determination was arrived at due to the following;
>\- CMMI models are developed based upon …
=> [NOREF] Fix CSV export bug

.github/workflows/pr_label_checks.yml
- Add on synchronize and ready_for_review
=> Add on synchronize and ready_for_review

pkg/storage/business_case.go
- Change order of logging & error type checking in `FetchBusinessCaseBySystemIntakeID`
- Create a System Intake (submit it, don't create a business case)
- Fetch the System Intake via the GQL query, and ensure your query requests the `SystemIntake.BusinessCase` object
- Ensure you get back a `null` businesscase, and no error is logged!
=> [NOREF] Reorder store logging to be after error type check

src/i18n/en-US/action.ts, src/queries/CreateSystemIntakeActionRejectIntakeQuery.ts, src/queries/types/CreateSystemIntakeActionRejectIntake.ts, src/types/graphql-global-types.ts, src/validations/actionSchema.ts, src/views/GovernanceReviewTeam/Actions/Resolutions/IssueLcid.test.tsx, src/views/GovernanceReviewTeam/Actions/Resolutions/NotApproved.tsx, src/views/GovernanceReviewTeam/Actions/components/ActionForm.tsx
[Figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=1-25110&mode=design&t=FtBIpeVhthdEQacD-0)
- IT Gov action form for Not Approved By GRB
- Log in with `itGovV2Enabled` flag turned on
- Go to /governance-review-team/:systemId/actions
- Select "Issue a decision or close this request"
- Select "Not approved by GRB"
- Test action form
=> [EASI-3233] Not approved by GRB action

src/i18n/en-US/action.ts, src/queries/CreateSystemIntakeActionReopenRequestQuery.ts, src/queries/types/CreateSystemIntakeActionReopenRequest.ts, src/types/graphql-global-types.ts, src/views/GovernanceReviewTeam/Actions/Resolutions/ReopenRequest.tsx
[Figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=331-105040&mode=design&t=ZerVbRCEi6gckhZ5-0)
- Re-open request action form
1. Log in with itGovV2Enabled flag turned on
2. Go to /governance-review-team/:systemId/actions
3. Select "Issue a decision or close this request"
4. Select "Close request" and complete form
5. Select "Issue a decision or re-open this request"
6. Select "Re-open request"
7. Test action form
=> [EASI-3235] Re-open request action

src/data/mock/govTaskList.ts, src/data/mock/systemIntake.ts, src/i18n/en-US/action.ts, src/queries/CreateSystemIntakeActionProgressToNewStepQuery.ts, src/queries/GetGovernanceTaskListQuery.ts, src/queries/types/CreateSystemIntakeActionProgressToNewStep.ts, src/queries/types/GetGovernanceTaskList.ts, src/types/graphql-global-types.ts, src/validations/actionSchema.ts, src/views/GovernanceReviewTeam/Actions/ManageLcid/RetireLcid.test.tsx, src/views/GovernanceReviewTeam/Actions/ManageLcid/RetireLcid.tsx, src/views/GovernanceReviewTeam/Actions/ProgressToNewStep.tsx, src/views/GovernanceReviewTeam/Actions/components/ActionForm.scss, src/views/GovernanceReviewTeam/Actions/components/ActionForm.tsx, src/views/GovernanceReviewTeam/Actions/components/ActionsSummary.tsx, src/views/GovernanceReviewTeam/Actions/index.test.tsx, src/views/GovernanceReviewTeam/Actions/index.tsx, src/views/TechnicalAssistance/AdminHome/__snapshots__/RequestEdits.test.tsx.snap, src/views/TechnicalAssistance/AdminHome/components/ActionFormWrapper/__snapshots__/Index.test.tsx.snap, src/views/TechnicalAssistance/AdviceLetterForm/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/Breadcrumbs.tsx, src/views/TechnicalAssistance/RequestForm/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/__snapshots__/PublicAdviceLetter.test.tsx.snap, src/views/TechnicalAssistance/__snapshots__/index.test.tsx.snap
[Figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=1-24083&t=dctzYjmLuYv8UIDH-0)
- Progress to new step action form
- Confirmation modal if edits have been requested
Notes on field validation:
- Selecting current step for "Which step of the IT Governance process should this request move to?" shows field error
- For Meeting date field, past date is allowed but shows warning below date picker
1. Log in with `itGovV2Enabled` flag turned on
2. Complete new intake form (action cannot be completed with seeded data because of mismatched v1/v2 fields)
3. Go to /governance-review-team/:systemId/actions
4. Select "Progress to a new step"
6. Test action form …
=> [EASI-3125] Progress to new step action

pkg/models/system_intake.go
- Copies changes from @mynar7's branch (https://github.com/CMSgov/easi-app/compare/EASI-2654/update-existing-it-gov-emails#diff-07247fb68505580ef17baf4c0aed9f612b250285815c54a4ee893d3228bebc6f) that update the SetV2FieldsBasedOnV1Status function.
=> [NOREF] Update SetV2FieldsBasedOnV1Status

src/components/FeedbackBanner/index.tsx, src/i18n/en-US/taskList.ts, src/queries/GetGovernanceRequestFeedbackQuery.ts, src/queries/types/GetGovernanceRequestFeedback.ts, src/queries/types/GovernanceRequestFeedback.ts, src/stylesheets/print.scss, src/types/graphql-global-types.ts, src/views/App/index.tsx, src/views/GovernanceTaskList/Feedback/FeedbackItem.tsx, src/views/GovernanceTaskList/Feedback/__snapshots__/index.test.tsx.snap, src/views/GovernanceTaskList/Feedback/index.test.tsx, src/views/GovernanceTaskList/Feedback/index.tsx, src/views/PrepareForGRB/__snapshots__/index.test.tsx.snap
- Created [new feedback page](https://github.com/CMSgov/easi-app/blob/EASI-3088/feedback-edits-requested-page/src/views/GovernanceTaskList/Feedback/index.tsx) for IT Gov v2
- Updated routes to hide new page behind feature flag
- Download feedback as PDF button functionality 
- Dynamic breadcrumbs and return link based on if you are navigating from the task list vs form feedback banner
- Set using [location state](https://github.com/CMSgov/easi-app/blob/EASI-3088/feedback-edits-requested-page/src/views/GovernanceTaskList/Feedback/index.tsx#L35-L40) from [FeedbackBanner link](https://github.com/CMSgov/easi-app/blob/EASI-3088/feedback-edits-requested-page/src/components/FeedbackBanner/index.tsx#L39-L45)
- Unit tests  
1. Go to /governance-review-team/:systemId/actions
2. Complete "Progress …
=> [EASI-3088] IT Gov v2 feedback page

src/i18n/en-US/articles/governanceReviewTeam.ts, src/queries/GetGovernanceRequestFeedbackQuery.ts, src/queries/types/GetGovernanceRequestFeedback.ts, src/views/GovernanceReviewTeam/AccordionNavigation/index.tsx, src/views/GovernanceReviewTeam/Feedback/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx, src/views/GovernanceReviewTeam/subNavItems.ts, src/views/GovernanceTaskList/Feedback/FeedbackList.tsx, src/views/GovernanceTaskList/Feedback/__snapshots__/index.test.tsx.snap, src/views/GovernanceTaskList/Feedback/index.test.tsx, src/views/GovernanceTaskList/Feedback/index.tsx
[Figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=1260-124150&mode=design&t=7rlZ36rxlb9nWhM3-0)
- Added Feedback tab to IT Gov admin section
- Tab navigation links and route are hidden behind `itGovV2Enabled` feature flag
- `FeedbackList` reusable component (src/views/GovernanceTaskList/Feedback/FeedbackList.tsx)
- Created from existing `GovernanceFeedback` component
- Made "Return to Task List" button optional
- Added info alert if request has no feedback
- Complete Edits Requested action on intake request to create feedback
- Go to /governance-review-team/:systemId/feedback to view admin feedback tab
- Check that all code is adequately covered …
=> [EASI-3576] IT Gov feedback tab

src/components/BusinessCaseReview/__snapshots__/index.test.tsx.snap, src/components/BusinessCaseReview/index.tsx, src/i18n/en-US/businessCase.ts, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionA.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionB.tsx, src/views/BusinessCase/AlternativeSolution/AlternativeSolutionFields.tsx, src/views/BusinessCase/BusinessCaseStepWrapper.tsx, src/views/BusinessCase/GeneralRequestInfo/index.tsx, src/views/BusinessCase/PreferredSolution/index.tsx, src/views/BusinessCase/RequestDescription/index.tsx, src/views/BusinessCase/Review/index.tsx, src/views/BusinessCase/ViewOnly/index.tsx
[Figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=11-22050&mode=design&t=GqkHWN7JBUykvLhG-0)
Note: Figma shows banner on intake form, but everything should be the same except replacing "Intake Request" with "Draft Business Case" or "Final Business Case".
- Added edits requested banner (`FeedbackBanner` component created in EASI-3448) to draft and final business cases
- Created `BusinessCaseStepWrapper` component to reduce duplicate logic to show feedback banner
- Includes feedback banner, title, description, error summary, and mandatory fields alert
- Business case text translations
- Misc. cleanup on business case form steps
- Mostly implementing updated components for consistency (`TextAreaField` for built-in character counter, …
=> [EASI-3450, EASI-3453] Business case edits requested banner

src/components/TaskList/index.tsx, src/i18n/en-US/itGov.ts, src/views/GovernanceTaskList/GovTaskBizCaseDraft/index.test.tsx, src/views/GovernanceTaskList/GovTaskBizCaseDraft/index.tsx, src/views/GovernanceTaskList/GovTaskBizCaseFinal/index.test.tsx, src/views/GovernanceTaskList/GovTaskBizCaseFinal/index.tsx, src/views/GovernanceTaskList/GovTaskDecisionAndNextSteps/index.tsx, src/views/GovernanceTaskList/GovTaskFeedbackFromInitialReview/index.test.tsx, src/views/GovernanceTaskList/GovTaskFeedbackFromInitialReview/index.tsx, src/views/GovernanceTaskList/GovTaskGrtMeeting/index.test.tsx, src/views/GovernanceTaskList/GovTaskGrtMeeting/index.tsx, src/views/GovernanceTaskList/GovTaskIntakeForm/index.test.tsx, src/views/GovernanceTaskList/GovTaskIntakeForm/index.tsx, src/views/GovernanceTaskList/index.test.tsx, src/views/GovernanceTaskList/index.tsx
[Figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=4369%3A86908&mode=design&t=j9uqoXnIVDNGzXpW-1)
- Updated feedback links in task list
- Changed "view feedback" to "view requested edits"
- Removed feedback link from GRB Meeting step
- Updated alert text for no feedback
- Added general feedback banner with link to view feedback ([Figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=4370%3A88401&mode=design&t=rlkY5cb2g5qR6HmA-1))
- Added alert for issued decision
- This was not in the ticket, but is shown in the [Figma](https://www.figma.com/file/ChzAP34A2DVvQUNQwD7lCt/IT-Governance-Next?type=design&node-id=4370%3A89931&mode=design&t=rlkY5cb2g5qR6HmA-1)
- Updated unit tests 
- Review text changes in …
=> [EASI-3446] Central task list feedback link

src/i18n/en-US/taskList.ts
=> [EASI-3030] Fix missing 'Governance Team' translation

cmd/migrate_intakes/main.go
- Update script to set biz case form states so that requesters can still view submitted biz cases on requests in V2 task list
=> [NOREF] Update V1 to V2 migration script to update biz case form states

src/i18n/en-US/action.ts, src/i18n/en-US/articles/governanceReviewTeam.ts, src/i18n/en-US/businessCase.ts, src/i18n/en-US/intake.ts, src/i18n/en-US/itGov.ts, src/views/BusinessCase/Confirmation/__snapshots__/index.test.tsx.snap, src/views/GovernanceReviewTeam/Actions/index.test.tsx, src/views/GovernanceReviewTeam/ActionsV1/__snapshots__/SubmitAction.test.tsx.snap, src/views/GovernanceReviewTeam/Documents/index.tsx, src/views/GovernanceReviewTeam/Summary/index.tsx, src/views/GovernanceReviewTeam/subNavItems.ts
Text update items from UX doc:
- [“Intake Request” form, not Initial request form](https://docs.google.com/document/d/1oZBAphS7VgoFIjcTXMSyXfb6LbAQMylTqPxMxlzHnyU/edit#heading=h.90rli3kmdkxr)
- [Risk register language](https://docs.google.com/document/d/1oZBAphS7VgoFIjcTXMSyXfb6LbAQMylTqPxMxlzHnyU/edit#heading=h.62k6dbsptxdn)
- [Retirement date field help text typo](https://docs.google.com/document/d/1oZBAphS7VgoFIjcTXMSyXfb6LbAQMylTqPxMxlzHnyU/edit#heading=h.i45pnzpkrjnh)
- [Sentence case governance task list page header and breadcrumbs](https://docs.google.com/document/d/1oZBAphS7VgoFIjcTXMSyXfb6LbAQMylTqPxMxlzHnyU/edit#heading=h.ehgj08jqktek)
- [Documents admin side nav label, page title, and missing description](https://docs.google.com/document/d/1oZBAphS7VgoFIjcTXMSyXfb6LbAQMylTqPxMxl …
=> [EASI-3716] IT Gov UX QA text updates

src/i18n/en-US/taskList.ts, src/queries/GetGovernanceRequestFeedbackQuery.ts, src/queries/types/GetGovernanceRequestFeedback.ts, src/views/GovernanceTaskList/Feedback/FeedbackList.tsx, src/views/GovernanceTaskList/Feedback/index.test.tsx
From UX doc: [Give PDF downloads human-readable names](https://docs.google.com/document/d/1oZBAphS7VgoFIjcTXMSyXfb6LbAQMylTqPxMxlzHnyU/edit#heading=h.5y2ehepimae)
- Replaced system intake ID with request name in feedback PDF titles
- Add feedback to system intake request
- Go to feedback admin page (/governance-review-team/:systemIntakeId/feedback)
- Click "Download feedback as PDF" link
- PDF filename should be "Feedback for {request name}"
=> [EASI-3716] Update feedback PDF file names

src/i18n/en-US/itGov.ts, src/views/GovernanceTaskList/index.tsx
[Link to item on UX doc](https://docs.google.com/document/d/1oZBAphS7VgoFIjcTXMSyXfb6LbAQMylTqPxMxlzHnyU/edit#heading=h.o6wieh7jlttx)
- Added request name to task list
=> [EASI-3716] Project title on task list

src/validations/businessCaseSchema.ts
Fixes business case validation for isBeingReviewed field - [issue described here](https://github.com/CMSgov/easi-app/pull/2318#issuecomment-1852777989)
=> [NOREF] Fix business case validation for isBeingReviewed field

src/i18n/en-US/technicalAssistance.ts, src/views/TechnicalAssistance/AdviceLetterForm/Done.tsx
- Fixed typo in success page text
- Updated success page breadcrumbs
- Submit advice letter
- Confirm text changes
=> [EASI-3822] Advice letter success page fixes

cypress/e2e/governanceReviewTeam.cy.js
Created tests for retire/expire LCID action forms:
- Retire LCID
- Update LCID retirement date
- Expire LCID
=> [EASI-3718] IT Gov v2 Cypress tests - retire/expire LCID

cypress/e2e/governanceReviewTeam.cy.js, src/views/GovernanceReviewTeam/Actions/index.tsx
- New Cypress test for Progress to a New Step action form
- Tests progressing to GRT step and setting meeting date
=> [EASI-3720] IT Gov v2 Cypress tests - progress to a new step

pkg/graph/generated/generated.go, pkg/graph/model/models_gen.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go
- Introduces several new query and mutation definitions that will define how we'll implement the System Intake linking logic for System-Centric EASi
This does not add any actual resolver logic, but just helps to set the direction that we want to go with these resolvers!
This shouldn't change any existing logic. Make sure the app compiles, and everything is named / designed as you'd expect!
=> [NOREF] GQL Schema for System Intake linking

pkg/integration/integration_test.go
=> [NOREF] Disable integration test suite while we figure out Okta auth

src/types/flags.ts, src/views/FlagsWrapper/index.tsx
- Added flag value for IT Gov Request Linking for Requesters
- Make sure everything compiles and runs! This flag's not currently used anywhere, so this shouldn't affect anything
=> [EASi-3755 / EASI-3877] Added default flag value for IT Gov Request Linking

pkg/graph/resolvers/system_intake_relation.go, pkg/storage/system_intake.go
- Create new functions to support transactions for Fetching and Updating System Intakes
- This should be a no-op to all existing functionality, so a smoke test of the app should suffice!
- Testing the mutations from https://github.com/CMSgov/easi-app/pull/2400 is also a good idea, as this PR modifies those mutations to use this new transactional logic more directly
=> [NOREF] Support Transactions in databases

.github/PULL_REQUEST_TEMPLATE.md, .spelling, CONTRIBUTING.md, README.md
- Add documentation to cover standards for branch and PR naming
- Read with your special eyes! 👀 
=> [NOREF] Add & update standards for branch and PR naming

pkg/graph/resolvers/resolver_test.go
- Add embedded `*require.Assertions` to ResolverSuite so that calls to functions that would otherwise be fulfillfed by `assert` are instead fulfilled by `require`
- The only difference between these packages is `require` will fail/stop an entire test when it fails, while `assert` will continue to run.
The goal of this PR is to make the default behavior for our Resolver test suite to stop a given test when a failure is reached. This allows us to more easily use logic like [this](https://github.com/CMSgov/easi-app/blob/f4fd4a9be88f640a5bb1aa0ce32720f69bb955b1/pkg/graph/resolvers/system_intake_relation_test.go#L48-L49) to ensure that pointers aren't `nil` before dereferencing in a test. It also helps keep unrelated failure output a bit more clean, since most subsequent failures in a test …
=> [NOREF] Replace use of assert with require in Resolver test suite

src/i18n/en-US/technicalAssistance.ts, src/views/TechnicalAssistance/RequestForm/DocumentUpload.tsx
- Expanded allowed file types for TRB Initial request form document upload
- Updated hint text to reflect additional allowed file types
- Create a TRB request
- Progress to TRB document upload
- Verify help text matches AC
- Verify document upload of each new type with samples
- Run `scripts/dev mino:clean`
- Download each sample
- Verify each opens successfully
=> [EASI-4048] - Additional file upload types, help text

src/types/flags.ts, src/views/FlagsWrapper/index.tsx
- Added LD flags for IT Gov and TRB Admin linked systems
- Added default value and type for both flags in code
- Verify the default `false` value gets overridden by LD API for both `itgovLinkRequestsAdmin` and `itgovLinkRequestsAdmin` and evaluate to `true` in local development
=> [EASI-3889] LD flags for IT Gov and TRB Admin linked systems

src/data/mock/systemIntake.ts, src/i18n/en-US/intake.ts, src/i18n/en-US/itGov.ts, src/queries/GetGovernanceTaskListQuery.ts, src/queries/SystemIntakeRelationQueries.ts, src/queries/types/GetGovernanceTaskList.ts, src/queries/types/GetSystemIntakeRelation.ts, src/stylesheets/custom.scss, src/types/graphql-global-types.ts, src/views/GovernanceOverview/index.tsx, src/views/GovernanceTaskList/AdditionalRequestInfo.tsx, src/views/GovernanceTaskList/index.tsx, src/views/RequestLinkForm/__snapshots__/index.test.tsx.snap, src/views/RequestLinkForm/index.test.tsx, src/views/RequestLinkForm/index.tsx, src/views/RequestTypeForm/index.test.tsx, src/views/RequestTypeForm/index.tsx
- This adds update functionality to https://github.com/CMSgov/easi-app/pull/2452
- Additional Info sidebar is just a stub at the moment, need to discuss overlap with @patrickseguraoddball
- [GovernanceReviewTeam/AdditionalInformation](https://github.com/CMSgov/easi-app/blob/ebc181ffc91c68833284e09e8e4de0593810f033/src/views/GovernanceReviewTeam/AdditionalInformation/index.tsx) looks nearly identical to a [version I started here](https://github.com/CMSgov/easi-app/blob/5f88fe29c758d6d99d5c47096faaaca91df904d8/src/views/GovernanceTaskList/AdditionalRequestInfo.tsx)
- Seed app data or create a new system intake
- Get to the it gov task list and "Edit Information" to update the request relation link type.
=> [EASI-3874] FE - Linked System Update

cypress/e2e/homepage.cy.js, src/components/TableResults/index.tsx, src/i18n/en-US/home.ts, src/i18n/en-US/tableAndPagination.ts, src/views/Home/index.test.tsx, src/views/Home/index.tsx, src/views/MyRequests/Table/__snapshots__/index.test.tsx.snap, src/views/MyRequests/Table/index.test.tsx, src/views/MyRequests/Table/index.tsx, src/views/MyRequests/Table/tableMap.ts
[Figma](https://www.figma.com/file/z8GeZPDfIh9oKfHK1cX7Fo/System-centric-EASi?type=design&node-id=1003-3694&mode=design&t=QbMlA2XqpGtm98oo-0)
The changes in this PR only pertain to governance processes and other services updates and not `My systems` table work or `Related systems` column on `My open requests`
I also added a filter on the requests data to remove closed requests.  We may want to offload/ticket this for BE dev
- Updated page heading to include user name, subtitle text
- Fix grid column on linking cards
- Made search/filter conditional on the presence of more than one page
- Updated table header text
- Reordered columns per figma
- Added `<Alert />` empty state
- Update unit testes
- Verify empty state on no requests
- Verify Figma matches with requests
- Verify search/filter …
=> [EASI-4074] User home - governance processes and other services updates

src/views/GovernanceTaskList/index.tsx
- Added flag around task list side nav system linking work
Verify that the IT Gov task list side nav does not render any of the linking system contect
=> [NOREF] - Added feature flag around task list linking

pkg/cedar/core/software_products.go, pkg/graph/schema.resolvers.go, src/i18n/en-US/systemProfile.ts, src/views/SystemProfile/components/ToolsAndSoftware/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/ToolsAndSoftware/index.scss, src/views/SystemProfile/components/ToolsAndSoftware/index.tsx
- Fix issue with missing Vendor Name field
- Add ELA purchase notice to software products
=> [EASI-3569] Tools & Software Fixes

.golangci.yml, .pre-commit-config.yaml, cmd/backfill/main.go, cmd/devdata/main.go, pkg/appconfig/config.go, pkg/cedar/core/system_summary_test.go, pkg/graph/resolvers/it_gov_task_statuses_test.go, pkg/graph/resolvers/system_intake_status_admin_test.go, pkg/graph/resolvers/system_intake_status_requester_test.go, pkg/integration/business_case_test.go, pkg/integration/system_intakes_test.go, pkg/services/services_test.go, pkg/storage/governance_request_feedback.go, pkg/storage/system_intake_test.go, pkg/testhelpers/okta.go
- update lint runner to run using config file
- clean up lint errors, add rule to allow err shadowing for consistent error naming
- run linter locally `golangci-lint run` and `scripts/dev lint`, and confirm output is the same
- also, run tests locally and confirm pass!
=> [NOREF] lint cleanup and config

gqlgen.yml, pkg/cedar/core/client.go, pkg/graph/generated/generated.go, pkg/graph/schema.resolvers.go, pkg/models/gql_scalars.go
- Follow up from a bug missed in https://github.com/CMSgov/easi-app/pull/2481
- TBD
=> [NOREF] Add null int for scalar for GraphQL

pkg/cedar/core/system_summary.go
- @mynar7 found a bug which would cause our cache to get skipped every time - fixed in here
- getting CEDAR systems should speed up after the first time 🙂 
- should not have any effect on `myCedarSystems`
=> [NOREF] fix bug in conditional - thanks Lee!!!

src/i18n/en-US/intake.ts, src/i18n/en-US/itGov.ts, src/i18n/en-US/technicalAssistance.ts, src/stylesheets/custom.scss, src/views/RequestLinkForm/__snapshots__/index.test.tsx.snap, src/views/RequestLinkForm/index.tsx, src/views/SystemIntake/ContractDetails/index.tsx
- Updated `RequestLinkForm` text for TRB and IT Gov
- Added radio hints for contracts
Verify matches Figma
https://www.figma.com/file/z8GeZPDfIh9oKfHK1cX7Fo/System-centric-EASi?type=design&node-id=2792-24721&mode=design&t=wSdQWTl3t0Qw5QoN-0
https://www.figma.com/file/z8GeZPDfIh9oKfHK1cX7Fo/System-centric-EASi?type=design&node-id=2139-133804&mode=design&t=ZG0JL2CpL0O9oTqw-0
https://www.figma.com/file/z8GeZPDfIh9oKfHK1cX7Fo/System-centric-EASi?type=design&node-id=440-31872&mode=design&t=JosbQZfk8b595E8D-0
- Always make comments, even if it's minor, or if you don't understand why …
=> [NOREF] Updated contract linking text

src/i18n/en-US/systemProfile.ts
https://docs.google.com/document/d/1l8epTngbG73Pyz7DDQDvTbbjckuqejbhQ0zI11wG0L8/edit#heading=h.k0n9z6wtpq2e
- Updated home text
=> [NOREF] UX finding - Updated home page text

src/i18n/en-US/home.ts
https://docs.google.com/document/d/1l8epTngbG73Pyz7DDQDvTbbjckuqejbhQ0zI11wG0L8/edit#heading=h.k0n9z6wtpq2e
- Subheader text fix
=> [NOREF] - Subheader text fix

src/types/flags.ts, src/views/App/index.tsx, src/views/FlagsWrapper/index.tsx, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/GovernanceOverview/index.tsx, src/views/GovernanceTaskList/index.tsx, src/views/RequestTypeForm/index.test.tsx, src/views/RequestTypeForm/index.tsx
Remove `itgovLinkRequestsRequester`
Skip tests with side-effects
=> EASI-4035 Remove `itgovLinkRequestsRequester` flag

src/types/flags.ts, src/views/FlagsWrapper/index.tsx, src/views/TechnicalAssistance/ProcessFlow.tsx, src/views/TechnicalAssistance/TaskList.test.tsx, src/views/TechnicalAssistance/TaskList.tsx, src/views/TechnicalAssistance/index.tsx
Remove `trbLinkRequestsRequester` flag
=> EASI-3870 Remove `trbLinkRequestsRequester` flag

deploy/base/db.yaml, docker-compose.ci_server_test.yml, docker-compose.yml
- Upgrade postgres to version 14.11
- This is a minor upgrade with no requirements for backup and restore, therefor testing should be relatively straight forward. You should see no changes in the behavior of the application.
=> EASI-4276: upgrade postgres to 14.11

src/data/mock/systemProfile.ts, src/i18n/en-US/systemProfile.ts, src/queries/GetSystemProfileQuery.ts, src/queries/types/GetSystemProfile.ts, src/views/SystemProfile/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SubSystems/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SubSystems/index.test.tsx, src/views/SystemProfile/components/SubSystems/index.tsx, src/views/SystemProfile/components/index.tsx
Update of the Sub-systems page as seen in [figma](https://www.figma.com/file/z8GeZPDfIh9oKfHK1cX7Fo/System-centric-EASi?type=design&node-id=1259-53124&mode=design&t=QFLI8KutJCcEdnRn-0).
Planned retirement date will be available later.
Unit tests updated with new query and mock data
=> EASI-3849 System Profile - Sub-systems sub-page (FE)

src/components/HelpFooter/__snapshots__/index.test.tsx.snap, src/components/HelpFooter/index.tsx, src/i18n/en-US/itGov.ts, src/views/RequestLinkForm/index.tsx
- EASI-4168 - Added Slack link to footer
- EASI-4206 - Added clarifying text to linking flows for TRB and IT Gov
EASI-4168
- Confirm Slack link appears in footer and works correctly
EASI-4206
- For both TRB and IT Gov, start new requests
- On "Is this request part of an existing system or contract" page, confirm warning shows when first option is selected
=> [EASI-4168, EASI-4206] Text updates

.github/workflows/deploy_to_environment.yml
-  Remove 'if dev' flag for Cedarproxy deploy
=> NOREF - Remove 'if dev' flag for Cedarproxy deploy

pkg/appconfig/config.go, pkg/server/config.go
- Fixes the CEDAR client check for the new/removed env vars.
=> [NOREF] Fix config check for CEDAR

src/views/SystemProfile/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/index.tsx
Enable the Contracts subpage that is already on prod
=> Contracts subpage is accessible without flag

src/components/NavigationBar/index.tsx, src/views/SystemList/__snapshots__/index.test.tsx.snap, src/views/SystemList/index.tsx
- See [request from Zoe](https://oddball.slack.com/archives/C06RSLZ4UKF/p1715787064538969) in the easi-potluck Slack channel
- Updated Systems navigation tab dropdown links:
- "All CMS systems" goes to top of systems page
- "Bookmarked systems" links to bookmarked systems section of systems page
=> [NOREF] Update systems nav links

pkg/cedar/core/system_summary.go, pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/local/cedarcoremock/system_summary.go, pkg/models/cedar_system.go, src/data/mock/systemProfile.ts, src/queries/GetSystemProfileQuery.ts, src/queries/types/GetSystemProfile.ts
- Creating this PR to address some comments @adamodd brought up in https://github.com/CMSgov/easi-app/pull/2598
- Either with mock data or real CEDAR data, navigate to System Profile and ensure the `CedarSystem` returns a `uuid` (or null, if the system doesn't have one)
=> [NOREF] Add CEDAR System UUID

src/components/shared/DescriptionGroup/index.tsx, src/data/mock/systemProfile.ts, src/i18n/en-US/systemProfile.ts, src/queries/GetSystemProfileQuery.ts, src/queries/types/GetSystemProfile.ts, src/utils/showVal.tsx, src/views/SystemProfile/BookmarkToggleButton.tsx, src/views/SystemProfile/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/index.tsx
https://www.figma.com/design/z8GeZPDfIh9oKfHK1cX7Fo/System-centric-EASi?node-id=1131-37102&t=Humrnds5bxhEGCMJ-0
=> EASI-3937 System summary updates (FE)

.github/workflows/run_tests.yml, .pre-commit-config.yaml, scripts/pre-commit-nginx-lint
- Adds nginx changes to pre-commit checks locally
Make changes to any of the files in `/cedarproxy` and run pre-commit.
=> [NOREF] lint nginx in pre-commit

src/views/GovernanceReviewTeam/Actions/ManageLcid/ExpireLcid.tsx, src/views/GovernanceReviewTeam/Actions/ManageLcid/RetireLcid.tsx, src/views/GovernanceReviewTeam/Actions/ManageLcid/UpdateLcid.tsx, src/views/GovernanceReviewTeam/Actions/ProgressToNewStep.tsx, src/views/GovernanceReviewTeam/Actions/RequestEdits.tsx, src/views/GovernanceReviewTeam/Actions/Resolutions/IssueLcid.tsx, src/views/GovernanceReviewTeam/Actions/Resolutions/NotApproved.tsx
- Removed code disabling invalid admin action forms
Test all admin action forms:
- Submit button is not disabled when form is invalid
- Field validation works as expected
=> [EASI-4283] Admin Actions - Date Picker Clarification

src/data/businessCase.test.ts, src/data/businessCase.ts
- Fix issue where alternative B lifecycle cost information was being overwritten by alternative A
Submit business case with all alternatives filled out (preferred, a, and b) and ensure the following:
- Business case can be submitted
- Business case lifecycle cost information is correct for all three alternatives
=> [NOREF] Business case alternative B LifecycleCost bug

src/constants/externalUrls.ts
Updating the cfacts url from the System workspace cards.
@downeyn-cms Feel free to update this branch if it's actually something else.
=> [NOREF] Update cfacts url

src/data/mock/systemProfile.ts, src/queries/GetSystemProfileQuery.ts, src/queries/types/GetSystemProfile.ts, src/views/SystemProfile/components/Contracts/index.tsx
- Previously: https://github.com/CMSgov/easi-app/pull/2645
- This also removes the aliased `systemID` so that the gql client doesn't misidentify objects
=> [NOREF] Fix the ContractCard key Part 2

.pre-commit-config.yaml, EASI.postman_collection.json, scripts/edit_postman_json.sh
- Added script and hook for updating postman collection JSON to remove fields that we don't really need, and often cause conflicts in PRs
- Import and re-export the postman collection, and run `scripts/dev lint` and ensure the file's properly edited!
=> [NOREF] Add script and pre-commit hook to clean up postman collection JSON

pkg/applychanges/apply_changes.go, pkg/cedar/core/budget.go, pkg/flags/client.go
- fix err check
- update `PtrTo()` (deprecated) to preferred `PointerTo()`
- remove unneeded parentheses
=> fix err check

.github/PULL_REQUEST_TEMPLATE.md
- Updates the PR template to have a bit more guidance on what's required and what's not required in a PR description/title.
- Added clarifying comments in the template to provide guidance on how to fill out the PR description
- Modified PR Author Checklist to have the items we _truly_ care about in a PR (often these checkboxes were going unused)
- Read -- read with your special eyes!
- Don't be afraid to leave comments or ask questions, especially if you don't …
=> [NOREF] Update PR template to hopefully be more useful

cmd/devdata/system_intake_grb_reviewers.go, cmd/test_email_templates/main.go, pkg/email/email.go, pkg/email/system_intake_create_grb_reviewer.go, pkg/email/system_intake_create_grb_reviewer_test.go, pkg/email/templates/system_intake_create_grb_reviewer.gohtml, pkg/graph/resolvers/resolver_test.go, pkg/graph/resolvers/system_intake_grb_reviewer.go, pkg/graph/resolvers/system_intake_grb_reviewer_test.go, pkg/graph/schema.resolvers.go
- Adds a new email notification sent to the added reviewer when creating a GRB reviewer for a system intake.
- Adds a call to the email generation code for that new email template.
- Run the automated test suite
- Add a GRB reviewer to an intake using the Postman collection
- Run `scripts/dev email`  …
=> [EASI-4343] Create GRB Reviewer email

EASI.postman_collection.json, cmd/devdata/main.go, pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake.go, pkg/graph/resolvers/system_intake_test.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/sqlqueries/SQL/system_intake_grb_reviewer/get_intakes_where_review_requested.sql, pkg/sqlqueries/system_intake_grb_reviewers.go, pkg/storage/system_intake.go
- Adds a GraphQL query for system intakes where the user is a requested GRB reviewer.
- Adds resolver tests for the new query/resolver.
- Adds the new query to the Postman collection.
- Start the app and seed the database, then use the postman collection to query for intakes where the current user is requested for GRB review.
- Run the automated tests.
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! …
=> [EASI-4327] - Add query for GRB participation requested intakes

src/i18n/en-US/systemProfile.ts, src/types/systemProfile.ts, src/views/SystemProfile/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/ATO/index.scss, src/views/SystemProfile/components/index.tsx, src/views/SystemProfile/pointsOfContactIds.ts
- Rename System Profile subpage in navigation panel from "ATO" to "ATO and Security"
- Go to System Profile module and modal to ensure that ATO and Security sub page is properly named in the side nav panel
- Check that all code is adequately covered by tests - if it isn't feel …
=> [NOREF] Rename System Profile ATO subpage

pkg/graph/schema.resolvers.go, pkg/server/routes.go, pkg/services/action.go, pkg/services/action_test.go, pkg/services/auth.go, pkg/services/auth_test.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/services/system_intakes.go, pkg/services/system_intakes_test.go
- loosen auth to allow for GRB viewers/voters to access system intakes
- remove multi-return where unused (needed for this PR)
- remove some unused functions
- try to load a system intake you should NOT have access to
- add yourself as a GRB reviewer
- try again to load, it should work
- example flow: 
1. locally, log in with `ABCD`, create system intake, copy system intake `id` and store
2. log in with `FAUI` (`EASI_P_USER` only) and attempt to view that system intake (`http://localhost:3000/governance-task-list/<intake UUID>`)
3. it should NOT load
4. in db, run this query
```sql
INSERT INTO system_intake_grb_reviewers (
id,
user_id,
system_intake_id,
voting_role,
grb_role,
created_by,
created_at,
modified_by,
modified_at
) VALUES (
gen_random_uuid(),
(SELECT id FROM user_account WHERE …
```
=> Easi 4328/access control

package.json, src/hooks/useCacheQuery.ts, src/index.tsx, src/types/util.ts, src/utils/testing/VerboseMockedProvider.tsx, src/views/GovernanceReviewTeam/Actions/ManageLcid/RetireLcid.test.tsx, src/views/SystemProfile/components/Team/Edit/index.test.tsx, src/views/TechnicalAssistance/AdminHome/Feedback.test.tsx, src/views/TechnicalAssistance/AdviceLetterForm/index.test.tsx, src/views/TechnicalAssistance/PublicAdviceLetter.test.tsx, src/views/TechnicalAssistance/TrbAdminTeamHome.test.tsx, yarn.lock
Attempting to upgrade some packages from our dependabot list to help reduce the size of those PRs: https://github.com/CMSgov/easi-app/pull/2655
Upgrades `@apollo/client` to the latest version. This change required a few upgrades (`typescript`, really) that were also made in the new [GQL Codegen branch](https://github.com/CMSgov/easi-app/compare/main...NOREF/introduce_new_gql_codegen). Other than those upgrades, nothing else was needed to get this functioning locally and passing tests
- Ensure all local tests pass with `scripts/dev test:js` (or in the pipeline)
- Ensure E2E tests pass in this pipeline
- Ensure that your linter/editor work as expected after running `yarn install --immutable` (as there's a `typescript` upgrade in this PR)
- It's best to pull the branch locally and test it, …
=> [NOREF] Upgrade @apollo/client

cmd/devdata/main.go, cmd/devdata/system_intake.go
- This adds some intakes related by contract number and mock CEDAR system to the seed script. This should aid in [EASI-4411](https://jiraent.cms.gov/browse/EASI-4411).
- It also fixes the seed script to use the system ID that's passed in instead of an empty system struct.
- Start the app locally.
- Run `scripts/dev db:seed`.
- Look at the generated system intake requests.
- Don't be afraid to leave comments or ask questions, especially if you don't understand why …
=> [NOREF] Add related intakes to seed data

pkg/server/routes.go
- This just changes the email service URL in the app from docker's internal URL to that of the service name. This should match up with k8s as well as docker compose.
- Send an email to mailcatcher!
- Check that all code is adequately covered by tests - if it isn't feel free to …
=> NOREF - change email URL to service name instead of internal docker host

src/i18n.ts
EASI was having instances where special HTML character were getting escaped by react-i18n library via interpolation values, as well as React (natively parsing all JSX values as plain text/not computed by the browser - we do NOT have `dangerouslysetinnerhtml` set in the application).  This was leading to special characters being escaped and also being rendered as plain text - ex: `Patrick&#39;s`
https://oddball.slack.com/archives/C059N01AYGM/p1719943391656779
- Verify user input characters are rendered as human readable throughout the app.  The are handled as plaint text natively by React
- e.g. "Approving because I tested it …
=> [NOREF] Added escapeValue false for i18n

pkg/graph/resolvers/resolver_test.go
- Just a small refactor of two helpers. Sometimes we want to make a request with certain properties set and this just adds that ability to the helpers through an optional callback fn.
- No modifications were made to existing tests, the function signatures changed but the callback is variadic and therefore optional.
- Run the test suite.
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a …
=> [NOREF] make resolver test helpers variadic for future use

src/views/SystemWorkspace/components/RequestsCard/index.tsx, src/views/SystemWorkspace/components/SpacesCard/__snapshots__/index.test.tsx.snap, src/views/SystemWorkspace/components/SpacesCard/index.tsx
Adjust some spacing
- https://cmsgov.slack.com/archives/CNU2B59UH/p1720627571612089
- https://www.figma.com/design/z8GeZPDfIh9oKfHK1cX7Fo/System-centric-EASi?node-id=4239-52213&t=opQylzp0lJuRaImV-0
=> [NOREF] Adjust spacing in Requests Card

pkg/dataloaders/dataloaders.go, pkg/dataloaders/fetch_user_info.go, pkg/dataloaders/trb_request_forms.go, pkg/graph/resolvers/trb_request_feedback_test.go, pkg/graph/resolvers/trb_request_form.go, pkg/graph/resolvers/trb_request_form_test.go, pkg/helpers/mapper.go, pkg/models/trb_request_form.go, pkg/models/user_info.go, pkg/sqlqueries/SQL/trb_request_form/get_by_ID.sql, pkg/sqlqueries/SQL/trb_request_form/get_by_IDs.sql, pkg/sqlqueries/trb_request_form.go, pkg/storage/trb_request_form.go
- Adds a dataloader to the TRB Request Form Resolver.
- Cleans up a few resolver tests
- Introduces a OneToOne helper!
- Ask for the `form` field when pulling TRB Requests.
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of …
=> [EASI-4457] Add dataloader to TRB request form resolver

pkg/dataloaders/dataloaders.go, pkg/dataloaders/system_intake_notes.go, pkg/graph/resolvers/system_intake_notes.go, pkg/graph/resolvers/system_intake_notes_test.go, pkg/models/system_intake_note.go, pkg/sqlqueries/SQL/system_intake_notes/get_by_intake_ID.sql, pkg/sqlqueries/SQL/system_intake_notes/get_by_intake_IDs.sql, pkg/sqlqueries/system_intake_notes.go, pkg/storage/system_intake_note.go
- Adds a dataloader for System Intake Notes
- Adds some basic tests for notes since apparently we never wrote any!
- Request the `notes` property on SystemIntakes in the GQL playground.
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the …
=> [EASI-4457] System intake notes dataloader

src/i18n/en-US/grbReview.ts, src/i18n/en-US/index.ts, src/types/flags.ts, src/views/FlagsWrapper/index.tsx, src/views/GovernanceReviewTeam/GRBReview/index.test.tsx, src/views/GovernanceReviewTeam/GRBReview/index.tsx, src/views/GovernanceReviewTeam/RequestOverview.tsx, src/views/GovernanceReviewTeam/subNavItems.ts
[Figma - GRB reviewer view](https://www.figma.com/design/G0UN35V7SY0g9nkTIESxsY/EASi-GRB-Experience?node-id=2266-44387&t=q1jIOcf03qyu8w8p-0)
[Figma - GRT admin view](https://www.figma.com/design/G0UN35V7SY0g9nkTIESxsY/EASi-GRB-Experience?node-id=2266-44336&t=q1jIOcf03qyu8w8p-1)
- Created GRB review admin tab
- [Figma - GRB reviewer view](https://www.figma.com/design/G0UN35V7SY0g9nkTIESxsY/EASi-GRB-Experience?node-id=2266-44387&t=q1jIOcf03qyu8w8p-0)
- [Figma - GRT admin view](https://www.figma.com/design/G0UN35V7SY0g9nkTIESxsY/EASi-GRB-Experience?node-id=2266-44336&t=q1jIOcf03qyu8w8p-1)
- Participants table and linking "add a GRB reviewer" button are handled in separate tickets
- Added GRB review link to admin navigation
- Hid navigation link and route behind feature flag
1. Log in as GRT …
=> [EASI-4331] GRB review admin tab

pkg/dataloaders/dataloaders.go, pkg/dataloaders/system_intake_actions.go, pkg/graph/resolvers/system_intake_actions_test.go, pkg/graph/schema.resolvers.go, pkg/models/action.go, pkg/sqlqueries/SQL/system_intake_actions/get_by_intake_ID.sql, pkg/sqlqueries/SQL/system_intake_actions/get_by_intake_IDs.sql, pkg/sqlqueries/system_intake_actions.go, pkg/storage/action.go, pkg/storage/action_test.go
- Adds a dataloader for the `actions` on the `SystemIntake` resolver.
- Also enables accessing `SystemIntake` on the action, since that was not possible before for some reason.
- 
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition …
=> [EASI-4457] System Intake Actions dataloader

src/views/SystemProfile/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SystemHome/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/SystemHome/index.tsx
- Fixed broken ATO link on system homepage
- Issue brought up in [easi-potluck](https://oddball.slack.com/archives/C06RSLZ4UKF/p1721305249977829)
- Make sure ATO link is working
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition …
=> [NOREF] Fix ATO link on system home

pkg/dataloaders/dataloaders.go, pkg/dataloaders/trb_request_documents.go, pkg/graph/resolvers/governance_request_feedback.go, pkg/graph/resolvers/system_intake_notes.go, pkg/graph/resolvers/system_intake_notes_test.go, pkg/graph/resolvers/trb_request_attendee.go, pkg/graph/resolvers/trb_request_attendee_test.go, pkg/graph/resolvers/trb_request_document.go, pkg/graph/resolvers/trb_request_document_test.go, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_test.go, pkg/models/trb_request_document.go, pkg/sqlqueries/SQL/trb_request_documents/get_by_TRB_ID.sql, pkg/sqlqueries/SQL/trb_request_documents/get_by_TRB_IDs.sql, pkg/sqlqueries/trb_request_documents.go, pkg/storage/trb_request_document.go
- Adds a dataloader for TRB Documents.
- Calls dataloaders instead of store methods in other various places in the resolvers to improve performance.
- Some general cleanup of function signatures.
- Run the automated tests, query for `documents` on TRB Requests.
- Check that all …
=> [EASI-4457] TRB documents dataloaders

pkg/dataloaders/dataloaders.go, pkg/dataloaders/trb_request_admin_notes.go, pkg/graph/resolvers/trb_admin_note.go, pkg/graph/resolvers/trb_admin_note_test.go, pkg/graph/schema.resolvers.go, pkg/models/trb_admin_note.go, pkg/sqlqueries/SQL/trb_request_admin_notes/get_by_TRB_ID.sql, pkg/sqlqueries/SQL/trb_request_admin_notes/get_by_TRB_IDs.sql, pkg/sqlqueries/trb_request_admin_notes.go, pkg/storage/trb_admin_note.go
- Adds a dataloader for admin notes.
- Pull `adminNotes` on TRB Requests in GQL.
=> [EASI-4457] TRB Admin Notes dataloader

pkg/graph/generated/generated.go, pkg/graph/schema.graphql
- Removes the requirement for `EASI_D_GOVTEAM` job code to access the query for intakes where user is requested as a reviewer.
- Query for `systemIntakesWithReviewRequested` without the `EASI_D_GOVTEAM` job code
- Check that all code is adequately covered by tests - if it isn't …
=> [NOREF] Remove admin perm requirement for review requested intake query

cmd/devdata/main.go, cmd/devdata/system_intake.go, pkg/dataloaders/dataloaders.go, pkg/dataloaders/system_intake_document.go, pkg/graph/resolvers/system_intake_document.go, pkg/graph/resolvers/system_intake_document_test.go, pkg/graph/schema.resolvers.go, pkg/models/system_intake_document.go, pkg/sqlqueries/SQL/system_intake_document/select_by_system_intake_ids.sql, pkg/sqlqueries/system_intake_document.sql.go, pkg/storage/system_intake_document.go
- Adds a dataloader for system intake documents
- Also adds some test data to add documents to intakes in the seed script
- Query `documents` on system intakes.
=> [EASI-4457] intake documents dataloader

cmd/devdata/main.go, cmd/devdata/system_intake.go, cmd/devdata/system_intake_business_case_v1.go, cmd/migrate_intakes/main.go, cmd/test_cedar_intake/main.go, pkg/appvalidation/business_case.go, pkg/appvalidation/business_case_test.go, pkg/cedar/intake/client.go, pkg/cedar/intake/translation/biz.go, pkg/dataloaders/business_case_lifecycle_costs.go, pkg/dataloaders/dataloaders.go, pkg/dataloaders/system_intake_business_case.go, pkg/graph/resolvers/system_intake_business_case.go, pkg/graph/schema.resolvers.go, pkg/graph/schema.resolvers_business_case_test.go, pkg/handlers/business_case.go, pkg/handlers/business_case_test.go, pkg/models/business_case.go, pkg/services/action.go, pkg/services/action_test.go, pkg/services/business_case.go, pkg/services/business_case_test.go, pkg/sqlqueries/SQL/system_intake_business_case/get_by_intake_ID.sql, pkg/sqlqueries/SQL/system_intake_business_case/get_by_intake_IDs.sql, pkg/sqlqueries/SQL/system_intake_business_case/get_lifecycle_costs_by_biz_case_ID.sql, pkg/sqlqueries/SQL/system_intake_business_case/get_lifecycle_costs_by_biz_case_IDs.sql, pkg/sqlqueries/system_intake_business_case.go, pkg/storage/business_case.go, pkg/storage/business_case_test.go, pkg/testhelpers/business_case.go
- Adds dataloaders for Business Cases on the intake resolver and lifecycle costs on the business case resolver.
- To accomplish the above, another model was created for legacy code that combines business cases with their cost lines in a single model. This allows the legacy code to function as before but the GraphQL code to separate the two and use dataloaders efficiently. When we refactor REST, we can remove the legacy code more easily as it uses the new combined model.
- Query for business cases with cost lines on intakes and/or run the test suite.
- e.g. "Approving because I tested it locally and all functionality works as …
=> [EASI-4457] Business Case dataloaders

pkg/graph/resolvers/trb_request_attendee.go
- EASI-4457 introduced a dataloader for TRB Requester Components, and it looks like there is the potential to not be able to retrieve a requester/attendee on a TRB request. This change introduces a nil check to prevent an error.
- Query for `requesterComponent` on a TRB request with no requester. …
=> [NOREF] Nil check for requester component

src/i18n/en-US/systemWorkspace.ts, src/views/SystemWorkspace/SystemWorkspaceRequests/__snapshots__/index.test.tsx.snap
According to https://cmsgov.slack.com/archives/CNU2B59UH/p1722462159089999?thread_ts=1722441673.111299&cid=CNU2B59UH
=> Copy changes to the Workspace Requests page description

pkg/oktaapi/client_wrapper.go
- Track a few (hopefully) useful fields for `FetchUserInfo` and `FetchUserInfos` functions
- Response Time from Okta API
- Number of results queried & returned
- Make sure your env vars set `export USE_OKTA_LOCAL="true"` so that the real Okta client is set
- Create a System Intake, adding an additional contact on the first page of the form, then save the page.
- Refresh the page so that we fetch user info for those contacts.
- Check the logs for messages that have `"service": "okta"`
```json
{
"level": "info",
"ts": 1722539893.0274274,
"caller": "oktaapi/client_wrapper.go:113",
"msg": "FetchUserInfos okta call",
"traceID": "93b2883d-60e1-4496-9d29-8b8224ce9164",
"app-name": "easi",
"app-env": "local",
"user": "BC0V",
"grt": true,
"service": "okta",
"method": "FetchUserInfos", …
```
=> [NOREF] Add logs to FetchUserInfo and FetchUserInfos that track response time

pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake_document.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, src/gql/gen/graphql.ts
- [The GRB Reviewers intake documents table shows buttons that allow a user to view or delete a document](https://www.figma.com/design/G0UN35V7SY0g9nkTIESxsY/EASi-GRB-Experience?node-id=2601-53153&t=Eco4b4LRox0YKMoL-0). The FE needs to be able to determine whether or not to show these buttons, so I've placed booleans on the document GQL schema. The resolvers use the core logic from the previous perm helpers.
- Query for documents on intakes using different EUAs and job codes. The Schema should return bools for `canView` and `canDelete` except when asking for a URL.
- e.g. "Approving because I tested it locally and all …
=> [EASI-4488] Add permissions to GQL schema for intake documents

src/types/flags.ts, src/views/AdditionalInformation/index.tsx, src/views/FlagsWrapper/index.tsx
- remove LD flags for `trbRelatedRequests`, and `systemIntakeRelatedRequests`
- confirm related requests table always shows up in `Additional Information` for a TRB Request/System Intake
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the …
=> remove unneeded flags from code

EASI.postman_collection.json
- Adds the ability to easily add/remove people to CEDAR systems (directly through CEDAR) using postman scripts and requests.
- Adds some checks to hopefully make using the CEDAR/Core "direct request" collection easier.
- Adds a direct call to Okta for a given user's EUA (I thought we might need it for the roles testing, but we don't. However, it's a good starting point if we ever need to test Okta directly).
- Import the collection and give it a go. Values for API keys/Urls can be found in `.envrc` and 1pass.
- e.g. "Approving because the …
=> [NOREF] Update postman scripts

src/types/flags.ts, src/views/FlagsWrapper/index.tsx
Added `systemWorkspaceTeam` to flags
=> [EASI-4550] Flag var `systemWorkspaceTeam`

pkg/server/server.go
- Modifies `server.go` to use [zap.NewDevelopment()](https://pkg.go.dev/go.uber.org/zap#NewDevelopment) to create the logger when running locally. This has the following effects:
- Logs will print in a human readable format instead of JSON
- Logs at `debug` level will print
- Run `scripts/dev up`
- Look at the application logs with `docker compose logs -f easi`
- Ensure they're readable!
- Don't be afraid to leave comments or ask questions, especially if you don't …
=> [NOREF] Use zap development logger for local development

src/views/SystemProfile/index.tsx
- Fixes type error caused by empty `cedarAuthorityToOperate` array
- [See console error in dev](https://dev.easi.cms.gov/systems/%7B3F585533-9CF2-4d85-AC58-BE91AE68303C%7D/home/top)
```tsx
// This returns undefined if array is empty
const cedarAuthorityToOperate = data.cedarAuthorityToOperate[0];
// Accessing this prop throws "TypeError: Cannot read properties of undefined"
cedarAuthorityToOperate.dateAuthorizationMemoExpires
```
- Mock empty `cedarAuthorityToOperate` array by changing [this code](https://github.com/CMS-Enterprise/easi-app/blob/NOREF/fix-undefined-ato/src/views/SystemProfile/index.tsx#L310) to `getSystemProfileData({...data, cedarAuthorityToOperate: []})`
- Go to /systems/%7B11AB1A00-1234-5678-ABC1-1A001B00CC4E%7D/home/top
- System profile should render
- To see original …
=> [NOREF] Fix undefined ATO bug in SystemProfile

src/data/mock/systemLinkedRequest.ts, src/views/SystemWorkspace/SystemWorkspaceRequests/__snapshots__/index.test.tsx.snap
- remove dynamic values from snapshot
- run tests locally and confirm pass
=> [NOREF] fix dynamic value in snap

package.json, yarn.lock
- Upgrades packages related to cypress (and cypress itself) -- identified from https://github.com/CMS-Enterprise/easi-app/pull/2800
- E2E tests passing in the CI/CD pipeline should suffice, but you can always run them locally by running `scripts/dev up`, `scripts/dev db:seed`, and `yarn cypress run` …
=> [NOREF] Upgrade cypress-related packages

package.json, yarn.lock
- Upgrades [luxon](https://www.npmjs.com/package/luxon?activeTab=readme) from 3.4.4 to 3.5.0
- Validate that none of the changes from [Luxon's CHANGELOG](https://github.com/moment/luxon/blob/master/CHANGELOG.md#350-2024-08-03) should impact the application. Otherwise, this is just a minor version update, and shouldn't require much testing outside E2E tests.
- If you want to validate luxon behavior specifically, we typically import it where we're rending/parsing dates, or using date pickers!
- e.g. "Approving because the change is simple and …
=> [NOREF] Upgrade luxon

cmd/devdata/system_intake_grb_reviewers.go, migrations/V190__Add_GRB_start_date_to_System_Intakes.sql, pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake_grb_reviewer.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/system_intake.go, pkg/storage/system_intake.go, src/gql/gen/graphql.ts
- Adds a start date for GRB reviews
- Current tests will fail because the updates to types and tests are in the other 4598 PR.
- Run the Seed Scripts and then use the GraphQL playground to call the `startGRBReview` mutation.
- Check that all code is adequately covered by tests - …
=> [EASI-4598] Start GRB review date

.vscode/settings.json, apollo.config.js, src/types/graphql-global-types.ts
- Adds properties to `.vscode/settings.json` to prompt us to use the "workspace" (i.e. `package.json`) version of Typescript instead of whatever version VSCode installs/manages
- Adds some settings to `apollo.config.js` to ensure it only parses files from `./src/gql/apolloGQL` and `./src/queries`. Previously, the apollo client was crashing because it was finding duplicate definitions in both the above folders and also in `./src/gql/generated`
1.  Ensure that when you launch VSCode you're prompted to set your Typescript version to the workspace version if it's not set already
2. Ensure that the Apollo VSCode extension doesn't crash
- When approving a PR, provide a reason _why_ you're approving …
=> [NOREF] Fix Typescript and Apollo client configs

cmd/test_email_templates/main.go, pkg/appses/ses.go, pkg/appses/ses_test.go, pkg/email/subject_prepender.go, pkg/email/subject_prepender_test.go, pkg/graph/resolvers/trb_request_attendee_test.go, pkg/graph/resolvers/trb_request_feedback_test.go, pkg/graph/resolvers/trb_request_form_test.go, pkg/graph/resolvers/trb_request_status_test.go, pkg/graph/schema.resolvers_test.go, pkg/local/email.go, pkg/server/routes.go
We had some folks reaching out that they were receiving emails about expiring LCIDs for `impl`, but were assuming they were coming from `prod`.
While we do have a different SES sender configured (and email clients could filter on those), adding the environment name to the subject makes it more clear at a quick glance!
> [!important]
> This _does not_ modify anything in the case of the production environment. This will only prepend the env name when running locally, in tests, or in dev and impl!
- `scripts/dev up` followed by `go run cmd/test_email_templates/main.go`
- Visit http://localhost:1080 -- you should see a bunch of `[local]` emails!
- If you want to try this with a different environment, you can edit this line! https://github.com/CMS-Enterprise/easi-app/blob/2e7040e1f1f5626e821782 …
=> [NOREF] Add environment name to email subjects

cedarproxy/Dockerfile.cedarproxy
- Pins the `nginx` version instead of using `mainline` which can fall out of sync with `pkg-oss`.
- `pre-commit run nginx-lint --all-files`
=> [NOREF] Pin nginx version

cmd/devdata/main.go
- An incorrect mock CEDAR system ID in the seed data caused the closed intake requests to throw errors when clicking into a request from the front-end.
- Run/Seed the app and click into a closed intake request with a title of `closed request #`.
- Check that all code is …
=> [NOREF] - fix mocked CEDAR sparx ID

.github/workflows/run_tests.yml
- Adds `actions/setup-python` to our CI Lint job, which is notably included in the examples from the [source repo](https://github.com/pre-commit/action), and was caught by some failing jobs ([example](https://github.com/CMS-Enterprise/easi-app/actions/runs/11329207255/job/31504344556?pr=2803)), and reported by others in [issues like this one](https://github.com/pre-commit/action/issues/214)
- Ensure CI/CD Lint job passes as expected!
- Don't be afraid to leave …
=> [NOREF] Add actions/setup-python for CI Lint

src/i18n/en-US/technicalAssistance.ts
=> in displayed text (fixed other typos in file too)

src/components/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/components/PrepareForGRB/__snapshots__/index.test.tsx.snap, src/i18n/en-US/articles/governanceReviewBoard.ts, src/i18n/en-US/governanceOverview.ts, src/views/GovernanceOverview/__snapshots__/index.test.tsx.snap, src/views/Help/ITGovernance/NewSystem/__snapshots__/index.test.tsx.snap, src/views/PrepareForGRB/__snapshots__/index.test.tsx.snap
- Update IT governance and Prepare for GRB i18n language to reflect new HHS guidelines
- Update snapshots to reflect changes
- Ensure that new language matches up with changes requested in the "EASi language Review and REQ" file posted in the slack thread associated with the JIRA ticket
- https://cmsgov.slack.com/archives/C0305U1014Y/p1727288934082439
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This …
=> [EASI-4651] ITGO Language Updates

cmd/test_email_templates/main.go, pkg/email/cedar_new_team_member.go, pkg/email/cedar_new_team_member_test.go, pkg/email/cedar_you_have_been_added_test.go, pkg/email/templates/cedar_new_team_member.gohtml, pkg/email/templates/cedar_you_have_been_added.gohtml, pkg/graph/resolvers/cedar_set_roles_for_user.go, pkg/graph/resolvers/cedar_set_roles_for_user_test.go
- Makes it so only CEDAR receives an email unless users are newly added to systems.
- Adjusts team leads email to be in line with new member email.
- `scripts/dev email`
- Add a user to a system, then add a new role.
- Check that all code is adequately covered by tests - if it …
=> [EASI-4653] Update other email template for team mgmt

src/i18n/en-US/technicalAssistance.ts
Change requested from Zoe - updates remove guidance modal heading
- 
=> [NOREF] Update heading on remove guidance modal

pkg/email/templates/trb_guidance_letter_internal_review.gohtml, pkg/email/templates/trb_guidance_letter_submitted.gohtml, pkg/email/trb_guidance_letter_internal_review_test.go, pkg/email/trb_guidance_letter_submitted_test.go
- Fixes some hard-coded copy in email templates that had capitalized instances of `guidance letter`
- Unit tests should reflect the changes, but you can also use the test email template command to validate in mailcatcher if desired.
- Check that all code is adequately covered by …
=> Fix email capitalization for Guidance Letter --> guidance letter

src/i18n/en-US/discussions.ts, src/i18n/en-US/index.ts
- Added the discussions translation file to src/i18n/en-US/index.ts
- Updated translations to use `count` variable name and use singular/plural language (ex: 1 reply vs 2 replies)
- [Docs on i18next plurals](https://www.i18next.com/translation-function/plurals)
- Fixed typos 
-  …
=> [NOREF] Discussions translation fixes

src/components/RequestRepository/csvPortfolioReportHeaderMap.ts
- Adds `Requester Name` and `EUA ID` headings & data to the Portfolio Export
> [!NOTE]
> Here's an example of some seed data of it running locally!
> ![image](https://github.com/user-attachments/assets/8f972026-4a7c-43e4-b642-7ee744b7947f)
- Log in as an IT Gov admin
- Run the portfolio export report, ensuring at least the current day is captured
- Ensure the new headings & data show up in the report CSV
- Don't be afraid to …
=> [EASI-4668] Add Requester Name and EUA ID headings to portfolio export

src/components/MentionTextArea/index.scss, src/components/MentionTextArea/index.tsx, src/views/DiscussionBoard/components/DiscussionForm.tsx
Continued changes from https://github.com/CMS-Enterprise/easi-app/pull/2897
This is just a rebranch from a better starting point.
=> MentionTextArea in DiscussionForm

cmd/test_email_templates/main.go, pkg/email/email.go, pkg/email/grb_review_discussion_group_tagged.go, pkg/email/grb_review_discussion_group_tagged_test.go, pkg/email/grb_review_discussion_individual_tagged.go, pkg/email/grb_review_discussion_individual_tagged_test.go, pkg/email/grb_review_discussion_reply.go, pkg/email/grb_review_discussion_reply_test.go, pkg/email/templates/easi_header.gohtml, pkg/email/templates/grb_review_discussion_group_tagged.gohtml, pkg/email/templates/grb_review_discussion_individual_tagged.gohtml, pkg/email/templates/grb_review_discussion_reply.gohtml
- follow on to https://github.com/CMS-Enterprise/easi-app/pull/2875
- add bool checks for `IsAdmin` to templates to determine if we should include footer section with itgov email
- set role to `Governance Admin Team` when needed
- add mention css class
- 
- Check that all code is …
=> Easi 4614/follow up items

.github/workflows/deploy_to_eks.yml
- replace exit 1 with a skip condition
- open new PR with `eks_ignore` tag, the pipeline should pass with the `eks` step being marked as Skipped instead of Failed
=> Skip `eks` step when `eks_ignore` label present

src/i18n/en-US/discussions.ts
Updates a typo and some content changes to accurately reflect current functionality!
- Just make sure the content looks correct, and that no snapshot tests fail!
=> [EASI-4614] Fix discussions content & typo

cmd/devdata/main.go
- address TODO: https://github.com/CMS-Enterprise/easi-app/pull/2874/files#diff-2a1838f04c769028de154e9e1f307017c22efa3ef48800edf6fc31c6554542e3R354
- (original TODO: `TODO, remove <b> when they're not supported when we add tagging. Just using it now to show this is HTML`)
- N/A …
=> swap `<b>` for `<p>`

.pre-commit-config.yaml, Dockerfile, Dockerfile.cypress, Dockerfile.db_seed, docs/dev_environment_setup.md, go.mod
- Updates `go` and `golangci-lint` versions
- See testing instructions from MINT PR https://github.com/CMS-Enterprise/mint-app/pull/1568
=> [NOREF] Upgrade go version and golangci-lint version

pkg/graph/schema.resolvers_test.go, pkg/server/routes.go
- fix lint by implementing deprecated method on our end
- in future, may look at reworking, but this works and is safe
- lint/run everything, confirm services start up
=> impl copy of deprecated method

src/i18n/en-US/grbReview.ts, src/views/GovernanceReviewTeam/GRBReview/index.scss, src/views/GovernanceReviewTeam/GRBReview/index.tsx
Fixed [QA findings](https://oddball.slack.com/docs/T1ZD0UBMZ/F084X1RK71S?focus_section_id=temp:C:QAbbc30c3cd371c48d9a1dd4a7a1):
- Added `scroll-margin-top` css property so headings show after clicking navigation links to page sections
- Updated supporting documents navigation link to scroll to "Supporting documents" heading
- Fixed capitalization issues
- Supporting Documents -> Supporting documents
- Business Case Overview -> Business Case overview 
- GRB Review sub navigation links should scroll to correct heading
- Check capitalization fixes
- e.g. "Approving because I tested it locally and all functionality works as …
=> [NOREF] GRB review nav menu / capitalization fixes

src/i18n/en-US/grbReview.ts
- Updated feature in progress alert text ([see Slack](https://oddball.slack.com/archives/C059N01AYGM/p1734621603420779))
- 
=> [NOREF] GRB Review text update

src/views/MyRequests/Table/index.tsx
- Fix admin status translation in My IT Governance requests table
- [Slack thread](https://oddball.slack.com/archives/C059N01AYGM/p1734633094941939) with details and screenshots
- In the My IT governance requests table, requests with GRB dates in the past should show "GRB meeting complete" …
=> [NOREF] Fix admin status translation

pkg/cedar/core/cedar_core.json, pkg/cedar/core/gen/client/role/role_client.go, pkg/cedar/core/gen/models/deployment.go, pkg/cedar/core/gen/models/exchange.go, pkg/cedar/core/gen/models/role_type.go
- bump CEDAR to include new role API data
- 
=> latest cedar

src/i18n/en-US/articles/governanceReviewTeam.ts
- This adds two admin leads to the FE list of leads.
- **NOTE:** Currently admin leads are stored as plain text names on the intake and not associated with user accounts. The list of leads is stored as a hardcoded array in the FE i18n package.
- Run/seed the app and open an intake as an admin. Click the "change admin lead" link on the overview page.
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This …
=> [EASI-4691] Add admin leads

cmd/devdata/system_intake_business_case_v1.go, cmd/test_cedar_intake/main.go, migrations/V198__Make_Costs_BigInt.sql, pkg/appvalidation/business_case.go, pkg/appvalidation/business_case_test.go, pkg/cedar/intake/translation/biz.go, pkg/graph/generated/generated.go, pkg/graph/schema.resolvers_business_case_test.go, pkg/models/business_case.go, pkg/testhelpers/business_case.go, pkg/validate/types.go
- Converts business case lifecycle costs to be able to accept amounts in the billions.
- Test by adding large numbers to business case costs.
=> [EASI-4699] convert lifecycle costlines to use 64bit integers

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/models_gen.go, pkg/sqlqueries/SQL/system_intake_grb_presentation_links/delete.sql, pkg/sqlqueries/system_intake_grb_presentation_links.go, pkg/storage/system_intake_grb_presentation_links.go, pkg/storage/system_intake_grb_presentation_links_test.go, src/gql/gen/graphql.ts
- adds delete GRB presentation links to graphql schema
- adds storage file which will be expanded upon
- adds (minimal) test which will also be expanded upon
- postman updates
- run tests/confirm pass
- confirm new postman request passes too
- Check that all code is adequately …
=> Easi 4697/delete links mutation

migrations/V199__Add_async_GRB_presentation_links.sql, pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/models_gen.go, pkg/models/system_intake_grb_presentation_links.go, src/gql/gen/graphql.ts
- This makes the `RecordingLink` field optional and introduces a database constraint to check for the presence of a single field to prevent an empty form being stored.
- The mutation input is changed but this can't truly be tested until the store methods are implemented.
- Check …
=> [EASI-4711] Remove required presentation links fields

src/stylesheets/custom.scss
- Fixed unintended style due to dependabot on font-weight on usa-table
- Verify no other unintended style changes from list of dependabot upgrades
=> [NOREF] Fixed font-weight on table

src/components/GrbParticipationNeeded/index.tsx, src/stylesheets/custom.scss, src/utils/tableSort.tsx, src/views/AdditionalInformation/RelatedRequestsTable.tsx, src/views/GovernanceReviewTeam/GRBReview/GRBReviewerForm/AddReviewersFromRequest.tsx, src/views/GovernanceReviewTeam/GRBReview/ParticipantsTable.tsx, src/views/GovernanceReviewTeam/IntakeReview/__snapshots__/index.test.tsx.snap, src/views/MyRequests/Table/__snapshots__/index.test.tsx.snap, src/views/SystemIntake/Documents/DocumentsTable.tsx, src/views/SystemList/__snapshots__/index.test.tsx.snap, src/views/SystemProfile/components/Team/Edit/__snapshots__/index.test.tsx.snap, src/views/SystemWorkspace/SystemWorkspaceRequests/__snapshots__/index.test.tsx.snap, src/views/SystemWorkspace/SystemWorkspaceRequests/index.tsx, src/views/SystemWorkspace/TeamTable.tsx, src/views/TechnicalAssistance/Homepage.tsx, src/views/TechnicalAssistance/RequestForm/DocumentsTable.tsx, src/views/TechnicalAssistance/RequestForm/__snapshots__/Documents.test.tsx.snap, src/views/TechnicalAssistance/TrbAdminTeamHome.tsx, src/views/TechnicalAssistance/__snapshots__/index.test.tsx.snap
- Fixed some unintended style changes from upgrading uswds
- Buttons/Headers on tables
- Site alerts, general alerts
- Icon margins
- Verify no other unintended style changes from USWDS
- Check that all code is adequately covered by tests - if it isn't feel …
=> [NOREF]Adjusted styles and updated snapshots

src/i18n/en-US/technicalAssistance.ts, src/views/TechnicalAssistance/AdminHome/components/ReviewGuidanceLetter/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/AdminHome/components/ReviewGuidanceLetter/index.tsx, src/views/TechnicalAssistance/__snapshots__/PublicGuidanceLetter.test.tsx.snap
* Update `requirementDescription` copy
* Add `nextStep` copy
* Update snapshots
1. Navigate to Guidance Letter 
2. Find the requirement copy to match requested change
3. Find the next step copy to be under the next step heading and matching the requested copy change
- Check that …
=> [EASI-4719] TRB Guidance Letter updates

src/i18n/en-US/home.ts
* Updated copy to match what is written in the ticket
1. Click the "What's included in the Portfolio Update Report?" on the ITGO Admin home page
2. Verify that the text in the "About the Portfolio Update Report" modal matches
- Check that all code is adequately covered by tests - …
=> [EASI-4683] Update About the Portfolio Update Report modal text

package.json, src/i18n/en-US/articles/prepareTrbConsultMeeting.ts, src/i18n/en-US/technicalAssistance.ts, src/views/Help/TechnicalReviewBoard/PrepareTrbConsultMeeting.tsx, src/views/Help/TechnicalReviewBoard/__snapshots__/PrepareTrbConsultMeeting.test.tsx.snap, src/views/TechnicalAssistance/AdminHome/components/ReviewGuidanceLetter/__snapshots__/index.test.tsx.snap, src/views/TechnicalAssistance/AdminHome/components/ReviewGuidanceLetter/index.tsx, src/views/TechnicalAssistance/__snapshots__/PublicGuidanceLetter.test.tsx.snap
* update copy from various places to match figma
- Navigate through the TRB Guidance Letter to see it matching figma
=> [EASI-4719]  Update and Add Copy to Places Specified in Figma

src/components/TablePagination/index.scss
In the latest USWDS style upgrades, a change was not caught that affected the background-color/transparency of pagination buttons `usa-pagination__button`
This was really only noticeable on the TRB admin home where there was a blue background
This PR reverts those class style to the standard/previous style in EASI
- Verify all table pagination looks and behaves as normal
- Don't be afraid to leave comments or ask questions, especially if you don't understand why …
=> [NOREF] Fix USWDS pagination button color

src/components/NavigationBar/index.scss, src/views/TechnicalAssistance/RequestForm/ViewSubmittedRequest.tsx
https://oddball.slack.com/archives/C06RSLZ4UKF/p1739196260738539
https://oddball.slack.com/archives/C06RSLZ4UKF/p1739196260738539
- Fixed main navigation `Systems` tab styling and hover styling be uniform
- Fixed `Close tab` button and icon styling on TRB request overview tab
- Verify potluck items are addressed
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code …
=> [NOREF] Potluck style fixes

src/hooks/useMessage.tsx, src/views/SystemProfile/components/Team/Edit/index.tsx
* update useMessage hook to have error message in modal and clear message functions
* plug in showErrorMessageInModal, errorMessageInModal, and clearMessage
1. System profile or Workspace, Team sub-page
2. Edit team button
3. Remove any team member
4. Modal shows confirming
5. Click remove
6. Error shouuld now be in the modal
7. close modal and open it again to ensure that error message is cleared out
- Don't be afraid to leave comments or ask questions, especially if …
=> [EASI-4612] Addressing Modal stays on screen when CEDAR errors

src/components/Modal/index.scss, src/components/Modal/index.tsx, src/components/NavigationBar/index.scss, src/setupTests.ts, src/stylesheets/custom.scss, src/views/TechnicalAssistance/AdminHome/components/RemoveInsightModal/Index.tsx, src/views/TechnicalAssistance/GuidanceLetterForm/Insights.tsx, src/views/TechnicalAssistance/GuidanceLetterForm/index.test.tsx, src/views/TechnicalAssistance/GuidanceLetterForm/index.tsx
- Fixed incorrect conditional on`setFormAlert` prop that was causing the success banner to automatically reset
- Fixed Truss button style on modal close button
- Added a better `scrollIntoView` offset when removing a TRB guidance letter
- Fixed incorrect global mock of `window.scroll` and `window.scrollTo`
- Tweaked style on systems tab navigation element
- Seed database
- Navigate to `Case 11 - Admin notes w/ category-specific data`
- Go to the guidance letter
- Add/remove/edit insights
- Verify alerts behave as expected
- e.g. "Approving …
=> [EASI-4664] Fixed TRB success banner and button styling

src/stylesheets/custom.scss
Found another artifact of recent package/style upgrades to USWDS - font-family override on modal heading
- Set modal heading font to `inherit` to conform with app
- Verify modal heading font is correct
- Check that all code is adequately covered by tests - if it isn't feel free …
=> [NOREF] Fix modal header font

src/views/GovernanceReviewTeam/Actions/index.scss
- Fixed border color due to style token changing with latest USWDS upgrade
- Verify border color matches figma
https://www.figma.com/design/JE39JNLbCSha4fk1m9ayPP/IT-Governance-Updates?node-id=1671-104634&t=9OcVbQcEz6ttUX3R-0  …
=> [NOREF] Border color style fix

pkg/graph/schema.resolvers.go
Fixed a typo in a resolver that was pointing 2 resolvers to the same underlying function, rather than using the (already coded) correct resolver!
- Make a system intake, progress it to the GRB step, and upload presentation links (a transcript file _and_ a presentation deck file)
- In the Minio client, set both files to `av-status: CLEAN`. Ensure both files show in the UI for the admin view
- In the Minio client, set just _one_ file to `av-status: INFECTED`. Ensure only that file stops showing up in the UI.
- Invert the statuses (setting the one to `av-status: INFECTED`, and one to `av-status: CLEAN`) , ensuring it doesn't show up
- When approving a PR, provide a reason _why_ you're approving …
=> [NOREF] Fix presentation deck file status

src/index.scss
Latest Truss upgrade has a style leak that set global scroll behavior to `smooth`
- Set global scroll behavior back to `auto`
- Verify the scroll behavior across the app is reverted to auto/not smooth unless explicitly set
- Check that all code is adequately covered by tests - if …
=> [NOREF] Revert global scroll behavior

.github/workflows/build_and_test.yml
- Comments out automatic EKS pipeline
- 
=> [NOREF] Update build_and_test to disable EKS pipeline

.pre-commit-config.yaml, package.json
Fixed an incorrect gql path on precommit
- Verify works as expected
=> [NOREF] Fixed incorrect gql path

src/features/Systems/SystemProfile/__snapshots__/index.test.tsx.snap, src/features/Systems/SystemProfile/index.tsx
#NOREF
System profile mobile nav seems to always be rendered.  Not sure how this got introduced, but this PR should fix and only render on mobile
- Verfiy mobile nav only renders on mobile widths
- Check that all code is adequately covered by tests - if it isn't feel free to …
=> [NOREF] Fix system profile mobile nav

pkg/graph/generated/generated.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, src/gql/generated/graphql.ts
- GQL Schema definitions to send reminder email for presentation deck
- Note: This functionality has not yet been enabled by the backend and will be implemented in a separate PR
- Review the GQL schema definition and ensure everything is designed as expected
- Check that all code …
=> [EASI-4727] Unblock FE to Send Presentation Deck Reminder Email Functionality

EASI.postman_collection.json, migrations/V201__Add_System_Intake_GRB_Review_Fields.sql, pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake_grb_review_form.go, pkg/graph/resolvers/system_intake_grb_review_form_test.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/models_gen.go, pkg/models/system_intake.go, pkg/storage/system_intake.go, src/gql/generated/graphql.ts
Updated mutations to a format more compatible with frontend needs
- Run scripts/dev test:go
- Test endpoints on Postman
- Create a new system intake
- Test: Update System Intake GRB Review Form Presentation (Standard)
- Test: Update System Intake GRB Review Form Presentation (Async)
- Test: Update System Intake GRB Review Form Timeframe (Async)
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is …
=> [NOREF] GRB Review Form mutation updates

cypress/e2e/grbReview.cy.js, src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/AdditionalDocumentation/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/GRBReviewFormStepWrapper/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/GRBReviewFormStepWrapper/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/Participants/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/Presentation/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/ReviewType/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/ReviewType/index.scss, src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/ReviewType/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/ReviewType/index.tsx, src/i18n/en-US/grbReview.ts
[Figma](https://www.figma.com/design/G0UN35V7SY0g9nkTIESxsY/EASi-GRB-Experience?node-id=2626-58627&t=UGJCt8SZ8CyMjYO6-1)
- Review type step of GRB review form
- Unit test updates
- Basic cypress test
- Added new `grbReview.cy.js` file for GRB review form tests
- Test first step of GRB review form
-  Make sure default value is pre-filled in review type field
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! …
=> [EASI-4706] GRB review form - review type

pkg/sqlqueries/SQL/system_intake_review_type/update.sql, pkg/storage/system_intake_grb_reviewer.go
Removed EUA user id setting from GRB Review Type mutation
- Execute unit tests and validate
- Test setting review type through FE
=> [NOREF] Fix grb review type eua setting

EASI.postman_collection.json, pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake_grb_review_form.go, pkg/graph/resolvers/system_intake_grb_review_form_test.go, pkg/graph/schema.graphql, pkg/models/models_gen.go, src/gql/generated/graphql.ts
It was discovered that the frontend needs the ability to set a review as started as well as set the end date at the same time. As such, it is necessary to update the `updateSystemIntakeGRBReviewFormInputTimeframeAsync` input to include a boolean param to start the GRB review. It follows the framework of the startGRBReview mutation, and will error if review is attempted to be started twice.
Use the postman collection to
1. Create a System Intake
2. Use the `UpdateSystemIntakeGRBReviewFormTimeframeAsync` to update the end date
3. Use the `UpdateSystemIntakeGRBReviewFormTimeframeAsync` endpoint again, but uncomment the ` startGRBReview: true` params
4. Assert that grbStartDate was set
5. Send the mutation again with start set to true
6. Assert that the operation fails
- It's best to pull the …
=> [Easi-4822] Introduce start review from page 4

pkg/cedar/intake/client.go, pkg/cedar/intake/client_test.go, pkg/server/routes.go
The cedar team has requested that data is exported on a daily basis instead of once weekly. This simplifies the logic to go from once weekly to find a time at the next weekday.
1. Start the app. 
2. Look at the logs.
3. Confirm that their is a message for `next intake publish to CEDAR in` that correlates to about 2 UTC the next day
4. Please also take a look at the new unit tests which assert the timing for the next interval to run a publishing
- Don't be afraid to …
=> [EASI-4778] Cedar data to export daily

src/components/MultiSelect/index.tsx
- Fixed issue where react-select custom multiselect option was closing on each selection
- Prevent the default click 
- Added `tabSelectsValue` prop to allow better accessibility to get out of the form component
https://github.com/JedWatson/react-select/issues/4666
- Verify selecting an option does not close multiselect.  Cant test this on the first form page of the TRB intake for selecting an lcid
- Don't be afraid to leave comments or ask questions, especially if …
=> [EASI-4815] - Multiselect close on select fix

cmd/devdata/trb_request.go, pkg/email/trb_guidance_letter_submitted.go, pkg/email/trb_guidance_letter_submitted_test.go, pkg/graph/generated/generated.go, pkg/graph/resolvers/trb_guidance_letter.go, pkg/graph/resolvers/trb_request_status_test.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/models_gen.go, src/features/TechnicalAssistance/Admin/GuidanceLetterForm/Review/index.tsx, src/features/TechnicalAssistance/Admin/_components/ActionFormWrapper/Index.test.tsx, src/features/TechnicalAssistance/Admin/_components/ActionFormWrapper/Recipients.tsx, src/features/TechnicalAssistance/Admin/_components/ActionFormWrapper/__snapshots__/Index.test.tsx.snap, src/features/TechnicalAssistance/Admin/_components/ActionFormWrapper/index.tsx, src/features/TechnicalAssistance/Admin/_components/ActionFormWrapper/useActionForm.tsx, src/gql/generated/graphql.ts, src/i18n/en-US/technicalAssistance.ts, src/types/technicalAssistance.ts
- Added input value for `copyITGovMailbox`
- Updated `Recipients` component to take prop to add IT Gov mailbox
- Add form component to capture selection and send to mutatino
- Seed db
- Navigate to TRB request as admin - `Case 8 - Guidance letter in review with document`
- Navigate to send guidance letter and verify the it gov mailbox is visible and default selected
- Verify mutation
- Tests pass
- Don't be afraid to leave comments or ask questions, especially if you …
=> [EASI-4820] TRB Guidance letter - Add IT Gov mailbox

EASI.postman_collection.json, pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake_grb_voting_information.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/system_intake_grb_voting_information.go, src/gql/generated/graphql.ts
This is the ground work and a bit of implementation for the decision record. It is mostly the schema at this point, so that the frontend can begin implementation that will use this data.
This is not feature complete. @samoddball will be taking over the rest of the backend implementation in another branch and PR to implement the remaining logic calculation as well as unit tests for fetching the data and calculating the information.
1. Bring the application up
2. Create a new system intake
3. Add a GRB reviewer to the intake
4. Use the new query (GetGRBVotingInformation(AndReviewers)) to validate that you can retrieve the reviewers, as well as the stubbed out methods to calculate more information
- It's best to pull the branch locally and test it, rather than just looking at the code …
=> [EASI-4823] Decision record schema

src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/Participants/index.tsx
#NOREF
Realized that the standard GRB form was using a mutation that required `grbReviewAsyncEndDate`.  We also had an unused legacy mutation that manually started the GRB review, -> `startGRBReview`.  Decided to reuse this mutation for the standard form
- Added `startGRBReview` mutation to the GRB form if the type is standard
- Seed db and as admin navigate to GRB review form
- Progress to last step as both standard and async versions
- Verify mutation payload and success
- e.g. "Approving because the change is simple and matches the Figma …
=> [NOREF] Add standard GRB start mutation

src/features/ITGovernance/Admin/GRBReview/BusinessCaseCard/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Admin/GRBReview/BusinessCaseCard/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/BusinessCaseCard/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewAdminTask/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.tsx, src/features/ITGovernance/Admin/GRBReview/index.tsx
This PR aims to refactor a bit of code and move them into their own files with unit tests where applicable
- Moved business case jsx to `<BusinessCaseCard />`
- Moved grb admin conditional jsx to `<GRBReviewAdminTask />`
- Refactored condition to render `<GRBReviewStatusCard />` to be self contained within the component
- Added unit test
- No functional or UI changes expected
- Tests pass
- Don't be afraid to leave comments or ask questions, especially if you don't …
=> [NOREF] GRB Review cleanup/refactor/refile

src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewerForm/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/ParticipantsSection/ParticipantsSection.tsx, src/features/ITGovernance/Admin/GRBReview/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/index.tsx, src/features/ITGovernance/Admin/RequestOverview/RequestOverview.test.tsx, src/features/ITGovernance/Admin/RequestOverview/RequestOverview.tsx, src/features/ITGovernance/Admin/index.tsx
Noticed GRB Review started to have a lot of prop drilling.  I refactored code to alleviate this a bit in favor of utilizing cache where applicable.  Also refactored, when we do pass down a queried prop, to pass the entire object as an entity, rather than spreading all the properties as props and redefining the types in the child component.
- Refactored GRB review props to alleviate prop drilling
- Passed down props as single entities rather than prop spread
- Unit tests pass
- GRB behaves functionally as normal
- e.g. …
=> [NOREF] Prop drill refactor

pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake_grb_review_form.go, pkg/graph/resolvers/system_intake_grb_review_form_test.go, pkg/graph/resolvers/system_intake_status_admin.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/models_gen.go, src/gql/generated/graphql.ts
This PR adds functionality to calculate the GRB Review status for standard reviews. We'd implemented async reviews, but never made one specific for standard reviews!
- Seed database
- Open a (standard, not async) intake that doesn't have a GRB date set yet
- Query the new `grbReviewStandardStatus` field on the intake from Postman. It should return `null`
- Set the GRB review date in the future through the admin UI, re-query, it should return `SCHEDULED`
- Set the GRB review date in the past through the admin UI, re-query, it should return `COMPLETED`
- Query an intake with an async review -- it should return `null`
- e.g. …
=> [EASI-4806] Standard grb review status

cypress/e2e/discussionBoard.cy.js, cypress/e2e/grbReview.cy.js
- Cypress testing on the GRB Setup form
- Happy path (for both standard and async), running through each step as usual, filling it out, making sure everything gets set as expected
- Headers
- Form validation
- Going back and forth through the steps, path variation
- Update discussionBoard.cy.js
- Remove code that skips test
- Fix steps to start GRB review to unlock discussion board
- Reseed environment! (kept running into this issue... EASi cypress tests don't auto reseed)
- Run `grbReview.cy.js` and `discussionBoard.cy.js` cypress test 
- Ensure code coverage 
- Ensure passes
- e.g. "Approving because I tested it locally and …
=> [EASI-4787] Cypress test for GRB Review and Discussion Board

src/features/ITGovernance/Admin/GRBReview/BusinessCaseCard/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Admin/GRBReview/BusinessCaseCard/index.tsx, src/features/ITGovernance/Admin/GRBReview/DecisionRecordCard/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBFeedbackCard/GRBFeedbackCard.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewAdminTask/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/Participants/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewerForm/AddReviewerFromEua.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewerForm/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewerForm/index.tsx, src/features/ITGovernance/Admin/GRBReview/IntakeRequestCard/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Admin/GRBReview/IntakeRequestCard/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/IntakeRequestCard/index.tsx, src/features/ITGovernance/Admin/GRBReview/ParticipantsSection/ParticipantsSection.test.tsx, src/features/ITGovernance/Admin/GRBReview/ParticipantsSection/ParticipantsSection.tsx, src/features/ITGovernance/Admin/GRBReview/ParticipantsSection/_components/ParticipantsTable.tsx, src/features/ITGovernance/Admin/GRBReview/PresentationLinksCard/PresentationLinksCard.tsx, src/features/ITGovernance/Admin/GRBReview/index.tsx, src/features/ITGovernance/Admin/index.tsx
There was a bit of uncleanliness on the GRB review home - decided to refactor to make it more organized.  Also reworked the participants form and table it decouple it from the various places it was integrated.  Hopefully this is more clear and intuitive.
- Fixed styling on all the card, converted to use Truss cards
- Move participants table out of the GRB review component, asserted it's own route
- Fixed the edit participant button on the grb setup form
- Style fixes
I ended up duplicated the remove reviewer button/modal as it was too entangled with disparate pieces of code.  This can be refactored into a new distinct and reusable component.  I may get to this if I have time.
- Everything works as expected
- It's best to pull the branch locally and test it, rather than just looking at the …
=> [NOREF] Refactor GRB review home and participants

.github/workflows/deploy_to_eks.yml
Now we need a label called eks_deploy to deploy this to EKS, otherwise it won't deploy. (instead of only ignoring ones with the ignore label)
- Confirm that this doesn't create an EKS deploy
- Check that all code is adequately covered by tests - if it isn't feel free to suggest …
=> [NOREF]only deploy to eks with label

pkg/graph/generated/generated.go, pkg/graph/resolvers/system_intake_grb_review_form.go, pkg/graph/resolvers/system_intake_grb_review_form_test.go, pkg/graph/schema.graphql, pkg/graph/schema.resolvers.go, pkg/models/models_gen.go, pkg/models/system_intake.go, src/gql/generated/graphql.ts
Refactor the `updateSystemIntakeGRBReviewFormTimeframeAsync` mutation into multiple discrete action mutations
- 
=> [EASI-4847] Refactor mutation for system intake grb form

src/features/TechnicalAssistance/Requester/TaskList/index.tsx
https://cmsgov.slack.com/archives/CNU2B59UH/p1747148305237859
-  Complete the TRB request and ensure that the `Remove your request` link is not there
=> [NOREF] remove 'remove your request' if the request is copmleted

pkg/scheduler/okta_jobs.go, pkg/scheduler/okta_jobs_test.go, pkg/scheduler/scheduled_job_wrapper.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/scheduler/timing/scheduled_job_timing_definitions.go, pkg/server/routes.go, pkg/testconfig/test_config_base.go
This PR should update the application to use the scheduler to send a request to Okta every 15 days. This request will use the Okta token, which will prevent it from expiring. This way we will avoid any disruptions regarding authentication, in case EASi is not being used.
- Clone the code locally
- Update line 25 in okta_jobs.go to use any reasonable timing faster than 15 days, I used Every5Seconds
- Fire up the app using `scripts/dev up:backend:debug`
- See that the "Okta token refreshed after 15 days" message is firing in the logs
- Alternatively, set up a breakpoint in vscode and step through the code running in the reauthenticateWithOktaJobFunction() and confirm there are no errors
- When …
=> [EASI-4859] - TECH DEBT: Job to run every 15 days to query OKTA

EASI.postman_collection.json, pkg/graph/resolvers/trb_request.go, pkg/graph/schema.resolvers.go
- prevent archiving completed TRB Requests/System Intakes
- confirm you cannot archive a TRB request if status is `completed`
- confirm you cannot archive a System Intake if status is neither `ready` nor `in progress`
- i did this via the updated postman request (included) and by setting specific statuses in DB
- note: the above conditions were written in the BE to match the UI conditions
- Don't be afraid to leave comments or ask questions, especially if you don't …
=> [EASI-4872] prevent removing completed intakes and TRB requests

src/features/ITGovernance/Requester/BusinessCase/AlternativeAnalysis/index.tsx
- Modify status column in alternative analysis to always use final solution schema regardless of business case schedule
- Ensure that status column properly shows "In Progress" status when business case is in draft
- Check that all code is adequately covered by tests - if it …
=> [NOREF] Fix validation in status column of alternative analysis table

pkg/models/enum_array.go
Introduce enum array from MINT into EASi. This will provide type safety for arrays of enums that we previously had to ignore, and use a string array for
- This is not directly testable, as this is just introducing a type. @cheinrichs-oddball will use this in his upcoming PR for the first implementation in EASI
To see it used in an app, look at the implementation in [MINT](https://github.com/CMS-Enterprise/mint-app/blob/6f3547ce6eb78301fa2bf802e19080a135a60c54/pkg/models/mto_solution.go#L49). Effectively, you just provide the type of the enum in the type definition and GQL and the db are able to interact with the type directly.
- …
=> [NOREF] Enum arrays from MINT

src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/__snapshots__/index.test.tsx.snap, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.tsx, src/i18n/en-US/grbReview.ts, src/utils/date.test.ts
[Figma](https://www.figma.com/design/G0UN35V7SY0g9nkTIESxsY/EASi-GRB-Experience?node-id=5769-17716&t=d4OFh0FQymoJhDcf-1)
- Updated `GRBReviewStatusCard` component for past due status 
- Unit tests
- Log in as user with admin job codes
- Go to GRB review tab of seeded request titled "grb meeting without date set"
- Complete and submit set up GRB review form for async review
- Set end date in past to put review in "past due" status
- Check that review status card matches Figma
- e.g. "Approving because the change is simple and matches the Figma …
=> [EASI-4895] Async GRB review - past due status

src/components/RequestRepository/AnnualEmail.tsx, src/i18n/en-US/general.ts, src/i18n/en-US/home.ts
- [Slack thread](https://oddball.slack.com/archives/C059N01AYGM/p1749576547136359)
- 
- Prevents form and buttons from rendering until data is available
- Adds a new 'loading' string to the general i18n namespace
- Adds new states to modal
- loading -- Display a spinner and loading text while requester email data is being fetched
- error -- Error alert 
- copied success
1. Load up and log in as admin
2. Click `Configure email list`
3. Ensure modal pops up
4. See below comments to see where to edit the code to verify the different states, like loading, error
5. Select a checkbox and hit copy to clipboard button
6. Verify that it does copy to clipboard and the text of button changes to show success.
7. 
- It's best to pull the branch locally and test it, rather than just looking at the code …
=> [NOREF] add loading state indicator to requester email modal

src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/Participants/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewerForm/AddReviewerFromEua.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewerForm/index.tsx, src/features/ITGovernance/Admin/GRBReview/ParticipantsSection/ParticipantsSection.test.tsx, src/features/ITGovernance/Admin/GRBReview/ParticipantsSection/ParticipantsSection.tsx, src/features/ITGovernance/Admin/GRBReview/ParticipantsSection/_components/ParticipantsTable.tsx, src/features/ITGovernance/Admin/GRBReview/index.tsx
- Addressing [Item #2](https://docs.google.com/document/d/1r5vLwLEwFG94PKviSUzw1TT_HiNqzR8nTwfkkeImmFc/edit?tab=t.0#heading=h.6ohcgri0t2ud)
- Adds grbReviewStandardStatus as a prop to support review types beyond async
- Defines shouldShowActionColumn to determine action visibility for IT Gov Admins
- Ensures action column displays only when a relevant review is active and incomplete
- Improves table behavior to support both async and standard GRB workflows
1. Go through the GRB Standard Review form
2. Make review date in the future some time  
3. Go through the form adding reviewers and etc.
4. Verify that `Add another GRB reviewer` button and Action column is visible
5. `Dates` on side nav >> set date GRB Date to sometime in the past >> `Save`
6. Check to see that the `Review status` is …
=> [NOREF] Async GRB v2 QA: Addressing Standard: Participants are still editable after the review date has passed and status is complete.

src/features/ITGovernance/Admin/Actions/ManageLcid/RetireLcid.test.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewerForm/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/ParticipantsSection/ParticipantsSection.test.tsx, src/features/ITGovernance/Admin/GRBReview/ParticipantsSection/ParticipantsSection.tsx, src/features/ITGovernance/Admin/GRBReview/index.tsx, src/i18n/en-US/grbReview.ts
Addressing [QA items #8 and #9](https://docs.google.com/document/d/1r5vLwLEwFG94PKviSUzw1TT_HiNqzR8nTwfkkeImmFc/edit?tab=t.0#heading=h.xj0silj95kq2)
1. Navigate to any ITGO and before you start the review, scroll down to participants section and verify that the copy changed and the blue info box is not there
| Before | After |
|--------|-------|
| <img src="https://github.com/user-attachments/assets/795a4957-0a20-4d6c-8e28-e253a0e11b35" alt="Before" width="700"/> | <img src="https://github.com/user-attachments/assets/c97ec12f-9919-4a00-a702-a52f155a82c4" alt="After" width="700"/> |
2. Proceed to complete a Async review.
3. Log in as a user of that system intake
4. scroll to `Additional documents` and verify that the `This review is over...` is not present
- 
- It's best to pull the branch …
=> [NOREF] Async GRB v2 QA: addressing #8 and #9

src/features/ITGovernance/Admin/GRBReview/PresentationLinksCard/PresentationLinksCard.test.tsx, src/features/ITGovernance/Admin/GRBReview/PresentationLinksCard/PresentationLinksCard.tsx, src/features/ITGovernance/Admin/GRBReview/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/index.tsx
Addresses [QA item #3](https://docs.google.com/document/d/1r5vLwLEwFG94PKviSUzw1TT_HiNqzR8nTwfkkeImmFc/edit?tab=t.0#heading=h.tfxukgygaq92).
- Hides "edit" and "remove" action buttons on presentation links card when standard meeting  is complete (with presentation links)
- Differs slightly from expected state on UX doc (no "this review is over" text). See [Slack thread](https://oddball.slack.com/archives/C059N01AYGM/p1752248923707429) and screenshot in testing instructions.
- Hides presentation links card if standard meeting is complete (without presentation links)
- Unit tests
- Log in as user with admin job codes
- Go to GRB review tab of request "GRB meeting with date set in past"
- Presentation links card should be hidden since review has no presentation links added
- Go to GRB review …
=> [EASI-4922] Presentation links card - standard meeting complete

src/features/ITGovernance/Admin/GRBReview/GRBReviewForm/Participants/index.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/_utils/getGRBReviewStatus.ts, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.test.tsx, src/features/ITGovernance/Admin/GRBReview/GRBReviewStatusCard/index.tsx
Fix for [QA "should fix" item #1](https://docs.google.com/document/d/1r5vLwLEwFG94PKviSUzw1TT_HiNqzR8nTwfkkeImmFc/edit?tab=t.0#heading=h.qe8fae5yu2gv)
- Updated `GRBReviewStatusCard` component to display "Complete" status if either `SystemIntakeGRBReviewAsyncStatusType` or `SystemIntakeGRBReviewStandardStatusType` are set to `COMPLETED`
- Fixed "Can't start" alert in GRB review set up form so that it does not render for completed reviews
- Unit tests
- Log in as user with admin job code
- Go to GRB review tab of seeded request "A Completed Intake Form"
- Review status card should display "Not started"
- Click "or, take a different action" link in blue Admin Task card
- Select "Progress to a new step"
- Select GRB review and set meeting date to date in past
- Submit form
- Go back to GRB …
=> [NOREF] GRB standard meeting complete status

pkg/scheduler/grb_email_jobs.go, pkg/sqlqueries/SQL/system_intake/get_where_grb_review_ended.sql, pkg/sqlqueries/system_intake.go, pkg/storage/system_intake.go
- move filters into DB, only look back one day to prevent repeat emails
- start a GRB review with the end date one day in the past (i.e., "yesterday")
- run new SQL statement to confirm it is picked up (below)
- change the date (manually in the DB) to be further in the past than yesterday
- run the same SQL statement to confirm it is _not_ picked up
- the rest of the infra is not changed and should continue to function as expected
```sql
SELECT *
FROM system_intakes si
WHERE
si.grb_review_type = 'ASYNC'
AND si.grb_review_started_at IS NOT NULL
AND si.grb_review_async_end_date IS NOT NULL
AND si.grb_review_async_manual_end_date IS NULL
AND si.archived_at IS NULL
AND si.grb_review_async_end_date BETWEEN (NOW() - INTERVAL '1 DAY') AND NOW();
```
- It's best to pull the branch locally and …
=> filter in DB and only look one day back to prevent repeat emails

pkg/graph/resolvers/system_intake.go, pkg/models/system_intake_contact.go, pkg/storage/system_intake_contact.go
- pre-work for upcoming migrations
- ensure we always save a user id with the system intake contact
- create a new system intake
- confirm the requester, business owner, product owner, and any other selected contacts all have user ids in the DB in the `system_intake_contacts` table
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation …
=> include user id on contact

.github/workflows/copilot-review.yml
This introduces automatic PR review from github copilot on all prs. This functionality was originally implemented in MINT in this [PR](https://github.com/CMS-Enterprise/mint-app/pull/1821)
1. Push to any branch
2. Open a PR
3. Verify copilot is automatically assigned as a reviewer
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation …
=> [NOREF] Copilot Automatic reviews

migrations/V216__Update_System_Intake_Systems_Historic.sql
The change to migrate historic data was left out of the feature to add system link relationships. This PR updates historic data where the relationship is null to primary support, and sets constraints to ensure the data is not null, and that it is not empty.
To test the migration
test on local test data
Either use psql with test data, or comment out new migration and update seed data by setting both the relation and other column to null
Smoke test the systems changes
1.  Bring up the app
2. Verify that you can link a system. 
3. Verify the invalid case when you try to link a system, but don't provide any relationships
- e.g. …
=> [NOREF] Historic System Intake Systems set to Primary Support

src/features/ITGovernance/Admin/GRBReview/DecisionRecordCard/index.tsx, src/features/ITGovernance/Requester/TaskList/AdditionalRequestInfo.tsx, src/features/Miscellaneous/AdditionalInformation/index.tsx, src/features/TechnicalAssistance/Requester/ProcessFlow/index.tsx, src/features/TechnicalAssistance/Routes/index.tsx
- addressing https://oddball.slack.com/archives/C059N01AYGM/p1756327571277139
- Updated TRB edit information link
- Was going to `system-information/link` instead of `additional-information/link`
- Update which component to render when user went to `additional-information/link`.  
- `<LinkedSystemsForm />` --> `  <RequestLinkForm requestType="trb" fromAdmin />`
- Reverted? to older way of figuring out `isITGovAdmin`. see comment below
1.  Log in as TRB Admin
2. Create a new TRB, linking a system
3. Go to the newly created TRB and click `Additional information`
4. Click `Edit information` and ensure that page loads and functionality of linking, unlinking works
5. Unlink all systems
6. verify that button and alert shows up and works
- It's best to pull the branch locally and test it, rather …
=> [NOREF] quick fix: correct additional-information links and unify admin check

Dockerfile.frontend_k8s, cedarproxy/Dockerfile.cedarproxy
- fix for nginx build failures
1.  confirm nginx builds locally (mine never has, maybe yours does)
2. more importantly, confirm nginx builds in github pipeline
=> NOREF fix nginx build

src/i18n/en-US/articles/governanceReviewTeam.ts
removed savannah as an option for the governance review team.
1.  Verify that you can no longer select Savannah as an option for an admin lead
=> [NOREF] Update IT go team options.

src/components/CedarContactSelect/__snapshots__/index.test.tsx.snap, src/components/CedarContactSelect/index.tsx, src/components/SystemIntakeContactsTable/index.tsx, src/features/ITGovernance/Requester/SystemIntake/ContactDetails/_components/ContactFormModal/__snapshots__/index.test.tsx.snap
Fixes from [QA slack thread](https://oddball.slack.com/archives/C059N01AYGM/p1759780721029629):
- Added pagination to table (only shows when 11th contact is added)
- Fixed bug where width of contact select field expands past modal when contact with long name is selected
1.  Create new system intake
2. On contact details page, click "Add another contact"
3. Select "Bryce Greenfield-Jones" as contact
4. Select field width should stay the same
5. Continue to add new contacts until there are 11 total (including requester)
6. Pagination should show at bottom of table
- e.g. "Approving because I tested it locally and all functionality …
=> [NOREF] Additional contacts QA fixes
